.travis.yml

Let's enforce better commit messages. This patch adds to travis the commit
message check, testing if it's at least 5 lines long:
```
HEADER
<blank line>
MESSAGE
<blank line>
Signed-off-by: Nono <nono@no.non>
```
and also looking for the 'Signed-off-by' string.

add commit message check to travis

---

io/disk/ssd/nvmetest.py

nvme write command expects an input from stdin or a file.
Without that input, write waits forever expecting an input.
Fixed that in nvmetest.py

Fixed nvme write command in nvmetest

---

io/pci/pci_hotplug.py
io/pci/pci_hotplug.py.data/README.txt
io/pci/pci_hotplug.py.data/pci_hotplug.yaml

PCI Hotplug test removes and adds the PCI adapter on the OS.
It is a ppc specific test.

Adding PCI Hotplug test

---

io/net/infiniband/mofed_install_test.py
io/net/infiniband/mofed_install_test.py.data/README.txt
io/net/infiniband/mofed_install_test.py.data/mofed_install_test.yaml

This test verifies the installation of MOFED iso with different
combinations of input parameters.

Adding MOFED Install test

---

io/driver/module_unload_load.sh
io/driver/module_unload_load.sh.data/README.txt
io/driver/module_unload_load.sh.data/config

This test runs only for loaded kernel modules for a total
of 100 counts
Signed-off-by: Narasimhan V sim@linux.vnet.ibm.com

Adding test for Module unload/load operation

---

io/disk/softwareraid.py
io/disk/softwareraid.py.data/Readme

Software raid test used to skip if number of disks were less than 4.
Changed this behaviour, so that if number of disks are applicable for a
certain raid level, it works. Else, test fails for that level.
Updated Readme file accordingly.

Software Raid number of disk fixes

---

generic/criu.py
generic/criu.py.data/version.yaml

This script downloads criu tarball and executes zdtm tests
Version can be specified in version.yaml file

Test to run criu test suit - v5

---

.travis.yml
requirements-travis.txt

add pylint check for Undefined variable (E0602))
in travis as enable travis to catch

Add pylint in travis requirement

---

io/disk/ssd/nvmetest.py
io/disk/ssd/nvmetest.py.data/README.txt

Added the following tests to nvme-cli test.
*) compare
*) flush
*) writezeroes
*) writeuncorrectable
*) dsm
*) reset
*) subsystemreset
Made sure installation of nvme-cli is skipped,
if latest nvme is installed already.
Fetching nvme-cli release tarball instead of git.

Adding tests to nvme-cli test

---

io/net/pktgen.py
io/net/pktgen.py.data/README.txt
io/net/pktgen.py.data/pktgen.yaml

Pktgen is included in linux kernel and used to test
the TX process of device drivers and NICs.
Signed-off-by: Sandeep K <sandeep@linux.vnet.ibm.com>

Adding Pktgen generator Test case

---

io/net/infiniband/ip_over_ib.py
io/net/infiniband/ip_over_ib.py.data/README.txt
io/net/infiniband/ip_over_ib.py.data/ip_over_ib.yaml

IP Over IB Test
IPoIB can run over two infiniband transports, Unreliable Datagram (UD) mode or Connected mode (CM)

IP Over IB Test

---

io/disk/smartctl.py
io/disk/smartctl.py.data/Readme
io/disk/smartctl.py.data/smartctl.yaml

[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/580153/job.txt)
[smartctl_run.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/580154/smartctl_run.txt)
smartctl tool checks the SMART statistics of hard drive.
v3 includes the fix for the traces found with timeout.

smartctl test cases - v3

---

perf/blogbench.py
perf/blogbench.py.data/blogbench.yaml
perf/blogbench.py.data/config_guess.patch

Blogbench is a portable filesystem benchmark that tries to reproduce the load
of a real-world busy file server.
Removed unwanted variables and added license info.

The test Fetches the blogbench tar and performs the benchmark.

---

kernel/kselftest.py
kernel/kselftest.py.data/README
kernel/kselftest.py.data/kselftest.yaml

Rebase, Fixed all the comments
Download linux source repository for the given git/http/tar
url, compile and run the kernel self test.
Reference PR: Linux kernel selftest #173
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/599985/job.txt)

Linux kernel selftest [v4]

---

io/disk/arcconf/arcconf_cntl_oper.py
io/disk/arcconf/arcconf_cntl_oper.py.data/Readme
io/disk/arcconf/arcconf_cntl_oper.py.data/arcconf_cntl_oper.yaml

arcconf_cntl_oper.py tests arcconf tools controller specific configs.
addressed all the suggestions in v2.
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/191
[results.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/626646/results.txt)
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/626647/job.txt)

arcconf controller specific tests - v3

---

io/disk/arcconf/arcconf_drive_oper.py
io/disk/arcconf/arcconf_drive_oper.py.data/Readme
io/disk/arcconf/arcconf_drive_oper.py.data/arcconf_drive_oper.yaml

arcconf_drive_oper.py tests arcconf tools device specific configs.
Includes all the changes required in v1.
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/630367/job.txt)
[results.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/630369/results.txt)

arcconf device specific tests - v2

---

toolchain/atlas.py
toolchain/atlas.py.data/atlas.yaml

It builds the ATLAS libraries and runs the tests present in it.
Several other test options can be given from yaml file and resp
tests can be run.

Added ATLAS test for avocado

---

io/disk/Avago_storage_adapter/avago9361.py
io/disk/Avago_storage_adapter/avago9361.py.data/Readme
io/disk/Avago_storage_adapter/avago9361.py.data/avago9361.yaml

Adjustable values such as cc, bgi, pr etc are set

Script to run adapter configuration for Avago_9361 adapter V2

---

io/disk/arcconf/arcconf_cntl_oper.py
io/disk/arcconf/arcconf_cntl_oper.py.data/Readme
io/disk/arcconf/arcconf_cntl_oper.py.data/arcconf_cntl_oper.yaml

CPLD, SETPOWER, SAVESUPPORTARCHIVE and SETCONFIG new tests are added to
arcconf controller functionality.
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/645768/job.txt)
[results.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/645769/results.txt)

New tests added to arcconf controller functionality - v1

---

io/disk/arcconf/arcconf_cntl_oper.py
io/disk/arcconf/arcconf_cntl_oper.py.data/Readme
io/disk/arcconf/arcconf_cntl_oper.py.data/arcconf_cntl_oper.yaml

firmware upgrade functionality for PMC adapter using arcconf
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/648922/job.txt)
[results.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/648923/results.txt)

firmware upgrade functionality for PMC adapters -v1

---

kernel/kselftest.py

Test checks for libcap1 & libcap1-devel packages. Correct dependency check should
be for libcap & libcap-devel.
Merge redhat package dependency list with fedora & centos.

kselftest fails to compile on redhat due to wrong dependency check

---

io/net/netperf_test.py
io/net/netperf_test.py.data/README.txt
io/net/netperf_test.py.data/netperf_test.yaml

This test runs netperf on the given network interface.
[job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/716338/job_log.txt)

Adding netperf test [v2]

---

kernel/kselftest.py

kselftest - fix compile error on Ubuntu
Package Dependency listed against Ubuntu was incorrect. Updated
correct packages in deps.extend statement.

kselftest - fix compile error on Ubuntu

---

perf/aiostress.py

This patch adds library required to be installed to run on
different distros. This also includes a workaround for compiling
aiostress in Ubuntu.

Added install libraries for aiostress test [v2]

---

fuzz/fsfuzzer.py
fuzz/fsfuzzer.py.data/fsfuzzer.yaml

Added btrfs file system support in yaml file
Added libattr-devel package, this is required for compiling
fsfuzz tool

Add btrfs file system and check for libattr-devel package

---

cpu/ppc64_cpu_test.py

subcore test fails on Linux running as a PowerVM guest.
In this environment subcores_per_core sysfs attribute is missing.
Add a check to skip the test if subcores_per_core is not available.

Add check for ppc64_cpu:subcore sub-test

---

perf/lmbench.py

os.system logs the output out of log file and has been
replaced by process.system

Changed os.system to process.system in lmbench

---

kernel/posixtest.py

posixtest fails to run due to following error
Command 'rpm -q gcc' finished with 0 after 0.164994955063s
Fetching http://ufpr.dl.sourceforge.net/sourceforge/posixtest/posixtestsuite-1.5.2.tar.gz -> /home/avocado-fvt-wrapper/data/cache/posixtestsuite-1.5.2.tar.gz.0JvAha
PARAMS (key=patch, path=*, default=posix-linux.patch) => 'posix-linux.patch'
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-44.0-py2.7.egg/avocado/core/test.py:469
Traceback (most recent call last):
File "/home/avocado-misc-tests/kernel/posixtest.py", line 55, in setUp
os.chdir(self.srcdir)
OSError: [Errno 2] No such file or directory: '/var/tmp/avocado_yGDhUM/1-kernel_posixtest.py_Posixtest.test/src/avocado'
Fix the failure by using a correct delimiter to extract version string. …

Fix posixtest runtime failure

---

io/disk/arcconf/arcconf_cntl_oper.py

Firmware flash test case was skipping due to im-proper check,
fixed the same

Added proper check for the script arcconf_cntl_oper

---

io/disk/Avago_storage_adapter/avago9361.py
io/disk/Avago_storage_adapter/avago9361.py.data/avago9361.yaml

A parameter in yaml file tool_location is added, so now the user
can give the location of the tool and can run the script from any
location

Added a parameter in yaml file for tool location

---

io/driver/module_unload_load.sh
io/driver/module_unload_load.sh.data/module_unload_load.yaml

Enhanced the test to run for all loaded modules.
Fixed the module test to skip the modules which have
dependencies.
Also, changed the way exit status is given, to check for errors
first.
Enhanced as per suggestion by @sacsant 

Enhanced the module unload test

---

memory/dma_memtest.py
memory/dma_memtest.py.data/dma_memtest.yaml

-Provided options to pass tmpdir from yaml file
-Disk space check is made
-Avoid printing output buffer when comparison error occurs

Made changes to dma_memtest

---

memory/memtester.py
memory/memtester.py.data/memtester.yaml

Memtester test for is a utility for testing the memory
subsystem in a computer to determine if it is faulty.

Added memtester for testing faulty memory subsystem [v3]

---

io/net/infiniband/mofed_install_test.py
io/net/infiniband/mofed_install_test.py.data/README.txt
io/net/infiniband/mofed_install_test.py.data/mofed_install_test.yaml

Added an uninstall flag, so that user can decide if mofed should be
uninstalled or not. This is useful when user needs to run tests which
uses installed mofed after this test.

Added uninstall flag for mofed install test

---

io/disk/multipath_test.py

multipath_test script was directly checking the multipath device
without installing the required packages and thenit is installing
the required packages. so made it first install multipath package
and then check for the multipath devices.

enhanced the workflow of multipath_test script

---

cpu/sensors.py

This patch skips the test in case if there are no sensors found

Skip test case if sensors are not found

---

toolchain/ltrace.py

This patch fixes distro name check due to which package
installation was not working

Fix for distro name in ltrace test

---

io/disk/tiobench.py
io/disk/tiobench.py.data/tiobench.yaml

[tiobench-logs-with-partition-utils.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/810234/tiobench-logs-with-partition-utils.txt)
Added disk parameter and different file system types in
tiobench.yaml and then implemented the unmount if it is already
mounted and then create the file system on it and mount on given
directory. used partition utility to do all these operations.
Signed-off-bynced: Naresh Bannoth <nbannoth@in.ibm.com>

Implemented disk mount on dir with partition utility in tiobench.py

---

fs/filebench.py

A typo in link used for download of filebench tarball causes test failure.

Fix a typo in link used for filebench tarball download.

---

memory/transparent_hugepages.py

The test sets THP to always and stresses the system using
dd command and checks whether THP has been allocated or not.

Added basic test for thp v2 with changes

---

memory/transparent_hugepages_swapping.py

This test enables THP and fills out all the available memory
in the system using dd workload and checks whether swapping occurs.

Added thp swap test version 2

---

perf/bonnie.py
perf/bonnie.py.data/bonnie.yaml

Initially script was accepting a mounted directory which involved
manual effort. Enhanced the code where accept disk and directory
names and take care of rest thing like mounting/unmounting.

Enhanced bonnie.py with disk mount on dir using partition utility [v3]

---

io/disk/fs_mark.py
io/disk/fs_mark.py.data/fs_mark.yaml

To avoid manually mount a disk on a directory and giving that
directory in yaml file, using partition utility handled this
mount/unmount on passing the disk and the dir name in yaml file

Added mount/unmount of disk on a dir using partition utility for fs_mark

---

fuzz/fsfuzzer.py

This patch handles packages required for fsfuzzer test to execute on different distros

Handle packages for different distributions

---

kernel/kselftest.py

popt-static is not needed for kselftest and also
libcap-ng-devel. so removed it from test

Remove unneeded packages from the test

---

fs/xfstests.py
fs/xfstests.py.data/README
fs/xfstests.py.data/local.config

Fix xfstest
1- enable xfstest to run fedora/centos/RHEL
2- enable local.config file to handle environment variable
3-  Rectify README File

FIx Xfstest v2

---

io/disk/disktest.py

The testscript is hardcoded as 100 GB as the default disk size.
test works for all disks <= 100GB and fails if the disk is larger size
like 1TB it fails with this
error "Free disk space is lower than chunk size (10240, 261409)"
the code says free as 100 byte, and in comment it says 100G
Please refer to:
https://github.com/avocado-framework-tests/avocado-misc-tests/issues/291

Fix the default disk size typo in the test

---

cpu/ppc64_cpu_test.py

ppc64_cpu supports smt values 0 to 8 for power8, and 0 to 4 for
other power processor levels.
Fixed that in the test.

Fix valid smt values in ppc64_cpu

---

perf/unixbench.py
toolchain/valgrind.py

Unixbench test fails without patch command. Valgrind requires g++ package.

Added missing packages in tests

---

memory/memcached.py
memory/memcached.py.data/memcached.yaml

The test runs the memcached in the background
and runs the stress tool on it.
Made changes to work in rhel too.

Added memcached test version 2

---

generic/ras.py

Most tests failed without support on PowerNV platform. This patch skips the unsupported tests

Added skip check for powernv platform [v2]

---

perf/rt_tests.py

As the old path was not in use, test case failed without expected files in tar. Updated newer tar path.

Updated rt_tests tar path

---

kernel/kselftest.py
kernel/kselftest.py.data/README
kernel/kselftest.py.data/kselftest.yaml

kselftest takes linux kernel source repository link and version as input.
Update the test to use master.zip instead. This ensures any new tests included
into kselftest will be available for execution.
With this change kselftest.yaml is no longer required, so remove it.
In addition the patch also fixes pep8 compliance warnings (length > 79)
git module import is not required, git package installation is no longer a
requirement. Cleanup the related code.

Update kselftest to always use latest kernel source code.

---

io/net/bonding.py
io/net/infiniband/ib_bw_perf.py
io/net/infiniband/ib_latency_perf.py
io/net/infiniband/ib_pingpong.py
io/net/infiniband/ip_over_ib.py
io/net/infiniband/mckey.py
io/net/infiniband/ping6.py
io/net/infiniband/rping.py
io/net/infiniband/ucmatose.py
io/net/infiniband/udaddy.py
perf/rt_tests.py
toolchain/valgrind.py

This patch fixes suse distro name as 'SuSE' in some of the tests

Fix suse distro name for tests

---

fs/xfstests.py
fs/xfstests.py.data/README
fs/xfstests.py.data/xfstests.yaml

Enables tests to be run on loop device
Runs all tests for given file system
(or)
Runs specific tests for given file system if range is provided.

Support for running xfstests on loop device [v2]

---

generic/hwinfo.py
generic/hwinfo.py.data/options.yaml

hwinfo is used to probe for the hardware present in the system.

Test to verify hwinfo tool options - V4

---

io/disk/ssd/nvmetest.py

nvmetest errors out if no nvme-cli is installed previously.
Added a check for it and installing nvme-cli in that case.

Fix nvmetest error if no previous nvme installed

---

fs/xfstests.py
fs/xfstests.py.data/README
fs/xfstests.py.data/xfstests.yaml

This patch allows to run xfstests on real disks

Support to run xfstests with real disk

---

cpu/ppc64_cpu_test.py

On a POWER6 based system smt level upto 2 is supported, while on a POWER7
based system smt level upto 4 is supported. Depending on the processor
generation some of the smt tests fails.
This patch adds a check for smt level support and limits the runtime values.

Update ppc64_cpu test with processor generation check.

---

io/pci/pci_info_lsvpd.py

Slot from sysfs returns a string.
strip() would fail if the string returned is None.
So, need to check if string exists before strip()

Fixup lsvpd test if slot from sysfs not found

---

generic/rcutorture.py

Modified code to skip the test if CONFIG_RCU_TORTURE_TEST is not enabled.
Signed-off-by: Pooja <pooja@linux.vnet.ibm.com>

Rcutorture test.

---

io/disk/multipath_test.py

Printing errors in self.fail, so that it is easier to view.

Print error log properly

---

perf/perf_events_test.py

This is a series of test is meant to validate that the perf_event subsystem is working.
It supports features like perf fuzzer, that tries to hit the extremes of the perf_event interface and find bugs in the kernel
perf_event_h, an archive of perf_event.h files over the history of the interface.Useful when figuring out when a feature was added.
It also supports various perf_event related tools and also tests PAPI library if it is supported.

Perf test suite to validate the perf interface

---

io/disk/lvsetup.py

pkg variable was initialized to " " instead of "".
Fixed that, and added that as a check in package installation.

Fixed package install check in lvsetup

---

toolchain/gcc.py

The gcc package contains the GNU Compiler Collection version. This test runs the test suites of gcc package.
Signed-off-by: Ramya BS <ramya@linux.vnet.ibm.com>

Testcase for gcc package

---

cpu/cpupower.py

This pull request add following fixes to cpupower test case
178f602 : Fix runtime syntax errors
ee60eee: Skip cpupower test on unsupported platform

cpupower testcase fixes

---

cpu/sensors.py

Fix sensors test case to run only on bare-metal and a minor pep8 compliance fixup.
0fbc116: Add platform check for sensors testcase.
b21c214: Fix pep8 warning for sensors

sensors testcase fixups

---

io/disk/multipath_test.py

multipaths were not stopped or flushed after the test run complete.
so added multipath flush in tearDown method.

Added code to Flush All multipath in multipath_test.py

---

cpu/sensors.py

1. Platform check specific to power arch 
2. Fixed sensors package name for Suse
3. Skip test if pre-requiste fails

Fix sensors test to run on x86

---

io/disk/multipath_test.py

When more than one multipath device was present, needed some
time after services are stable for flushing the paths. So, added
a sleep.

Fixed path flush error in multupath_test

---

io/disk/htx_block_devices.py
kernel/kselftest.py

As zip names are common in cache dir, tests fail with expected files. Provided unique names for zip files

Fix common zip names for tests

---

generic/interbench.py

Test skips if disk space is less than total memory of the system

Skip test if disk space is insufficient

---

fuzz/trinity.py

Used getent command to check whether the user and group
'trinity' exists before creating it.

Check for trinity group/user before creation

---

cpu/ppc64_cpu_test.py

This patch adds a sub test to turn off/on SMT capabilities in a loop
with count of 100.
Additionally the test collects dmesg output at the end of the test.

Add SMT on/off loop subtest to ppc64_cpu_test

---

io/net/multiport_stress.py
io/net/multiport_stress.py.data/README.txt
io/net/multiport_stress.py.data/multiport_stress.yaml

Script will run a ping test on multiple interfaces parallely
with user specified number of packets. Default is 1000

Script to run IO parallely on multiple interfaces

---

io/disk/fiotest.py
io/disk/fs_mark.py
io/disk/ltp_fs.py
io/disk/tiobench.py

Some tests were using self.srcdir for multiple purposes.
Changed the tests which mount a disk as well as download a
tarball, to use default mountpoint as self.teststmpdir.

Changed the default mountpoint to teststmpdir

---

io/disk/lvsetup.py

Package name is btrfsprogs on SuSE, but btrfs-progs on other
distros. Fixed it.

Fix btrfs-progs package name for SuSE

---

memory/stress-ng.py

test runs 'mmapfork' as default stressor, for 5 minutes
other stressor can also be passed from yaml file
ToDo : Imporve this test to include more stressor

[v2] Stress-ng stressor tests to stress memory

---

io/driver/module_unload_load.sh
io/driver/module_unload_load.sh.data/module_unload_load.yaml

module_unload_load.sh ran for all modules in the system.
Now, added a parameter in yaml file to specify it to run only for
IO drivers for the PCI devices in the system.

Module_unload_load can run only for IO drivers too

---

io/disk/ssd/ezfiotest.py

Output dir was having ';'.
-o option was taking the directory without "", and thus was
parsing them as 2 commands.
Fixed it.

Fixed exfiotest output dir parameter

---

io/disk/htx_block_devices.py

Skip if MDT File not found in HTX test

Skip if MDT File not found in HTX test

---

io/disk/fiotest.py

Tests create unwanted files as file-1.0.0.. and does not delete after test completes. Using same file for all variants and deleting at end.

Remove unwanted image files created by fiotest

---

io/disk/ssd/ezfiotest.py

aio-max-nr is 65536 by default, and test fails if QD is 256 or above.
So, setting it to 1048576.
Refer: https://github.com/earlephilhower/ezfio/issues/6
Also adding sdparm package as dependent package to be installed.

Set fs.aio-max-nr to 1048576 for ezfio test

---

io/net/infiniband/ip_over_ib.py
memory/memtester.py
memory/stress-ng.py
perf/perf_events_test.py
toolchain/gcc.py
toolchain/libvecpf.py

To avoid clash of zip names in cache dir, unique zip names are added for missed tests.

Provide file name for master zip files

---

io/disk/multipath_test.py

The multipath package and service names are different for rhel
and sles. hence script was skipping while running. so added
the same to the script and now it is working fine.

Added the multipath package and service name for Sles OS.

---

generic/hwinfo.py

hwinfo is supported on other platforms also.

Removed check for platform.

---

fs/xfstests.py
fs/xfstests.py.data/xfstests.yaml

Test now runs with loopdevice creation under root if base disk is not provided.

Use root space by default to create loop device

---

io/disk/bonnie.py
io/disk/fiotest.py
io/disk/ltp_fs.py
io/disk/lvsetup.py
io/disk/ssd/ezfiotest.py
io/disk/ssd/nvmetest.py
io/disk/tiobench.py
io/net/infiniband/ip_over_ib.py
io/net/netperf_test.py

teststmpdir is common for all variants of a test. So, it is the
ideal location to extract repos / tar-balls, for reuse by other
variants of the test.
So, changed the usage of some IO tests accordingly.
This is in line with the discussion at https://github.com/avocado-framework/avocado/issues/1924

Usage of srcdir and teststmpdir in a better way

---

io/disk/multipath_test.py

utility is taking care of waiting time after the service is
started. hence no need here.

sleep time is set in the utils itself, so removing sleep here

---

toolchain/atlas.py

Fixes 'Aborting due to throttling' with a required option.

Fix atlas test for throttling error

---

io/pci/PowerVMEEH.data/PowerVMEEH.yaml
io/pci/PowerVMEEH.data/Readme
io/pci/PowerVMEEH.py

[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/969729/job.txt)
This script injects one EEH error on all PE device in
the machine

Basic EEH test case for PE

---

io/disk/bonnie.py
io/disk/fiotest.py
io/disk/fs_mark.py
io/disk/tiobench.py

The package for btrfs file system is different in ubuntu. hence it
was failing while running for btrfs file system. added the code to
fix the same issue. now it is working fine.

Fix for btrfs package issue for Ubuntu distribution

---

fs/xfstests.py
generic/criu.py
generic/gdb.py
generic/hwinfo.py
generic/service_check.py.data/services.cfg
generic/sosreport.py
io/net/bonding.py
io/net/infiniband/ib_bw_perf.py
io/net/infiniband/ib_latency_perf.py
io/net/infiniband/ib_pingpong.py
io/net/infiniband/ip_over_ib.py
io/net/infiniband/mckey.py
io/net/infiniband/ping6.py
io/net/infiniband/rping.py
io/net/infiniband/ucmatose.py
io/net/infiniband/udaddy.py
kernel/kselftest.py
memory/libhugetlbfs.py
memory/memcached.py
perf/aiostress.py
perf/perf_events_test.py
perf/perftool.py
toolchain/atlas.py
toolchain/ltrace.py
toolchain/valgrind.py

Avocado has a change proposed for inclusion during the 50.0
development time that will change the distro name for Red Hat
Enterprise Linux from "redhat" to "rhel".
These changes keep the old name ("redhat"), while adding the new name
and a very verbose FIXME message explaining the deprecation.  Then, at
a later time, the support for the "redhat" name can be dropped without
causing compatibility issues.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

RHEL distro name: adapt tests to change in Avocado's definition

---

fs/xfstests.py

1. Fix condition for unmounting
2. Skip ext3 root file system

Fix: xfstests unmounting and ext3 file system skip

---

io/pci/pci_info_lsvpd.py

Improved error message in pci_info_lsvpd.
And pep8 fixes.

Improved error message in pci_info_lsvpd

---

io/pci/PowerVMEEH.data/PowerVMEEH.yaml
io/pci/PowerVMEEH.py

Now script will be able to inject one error more than the
eeh_max-freeze bit, so that we can test adapter failure.
Also, if there is EEH miss for more than 5 times for a perticular
function, it continues with next adapter throwing a warning

Enhanced PowerVMEEH script

---

io/disk/multipath_test.py

Script was throwing an error, for WWID which are not present,
but were cached. So we need to skip the older WWID
Suggested-by:  Narasimhan V sim@linux.vnet.ibm.com

Fixed the script to skip cached WWID

---

fs/xfstests.py

local.config was not overwritten in case loop devices were used. This patch fixes it.

Fix local.config file when using loop devices

---

io/disk/htx_block_devices.py
io/disk/htx_block_devices.py.data/Readme.txt
io/disk/htx_block_devices.py.data/htx_block_devices.yaml

Enhanced HTX test to run SMT changes once every hour,
since running it very frequently is not a proper use case.

SMT Changes in HTX now runs once every hour

---

io/disk/softwareraid.py

mdadm metadata does not get removed by only stopping the md device.
The block should be overwritten with zeroes.

tearDown enhancements for softwareraid

---

cpu/pmqa.py

fix pmqa test to fail for non root users. Previously it was a false PASS.

Fix Pmqa test to fail for non root users

---

io/disk/arcconf/arcconf_cntl_oper.py
io/disk/arcconf/arcconf_cntl_oper.py.data/arcconf_cntl_oper.yaml
io/disk/arcconf/arcconf_drive_oper.py
io/disk/arcconf/arcconf_drive_oper.py.data/arcconf_drive_oper.yaml
io/disk/arcconf/arcconf_migration.py
io/disk/arcconf/arcconf_migration.py.data/arcconf_migration.yaml
io/disk/arcconf/arcconf_raid_oper.py
io/disk/arcconf/arcconf_raid_oper.py.data/arcconf_raid_oper.yaml

This patch will check the Arcconf package with correct case letter,
also will remove the default tool and firmware path for the adapter.
Signed-off-by: Naveed Ahmed U S <naveedus@linux.vnet.ibm.com>

Check the Arcconf package and remove the http repo path in yaml file

---

cpu/cpupower.py

scaling_available_frequencies file had a space in the end, which
when split, returned an empty element in array.
Fixed that with returning after stripping the space in the end.

Fix cpupower cpu_freq_path function return value

---

cpu/ebizzy.py
io/disk/dbench.py
io/disk/iozone.py
io/disk/parallel_dd.py
kernel/tlbflush.py
perf/hackbench.py

The following five tests use a custom file to record performance
data.  Avocado test API makes an attribute available that will
automatically preserve test data in any arbitraty format, the
whiteboard, documented here:
http://avocado-framework.readthedocs.io/en/49.0/WritingTests.html#saving-test-generated-custom-data
This patch is a suggestion/RFC to just use the whiteboard instead of
yet another external file.  The upside is less code and possible
future goodies that the framework may bring (for instance, we may show
the whiteboard by default on job reports).  The downside of this
change is that, if there are scripts consuming this performance data,
they'd have to be adjusted to use the whiteboard file path.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
---
Changes from v1 (#492):
* …

Use whiteboard for performance data [v2]

---

fs/xfstests.py
fs/xfstests.py.data/xfstests.yaml

This patch provides support to exclude a range of xfstests specific to a filesystem running as a whole.

Support to exclude tests run in xfstest suite

---

io/pci/pci_hotplug.py

there was a typo error in pci_hotplug.py where cpu_info should there,
it was a cpuinfo, hence test was failing. so edited the same and now
it works fine.

7th floortypo error fix in pci_hotplug.py script

---

io/disk/ltp_fs.py

ltpbin_dir was getting created across variants, which caused the
test to ERROR out.
Made sure it gets created only when not created already.

ltpbin_dir fix for ltp_fs

---

io/driver/driver_bind_test.py

Used pci utility to get the driver name for a pci device.

Use pci utility to get driver

---

memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py
memory/transparent_hugepages_swapping.py

If the linux pagesize of the given system is 4K than skip
the THP testcases, as the transparent huge pages are not supported
if the PAGESIZE is 4096

SKIP : THP tests are not supported for 4K pages

---

io/disk/ltp_fs.py

configure was throwing an error when trying for second variant
onwards, due to a change in the previous commit.
Fixed that.

Fixing an issue with previous change ltp_fs

---

README.rst
cpu/cpupower.py
cpu/ebizzy.py
cpu/linsched.py
cpu/pmqa.py
cpu/ppc64_cpu_test.py
cpu/sensors.py

The tests on this repo are already well categorized by the directory
structure, but that can only give so much info about them. Let's also
make use of some basic (initially) tags.
Some exampels of the immediate benefits include listing/running only
tests that can run as regular users:
$ avocado list --filter-by-tags=-privileged cpu/
INSTRUMENTED cpu/ebizzy.py:Ebizzy.test
INSTRUMENTED cpu/linsched.py:Linsched.test
Listing/running tests that require a Power architecture:
$ avocado list --filter-by-tags=power cpu/
INSTRUMENTED cpu/cpupower.py:cpupower.test
INSTRUMENTED cpu/ppc64_cpu_test.py:PPC64Test.test
This is a *partial* implementation (only includes tests under the
"cpu" directory) of the extended information using tags, intended as
an RFC (or initial step).  This is related to an RFC …

Extend test category using tags [v2]

---

perf/perf_genericevents.py

Performance Monitoring Unit (PMU) provides a list of events to measure micro-architectural events such as the number of cycles,instructions retired, L1 cache misses and so on.Those events are called PMU hardware events or hardware events.The generic hardware and cache perf events for Power are exported to sysfs,so users can precisely determine the PMU event monitored by the generic event.
The script tests Display event codes for Generic HW (PMU) events.It will read content of each file from
/sys/bus/event_source/devices/cpu/events and compare the raw event code for each generic event.

Test to verify raw event code for each generic event

---

perf/perf_24x7_hardware_counters.py

24*7 performance counters is supported on Power VM platform.
Script will cover basic testing of events in 24x7 counters that belong to different
domains like core,chip,virtual CPU home core, etc.To monitor an event, the user must
specify the required parameters for the event,which include its name,
the chip/core on which to monitor the event as well as the domain.
Added the check for VCPU, added failure info for all failures, optimized the code.

Test to verify 24x7 hardware counters

---

generic/stress-ng.py
generic/stress-ng.py.data/readme.rst
generic/stress-ng.py.data/stress-ng.yaml

stress-ng can now by default run test for all linux components like
cpu, memory, scheduler, io, kernel .etc user can also run individual
components from yaml supplied.
stress-ng removed from memory and added generic tag

Stress-ng : Improved test to cover all test scenarios

---

io/disk/arcconf/arcconf_cntl_oper.py

This patch will help in checking arcconf/Arcconf tool with
right case according to the installed OS.
Signed-off-by: Naveed Ahmed U S <naveedus@linux.vnet.ibm.com>

Patch to check arcconf/Arcconf for respective OS

---

io/disk/Avago_storage_adapter/avago3008.py.data/avago3008.yaml
io/disk/Avago_storage_adapter/avago9361.py.data/avago9361.yaml

Fix Spelling in yaml files in Avago test

Fix Spelling in yaml files in Avago test

---

io/net/net_data.py

ifconfig commands in net_data.py scripts is replaced with
ip link commands as it is obsolte based on info in
ifconfig man page

Changes to net_data.py script to use ip link commands

---

cpu/ppc64_cpu_test.py

POWER9 processor supports SMT4.
This patch adds the code to support POWER9 processor.

Add support for POWER9.

---

io/driver/module_unload_load.sh

Module unload test would skip the dependency part, even if found
in config file.
Fixed that to check in config file before skipping.

Fixed how dependent module is unloaded or loaded

---

kernel/kselftest.py
kernel/posixtest.py
kernel/rmaptest.py
kernel/tlbflush.py
memory/dma_memtest.py
memory/eatmemory.py
memory/libhugetlbfs.py
memory/memcached.py
memory/memtester.py
memory/stutter.py
memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py
memory/transparent_hugepages_swapping.py

Each tests have been tagged under its components for kernel and memory
missing doc strings are added for few tests along with tags

tags: memory and kernel tests are grouped under respective components

---

generic/rcutorture.py

CPU off-on commands from process.system() function never got
executed, replace with cpu off on functions in utils.py
Also added tags to be a kernel tests and replace skip with cancel

generic/rcutorture: Reuse cpu functions for offline and online

---

io/net/htx_nic_devices.py
io/net/htx_nic_devices.py.data/README.txt
io/net/htx_nic_devices.py.data/htx_nic_devices.yaml

This test as of now assumes htx is installed in both Host & Peer.
And this test will be of two phases
Phase 1: Configure all necessary pre-setup steps for both the n/w
interfaces in both Host & Peer
Phase 2: Start the HTX setup & execution of test for a time_limit
and monitor's the HTX error log for any errors in both
Host & Peer

HTX stress test for NIC devices.

---

io/net/tcpdump.py
io/net/tcpdump.py.data/tcpdump.yaml

tcpdump would wait for some network traffic to be in place, else
it waits forever.
Fixed that by generating a background traffic on the interface.

Add background traffic to tcpdump

---

io/disk/ssd/nvmetest.py
io/disk/ssd/nvmetest.py.data/README.txt
io/disk/ssd/nvmetest.py.data/nvmetest.yaml

Namespace related tests were not completely implemented in nvmetest
as multiple namespaces were not supported on older controllers.
Also, a newer selftest for nvme-cli is added which does namespace
tests.
So, removing them from nvmetest.
Also, a small pylint fix is included.

Removed the namespace tests from nvmetest

---

io/net/infiniband/ib_pingpong.py

ibverbs-utils package is needed for Ubuntu

Patch to fix ib_pingpong test for Ubuntu

---

io/net/port_bounce.py
io/net/port_bounce.py.data/README.txt
io/net/port_bounce.py.data/port_bounce.yaml

This testcase executes the portbounce test for adapters which
are under fc switch ports.
portbounce test is basically enable/disabling fc port for short
& long durations.
Currently full testcase is implemented for fc switches as setup
available.
TODO: Update fcoe switch login and run command API's. And also
update portdisable test for fcoe switch

Portbounce testcase for fc switches.

---

generic/rcutorture.py

Some times when test fails, rcutorture modules is still loaded
and test never ends.. so add a clean up to unload the modules
also the cpu parameter is contradicting with the cpu object.

rcutorture: add tearDown and change variable name

---

io/net/htx_nic_devices.py
io/net/htx_nic_devices.py.data/htx_nic_devices.yaml

HTX Changes the test interface ips before starting the
test, due to which the commands to be executed in peer
will no more functional.
So this patch has below improvements.
1. Falling back to password based ssh to the public IP
which is not going to be effected by HTX.
2. Imprved pingum test work flow. If N/W interfaces are
in different topology N/W ping test takes some time.
So running the pingum test in a loop for 10 times until
it passes.
3. As HTX changing test interface ips, we need to restore
back to original ips. So in tearDown handling this.

Improvements for HTX on NIC Interface Stress test.

---

cpu/sensors.py

cpu._get_cpu_info returns only 1st cpu details and hence fails to check bare-metal enviroinment. This fixes it.

Fix enviroinment check for power systems

---

io/disk/mvcli_test.py
io/disk/mvcli_test.py.data/README.txt
io/disk/mvcli_test.py.data/mvcli.yaml

Mvcli Test for OpenPower based Marvell adapter 88SE9230.
This tests the different mvcli tool operations like
info, get, set, smart, locate, register, delete, create, event
on RAID Marvell adapter 88SE9230

MVCLI Testcase for OpenPower Marvell adapters.

---

perf/perf_24x7_hardware_counters.py
perf/perf_genericevents.py

perf_24x7_hardware_counters : changed 'redhat' to 'rhel'
perf_genericevents: self.warn to self.log.warn

fix: change the distro and warn key words

---

io/net/port_bounce.py
io/net/port_bounce.py.data/port_bounce.yaml

Currently testcase just verifies port enable/disable
status only in fc switch after portbounce.
This patch adds the facility to verify the port toggle
status in Host also. By checking in below sysfs path
cat /sys/class/fc_host/host1/port_state
Online

Improvements for fc port bounce testcase.

---

io/disk/ltp_fs.py

Clearing the disk after unmounting fs

Clearing the disk after unmounting fs

---

io/net/vlan_test.py
io/net/vlan_test.py.data/README.txt
io/net/vlan_test.py.data/vlan.yaml

This testcase tests below 3 scenarios.
Scenario 1: keep both host & peer in default VLAN id, VLAN 1.
Now ping each other. it should PASS
Scenario 2: Keep host in vlan 1 and Peer in vlan 2230.
Now ping. it should FAIL
Scenario 3: Keep both in the vlan id (taken from yaml file),
and create vlan interfaces and then ping.
It should PASS.

Vlan Testcase

---

generic/pstore.py
generic/pstore.py.data/config.yaml

This script triggers crash on the machine configured in config.yaml and verifies files under /sys/fs/pstore.

Test to verify pstore - v2

---

cpu/cpustress.py
cpu/cpustress.py.data/cpustress.yaml

serial off all, serial on all cpus
off/on single cpu 100 times all cpus
off/on one cpu at a time all cpus
Affine task to single NUMA node and do off-on
affine to shared multiple cpus and off on
Do multiple cpu off on at once ppc64_cpu --smt
LPAR/GUEST : trigger DLPAR CPU using drmgr command
Few bugs reported from above scenarios:
https://lkml.org/lkml/2017/6/12/212
https://lkml.org/lkml/2017/7/3/21
https://lkml.org/lkml/2017/5/30/122
Rework for PR #591 

CPU/cpustress: new tests to stress the cpu component [v2]

---

generic/ras_extended.py

The rtas_event_devocde command is not supported for PowerNV platform. Added skip for handling it.

Skip rtas_event_decode for PowerNV platform

---

generic/ras_extended.py

lscfg command failed with a non-generic option. This patch fixes the option to be generic across machines.

Fix lscfg command with proper option

---

io/net/infiniband/mofed_install_test.py.data/mofed_install_test.yaml

Add with-nvmf to mofed install options.
This option tries to install mofed with nvme over fabrics support,
if the mofed version has support for it.

Add with-nvmf to mofed install options

---

cpu/cpustress.py
cpu/cpustress.py.data/cpustress.yaml

removed unwanted sleep, as the cpu code itself will take care
of on-of timeout, now test will run with medium time slot.

cpustress : modified test to run for less time

---

io/net/infiniband/ib_bw_perf.py
io/net/infiniband/ib_bw_perf.py.data/ib_bw_perf.yaml
io/net/infiniband/ib_latency_perf.py
io/net/infiniband/ib_latency_perf.py.data/ib_latency_perf.yaml
io/net/infiniband/ib_pingpong.py
io/net/infiniband/ib_pingpong.py.data/ib_pingpong.yaml
io/net/infiniband/ip_over_ib.py
io/net/infiniband/ip_over_ib.py.data/ip_over_ib.yaml
io/net/netperf_test.py
io/net/netperf_test.py.data/netperf_test.yaml

* Avocado treats yaml parameter 'timeout' as test timeout.
So, if we want a yaml parameter timeout to mean something else, we
can use it in any other form / case, here we use upper case: TIMEOUT
* PEP8 and Pylint fixes

Changing yaml parameter timeout to TIMEOUT

---

generic/gdb.py

gdb test failed due to makeinfo command not found
fixed it as making texinfo and texi2html should be installed
Signed-off-by: chidanand <chidanand.harlapur@in.ibm.com>

Fixed package issue in gdb Test

---

cpu/numactl.py

Fixed numactl typo

---

cpu/numactl.py
cpu/numatop.py

Added tags for new test cases on cpu category
[praveen@dhcp-9-109-222-39 avocado-misc-tests]$ avocado list   --filter-by-tags=cpu,privileged cpu/
INSTRUMENTED cpu/numatop.py:Numatop.test
[praveen@dhcp-9-109-222-39 avocado-misc-tests]$ avocado list   --filter-by-tags=cpu cpu/
INSTRUMENTED cpu/numactl.py:Numactl.test
INSTRUMENTED cpu/numatop.py:Numatop.test
[praveen@dhcp-9-109-222-39 avocado-misc-tests]$

Extend test category using tags

---

io/disk/Avago_storage_adapter/avago3008.py
io/disk/Avago_storage_adapter/avago3008.py.data/Readme
io/disk/Avago_storage_adapter/avago3008.py.data/avago3008_cleanupraid.yaml
io/disk/Avago_storage_adapter/avago3008.py.data/avago3008_setupraid.yaml

Added the following functionalities to avago3008 test:
* Setup: Based on yaml parameter setup_raid, test just creates raid.
* Cleanup: Based on yaml parameter cleanup_raid, test just deletes
raid.
* ClearConfig: Based on yaml parameter clear_config, test decides
whether to clear the raids in the drives or not before starting the
other tests.
Changed the yaml parameter disk to disk_bay.
Made HotSpare and Rebuild test to run only if hotspare drive is
given and clear_config is True

Avago3008 - Added Setup, Cleanup, ClearConfig

---

io/disk/bonnie.py

configure failed due to per-requisite
2017-09-16 16:38:59,012 download         L0066 INFO | Fetching http://www.coker.com.au/bonnie++/bonnie++-1.03e.tgz -> /var/lib/avocado/data/cache/bonnie++-1.03e.tgz.ev2AJ3
2017-09-16 16:39:01,433 process          L0389 INFO | Running './configure'
2017-09-16 16:39:01,512 process          L0479 DEBUG| [stdout] checking for g++... no
2017-09-16 16:39:01,513 process          L0479 DEBUG| [stdout] checking for c++... no
2017-09-16 16:39:01,513 process          L0479 DEBUG| [stdout] checking for gpp... no
2017-09-16 16:39:01,513 process          L0479 DEBUG| [stdout] checking for aCC... no
2017-09-16 16:39:01,514 process          L0479 DEBUG| [stdout] checking for CC... no
2017-09-16 16:39:01,514 process          L0479 DEBUG| [stdout] checking for cxx... …

Fixed issue in io:disk:bonnie

---

perf/stress.py

1 -  Fixed perf:stress.py
a- fix pep8 issue
b- added expire param on fetch_asset
2-Fixed perf:stress  due to change of test build dir test run is failing due to directory missing

Fixed perf:stress.py

---

memory/memhotplug.py
memory/memhotplug.py.data/memhotplug.yaml

Stress test to exersizes memory component
This test performs memory hotunplug/hotplug tests with below scenarios:
1. hotunplug one by one in a loop for all
2. Toggle memory blocks by making off/on in a loop
3. hot unplug % of memory for different ratios
4. dlpar memory hotplug using  drmgr
5. shared resource : dlpar in CMO mode
6. try hotplug each different numa node memblocks
7. run stress memory in background
Implemented all the review comments

memstress : New test to stress memory hotplug code [v2]

---

io/disk/multipath_test.py

Multipath test was flushing all the paths in teardown.
This will cause all multipath devices to stop, which is not
expected. The system state should be retained after the test

Removed multipath flush from teardown

---

io/pci/PowerNVEEH.py
io/pci/PowerNVEEH.py.data/PowerNVEEH.yaml
io/pci/PowerNVEEH.py.data/Readme

This sets max_eeh_freeze, and injects EEH error on specified PE
checks for recovery of the adapter.

Patch to inject EEH on Specified PE on PowerNV platform

---

io/disk/dbench.py
io/disk/ioping.py
io/disk/iozone.py
io/disk/tiobench.py

teststmpdir is same for all of a test's variants. Thus, it is
better to use it as target to build our packages so that we save
time in re-compiling.

Changed srcdir to teststmpdir

---

generic/ltp.py

Few tests had test status being split with ":" like "TFAIL:" and script did not catch in the failure list generated. This patch fixes this issue.

Fixed test analysis of ltp failures

---

cpu/ppc64_cpu_test.py

Use avocado library function for processor check and Handle SMT mix state in ppc smt test.

Fix ppc test

---

generic/ras.py
generic/ras_extended.py

Use avocado library function for processor check and Move ras_extended test to ras test.

Ras test fix

---

perf/rt_tests.py

because distro name it was checking for redhat
now made changes to check centos,fedora, rhel and redhat
Signed-off-by: chidanand <chidanand.harlapur@in.ibm.com>

numactl-devel package was not getting installed

---

toolchain/valgrind.py

There is a compiling error when running valgrind testcase on ppc64el.
m_debuglog.c: In function ‘local_sys_write_stderr’:
m_debuglog.c:203:4: error: PIC register clobbered by ‘r2’ in ‘asm’
__asm__ volatile (
^~~~~~~
m_debuglog.c: In function ‘vgPlain_debugLog’:
m_debuglog.c:228:4: error: PIC register clobbered by ‘r2’ in ‘asm’
__asm__ volatile (
^~~~~~~
In the upstream version (v3.13) it's already fixed. So, by just using
the upstream version instead of v3.12, this error does not happen.
Signed-off-by: Rodrigo R. Galvao <rosattig@br.ibm.com>

Fix compiling error Valgrind test (ppc64el)

---

memory/transparent_hugepages_swapping.py

Avocado memory library has now a meminfo object. Let's take advantage of it.
Signed-off-by: Amador Pahim <apahim@redhat.com>

Use new meminfo object

---

memory/transparent_hugepages_swapping.py

Patch fixes a wrong comparison between a list and int in thp_swap test case. Replace with actual value to be compared.

Fix thp_swap test

---

io/disk/fiotest.py.data/fio-rand-RW.job
io/disk/fiotest.py.data/fio-rand-read.job
io/disk/fiotest.py.data/fio-rand-write.job
io/disk/fiotest.py.data/fio-seq-RW.job
io/disk/fiotest.py.data/fio-seq-read.job
io/disk/fiotest.py.data/fio-seq-write.job
io/disk/fiotest.py.data/fio_rand_RW.yaml
io/disk/fiotest.py.data/fio_rand_read.yaml
io/disk/fiotest.py.data/fio_rand_write.yaml
io/disk/fiotest.py.data/fio_seq_RW.yaml
io/disk/fiotest.py.data/fio_seq_read.yaml
io/disk/fiotest.py.data/fio_seq_write.yaml

multiple yaml files are needed because the requirement is to have profilers run individually for each test
Signed-off-by: Venu <venutiwa@in.ibm.com>
With reference to https://github.com/avocado-framework-tests/avocado-misc-tests/pull/644: as per the comment on this PR, adding the changes in single commit.

adding support for multiple fio jobs for KVM perf CI

---

cpu/numatop.py

mgen application does not necessarily to be on first line. Patch checks for its existence in the file rather than the first line.

Fix numatop test

---

generic/packages.py
generic/packages.py.data/list.yaml

This test checks whether powerpc-utils, ppc64-diag and lsvpd are installed by default. Additional packages can be mentioned in yaml file.

Test to verify packages to be installed by default - v3

---

cpu/em_cpuidle.py

Cpupower tool reads the idle states, statistics and descriptions from sysfs files,exported by the
cpuidle kernel subsystem.The script reads the idle states from the cpupower tool and validates the reading from
device tree.Device tree reading we can get from : cd /proc/device-tree/ibm,opal/power-mgt ;lsprop ibm,cpu-idle-state-names
This script is supported on P8 and P9 Power NV platform.

Test to validate idle states read from cpupower tool and device tree.

---

kernel/kernbench.py
kernel/kernbench.py.data/kernbench.yaml

Kernbench is a standard CPU benchmark. Runs a kernel compile and measures the performance by using time command. By default it runs only once with 2 * number of CPUs.

Adding kernbench test

---

cpu/cpustress.py

dlpar removes random cpus and after some iterations the dlpar command fails
to remove cpus making the cpu count constant. so just inform instead of warn

cpustress: do not warn if there are no more hotplug cpus

---

kernel/kernbench.py

URL failed to fetch with location of fetch_asset provided as a string rather than a list. This patch fixes it.

Fix kernbench test

---

fs/xfstests.py

xfstests checks for 15GB of availabe space but default sizes are more than that and hence test fails to create loop devices. So default sizes are reduced.
As fallocate is not supported on ext3 root file system, it is replaced with dd command for loop device creation for ext3 fs.

Use dd for loop device creation on ext3 root fs and change default disk device

---

cpu/em_cpufreq.py

The script validate frequency transition for userspace governor. Set the governor to userspace,
select the random frequency for random cpu and verify it using ppc64_cpu --frequency tool.
The difference is between frequency setting using cpupower tool and read using ppc64_cpu tool
is calculated and asserted if it crosses threshold value.
Test is applicable only on baremetal platform.

Validate Frequency transition on Baremetal

---

io/pci/pci_info_lsvpd.py

VPD prints Sub Vendor ID + Sub Device ID in general.
If Sub Device ID is 0xffff, then:
VPD prints Sub Vendor ID + Device ID.
To accomodate this behaviour, checking VPD's Device ID field with
both Sub Device ID and Device ID.

Accomodating VPD behaviour for PCI Device ID

---

fs/xfstests.py

fallocate fails on ext4 root filesystem, this patch handles it

Support ext4 root filesystem

---

io/pci/dlpar.py
io/pci/dlpar.py.data/README
io/pci/dlpar.py.data/dlpar.yaml

This patch is for performing DLPAR add/remove/move
operations on PowerVM hypervisor. One can run the script
from the host machine.
Most the code is copied from avocado-misc-test IBM internal repo.
Made chages to pci.py in utils, which takes care only to return
exact adapter location, earlier it was returning till port level.
Tested with latest utils.

Patch for DLPAR operation add/remove/move

---

generic/sysbench.py
generic/sysbench.py.data/readme.rst
generic/sysbench.py.data/sysbench.yaml

Enable sysbench (cpu & threads) tests in avocado
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>

Add sysbench perfomance test

---

cpu/cpustress.py
generic/stress-ng.py
memory/memhotplug.py

the code was spliting the dmesg due to which multi-word match will fail. This
was a critical issue were we may mix the bugs. the same is fixed with this patch.
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>

Fixed checking for ERROR in dmesg

---

cpu/numactl.py

1-fixed compilation issue as it is failing due to package missing
2- added numa package for all distribution
issue :
04:51:34 INFO | Running './autogen.sh'
04:51:40 DEBUG| [stderr] configure.ac:9: installing 'build-aux/install-sh'
04:51:40 DEBUG| [stderr] configure.ac:9: installing 'build-aux/missing'
04:51:40 DEBUG| [stderr] Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
04:51:40 DEBUG| [stderr] Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
04:51:40 DEBUG| [stderr] Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
04:51:40 DEBUG| [stderr] Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
04:51:40 DEBUG| [stderr] Makefile.am:8:   its definition is in aclocal's search path.
04:51:40 DEBUG| [stderr] …

Fixed cpu:numactl compilation issue

---

generic/cxl.py
generic/cxl.py.data/cxl.yaml

This is to test CAPI cxl driver and libcxl library . Wrapper is making use of the test cases  at https://github.com/ibm-capi/cxl-tests
Signed-off-by: sudeesh john <sudeesh@linux.vnet.ibm.com>

Adding cxl(CAPI) tests

---

toolchain/ltrace.py
toolchain/ltrace.py.data/ltrace.patch

Fixed (cleanup) toolchain:ltrace 
1- removed build package dependencies from suse pacakge list
2- clean up
a- removed redundant code for checking package dependencies
b- change append list of package method
c- change variable name to valid name
Fixed toolchain:ltrace compilation issue 

Ltrace fix

---

generic/kdump.py
generic/kdump.py.data/config.yaml

This test triggers kdump on the machine configured in config.yaml and checks if vmcore is generated.

To verify kdump on RHEL and Ubuntu -v5

---

io/disk/fiotest.py.data/fio-simple.job

Reducing the file size of fio for fio-simple.job so that the
maximum file size at any point of time is 1024M.
Also, re-ordered the parameters for easier reading and editing.

Reducing the file size of fio for fio-simple.job

---

kernel/kselftest.py

Few test failures are not getting captured due to regex mismatch. sample failure: tm-unavailable. This patch fixes it.

Fix regex for failure in kselftest

---

fs/xfstests.py

xfstests user specific tests fail due to lack of home dir creation on SuSE. This patch adds option to do the same.

 Add options in xfstests for user creation and deletion on SuSE

---

generic/sysbench.py
generic/sysbench.py.data/sysbench.yaml

Few distro does not provide sysbench as part of ISO, For those
distros git clone upstream sysbench, compile and use it.
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>

code to git clone upstream sysbench

---

fs/xfstests.py

Patch adds a package required for xfstests on SuSE distro

Added a package for xfstest on SuSE

---

generic/lshw.py

Lshw command fails were not collected properly for report. This patch fixes the failures collection.

Fix lshw test failure collection

---

generic/openblas.py

Openblas test failed with wrong syntax on list append. Patch fixes the syntax.

Fix openblas syntax

---

kernel/kernbench.py

fixed issue in test as value of allow_output_check should not be 'None' it should be None
issue:
Command 'make oldnoconfig' finished with 0 after 4.20647501945s
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/test.py:819
Traceback (most recent call last):
File "/root/avocado-misc-tests/kernel/kernbench.py", line 135, in test
self.time_build(self.threads, timefile,"")
File "/root/avocado-misc-tests/kernel/kernbench.py", line 59, in time_build
ignore_status=True, shell=True)
File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/utils/process.py", line 1240, in system
sudo=sudo, ignore_bg_processes=ignore_bg_processes)
File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/utils/proces …

Fixed issue in kernel:kernbench

---

generic/sosreport.py

This command fails on SuSE
01:51:43 INFO | Running 'sosreport'
01:51:43 ERROR|
01:51:43 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-55.0-py2.7.egg/avocado/core/test.py:797
01:51:43 ERROR| Traceback (most recent call last):
01:51:43 ERROR|   File "/home/harish/avocado-fvt-wrapper/tests/avocado-misc-tests/generic/sosreport.py", line 45, in setUp
01:51:43 ERROR|     if not process.system("sosreport", ignore_status=True, sudo=True):
01:51:43 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-55.0-py2.7.egg/avocado/utils/process.py", line 1165, in system
01:51:43 ERROR|     sudo=sudo, ignore_bg_processes=ignore_bg_processes)
01:51:43 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-55.0-py2.7.egg/avocado/utils/process.py", …

Remove unnecessary check for command existence

---

kernel/kernbench.py

test run is failing due to wrong package dependencies
[stdout] 'libcap1' not found in package names. Trying capabilities.
[stderr] No provider of 'libcap1' found.
Command '/usr/bin/zypper -n install -l libcap1' finished with 104 after 1.40578007698s
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/test.py:796
Traceback (most recent call last):
File "/root/avocado-misc-tests/kernel/kernbench.py", line 105, in setUp
self.cancel('%s is needed for the test to be run' % package)
File "/usr/lib/python2.7/site-packages/avocado_framework-56.0-py2.7.egg/avocado/core/test.py", line 1032, in cancel
raise exceptions.TestCancel(message)
TestCancel: libcap1 is needed for the test to be run
CANCEL 1-kernbench.py:Kernbench.test -> TestCancel: …

Fixed Suse package issue in kernel:kernbench

---

generic/sysbench.py

1- add ignore_status=True in "which sysbench" as if command failed it make script error out
2- fixed many pep8 issue

Fixed issue in generic:sysbench

---

fs/xfstests.py

on Ubuntu 14.04 libtool-bin has been replaced with libtool
Reference: GH-744

install libtool for Xfstests.test on Ubuntu 14

---

generic/lshw.py

The call of ifconfig may contain info about the
link encapsulation in the output in addition to
the network interface. If the link encapsulation
info is not included in the output `.split()[0]` works
as well.
Reference: GH-739
Signed-off-by: kromer <florian.kromer@roboception.de>

consider link encapsulation output of ifconfig

---

toolchain/ltrace.py

Test failed with patch command not available, this patch fixes it
Running 'patch -p1 < /root/avocado-fvt-wrapper/tests/avocado-misc-ests/toolchain/ltrace.py.data/ltrace.patch'
[stderr] /bin/sh: patch: command not found
Command 'patch -p1 < /root/avocado-fvt-wrapper/tests/avocado-misc-tests/toolchain/ltrace.py.data/ltrace.patch' finished with 127 after 0.00122499465942s

Add patch to ltrace test

---

io/driver/module_unload_load.sh

Inbuilt drivers are excluded from unload/reload test. But they
were not matched exactly when searching, resulting in false passes.
Fixed it with exact match of grep command.
Also fixed the message for reload driver to display after reload is
done, such that it signifies the operation is complete.

Fix the way inbuilt drivers are excluded

---

io/disk/ssd/nvmetest.py

* Skipping unsupported tests in nvmetest, with the output from
nvme id-ctrl
* Some tests support input as both full namespace or specifying
namespace id with -n option. But that is applicable only when
there is one namespace. When more than one namespace is active,
input using -n is not supported. Full namespace name needs to be
given. Changed that in such tests.

Skip unsupported tests in nvmetest

---

io/net/uperf_test.py

uperf compilation needs autoreconf which updates the configuration
files. Added that.

Fix compilation of uperf

---

toolchain/valgrind.py
toolchain/valgrind.py.data/valgrind_source.yaml

Added support to run tests from distrution valgrind source

Support to run distribution specific valgrind test

---

toolchain/ltrace.py
toolchain/ltrace.py.data/ltrace.yaml

Added support to run tests from distrution ltrace source

Support to run distribution specific ltrace test

---

io/disk/fiotest.py.data/fio-perf.yaml
io/disk/fiotest.py.data/fio_rand_RW.yaml
io/disk/fiotest.py.data/fio_rand_read.yaml
io/disk/fiotest.py.data/fio_rand_write.yaml
io/disk/fiotest.py.data/fio_seq_RW.yaml
io/disk/fiotest.py.data/fio_seq_read.yaml
io/disk/fiotest.py.data/fio_seq_write.yaml

In reference to commit 3cc16493d034db3a385ab06941267337ff987ce8,
wherein since profilers and sysinfo per test was not supported,
we allowed this commit to have multiple yaml files.
Since that was fixed in avocado, we are compressing the yaml files
into single yaml.

Compressing multiple yaml into 1

---

memory/dma_memtest.py
memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py

Test error's out as mkdir fails as it already exists. Patch fixes it.

Fix dma_memtest for tmp dir creation

---

memory/dma_memtest.py
memory/stutter.py
memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py

Patch replaces mkdir to makedirs to support creation of mult-level directory.

Fix memory tests for multi-level makedirs

---

io/net/multicast.py

ensure that the multicasts to the peer will go via
this route from the test interface

This patch will add a multicast route to the peer to

---

cpu/cpustress.py

Some times the process gets killed while testing affinity as expected,
so kill command fails when process not found so ignore the sataus

Fix: ignore the kill command status

---

cpu/ppc64_cpu_test.py

In SLES 11, and could be with other older distros, the smt snooze
delay of cpu in sysfs is /sys/devices/system/cpu/.
Whereas in newer distros, it is /sys/bus/cpu/devices/.
Handled this in this commit.

Handling smt snooze delay for sles 11

---

generic/kdump.py
generic/pstore.py

some tests depend on virttest.remote
Reference: GH-754
Signed-off-by: kromer <florian.kromer@roboception.de>

add tag of remote only tests

---

memory/fork_mem.py
memory/fork_mem.py.data/Makefile
memory/fork_mem.py.data/fork_mem.yaml
memory/fork_mem.py.data/forkoff.c

Test has three scenarios each of which uses 85% of the free memory by creating processes and using some part of memory per process.

Added memory-fork test for memory sanity test

---

cpu/numatop.py

numatop compile failed due to a package install failure. Patch adds the package required

Fix numatop compilation

---

generic/stress-ng.py
generic/stress-ng.py.data/stress-ng-numa.yaml
generic/stress-ng.py.data/stress-ng.yaml

Stress-ng can be run with numa, patch adds the same

Add numa scenario in stress-ng

---

io/disk/bonnie.py
io/disk/disktest.py
io/disk/fiotest.py
io/disk/fs_mark.py
io/disk/ltp_fs.py
io/disk/tiobench.py

Some linux distros do not support certain filesystems. In such
cases, mount throws an error. Since that was not handled in the
test, test ERRORs out. So, handling the exception and failing
gracefully.
Also, taking care of cleaning the filesystem on the disk, in
tearDown()

Handling Exception when unable to mount filesystem

---

io/pci/PowerNVEEH.py

There was a mistake introduced in PowerNVEEH test with the last
commit in self.params.get, and this commit fixes it.

Fixed mistake in parameter reading in PowerNVEEH

---

generic/stress-ng.py

Fix workers yaml input
workers input was overwritten by number of processor. Instead changed the value as default value
Fix stress-ng errors and python standard
stress-ng had a joing typo, fixed it and changed script to adopt python standards
Signed-off-by: Harish harish@linux.vnet.ibm.com

Fix workers yaml input and stress-ng typo, standards

---

generic/stress-ng.py
generic/stress-ng.py.data/stress-ng-numa.yaml
generic/stress-ng.py.data/stress-ng.yaml

'numa' was used wrongly as class instead of stress. Handled a minor fix if either of the stressors are None

Fix numa as stressor instead of class

---

fuzz/trinity.py

Trinity test failed to get yaml input due to a typo, patch fixed the typo

Fix: trinity yaml input

---

memory/memory_api.py
memory/memory_api.py.data/Makefile
memory/memory_api.py.data/memory_api.c
memory/memory_api.py.data/memory_api.yaml
memory/memory_api.py.data/mremap.c

Patch adds memory_api tests from autotest. Modified code necessary to be architecture independent.
Source: https://github.com/autotest/autotest-client-tests/blob/master/memory_api/

Added memory_api test to check memory syscalls

---

toolchain/power_time_base_bug.py
toolchain/power_time_base_bug.py.data/Makefile
toolchain/power_time_base_bug.py.data/print_power_time_base.c

This test verifies whether valgrind power architecture time base
bug exists or not.
This applies to 'ppc64le' architecture.

Check for valgrind power arch time base bug

---

memory/hugepage_sanity.py
memory/hugepage_sanity.py.data/Makefile
memory/hugepage_sanity.py.data/hugepage_sanity.c
memory/hugepage_sanity.py.data/hugepage_sanity.yaml

This test uses mmap call to allocate and memset hugepages of supported sizes. By default uses default hugepage size allocating one page of it.

Hugepage sanity test to make use supported hugepages

---

generic/stress-ng.py
io/disk/ssd/nvme_cli_selftests.py
perf/libunwind.py
perf/perftool.py
toolchain/atlas.py
toolchain/gcc.py
toolchain/libvecpf.py
toolchain/valgrind.py

With build.run_make deprecating few optional parameters, tests are changed to adopt the deprecation

Fix: Tests using run_make parameters in utils/build.py

---

generic/ras.py

It makes more sense to skip a test altogether if possible.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

generic/ras.py: skip test instead of canceling it

---

kernel/kernbench.py
kernel/kselftest.py

Patch adds required packages for Ubuntu to compile kernel and compile selftests/vm tests properly

Fix kernel compile on Ubuntu

---

io/disk/lvsetup.py
io/disk/lvsetup.py.data/README
io/disk/lvsetup.py.data/lvsetup.yaml
io/disk/softwareraid.py
io/disk/softwareraid.py.data/softwareraid.yaml

Some tests support multiple disks as input from multiplexer
file. This commit makes this explicit, and differentiates it
from other tests which accepts only one disk as input.

Differentiate tests that support multiple disks

---

generic/stress-ng.py

Timeout stressors have a timeout calculated for variable stressors. Patch fixes adding --timeout needed to run the variable stressors.

Fix: timeout for variable stressors

---

memory/memhotplug.py
memory/transparent_hugepages_swapping.py
memory/vatest.py

With memory.MemInfo recent changes mb, kb has changed to m,k. This patch makes the changes needed in tests.

Fix: Adopt meminfo with avocado library fix

---

generic/sysbench.py
generic/sysbench.py.data/sysbench.yaml

as in powerpc64 bit system compilation of upstream branch is failing
so this patch address that issue as try to clone ppc64 specfic LuaJIT upstream
based on issue : https://github.com/akopytov/sysbench/issues/129

Fixed generic:sysbench test

---

cpu/cpustress.py

Do not put the sub-process into background,
otherwise the returned PID from threading.start()
is not the PID of the sub-process.
Later on when the test script tries to kill
the sub-process, kill fails with 'No such process'.
The sub-process will keep running when test finished.
Signed-off-by: Li Yi <liyiadam@gmail.com>

Fix issue that sub-process cannot be killed

---

io/net/infiniband/mofed_install_test.py.data/mofed_install_test.yaml
io/net/infiniband/mofed_install_test.py.data/mofed_install_test_nvmf.yaml

1. Moved the method to install mofed by default to last in yaml file.
2. Created a new yaml to install mofed only for nvmf, since that is
needed for nvmf tests.

Mofed install yaml changes

---

memory/sum_check.py
memory/sum_check.py.data/sum_check.yaml

Test creates a chunk of RAM size and checks its md5sum multiple times so that memory integrity is intact

Test for memory check using md5sum

---

io/disk/softwareraid.py
io/disk/softwareraid.py.data/Readme
io/disk/softwareraid.py.data/softwareraid.yaml
io/disk/softwareraid.py.data/softwareraid_setup.yaml

Adding metadata support to softwareraid tests.

Adding metadata support to softwareraid tests

---

io/disk/bonnie.py
io/disk/disktest.py
io/disk/fiotest.py
io/disk/fs_mark.py
io/disk/ltp_fs.py
io/disk/tiobench.py

I had induced a syntax error in self.fail after mkfs.
Fixing it.

Fix self.fail after mkfs failed

---

cpu/numactl.py

Most of the tests should succeed with https://github.com/numactl/numactl/pull/22. Though, in case of
failure this patch allows to continue with other tests.

numactl: Execute all tests without stoppage

---

io/net/infiniband/rdma_tests.py.data/ib_read_bw_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_read_lat_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_send_lat_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_write_bw_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_write_lat_extended.yaml

Some RDMA tests do not support certain parameters or combinations:
1. bidirectional is supported only on bandwidth test.
So removed it from latency test.
2. Duration > 2 * Margin.
So, -f 5s should have -D 11s atlease. Fixed that.
3. -D option was repeated, removed that.

Fixing options for RDMA tests

---

generic/stress-ng.py

* Add basic required packages
Stress-ng fails to compile without gcc, hence this patch adds basic packages to compile.
* Detect Hard LOCKUP after test
Appending Hard LOCKUP to the list of possible failures with stress-ng running

Basic packages addition and adding hard lockup dectection

---

memory/memhotplug.py
memory/memhotplug.py.data/Readme
memory/memhotplug.py.data/memhotplug.yaml

Test was unplugging whole free memroy making the system go hung, so
now user has option to specify % of memory to unplug. by default we have
5 % memory. Now we do not have OOM killers being called while test.
JOB ID     : 86da0d47189f331471727f3a1128d2f44947639b
JOB LOG    : /root/avocado-korg/korg/results/job-2018-04-12T06.05-86da0d4/job.log
(1/4) memhotplug.py:memstress.test_hotplug_loop: PASS (205.33 s)
(2/4) memhotplug.py:memstress.test_hotplug_toggle: PASS (104.39 s)
(3/4) memhotplug.py:memstress.test_dlpar_mem_hotplug: PASS (116.04 s)
(4/4) memhotplug.py:memstress.test_hotplug_per_numa_node: PASS (125.34 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 570.22 s
JOB HTML   : …

memhotplug.py: optimised to run for user specified memory ratio

---

memory/libhugetlbfs.py

This patch fixes fallocate headers for centos while building libhugetlbfs.
Fixes: #866

Fix: Apply fallocate patch for centos

---

memory/mprotect.py
memory/mprotect.py.data/Makefile
memory/mprotect.py.data/mprotect.c
memory/mprotect.py.data/mprotect.yaml

This test verifies mrpotect most pages of the free memory by read, write and accessing protected pages accordingly

Test to verify mprotect with data read, write

---

requirements-travis.txt

added pycodestyle version as ymal requirement

Added pycodestyle on yaml

---

memory/vatest.py
memory/vatest.py.data/va_test.c

Failure is suppressed as False positive in some cases where keyword is not found. Patch solves this issue.

Fix: Failure detection in vatest

---

memory/memhotplug.py

Test reports failure as dmesg prior to the start of tests has some keywords which is not cleared before starting the test

Clear dmesg before starting test

---

memory/numa_test.py
memory/numa_test.py.data/Makefile
memory/numa_test.py.data/numa_test.c
memory/numa_test.py.data/numa_test.yaml
memory/numa_test.py.data/util.c

This patch provides tests to exercise pages being moved between numa nodes using mbind and numa_move_pages. The compares the old PFN with the new PFN.

Test to exercise page move/bind between numa

---

io/pci/PowerVMEEH.py

PowerVMEEH is only supported on LPAR, so cancle when the system is baremetal
So we have a clean run for CI

PowerVMEEH: Skip eeh test on baremetal

---

generic/service_check.py

When the bare-metal machine is BMC than opal_errd service is not valid.
With Ubuntu 17.10 and later the 'networking' service is deprecated. one
has to use netplan going forward.
Removing 'networking' and 'opal_errd' in respective cases

BMC and Ubuntu check for service networking

---

io/net/scp_ssh.py

The /tmp/tmpfile is read as string and not converted to unicode on python2.7
so test is failing with this error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 18: ordinal
fixed to decode from str to unicode(UTF-8)

fix: add unicode param when file is read as string

---

memory/eatmemory.py
memory/eatmemory.py.data/eatmem_getch.patch

1) Fix: eat memory test patch apply
Existing patch does not apply properly. That too, is applied in the wrong location and does not serve the purpose of exiting from the application. This patch fixes it.
2) Use only maximum possible memory
Patch allows to use only maximum possible memory of the system as using total memory gets the process killed

 Fix: eatmemory test patch apply and use maximum possible memory

---

memory/ksm_poison.py
memory/ksm_poison.py.data/Makefile
memory/ksm_poison.py.data/ksm_poison.c
memory/ksm_poison.py.data/ksm_poison.yaml

Patch adds test to verify soft/hard offline with kernel samepage merging. As pages are offlined, only 10% of free memory is being used in the test

Add page poisoning test with KSM

---

generic/lshw.py

lshw output should not contain modified timestamp when -notime option is used.

Patch to fix -notime option failure.

---

kernel/rmaptest.py

prevents test to error out as process.system command failed

Fixed issue in rmaptest

---

memory/numa_test.py

1) Fix: numa_test ERROR's not handled
Patch prevents numa_test from error as process.system is handled
2) Handle pre-requisite for numatest
Patch skips numa_test from running on single numa node machines
3) Fix: Packages for numa_test
The existing packages were not handled properly for sles. Hence, fixed in this patch

Fix: Handle numa_test

---

io/disk/ssd/nvme_cli_selftests.py
io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml

NVMe cli selftest had imported pip to check the python packages
installed. This is not recommended.
So, changed it to use pkg_resources instead.

Fixed importing pip in nvme cli selftest

---

generic/service_check.py
generic/service_check.py.data/services.cfg

1) Fix: service_check syntax 
Test failed with the following error as it was trying to remove a list instead of a string
L0047 ERROR|     services_list.remove(['networking'])
L0047 ERROR| ValueError: list.remove(x): x not in list
2) Fix: newly changed SuSE service 
Patch fixes newly changed firewall service in SuSE versions higher
than 15.
3) Fix: Packages for SuSE services
Added packages for SuSE service failures as pre-requisite

Fix: service_check test

---

generic/ras_extended.py

bootlist test faild as the return code is 255.

Removed --help option test for bootlist

---

generic/ras.py

rtas_event_decode returns 17 even after successful run so removed check for return value 0.

Fixed rtas_event_decode failure.

---

io/net/uperf_test.py

With uperf release v1.0.6, the docs dir is renamed to manual.
https://github.com/uperf/uperf/compare/v1.0.6...master
Fixed with this commit.

Fix uperf xml dir change

---

io/net/virt-net/network_virtualization.py

mac id should be passed without the ':' in the HMC command.
So, removing it in the test.

Fix mac id param in vnic test

---

cpu/numactl.py
memory/numa_test.py

Patch adds pre-check for few tests which requires NUMA memory nodes with newer avocado API

Add check for numa tests

---

memory/hugepage_sanity.py

Patch fixes the following error, as default value is missing when test is executed without any inputs.
ValueError: invalid literal for int() with base 10: ''. This patch fixes it.

Change default parameter values for standalone test execution

---

io/disk/fs_mark.py.data/fs_mark.yaml

Default yaml file parameter was '' instrad of Null.
Fixed that.

Changing the default yaml file param to be empty

---

io/disk/ssd/nvmetest.py

NVM Subsystem Reset is not supported in all nvme controllers.
So, added a check and skipped the test if not supported.

Added check for NVM Subsystem Reset

---

generic/diag_encl.py

This test verifies '-d' option of diag_encl. It checks whether single xml file is generated when "diag_encl" command is run multiple times and validates xml content.

Test to verify diag_encl - v4

---

fs/flail.py
fs/xfstests.py
fuzz/fsfuzzer.py
generic/connectathon.py
generic/interbench.py
generic/ltp.py
generic/ras.py
generic/service_check.py
generic/servicelog.py
kernel/posixtest.py
kernel/tlbflush.py
memory/eatmemory.py
memory/fork_mem.py
memory/hugepage_sanity.py
memory/integrity.py
memory/ksm_poison.py
memory/libhugetlbfs.py
memory/memory_api.py
memory/mprotect.py
memory/numa_test.py
memory/vatest.py
perf/blogbench.py
perf/lmbench.py
toolchain/ltrace.py
toolchain/power_time_base_bug.py

This patch replaces self.datadir with self.get_data() as former is deprecated. This patch addresses 25 such tests across fs, fuzz, generic, kernel, memory, perf, toolchain.

Fix: Replace self.datadir with self.get_data()

---

cpu/ebizzy.py
cpu/linsched.py
io/disk/dbench.py
io/disk/disktest.py
io/disk/fiotest.py
io/disk/iozone.py
io/nvmf/nvmftest.py

datadir is deprecated. get_data() should be used instead.
commit id: 53445a82cf37905a57b4aad958b3000c33ed64ff
https://github.com/avocado-framework/avocado/commit/53445a82cf37905a57b4aad958b3000c33ed64ff
Fixed it for cpu and io tests.

Handle the depracation of datadir for cpu and io tests

---

io/pci/PowerNVEEH.py
io/pci/PowerVMEEH.py

EEH Recovery is not similar for all adapters. For some adapters,
specifically multipath, we see that the adapter needs some more
time to recover after the message "Notify device driver to resume"
on the dmesg.
There is no reliable way to determine this extra time required,
nor a way to determine the recovery. So, a sleep time of 10s is
introduced.

Adding a sleep time for EEH recovery

---

io/driver/module_unload_load.sh

AVOCADO_TEST_DATADIR is deprecated.
Fixed its usage in module_unload_load test.

Fixing the usage of deprecated DATADIR

---

cpu/ppc64_cpu_test.py

1) ppc64_cpu: Change bash commands to python native code
This patch changes bash commands to python native code and reduces execution time.
2) Fix: dscr test 
dscr_default file has a hex value and hence the comparison fails. This patch fixes it.
3) Fix pylint issues

 ppc64_cpu: Fixes and enhancements

---

memory/numa_test.py
memory/numa_test.py.data/Makefile
memory/numa_test.py.data/numa_test.c
memory/numa_test.py.data/numa_test.yaml

With this patch, test optionally allows hugepages to be set and migrated between available numa nodes

Enhance numa migration test with huegpage

---

memory/vatest.py

1) Check MMU for setting different page sizes 
Patch checks for MMU rather than the previous implementation of check of different architecture. This allows machines with hash page table to run properly irrespective of the sub-arch.
2) Check 16G hugepage as default
This patch checks whether 16G hugepages is default, elsewhere it cannot be configured and used. So check and skip scenarios which are not applicable.
3) Fix pep8 and pylint issues

vatest: Detect MMU and configure test

---

cpu/ppc64_cpu_test.py

Seperated the ppc64_cpu tests into test_params and test_smt_loop.

Seperate the ppc64_cpu tests

---

io/net/infiniband/mofed_install_test.py.data/mofed_install_test.yaml

MOFED comes with a file which gives information on the distro
supported. Using that in the yaml parameter.

Using supported distro for MOFED install test

---

io/net/infiniband/ib_pingpong.py
io/net/infiniband/ip_over_ib.py
io/net/infiniband/mckey.py
io/net/infiniband/ping6.py
io/net/infiniband/rdma_tests.py
io/net/infiniband/rping.py
io/net/infiniband/ucmatose.py
io/net/infiniband/udaddy.py

SLES 15 has a different firewall disable command than SLES 12.
So, handling the differences with this commit.

Handling firewall command for sles 15

---

memory/libhugetlbfs.py

Fixed libhugetlbfs test 
1-change self.error to self.cancle
2-Removed  root privilege check and used avocado lib param for this
3- added ignore_status=True as a param in process.system to aviod
to error out script when command failed

Fixed libhugetlbfs test

---

io/net/net_data.py

Ubuntu18.04 (bionic) does not support ifdown and ifup commands by default.
So instead of ifup and ifdown we can carry out same functionality using
"ip link" command. changed the same in the net_data.py script and it is
working fine.

Replacing ifdown and ifup with "ip" command.

---

cpu/ebizzy.py

Patch fixes getting file from datadir, which already had been obtained using get_data method.

Fix: ebizzy test to get file from datadir

---

cpu/em_smt_folding_test.py
cpu/em_smt_folding_test.py.data/Fix-build-issues-with-ebizzy.patch

SMT folding is achieved through hotplug.To verify this test, the script runs ebizzy workload
when SMT is off and when SMT is on. Observe the records generated for single thread for 60s on
one cpu.Expected is single thread performance is better then multi thread and it is proved by
comparing the records generated.To observe better results, the script disables all the idle states
before running ebizzy using cpupower tool.
: Shriya Kulkarni	<shriyak@linux.vnet.ibm.com>

Throughput test for SMT folding in presence of swizzle

---

perf/perftool.py

Fixed perftool test
1- fixed pep8 issue
2- added gcc-c++ as prerequisite package as some of perf test require g++
LOG:
[stderr] make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[stdout] ## [ PASS ] ## perf_mem :: cleanup SUMMARY
[stderr] make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[stderr] /bin/sh: g++: command not found
[stderr] /bin/sh: g++: command not found
[stderr] /bin/sh: g++: command not found
[stderr] /bin/sh: g++: command not found
[stderr] /bin/sh: g++: command not found
[stderr] /bin/sh: g++: command not found
[stderr] /bin/sh: g++: command not found
[stderr] make[1]: *** [Makefile:21: test_opts] Error 127

Fixperftool

---

io/net/net_data.py.data/net_data_virt_net.yaml

Virtual Network devices do no support MTU values other than
1500 and 9000.
So, created a separate yaml for virtual network devices.

Jumbo Frames yaml for Virtual Networks

---

kernel/kernbench.py
kernel/kselftest.py

Compilation fails on SuSE distros due to lack of few packages. This patch fixes it.

Fix compilation fail on SuSE distros

---

cpu/em_quad_level_frequency_transitions.py
cpu/em_quad_level_frequency_transitions.py.data/em_quad_level_frequency_transitions.yaml

In Power 9, when one of the cpu's frequency is set to maxmimum or higher than other cpus beloging
to same quad,then complete quad will be set to max frequency irrespective of the frequency on
other cpus.This test will set the governor to userspace, and randomly set the frequency on each cpu.
Maximum frequency set for each quad is recorded  and it will be verfied by running perftool on each cpu
to monitor the cycles, which will give frequency count as same as maximum frequency recorded for that
quad.

validate quad-level frequency transitions

---

kernel/kernbench.py

bison, flex packages names are common across distributions. Move them
to common dependencies list.

kernelbench.py: Move bison, flex to common dependencies

---

memory/eatmemory.py

The test doesn't install any distro specific packages, so
remove the variable and its import too.

memory/eatmemory: Remove unused variable/import

---

cpu/cpustress.py

Remove the unused list variable output.

cpu/cpustress: Remove the unused list variable

---

cpu/ebizzy.py

Remove the unused variable 'logfile'.

cpu/ebizzy: Remove unused variable logfile

---

io/pci/pci_hotplug.py

cpuinfo is read from '/proc/cpuinfo', instead of executing the command
to read it. So remove the unused variable.

cpu/pci_hotplug: Remove unused variable 'cmd'

---

kernel/kernbench.py

Fix the spelling of 'bulding' -> 'building' in the time_build()
description.

kernel/kernbench: Fix trivial spelling mistake

---

generic/stress-ng.py

Fix the typo in the test failure message.

generic/stress-ng: Fix test failure message

---

fs/fsshrink.py

This patch removes depricated datadir from fs/fsshrink.py
With out patch job run will error out:
(1/1) fs/fsshrink.py:Fsshrink.test: ERROR (0.00 s)
With patch job run will continue with out errors:
(1/1) fs/fsshrink.py:Fsshrink.test: PASS (123.51 s)

fs/fsshrink.py: Remove depricated datadir

---

ras/hwinfo.py

Fixed hwinfo test
1- fixed pep8 issue
2- change self.error to self.cancel as if hwinfo package is not installed test should not error out

Hwinfo test 

---

cpu/cpustress.py
fs/flail.py
fs/fs-fuzz.py
fs/fsshrink.py
generic/stress-ng.py
generic/sysbench.py
io/disk/mvcli_test.py
io/genwqe/genwqetest.py
memory/memhotplug.py

dmesg buffer is cleared '-c', as well as with '-C'. Whereas the latter
does not prints the contain of dmesg before clearing it, while '-c'
prints the dmesg buffer before clearing it. We are not interested in
the dmesg before the test run's so convert the switch from '-c' to '-C'.

Convert dmesg switch '-c' to '-C'

---

ras/sosreport.py

Mute output from commands, those outputs are not parsed, like '-h help'
switch(s). We are only worried about the exit status of such commands
and as the side effect, the job.log is uncluttered with the
non-interesting information.

ras/sosreport: Mute unparsed output from commands

---

ras/perf.py

This testcase verifies the following perf subcommands:
- help
- version
- list
- record
- report
- kallsyms
- annotate
- evlist
- stat
- bench
Additionally executes the builtin test benchmark

ras/perf: Add perf tool testcase

---

io/disk/htx_block_devices.py

Currently excerciser getting shut down is hardcoded, fixing it.
Signed-off-by: Srikanth Aithal <sraithal@linux.vnet.ibm.com>

Shutdown right HTX exerciser

---

io/disk/htx_block_devices.py

"ppc64_cpu --smt" command doesn't accept any arguments, rather prints
the current '--smt' state. This patch removes the argument from the
command to be executed.

io/disk/htx_block_devices: Fix run_smt function

---

io/disk/mvcli_test.py
io/net/vlan_test.py
ras/kdump.py
ras/kdump_nfs.py
ras/lshw.py
ras/pstore.py
ras/servicelog.py

This series converts the non-class specific functions into staticmethod, mostly converts `run_cmd_out()` into staticmethod, expect for ` io/net/vlan_test.py` where another function `ping_check_host()` can also be converted into staticmethod. This series is inspired by review comments from pull request #1000

[RFC] Convert non class member as static methods

---

ras/sosreport.py

Refactor the sosreport, to group them into individual tests such as
basic short test, user define test from yaml file, plugins test,
archive test and so on.
Functionally there is no change expect for skipping Power testcase, if
the underlying platform is not 'PPC'.

ras/sosreport: Refactor into individual testcases

---

ras/kprobe.py

This patch adds test the kprobe functionality of the kernel. The
kprobe functionality is tested by:
1. Creating a kernel module from the
<kernel-src>/samples/kprobe/kprobe_example.c
2. Load the module a.k.a planting the kprobe in do_fork syscall
3. Execute 'date' command to invoke do_fork syscall
4. Unload the module a.k.a unregister the kprobe

ras/kprobe: Add kprobe testcase

---

kernel/kselftest.py
kernel/kselftest.py.data/kselftest.yaml

This patch enables self-tests to be run from source of different distributions. Each distribution source fetching and preparation differs, which is handled in this patch.
This patch also introduces an input to run upstream/distro source selftests.

Run kernel self-tests from distribution source

---

kernel/livepatch.py

This patch add the testcase to verify the basic livepatching
functionality of the kernel. The verification is done by:
1. Checking if the current kernel supports livepatching
2. Build the livepatch-sample kernel module, the source of the
module is downloaded from:
kernel-src/samples/livepatch/livepatch-sample.c
3. Enable the livepatching for the function, which patchs
/proc/cmdline
4. Verify the ouput from 'cat /proc/cmdline'
5. Disable the livepatching for '/proc/cmdline'
6. Again verify if the 'cat /proc/cmdline' output for unpatching

kernel/livepatch: Add kernel livepatching testcase

---

perf/perf_events_crash_test.py

Perf event test suite also host the testcases to crash the running
unpatched kernel against know issues. This patch adds the test from
the test suite to check any know regression, still unfixed in the
kernel.

perf/perf_events_crash_test: Add crash test

---

perf/perf_events_test.py

Use the genio methods to read/write into `/proc` file, instead of
run_cmd_out and return by testcase cancel instead of error'ing out.

perf/perf_events_test: Use genio to read/write file

---

kernel/kernbench.py

To maintain the consistency across testcases, have the testcase get and
untar code in the setup. In this case, the linux source is the testcase.
So move the get and untar of linux archive to setup code.

kernel/kernbench: Move the linux archive untar to setup

---

toolchain/bcc.py

Fix a trivial typo in the error message 'Upsupported' -> 'Unsupported'.

toolchain/bcc: Fix the typo in error message

---

generic/connectathon.py
generic/criu.py
generic/stress-ng.py
perf/hackbench.py
ras/kdump.py
ras/ras.py
toolchain/libvecpf.py

To maintain consistency across all the testcases, convert the error to
cancel if the package dependency is not meet.

Convert error to cancel for package installation failure

---

ras/uprobe.py

This patch adds the uprobes test:
1. Find for the libc's malloc function
2. Clear the ftrace buffer
3. Plant a uprobe from the address located by step 1
4. Execute bash commands
5. Check ftrace buffer if the uprobe was hit
6. Clear the ftrace buffer and un-plant the uprobe

ras/uprobes: Add uprobes test

---

perf/perf_genericevents.py
perf/perf_genericevents.py.data/raw_code.cfg

This patch series is motivated by #911, Where the raw code events file is adopted from it with a minor addition of event code for `mem_access` on `POWER8`. `perf_genericevents` file, will use the raw code events file in the second commit, instead of using the hard coded value. Each commit message explains in details about the changes made by the commits.

perf/generic_events: Add support for POWER9 events

---

fs/blktests.py

Use the inbuilt the genio library to write into /proc/, instead of
passing the command via system().

fs/blktest: Use inbuilt genio to write into /proc

---

memory/numa_test.py

This patch fixes hugepage file path which misses a '/' in page migration test.

Fix: hugepage file path in page migration test

---

perf/perftool.py

This patch corrects the variable scope.
With out this patch, the test case errors out saying self object
doesn't contain attribute named 'count'.

Corrected variable scope

---

generic/stress-ng.py

Remove unnecessary package for building stress-ng, Also some rhel and sles releases does not provide it.

Remove unnecessary package for building stress-ng

---

generic/ltp.py.data/ltp.yaml

aadmin_tools tests are removed from ltp
Reference : https://github.com/linux-test-project/ltp/commit/0fc9b8624bea8acfdb408bf5ff4916b1453e3daa
signedoff-by: spoorthy@linux.vnet.ibm.com

Removing aadmin_tools tests from ltp

---

memory/eatmemory.py

eatmemeory test requires 'patch' package to be installed in the system
Hence added patch to the dependency package list
signedoff-by: spoorthy@linux.vnet.ibm.com

Fixing eatmemory test failure

---

io/disk/fs_mark.py

fs_mark binary requires the mount dir length to be less than
40 characters. But avocado workdir is longer. To handle this,
we create a symbolic link to the workdir and provide that as
input to fs_mark command.

Handling mount dir on fs_mark test

---

generic/ltp.py
generic/ltp.py.data/ltp.yaml

1-Fix Ltp test as runltplite.sh removed from LTP upstream code 
2-change error to cancel as if package condition not match script error out
so changing to cancel

Fix ltp test

---

cpu/ppc64_cpu_test.py

On a POWER9 machine different SMT levels are supported based on the environment.
On PowerVM LPAR runing Linux SMT8 is supported while SMT4 is supported with Linux running in non virtualized mode.
This patch Adds support for POWER9 PowerVM LPAR.
SMT8 is supported inside POWER9 PowerVM LPAR running Linux.

ppc64_cpu: Add support for POWER9 PowerVM config

---

cpu/em_smt_folding_test.py

ebizzy returns the throughput followed with records/s, this
needs to be parsed using split syntax than splitlines to
get only the throughput.

fixed ebizzy output parsing

---

perf/perf_uprobe.py
perf/perf_uprobe.py.data/Makefile
perf/perf_uprobe.py.data/uprobe.c

Adding uprobe test cases to test the following scenarios
test_uprobe
test_uprobe_return
test_uretprobe_variable

perf: Adding uprobe test cases with perf command

---

perf/perf_basic.py

Removed 'perf test' test case as it is already handled well in
perftool.py

Remove 'perf test' test case

---

memory/libhugetlbfs.py

unmounting failed with
TypeError: range() integer end argument expected, got list.
This patch fixes the above issue.

Fix issue with unmounting page pools

---

fs/xfstests.py

indent package support drop from RHEL8 so removing this from
required list of package

Fixed fs:xfstest

---

ras/hwinfo.py

Split in to different tests.
Earlier under one tests all the commands were run, now each and every
command runs in different test.

hwinfo.py: split in to different tests

---

cpu/sensors.py

fixed cpu:sensors as avocado:utils:linux_modules.check_kernel_config
return ModuleConfig enum

Fixed cpu:sensors test

---

io/pci/dlpar.py
io/pci/dlpar.py.data/README
io/pci/dlpar.py.data/dlpar.yaml

HMC, LPAR Name, Server Name are found out using lsrsrc now.
So, users no longer need to provide these informations.

Using lsrsrc to get HMC and Server details

---

io/disk/ssd/nvme_cli_selftests.py
io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
io/disk/ssd/nvmetest.py
io/disk/ssd/nvmetest.py.data/README.txt
io/disk/ssd/nvmetest.py.data/nvmetest.yaml

Previously NVMe tests required to get:
1. device name (/dev/nvme0)
2. namespace id (1, 2)
The logical way to do is, get the
1. interface name (nvme0) and use it instead
2. find the namespace on the interface, and skip if none exists.
This commit takes care of these changes for 2 of the nvme tests.

Using interface name for nvme test

---

io/disk/htx_block_devices.py
io/disk/htx_block_devices.py.data/Readme.txt
io/disk/htx_block_devices.py.data/htx_all_devices.yaml
io/disk/htx_block_devices.py.data/htx_block_devices.yaml

1.    Enabling running HTX for all disks possible
Sometimes, we need to run HTX for all disks in the system.
This commit enables this functionality, via a yaml parameter.
2.    Fix htx_block_devices test
* Made the test to build open-power/HTX for all distros.
* Handle SMT change case for all code blocks.
* Minor fixes

Fix htx_block_devices test

---

generic/rcutorture.py
kernel/livepatch.py
ras/kprobe.py

Adopt linux_modules API changes
ModuleConfig.NOT_SET
to test scripts
generic/rcutorture.py
kernel/livepatch.py
ras/kprobe.py

Adopt linux_modules API changes

---

kernel/livepatch.py
ras/kprobe.py
ras/kretprobe.py

Corrected kernel-syms package name in the following files
kernel/livepatch.py
ras/kprobe.py
ras/kretprobe.py

Correct kernel-syms name

---

io/net/bonding.py.data/bonding_infiniband.yaml
io/net/bonding.py.data/bonding_virtual.yaml

Infiniband supports only active backup bonding mode.
Virtual networks support only active backup and 802.3ad bonding
modes.
So, adding yaml files for them.

Bonding yaml for infiniband and virtual networks

---

io/pci/dlpar.py
io/pci/dlpar.py.data/README

Since ibmtool is no longer working/available for install rsct and
DynamicRM package installation for dlpar operation, I have added the
the package names and thier install check skipping the ibmtool.

Changing the method of rsct package installation for dlpar

---

memory/hugepage_sanity.py

Patch modifies system supported default hugepage size as default hugepage size instead of hard coding it.

Use system supported hugepage size as default hugepage size

---

io/net/netperf_test.py.data/netperf_test.yaml

Some of the yaml parameters were not compatible with each other.
600s run for netperf and 5 iterations were not completed before
600s timeout.
Also, the netserver_run parameter is set to 1 by default.

Change the netperf test yaml parameters

---

generic/htx_test.py

Some exercisers like hxecapi, hxeocapi, hxedapl have dependent library packages, which are not available in some distros. To handle it, we are ignoring those packages during HTX compilation
Adopted from io/net/htx_nic_devices.py

Building HTX with only needed exercisers

---

io/net/uperf_test.py

uperf test had 2 issues:
1. compilation failed due to dependency package automake
2. run failed due to change in directory.
Fixed both with this commit.

Fix uperf test

---

memory/hugepage_sanity.py.data/hugepage_sanity.c

minor fix to add the missing braces, commit 7a4b8a introduced
to return -1 appropriately on failure but missed the braces.
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

hugepage_sanity.c: fix the missing braces

---

perf/perf_uprobe.py

Adjusting test script to run on latest RHEL7 release
with out patch:
ERROR: Command 'perf record -o /var/tmp/tmpYdXQv_ -e
probe_uprobe_test:doit ar ./uprobe_test' failed.
\nstdout: ''\nstderr: "event syntax error: 'probe_uprobe_test:doit'\n
\\___ unknown tracepoint\n\nError:\tFile
/sys/kernel/debug/tracing/events... (1.15 s)

perf_uprobe Adjusting for latest RHEL7

---

io/net/htx_nic_devices.py

dapl-devel is provided by MOFED, which is not installe via any
repositories, rather MOFED installs all needed packages.
So, we only build HTX with hxedapl on such systems where
dapl-devel is installed via MOFED.

Building HTX with hxedapl on supported systems

---

io/disk/ssd/nvmetest.py

Subsystem reset support is mentioned differently in the nvme
controller register. So, handling it.

Subsystem reset support fix for nvmetest

---

io/net/bonding.py
io/net/bonding.py.data/README.txt
io/net/bonding.py.data/bonding.yaml
io/net/bonding.py.data/bonding_infiniband.yaml
io/net/bonding.py.data/bonding_single.yaml
io/net/bonding.py.data/bonding_virtual.yaml

Bonding test needed input interfaces as host_interfaces, which is
now changed into bond_interfaces.
This is needed, since when we run multiple tests with bonding,
and if they need to run on the bond interface created, then the
parameter name on bonding test and other tests need to be
different.

Changing bonding interface parameter in yaml

---

io/disk/softwareraid.py
io/disk/softwareraid.py.data/Readme
io/disk/softwareraid.py.data/softwareraid_cleanup.yaml
io/disk/softwareraid.py.data/softwareraid_setup.yaml

Softwareraid test creates raid devices only by the name
/dev/md/mdsraid. So, we are making it take the raid name from
the user via yaml, and defaults to /dev/md/mdsraid.

Make softwareraid test accept user given raid name

---

memory/transparent_hugepages.py
memory/transparent_hugepages.py.data/transparent_hugepages.yaml

* Use library functions to fetch machine configuration
Patch replaces library functions to fetch machine configuration
* Provide ways to run thp test with input parameters
Patch provides ways to run thp tests with custom inputs which also provides a way
to use the test when system memory is fragmented and existing memory could not be
used with dd operation.

Use library functions & provide input parameters in THP test

---

io/disk/lvsetup.py
io/disk/lvsetup.py.data/lvsetup.yaml

Removing the necessity to provide a lv size, ramdisk size, etc
by calculating them, if not provided in yaml.
In case disk is not provided, lvsetup creates a loop device, for
which case also this behaviour is same, by defaulting it to 1G.

Disk size enhancement for lvsetup

---

memory/sum_check.py

* Fix: Wrong unit reported for disk space
Patch fixes wrong report of disk space needed after comparison with system memory
* sumcheck: Use free memory instead of total memory
Patch replaces free memory instead of total memory as there is a risk of reaching "out of memory" when write exceeds existing free memory which in some cases could be less than 90 percent of total memory

 Fix: unit reported for disk space & replace total memory with free memory

---

generic/interbench.py
generic/stress-ng.py
io/disk/disktest.py
memory/fork_mem.py
memory/memcached.py
memory/memory_api.py
memory/memtester.py
memory/mprotect.py
memory/numa_test.py
memory/stutter.py
memory/transparent_hugepages_defrag.py
perf/stress.py

Patch makes memory library usage uniform across tests which avoids unwanted calculations and provides better readability

Use memory.meminfo library to avoid memory derivations

---

io/net/htx_nic_devices.py
io/net/htx_nic_devices.py.data/README.txt
io/net/htx_nic_devices.py.data/htx_nic_devices.yaml

Split the htx_network test into start, check, stop, so that the
test can be start to make HTX run in background and other tests
can be run in parallel, and HTX can be stopped later.
test_check can be used whenever necessary, to check if HTX is
still running in the background.

Split the htx_network test into start, check, stop

---

kernel/kselftest.py

* Add package required for few selftest compilation
Patch adds a package required for few tests which fails with -lpopt missing on RHEL based distributions
* Remove older "redhat" distro name
Remove older "redhat" distro name as it is no longer required

Add package required and remove older distribution name

---

io/disk/htx_block_devices.py
io/disk/htx_block_devices.py.data/Readme.txt
io/disk/htx_block_devices.py.data/htx_all_devices.yaml
io/disk/htx_block_devices.py.data/htx_block_devices.yaml

1. Separate HTX test into start, check (monitor), stop. This
allows us to start HTX in the background, and run other tests,
and stop when done.
2. Since this voids the SMT test being done as part of HTX, we
are removing that.
3. disk param is renamed to htx_disks as we need a way to
differentiate the disks for htx and disks for other tests.

Separate HTX test into start, check and stop

---

generic/htx_test.py
generic/htx_test.py.data/htx_test.yaml

This allows us to start HTX in the background, and run other tests and stop when done.
Since this voids the SMT test being done as part of HTX, we are removing that.

Split HTX to start, check and stop tests

---

memory/memory_api.py

Patch splits memory syscalls and memory remap tests for better accountability

Split memory syscalls API tests

---

io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
io/disk/ssd/nvmetest.py
io/disk/ssd/nvmetest.py.data/README.txt

Add namespace creation tests for nvme. This involved methodising
some of the code snippets we have for re-usability.

Add nvme namespace create tests

---

generic/ltp.py

numa bucket in LTP fails with
test requires libnuma >= 2 and it's development packages
Patch installs and enables numa tests to be run

Fix: Install package for numa tests to run

---

generic/htx_test.py
generic/htx_test.py.data/htx_test.yaml

Patch removes leftover SMT details in HTX

Remove SMT specific details

---

memory/memcached.py

Patch adds fedora support for memcached test

Add fedora support for memcached test

---

generic/htx_test.py
generic/htx_test.py.data/htx_mem.yaml

Patch provides a way to skip tests if the specified mdt is not generated and subsequent monitor would also skip.
Currently monitor and stops test runs even if MDT is not available. This patch addresses it.

Fix: Handle HTX test run based on mdt availability

---

ras/lshw.py

lshw.py: correct iproute package name for SuSE

---

memory/stutter.py

Patch fixes issue with setting environment variable which expects
string argument.

stutter.py: corrected int variable to string

---

memory/ndctl.py
memory/ndctl.py.data/ndctl.yaml

Test adds basic set of tests for ndctl userspace tool which covers listing DIMMs, busses and enabling, disabling regions

Add basic set of tests for ndctl userspace tool

---

io/net/netperf_test.py

Netperf tests was showing results in numeric values. This patch
will display output in percentage format.
Signed-off-by: Bismurti bidhibrata pattjoshi <bbidhibr@in.ibm.com>

Formating output of netpref in percentage

---

toolchain/gdb.py

texi2html package is not supported in suse

gdb.py:in Suse removed texi2html package

---

generic/stress-ng.py

After stress runs, on newer distro kernels the Hard lockup pattern has changed.
eg. hard LOCKUP @ _raw_spin_lock_irq+0x20/0xe0
This patch allows to support new and old kernel lockups

Fix: hard lockup detection after stress

---

kernel/livepatch.py

In SuSE openssl-devel package is shipped as libopenssl-devel.

livepatch.py: Corrected openssl-devel package name

---

perf/perf_24x7_all_events.py

On any machine Power8 or Power9 dynamically get all HV_24x7
events and according to the event's syntax fill the details and
run them.

perf run all hv_24x7 events

---

memory/libhugetlbfs.py

The test would fail if run inside VM as hugepages are
hardcoded for PowerNV, query the supported hugepage sizes
to proceed for test.
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

memory/libhugetlbfs: get supported hugepage sizes

---

perf/perf_hv_gpci.py

This patch adds tests of hv_gpci events. These events are generated
dynamically and run then using 'perf' command.

Perf: Adding hv_gpci tests

---

cpu/cpupower.py
cpu/em_cpufreq.py

In PowerVM cpufreq is not supported
so changed the script that cpufreq supports only in PowerNV environment

cpupower.py: cpufreq feature only supported on PowerNV

---

io/net/netperf_test.py

Netperf tests was showing results in numeric values. This patch
will display output in percentage format.
Signed-off-by: Bismurti bidhibrata pattjoshi <bbidhibr@in.ibm.com>

[v2] Formating output of netpref in percentage

---

cpu/sensors.py

Checking PowerVM/PowerNV early in the test, by that with out
installing the packages can take decision on to continue/cancel
the test.

sensors.py: checking machine type early

---

perf/perf_nest_events.py

Adding nest event test case.
Dynamically collect all the nest events using 'perf list' and
run them using 'perf stat'.

Perf: Adding nest event test case

---

kernel/kselftest.py
kernel/kselftest.py.data/kselftest.yaml

RHEL provides a kernel-alt for few of the architectures like PPC and ARM. This patch adds support for detecting such environment and using the kernel source name accordingly

Add kernel-alt source package name

---

kernel/kselftest.py

Removing popt package name for SuSE, because it is no longer
shipped with the latest versions

kselftest.py: removing unwanted package for SuSE

---

memory/numa_test.py
memory/numa_test.py.data/numa_test.c
memory/numa_test.py.data/util.c

Before the actual tests starts, there may be failures owing to the existing environment. Patch skips the test rather than reporting a false failure.

Cancel tests if enviroinment is not suitable

---

memory/ndctl.py

Test verifies metadata for sector mode namespaces using ndctl check-namespace command

Add test to check metadata for sector mode namespaces

---

generic/ltp.py

Patch adds package required for basic utilities like killall which is used in ltp

Add package required for basic utilities used in ltp

---

kernel/kselftest.py

Fix: Missing braces in kernel selftests
Commit 25c5c9 introduced an issue with braces missing when an
asset is fetched. Patch fixes it
Fix: SuSE distribution selftest runs
SuSE with its recent distributions does not install dependency
packages to be installed when using kernel-source as package name.
Patch fixes it by adding a kernel-default source installation.

Fix: kselftest.py missing brace and SuSE source installation 

---

generic/ltp.py
generic/ltp.py.data/ltp-mem.yaml

Patch adds necessary changes to run few memory tests which needs setup before actual test execution.

Add memory specific changes to LTP

---

io/net/virt-net/lpm.py
io/pci/dlpar.py

LPAR names are usually appended with string which identifies the
usage / user of the LPAR. With the recent code change finding
LPAR name with lsrsrc, such LPAR names are ignored and test
cancels. This commit handles such strings appended and gets the
LPAR name.

DLPAR: Finding LPAR name when string is appended

---

fs/xfstests.py

Test failed to run when test_range is specified as the create_list method does not return any value here
self.test_list = self._create_test_list(self.test_range)
Patch fixes it by returning the test list

Fix: xfstests.py for proper test_range

---

generic/stress-ng.py

Rectified existing flow on processing dmesg
1-In Test There is no operation perform on collected dmesg
so removed duplicated logic to perform dmesg operation
and used already collected dmesg
2- Removed global variable to hold dmesg output as it waste
of heap memory
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com

Rectified existing flow on processing dmesg in stress-ng test 

---

io/disk/softwareraid.py
io/net/tcpdump.py
io/pci/pci_hotplug.py
memory/memhotplug.py
ras/kdump.py
ras/kdump_nfs.py

Patch replaces print statements to log.info so that we can avoid both python2 and python3 compatibility

Change print statements to log.info

---

memory/ndctl.py
memory/ndctl.py.data/ndctl.yaml

Add test to create namespaces with different modes with single region

Add test to create namespaces with different modes with single region

---

fs/xfstests.py
fs/xfstests.py.data/nvdimm.yaml
fs/xfstests.py.data/nvdimm_log.yaml

Patch adds support to run Xfstests suite with NVDIMM devices on power architecture

Add support to run xfstests on nvdimm devices power

---

io/net/infiniband/rdma_tests.py.data/ib_read_bw_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_read_lat_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_send_bw_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_send_lat_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_write_bw_extended.yaml
io/net/infiniband/rdma_tests.py.data/ib_write_lat_extended.yaml

-x option is part of input file to run rdma tests. The help states
-x, --gid-index=<index>  Test uses GID with GID index (Default : IB - no gid . ETH - 0)
current values were -x=1 which is invalid.  Removing the option as it is creating more confusions during the tests.

Addressing the -x error during rdma tests

---

io/net/infiniband/ip_over_ib.py
io/net/vlan_test.py

In two file replacing ifconfig commands with ip commands.

Replacing ifconfig commands with ip commands

---

io/net/infiniband/ib_pingpong.py.data/README.txt
io/net/infiniband/ib_pingpong.py.data/ib_pingpong.yaml
io/net/network_test.py.data/network_test_infiniband.yaml

network mtu yaml has been created for infiniband specific MTU sizes and also -s option is made generic for all MTU sizes.
going forward using cfg file would enable covering different MTU size tests for each pingpong tests.

Cover different MTU size based test for pingpong -v2

---

perf/perf_c2c.py
perf/perf_c2c.py.data/record_report.yaml

Adding tests of 'perf c2c' command with main options namely
record, report with all possible arguments through yaml file

perf_c2c.py: Adding perf c2c tests

---

memory/ndctl.py

Patch fixes size variable in ndctl test

Fix: size variable in ndctl test

---

perf/perftool.py

as if command failed test error out and next block of test not at able to execute so adding
igonre_status=True in process.run
without patch:
19:05:59 INFO    : Running: /usr/bin/avocado run  avocado-misc-tests/perf/perftool.py --force-job-id 1a69a2ba6a8609322110aa064d6f895551fa1cad
JOB ID     : 1a69a2ba6a8609322110aa064d6f895551fa1cad
JOB LOG    : /home/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/results/job-2019-07-23T19.06-1a69a2b/job.log
(1/1) avocado-misc-tests/perf/perftool.py:Perftool.test: ERROR: Command 'perf test' failed.\nstdout: ''\nstderr: " 1: vmlinux symtab matches kallsyms            : Skip\n 2: Detect openat syscall event                : Ok\n 3: Detect openat syscall event on all cpus    : Ok\n 4: Read samples using the mmap interface     ... (29.57 s)
RESULTS    : …

Fix perf:perftool 

---

memory/dma_memtest.py
memory/fork_mem.py
memory/memhotplug.py
memory/ndctl.py
memory/sum_check.py
memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py
memory/transparent_hugepages_swapping.py
memory/vatest.py

Move memory tests to run with python3.
Tested on latest RHEL and SuSE releases.

[python3] Move memory tests to run with python3

---

cpu/em_cpufreq.py

cpu/em_cpufreq.py tests fails to run on PowerNV with following message:
SKIP 1-cpu/em_cpufreq.py:Cpufreq.test -> TestSkipError: This test is not supported on PowerVM platform
This test was written to run on PowerNV. The logic to detect PowerNV platform
does not work. This patch corrects it.

Fix environment detection logic for em_cpufreq test

---

perf/perf_c2c.py

perf c2c runs on any architecture, this patch removes the checking
of ppc64.

perf_c2c.py: removed arch dependency

---

io/net/network_test.py.data/network_test_one_variant.yaml
io/net/virt-net/lpm.py.data/lpm_5_iterations.yaml

Adding network_test yaml to try for one mtu size.
Adding lpm yaml to try multiple iterations.

Adding multiple yamls for specific usecases

---

cpu/cpustress.py

Checking for whether the processor is a ppc or not before running
ppc64_cpu command.

cpustress.py: checking for ppc much before

---

kernel/kselftest.py

Patch fixes selftest compilation with installing rsync package

Fix: selftest fails to compile without rsync

---

kernel/kselftest.py

Patch fixes selftests compilation with rsync install

[Backport] Fix selftest compilation with rsync

---

fs/pjdfstest.py

added openssl package as dependency package as without that test run stuck

Fix issue in fs:pjdfstest test case

---

io/disk/scsi_add_remove.py
io/disk/scsi_add_remove.py.data/README.txt
io/disk/scsi_add_remove.py.data/scsi_add_remove.yaml

existing test script cannot be run on vfc disk which does not has pci_address.
and also, script doesn't has verification part after remove or added the scsi
disk. So modified the script to run using wwid or pci domains and also added
the verification part to it.

Enhancment of scsi_add_remove test script

---

memory/vatest.py.data/vatest.yaml

skipped 3rd to 10th scenarios because they causing memory-spaces issues.

Vatest:Skipped some scenario's

---

memory/libhugetlbfs.py

*  [python3] Enable libhugetlbfs test to run with python3
Patch changes python3-enabled branch of libhugetlbfs and few other
fixes to run test with python3.
* Fix: Removed unused variable
Patch removes an unnecessary line from the test

 [python3] Enable libhugetlbfs test to run with python3

---

generic/ltp.py
generic/ltp.py.data/ltp-mem.yaml
generic/ltp.py.data/ltp.yaml

Most of the system time and resources gets exhausted with memory leak check on each test by default, hence making it configurable from yaml

Make memory leak check configurable

---

generic/ltp.py
generic/ltp.py.data/ltp-mem.yaml
generic/ltp.py.data/ltp.yaml

Most of the system time and resources gets exhausted with memory leak check on each test by default, hence making it configurable from yaml

[Backport] Make memory leak check configurable

---

io/net/Network_config.py
io/net/bonding.py
io/net/bridge.py
io/net/ethtool_test.py
io/net/htx_nic_devices.py
io/net/iperf_test.py
io/net/multicast.py
io/net/multiport_stress.py
io/net/netperf_test.py
io/net/network_test.py
io/net/tcpdump.py
io/net/uperf_test.py

changing all network test form python2 to python3 except pktgen.py,
port_bounce.py, vlan_test.py, net_tools.py.

Changing network tests from python2 to python3

---

io/net/virt-net/lpm.py
io/net/virt-net/lpm.py.data/lpm.yaml
io/net/virt-net/lpm.py.data/lpm_5_iterations.yaml

For LPM, there are different options to use along with the command,
which specifies what configuration to maintain and what not to.
To start with, we are enabling --vniccfg option with a value of 2,
which means "maintain virtual network configuration if possible".

Add: option to optionally maintain virt-net config

---

perf/stress.py

tar file has been removed from people.seas.harvard.edu
And now downloading tar file from fossies.org.

Added new link for downloading Stress-1.0.4.tar.gz

---

perf/stress.py

tar file has been removed from people.seas.harvard.edu
And now downloading tar file from fossies.org.

[Backport]Added new link for downloading Stress-1.0.4.tar.gz

---

perf/perf_invalid_flag_test.py

segfaults with invalid flag is observed
for command for 'perf --version -test'

perf_invalid_flag_test.py:Adding testcase for perf segfaults

---

toolchain/libpfm.py
toolchain/power_time_base_bug.py

fixed test case to run in python3
fixed power_time_base_bug.py libpfm.py
logs
[root@ltc-zz189-lp6 toolchain]# avocado run power_time_base_bug.py
JOB ID     : 6bb2cc2f939f844045c1822c9fc45083f1474c9f
JOB LOG    : /root/avocado/job-results/job-2019-09-30T04.18-6bb2cc2/job.log
(1/1) power_time_base_bug.py:PowerTimeBaseBug.test: PASS (31.25 s)
JOB TIME   : 31.52 s
[root@ltc-zz189-lp6 toolchain]# avocado run libpfm.py
JOB ID     : 59bfb96066fce8b22073aee9c0bf1e048f7563aa
JOB LOG    : /root/avocado/job-results/job-2019-09-30T04.23-59bfb96/job.log
(1/1) libpfm.py:Libpfm.test: PASS (2.66 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 …

fixed test case power_time_base_bug.py libpfm.py

---

io/net/network_test.py

network_test had been removing remote files created as part of
scp test. This failed in other tests, which did not create those
remote files at all. So, handling teardown only for scp test.

Handling teardown better in network_test

---

perf/perf_genericevents.py

Changed the module name according to python3

In Python3, ConfigParser has been renamed to configparser

---

ras/lshw.py

In verifying mac address corrected an Error: No closing quotation
Corrected indentation for -numeric command.

lshw.py:Made some changes for "ip addr" and "lshw -numeric" command

---

io/disk/Avago_storage_adapter/avago9361_vd.py
io/disk/Avago_storage_adapter/avago9361_vd.py.data/Readme
io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml

Rename generic disk variable in lsi9361 to disk_vd so that the input file in test suite can cover all the disk related tests.

Rename generic disk variable in lsi9361 scripts -v2

---

io/disk/Avago_storage_adapter/avago9361_vd.py
io/disk/Avago_storage_adapter/avago9361_vd.py.data/Readme
io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml

Rename generic disk variable in lsi9361 to disk_vd so that the input file in test suite can cover all the disk related tests.
Backport of fix to py2-lts.

[Back-port] Rename generic disk variable in lsi9361 scripts

---

fs/xfstests.py

The result being parsed requires a string to be split, patch fixes the error

Fix: xfstests python3 string decode

---

generic/htx_test.py
generic/htx_test.py.data/htx_test.yaml

time_units m,h are added to time_limit
for specifying run-time.

[Backport]htx.py:Adding time_units m-minutes h-hours.

---

io/net/network_test.py

Especially For test like LRO/GRO, Test should be sending higher packets via flood

Enhancing the basic NIC test to send higher packets.

---

io/net/iperf_test.py

typo error at line 148, it was deocde instead decode.
so changed the same.

correcting the typo in iperf_test.py

---

io/disk/lvsetup.py

Removing btrfs specific tests from py2-lts branch from LVM script.

Removing btrfs specific tests from py2-lts branch from LVM script - v5

---

perf/perf_basic.py

To get rid of error 'Job' object has no attribute 'args',
modified the script

Removed few lines of code

---

perf/perf_24x7_all_events.py
perf/perf_hv_gpci.py

To get rid of 'module' object has no attribute
'get_perf_events'.

Changed attr name a/c to process.py

---

io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml

nvme_format_test covers formatting namespace, and deleting and
creating namespace. These are already taken care in nvmetest.py.
So, removing the test.

Remove nvme_format for nvme-cli selftest

---

kernel/kernbench.py

command out the certificate section in the /boot/config*,
in order to prevent build errors in rhel or rhel origin distros.
Signed-off-by: Chih Yuan Hsi <gofar.hsi@gmail.com>

[Backport] change the fix to be specific to rhel and rhel origin distro

---

cpu/em_quad_level_frequency_transitions.py

1-added functionality as script able to calculate system frequency threshold
so automated run  works well
2-change test cancel to fail as if frequency scaling if not fit
in the threshold, test should fail
3- fix pep8 issue in em_quad_level_frequency_transitions 

Fix emtest

---

io/disk/bonnie.py
io/disk/disk_info.py
io/disk/disktest.py
io/disk/fiotest.py
io/disk/fs_mark.py
io/disk/ltp_fs.py
io/disk/parallel_dd.py
io/disk/tiobench.py

Removing btrfs specific tests from py2-lts branch from all disk tests

Removing btrfs specific tests from py2-lts branch from all disk tests

---

perf/perf_24x7_all_events.py
perf/perf_hv_gpci.py

To get rid of 'module' object has no attribute
'get_perf_events'.

Changed attribute name a/c to py3(process.py)

---

memory/ndctl_selftest.py
memory/ndctl_selftest.py.data/ndctl_selftest.yaml
memory/ndctl_selftest.py.data/ppc.patch

Patch enables functional verification test for non-NFIT NVDIMM devices from ndctl source. This patch internally patches source with yet-to-be-upstream accepted proposal to run on non-NFIT devices. Once accepted the patching process would be removed from the test.

Enable ndctl selftest from source

---

ras/lshw.py

lshw -numeric command returns fail even it completes
succesfully, that is because of indentation error in loop.

[Backport]lshw.py : Corrected indentation error for lshw_options

---

memory/memtester.py.data/memtester.yaml

Patch fixes a minor issue with yaml default inputs '1G' which is a string compared with an integer value. Hence making the input an integer, adding a NOTE explicitly and commenting other inputs
to be used on need basis.

Correct memtester yaml file

---

ras/lshw.py

lshw -numeric command returns fail even it completes
succesfully, that is because of indentation error in loop.

lshw.py : Corrected indentation error for lshw_options

---

io/disk/lvsetup.py
io/disk/lvsetup.py.data/lvsetup.yaml
io/disk/lvsetup.py.data/lvsetup_single.yaml

Split lvsetup test to have a create_lv and delete_lv, so that
other tests can be run on the created lv.

Split lvsetup test to create and delete lv

---

memory/memtester.py.data/memtester.yaml

Patch fixes a minor issue with yaml default inputs '1G' which is a string compared with an integer value. Hence making the input an integer, adding a NOTE explicitly and emptying other inputs to
be used on need basis.

[Backport] Correct memtester yaml file

---

memory/libhugetlbfs.py

Since necessary python3 changes are made to master of libhugetlbfs removed explicitly specified next branch

Remove next branch from libhugetlbfs

---

memory/hugepage_sanity.py
memory/libhugetlbfs.py
memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py
memory/transparent_hugepages_swapping.py

When Hugepage is not defined in kernel, memory.hugepage() is not defined -
Skipping test on that platform
Signed-off-by: thierry <tfauck@free.fr>

Hugepage may not be defined in kernel

---

io/disk/bonnie.py
io/disk/disk_info.py
io/disk/disktest.py
io/disk/fiotest.py
io/disk/fs_mark.py
io/disk/ltp_fs.py
io/disk/lvsetup.py
io/disk/parallel_dd.py
io/disk/tiobench.py

Removing btrfs specific tests from all disk tests.

[Back-port] Removing btrfs specific tests from all disk tests.

---

io/disk/fiotest.py
io/disk/fiotest.py.data/fio.yaml

Updating fiotest to use latest fio tarball

Updating fiotest to use latest fio tarball

---

io/net/switch_test.py

correction of a spelling mistake.

fixed  spelling issue in switch_test

---

io/net/tcpdump.py

fixed avocado.utils.process.CmdError: Command './configure' failed

Fixed configure issue for Tcpdump

---

io/net/virt-net/lpm.py
io/net/virt-net/network_virtualization.py
io/pci/dlpar.py

Handling lpar name via lparstat command since it is better.
The previous method of lsrsrc had a prerequisite of hostname to
be set properly, which was not consistent.

Multiple enhancements to DLPAR, LPM and virt-net tests

---

io/pci/PowerVMEEH.py

we use to get fc_host as pci_class_name for fc adapter but
the EEH command uses scsi_host as class name to trigger EEH.
hence changing accordingly.

changing the pci_class_name for fc adapter in PowerVMEEH.py

---

.travis.yml

Allow 2.7 failure as this repo will hold good for python3

Allow 2.7 failure in travis as this repo will hold good for python3

---

io/net/multiport_stress.py
io/net/multiport_stress.py.data/multiport_stress.yaml
io/net/tcpdump.py
io/net/tcpdump.py.data/tcpdump.yaml
io/net/tcpdump.py.data/tcpdump_extended.yaml

set mtu value for both host and peer machine added to test file.
fixed issue,ERROR: sequence item 0: expected str instance, bytes found
for multiport_stress

set mtu value added to the script

---

generic/connectathon.py
generic/openblas.py

Missing pre-req libtirpc for centos and fedora prevented compiling

Add pre-req for some distro

---

memory/ksm_poison.py.data/ksm_poison.c

Parameters of ksm poison had a typo which made the inputs mutually exclusive. This patch fixes the issue.

Fix: ksm poison test input parameters

---

memory/ksm_poison.py.data/ksm_poison.c

Parameters of ksm poison had a typo which made the inputs mutually
exclusive. This patch fixes the issue.

[Backport] Fix: ksm poison test input parameters

---

cpu/ppc64_cpu_test.py

Set of SMT can only be allowed in range [1,max_smt]

Don't set SMT greater than mas_smt

---

io/disk/ltp_fsstress.py
io/disk/ltp_fsstress.py.data/ltp_fsstress.yaml

fsstress is a testcase under ltp/testcases/kernel/fs directory
and is used for filesystem stress over nfs

adding fsstress test to the ltp_fs.py file

---

ras/kprobe.py
ras/kretprobe.py
ras/lshw.py

lshw --numeric |grep HCI make sense only if USB enabled
lshw --class network doesn't get the ip name
add check on ppc64el and ppc64le

   Fix some lshw powerpc behaviour

---

io/disk/lvsetup.py
io/disk/lvsetup.py.data/lvsetup_single.yaml

Moving filesystem creation out of lv_create, so that only the
tests that need filesystem creates it.
Some variable name changes go along with it as enhancements.

lvsetup: moving fs creation out of lv_create

---

perf/perf_24x7_hardware_counters.py
perf/tbench.py

Add more relevant message test if perf not enabled at BMC level
grep -E returns error if ls returns null string

Enhance perf_24x7_hardware test errors

---

generic/htx_test.py
io/disk/htx_block_devices.py
io/net/htx_nic_devices.py

htx shutdown gets hung for long time. so,
adding timeout for htx shutdown command.

htx : Added timeout for htx shutdown command

---

ras/sosreport.py

dict.iteritems() was removed in python3,instead using dict.items()
So changed the script in order to get rid of that error

sosreport.py:AttributeError: 'dict' object has no attribute 'iteritems'

---

memory/ndctl.py

1) Add daxctl package for running DAX test
Patch adds daxctl package for running DAX test
2) Fix: Install packages before configuring ndctl
Patch fixes packages installation before configuring ndctl repo
3) Add support to run test on RHEL distribution
Add support to run ndctl test on RHEL distribution
4) Fix: namespace creation size with multiple regions
Current implementation overwrites size on first iteration and uses the same for all regions. hence replacing the variable with a proper persistence.

ndctl.py: Fixes and enhancements

---

io/net/tcpdump.py

tcpdump requires nmap package to be istalled to run
nping

bug fix for tcpdump.py by including nmap package 

---

io/pci/PowerNVEEH.py

ERROR: a bytes-like object is required, not 'str'

PowerNVEEH.py bug fix for ERROR: a bytes-like object is required, not 'str'

---

io/driver/driver_bind_test.py
io/driver/driver_bind_test.py.data/README.txt
io/driver/driver_bind_test.py.data/driver_bind_test.yaml

Added the support to run for multiple pci_devices for given number of
times. added the count in yaml for stress run.

modified the driver_bind_test.py script to run for multiple pci_adress.

---

perf/unixbench.py
perf/unixbench.py.data/make1.patch

Add debian as distro
decode() added when necessary
test on null string fixed
upgrade valgrind release to current one

uname for machine name

---

io/net/ethtool_test.py.data/ethtool_vnic_test.yaml

removed action_lapse option from vnic yaml file, the argument
is not applicable for virtual interface

action_lapse option is invalid for -g with vnic

---

memory/libhugetlbfs.py
memory/libhugetlbfs.py.data/libhugetlbfs.yaml

Patch enables test to run even with fewer available pages, which would be helpful with system with lesser memory/larger page size.

Enable libhugetlbfs test to run with available pages

---

io/net/virt-net/Network_virtualization_driver_bind.py

ubind/bind script fails on py3 so fixed the syntax

vNIC bind unbind: fixed for python3

---

memory/memory_api.py
memory/memory_api.py.data/memory_api.yaml

Patch fixes memory API test to induce error through yaml and handle the same in test

Fix: Memory API test to induce error through yaml

---

io/net/network_test.py

to check if the neterface link is up or not before starting the
tests.
Used instead of sleep and this function waits for max 120s

network_test.py : use is_interface_link_up from configure_network utility

---

kernel/livepatch.py

Adding decode("utf-8") to avoid string pattern error.

livepatch.py: Added decode("utf-8")

---

io/disk/vfc-tests/vfc_dlpar.py

there was a hardcoded data in the test script, changing it
to generic thing.

removing the static data of lpar name and made it generic.

---

io/net/multiport_stress.py.data/multiport_stress_virt.yaml

in case of vnic only mtu 1500 and 9000 size is supported, so added
the yaml specific to virutal interface

multiport : add yaml file for virtual interface

---

io/net/iperf_test.py
io/net/uperf_test.py

fixed iperf and uperf test for running the subprocess in background.

fixed iperf and uperf for running background command

---

memory/ndctl.py

Patch adopts new pmem library which is moved to avocado framework so that other tests can also leverage this.

Adopting new pmem library

---

io/driver/driver_parameter_block_device.py
io/driver/driver_parameter_block_device.py.data/README.txt
io/driver/driver_parameter_block_device.py.data/driver_parameter_block_device_ibmvfc.yaml

Script to check the different values of given driver module parameter.
This is for only black device driver modules like FC, IPR, NVMe.

driver_parameter test script for block devices

---

io/net/virt-net/Network_virtualization_driver_bind.py
io/net/virt-net/Network_virtualization_driver_bind.py.data/Network_virtualization_driver_bind.yaml

Before starting the test make sure the test interface is
configured with proper ip and is pingable, else cancel the
test

Add interface ip configuration check

---

fs/xfstests.py
fs/xfstests.py.data/nvdimm.yaml
fs/xfstests.py.data/nvdimm_log.yaml

Patch uses pmem library to create pmem devices and run xfstests suite

Use pmem library to create pmem devices and run xfstests

---

io/net/network_test.py

vNIC do not support enabling lro option, so check and skip for vnic
interface

Skip lro test for vNIC interface

---

memory/numa_test.py.data/bench_movepages.c
memory/numa_test.py.data/numa_test.c
memory/numa_test.py.data/softoffline.c
memory/numa_test.py.data/util.c

THP migration should take less time.
Should fix the below erros
(09/12) memory/numa_test.py:NumaTest.test_thp_compare;s_type-wo_huge-f08a: FAIL: Please check the logs for failure (1.63 s)
(10/12) memory/numa_test.py:NumaTest.test_thp_compare;s_type-with_huge-e569: FAIL: Please check the logs for failure (1.68 s)
(11/12) memory/numa_test.py:NumaTest.test_thp_compare;p_type-wo_huge-526a: FAIL: Please check the logs for failure (1.62 s)
(12/12) memory/numa_test.py:NumaTest.test_thp_compare;p_type-with_huge-6cd4: FAIL: Please check the logs for failure (1.65 s)

numa_test: Fix error condition

---

io/net/network_test.py

Cancel the lro test if interface is vNIC, do not use skip function
and remove hardocded interface name

Remove the hardcoded interface name

---

io/disk/scsi_add_remove.py
io/disk/scsi_add_remove.py.data/scsi_add_remove.yaml
io/driver/driver_bind_test.py
io/driver/driver_bind_test.py.data/README.txt
io/driver/driver_bind_test.py.data/driver_bind_test.yaml
io/pci/pci_hotplug.py
io/pci/pci_hotplug.py.data/README.txt
io/pci/pci_hotplug.py.data/pci_hotplug.yaml

To differentiate between a single device(other test) and multiple device
changed the param from pci_device to pci_devices

Rename pci_device to pci_devices

---

io/disk/softwareraid.py.data/Readme

User needs an example to pass the input disks format, so added to
readme

doc: added software raid input example in readme

---

io/common/bootlist_test.py
io/common/bootlist_test.py.data/README.txt

bootlist test now expect the input disk/interface value to be
space separated as standard format and also updated Readme about the
input format

bootlist parameter input made space separted

---

io/net/net_tools.py

SLES15 onwards the tools are deprecated, so added a check to
skip the test

net_tools : skip test if the tool is deprectated

---

README.rst

https://avocado-framework.readthedocs.io/en/`latest` is no longer an endpoint. The latest version of the docs is 77.0.

Updated broken reference link in README

---

generic/openblas.py

Missing space after gfortran parameter

Missing space in argument line

---

generic/htx_test.py
generic/htx_test.py.data/htx_pmem.yaml
generic/htx_test.py.data/htx_test.yaml

1. Add way to provide rpm type test run for HTX
Patch adds a way to provide rpm based install for HTX test
2. Add yaml file for pmem devices
Patch adds yaml file with pmem exercisers

Add way to provide rpm type test run for HTX

---

memory/ndctl_selftest.py

1. Disable docs while building ndctl
Patch disables docs while building ndctl, removes its dependencies
2. Skip test on legacy hardware
Skip test on legacy hardware since most tests tries to create multiple namespaces of the same device

Ndctl selftest fixes

---

io/disk/scsi_add_remove.py
io/driver/driver_bind_test.py
io/driver/module_unload_load.py
io/pci/PowerNVEEH.py
io/pci/PowerVMEEH.py
io/pci/distro_tools.py
io/pci/dlpar.py
io/pci/pci_hotplug.py
io/pci/pci_info_lsvpd.py

Adding pciutils package as part of dependenciy packages for all
pci related tests.

Adding pciutils package to dependencies

---

io/pci/dlpar.py

On large systems dlpar tests are failing due to timeout, as changehwres
takes more time to release the hardware. Hence added the timeout to
3000 secs. So that tests will pass even on large systems.
Signed-off-by: Hariharan T S <hari@linux.vnet.ibm.com>

Added timeout value to runcommand function call in function changehwres

---

memory/ndctl.py

Patch fixes retrieving ndctl list after namespace creation

Fix: Retrieve ndctl list after namespace creation

---

io/net/virt-net/lpm.py
io/net/virt-net/network_virtualization.py
io/pci/dlpar.py

Earlier, we were finding LPAR name by using lsrsrc to find LPAR
host name and then using that to find LPAR name from HMC. But
we came up with lsslot later which was a better way. So, removing
some leftover workarounds from the older method using this commit.

Fixing the way lpar name is found

---

io/disk/port_bounce.py

portbounce test was failing due to local variable
referenced out the for loop. Fixed the same moving
the variable out of the loop.
Signed-off-by: Hariharan T S <hari@linux.vnet.ibm.com>

Fixed local variable issue in port_bounce script

---

generic/ltp.py

Patch skips check of device mounted device through partition library

Skip checking of mounted device

---

memory/dma_memtest.py
memory/eatmemory.py
memory/ksm_poison.py
memory/memhotplug.py
memory/mprotect.py
memory/numa_test.py
memory/vatest.py

Use integer whenever it is required in memory tests

memory: Use integer whenever required

---

io/disk/disktest.py

disktest runs for any size of disk against any size of memory.
So, removed the unnecessary condition.
Co-authored-by: Naresh Bannoth <nbannoth@in.ibm.com>

Removal of unnecessary condition in disktest

---

memory/mprotect.py
memory/mprotect.py.data/mprotect.c
memory/mprotect.py.data/mprotect.yaml

1. mprotect: Add backing file as an input
Patch adds backing file as an input for mprotect test
2. Add support to create and run test on nvdimm device
Patch adds support to create and run on nvdimm device

Support mprotect test to run with nvdimm device

---

io/net/bridge.py

Network Bridge check to CANCEL tests for IB.

Network Bridge check to CANCEL tests for IB.

---

perf/perf_nest_events.py

this patch fix https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1626

Fix issue in perf_nest_event test as adopted latest lib change

---

perf/perftool.py

Since gcc-g++ is not available replacing it with gcc-c++ which is needed for the test to be run.

perftool.py:Replacing package name 'gcc-g++' with 'gcc-c++'.

---

generic/criu.py
generic/criu.py.data/version.yaml

So changed the package name and using the new version of criu in yaml file, and added one
more package 'libnet-devel.' which makes compilation success

criu.py: protobuf-python package as well as criu compilation has failed

---

kernel/kselftest.py

1. Fix: Use same search string for result
The existing upstream string search matches both old, new result summary of selftest. So removing the old string for distro version
```
>>> re.search(r'not ok (.*) selftests:(.*)', "not ok 15 selftests: powerpc/ptrace: ptrace-syscall # exit=1")
<_sre.SRE_Match object; span=(0, 60), match='not ok 15 selftests: powerpc/ptrace: ptrace-sysca>
>>> re.search(r'not ok (.*) selftests:(.*)', "not ok 1..13 selftests: ptrace: core-pkey [FAIL]")
<_sre.SRE_Match object; span=(0, 48), match='not ok 1..13 selftests: ptrace: core-pkey [FAIL]'>
```
2. Add a summary option to kselftest
This allows the failed tests search to be faster as only summary lines are emitted to stdout

Fixes for kselftests

---

cpu/pmqa.py

In PowerVM cpufreq is not supported
so changed the script that cpufreq supports only in PowerNV environment

pmqa.py:cpufreq feature only supported on PowerNV

---

io/disk/ssd/nvmetest.py

When creating nvme namespace, blocksize needs to be integer.
We compute that, but did not make it integer earlier. Fixed it.

Fixing blocksize to be integer in nvmetest

---

io/net/virt-net/network_virtualization.py
io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml

changing netmask to netmasks its because of scenario testing
with multiple vnic,in vnic test will pass multiple netmask.

change netmask to netmasks in yaml and test file

---

ras/ras.py

So replaced the command with lsslot -c pci'

ras.py: 'lsslot -ac pci' command is failing

---

io/net/Network_config.py
io/net/ethtool_test.py
io/net/iperf_test.py
io/net/multicast.py
io/net/multiport_stress.py
io/net/netperf_test.py
io/net/network_test.py
io/net/switch_test.py
io/net/tcpdump.py
io/net/uperf_test.py

to remove backup config files and to restore the old config
back.

added restore_from_backup() to network tests

---

io/disk/fiotest.py

Fixing disk parameter name, as it should have been l_disk.

fiotest: Fixing disk parameter name in create_lv

---

io/disk/fiotest.py
io/disk/fiotest.py.data/fio-devdax.job
io/disk/fiotest.py.data/fio-libpmem.job
io/disk/fiotest.py.data/fio-pmem.yaml

Patch adds support to create and run pmem device type with both fsdax and devdax modes

Add support to run FIO with pmem devices

---

io/net/iperf_test.py
io/net/iperf_test.py.data/iperf_test.yaml

iperf2 file location has changed and hence he default is not working
adding the param "iperf_download" to yaml file as this location
is not consistent and cannot rely on default always.

iperf2 file location has changed

---

ras/uprobe.py

glibc-devel package is required to run the test for Distro SuSE.

uprobe.py: Adding "glibc-devel" package for SuSE.

---

io/net/ethtool_test.py

make changes for unsupported operation as warn
in place of failed.
Reported-by Abdul Haleem <abdhalee@linux.vnet.ibm.com>

ethtool fix for unsupported operation

---

io/disk/disk_info.py

Name of a multipath library function that used in disk_info.py
has changed. corrected it with new changed function name

Correcting the changed library function name in disk_info test 

---

io/net/htx_nic_devices.py
io/net/htx_nic_devices.py.data/htx_nic_devices.yaml

add a function for ip config to original ip address
for host and peer after htx run.
Reported-by Abdul Haleem abdhalee@linux.vnet.ibm.com

fixed htx for ip restore in host and peer

---

memory/dma_memtest.py

1. Fix: checking output buffer
Patch fixes output check of dma_buffer which converts b"" to ""
2. Remove compress_ratio and find the actual size
Patch removes compress_ratio for a tar file and uses the actual size of the uncompressed tar folder.
3. Use library to get the memory bytes
Patch uses library to get the memory bytes required

Dma memtest fixes

---

io/disk/fiotest.py.data/fio-libpmem.job

Some machine does not have node id 0 and hence the fio job fails.

Remove hardcoded node id

---

io/net/bonding.py

add restore_from_backup() in to bonding for old config file
restore.

added restore backup file in bonding test

---

memory/ndctl.py

Patch adds positive and negative tests using write infoblock and verifies it is works as expected.

Add tests for ndctl write-infoblock

---

io/disk/ssd/nvmetest.py

NVMe devices may have more than one controller, and in such cases,
using the first controller will always work when creating
namespaces. This commit forces the test to use the first
controller always.
Example:
nvme list-ctrl /dev/nvme0
[   0]:0x41
[   1]:0x42

Using the first controller for nvme

---

perf/tbench.py

To get rid of modulenotfound error

changed module name to subprocess

---

memory/pmem_dt_check.py

Patch adds test to validate device-tree node associativity against OS level node associativity for pmem devices

Add test to validate numa associativity for pmem device

---

fs/xfstests.py

Xfs logdevice size should be less than 2G and also page aligned.
hence patch changes log device size to be page aligned(16M).

Change log device size to be page aligned

---

perf/perf_uprobe.py

An unknown tracepoint error has occured because of syntax error.

perf_uprobe.py: Handled syntax error for Distro SLES15 SP2.

---

generic/htx_test.py

Patch adds shell argument to unmount devices properly. Without this argument, umount fails to unmount devices.

Add shell argument to unmount devices

---

io/disk/Avago_storage_adapter/avago9361_vd.py

Handle string output properly in process.run()

avago9361_vd: Handle string output properly

---

io/disk/lvsetup.py
io/disk/lvsetup.py.data/README
io/disk/lvsetup.py.data/lvsetup_single.yaml

Reduce the usage of vg_ramdisk() functions so as to maintain
the code better. vg_ramdisk() does a lot more than is needed,
in a complex way.
Follow the issue for more details:
avocado-framework/avocado/pull/3857

lvsetup: Reduce usage of unnecessary utilities

---

io/net/bonding.py
io/net/htx_nic_devices.py
io/net/infiniband/ib_pingpong.py
io/net/infiniband/mckey.py
io/net/infiniband/ping6.py
io/net/infiniband/rdma_tests.py
io/net/infiniband/rping.py
io/net/infiniband/ucmatose.py
io/net/infiniband/udaddy.py
io/net/iperf_test.py
io/net/multiport_stress.py
io/net/netperf_test.py
io/net/network_test.py
io/net/tcpdump.py
io/net/uperf_test.py

Test which uses RemoteHost module to open multiple ssh
connections are not being terminated at the end of test,
Results in un clean setup for next runs. So this patch adds
remote_session.quit() after test finishes

Terminate all open remote ssh connections in nic tests

---

io/disk/disktest.py
io/disk/fiotest.py
io/disk/ssd/blkdiscard.py

lv_utils recently deprecated the get_diskspace() in favour of 2
new functions get_device_total_space() and
get_devices_total_space(). So, updating the tests to use the
newer functions.

Using latest get_device_total_space function

---

memory/ndctl.py

Patch cancels tests before namespace is created, which is not done earlier and hence the subsequently tests failed due to change in environment

Cancel test before namesapce creation

---

memory/transparent_hugepages.py
memory/transparent_hugepages_defrag.py
memory/transparent_hugepages_swapping.py

Patch adds option to not check mountpoint for generic device type

Added option to not check mountpoint for generic device type

---

memory/ndctl.py

Patch adds negative test for unaligned namespace creation

Add negative test for unaligned namespace creation

---

io/net/Network_config.py

Interface type was got by checking the command:
`basename /sys/class/net/<iface>/device/driver/module/drivers/*`
But mellanox devices had 2 types, as below:
```
mdev:mlx5_core  pci:mlx5_core
```
So, handling such cases with this commit.
Reported-by: Manvanthara Puttashankar <manvanth@linux.vnet.ibm.com>

Network_config: Fix getting interface type

---

io/net/virt-net/network_virtualization.py
io/pci/dlpar.py

removed pxssh session close from teardown and
added ssh session terminate option

Remove pxssh console code

---

io/net/bonding.py
io/net/iperf_test.py
io/net/multicast.py
io/net/netperf_test.py
io/net/uperf_test.py

to avoid password during command run in peer machine.

add connect() from ssh.py to avoid ssh-keygen

---

io/disk/multipath_test.py

When restoring multipath.conf backup, we are just checking
if conf file is present. But we should actually check if the
backup file is present. Fixing that with this commit.
```
Traceback (most recent call last):
File "/io/disk/multipath_test.py", line 305, in tearDown
shutil.copyfile("%s.bkp" % self.mpath_file, self.mpath_file)
File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/multipath.conf.bkp'
```

multipath: Fix restoring config file backup.

---

memory/dma_memtest.py

There is a possibility that temp dir can be used with partitions with more space, this patch enabled that

Use partition with more space

---

io/disk/dlpar_vscsi.py
io/net/virt-net/network_virtualization.py
io/net/virt-net/veth_dlpar.py
io/pci/dlpar.py

to avoid password of hmc and vios during test run chnage for
dlpar_vscsi.py,veth_dlpar.py,veth_dlpar.py,network_virtualization.py

add connect() from utils to avoid ssh-keygen for hmc and vios

---

io/disk/ssd/nvme_cli_selftests.py

Certain python packages are not necessary. So, removing them
from the dependency list.

nvme_cli_selftests: Remove unwanted dependencies

---

perf/perf_pcp.py

Recently there are changes in hv_24x7_events
So, updated code for fetching PM_MBA0_CLK_CYC and PM_PB_CYC events.

perf_pcp.py:Updated code for fetching perfevent_24x7_events.
