memory/integrity.py, memory/integrity.py.data/mem_integrity_test.c
Failures like below does return a code of 255
```
$ ./mem_integrity -s 3
...
...
madvise: Device or resource busy
```
So use a different, unique code to catch the failure
=> Fix: Use a unique exit status to avoid failures

io/disk/fiotest.py, io/disk/fiotest.py.data/fio.yaml
Test creates software raid and runs fio on them, as an option.
This is done by the boolean parameter raid in yaml
=> fiotest: Adding option to run on softwareraid

cpu/ebizzy.py
Ebizzy test fails to fetch source tarball as the link used for download is no longer working/valid.
#
Fetching asset from cpu/ebizzy.py:Ebizzy.test
JOB ID     : bd2879565ad2afa97a748cabc0136654898bac33
JOB LOG    : /home/tests/results/job-2020-07-22T05.24-bd28795/job.log
(1/1) cpu/ebizzy.py:Ebizzy.test:  ERROR: Failed to fetch ebizzy-0.3.tar.gz. (132.88 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
Update the test to fetch the tarball using the correct link.
This patch also fixes a pylint warning for p1 variable.
Signed-off-by : Sachin Sant <sachinp@linux.vnet.ibm.com>
=> Update ebizzy tarball download link

io/disk/Avago_storage_adapter/avago9361.py, io/disk/Avago_storage_adapter/avago9361.py.data/avago9361.yaml
There are some parameters which need extra options, as
described in the github issue:
avocado-framework-tests/avocado-misc-tests/issues/1776
Handling that via this commit
Reported-by: Gene-Lo
=> avago9361: Handle extra option for some parameters

io/net/iperf_test.py, io/net/netperf_test.py, io/net/network_test.py, io/net/uperf_test.py
changes for copy files using utils in iperf, netperf, uperf
and network_test files.
=> copy files using utils module

generic/ltp.py
Avocado's temporary creation API by default allows only created user to read, write and execute from the tmp dir. Due to this lot
of LTP tests fail without access from ltp user, hence changing the mode before running the tests, also using teststmpdir which is apt here
=> Fix: Access mode of temporary directory

perf/perf_24x7_hardware_counters.py
perf event related error logging was corrected, so to reflect the correct
error, the condition to check the error was modified.
=> perf_24x7_hardware_counters.py: event error logging corrected

memory/ndctl.py
Patch adapts write_infoblock to new library
=> ndctl.py: Adapt write_infoblock to new library

memory/sum_check.py
Patch checks the space of /home as well, so that test case can run on machines with less root FS space.
=> sum_check: Use partition with more space

kernel/kselftest.py
Added logic in kself test case as location can be provided
just as upstream git format as this can be used to provide
custom or fork kernel self test case
=> Added logic to provide upstream git url for kself test case

io/pci/PowerNVEEH.py, io/pci/PowerVMEEH.py, io/pci/PowerVMEEH.py.data/PowerVMEEH.yaml, io/pci/PowerVMEEH.py.data/PowerVMEEH_nvme.yaml, io/pci/PowerVMEEH.py.data/Readme, io/pci/pci_hotplug.py
make sure the default value is porper and skip the test
for all non pci devices
=> pci_hotplug: cancel test if pci not given

io/disk/fiotest.py, io/net/ethtool_test.py.data/ethtool_iscsi_test.yaml
I've made some tests that test iSCSI specific configs. These tests are based off of existing network and disk tests so I've titled my tests [old_test]_iscsi.py. Hopefully this makes it easier to compare to old tests and understand their functionality. Please review and let me know if more work needs to be done on these tests. 
This is just a starting point to enable basic testing for iSCSI. Hopefully more tests will be added in the future.
I've also made a config file for the fvt-avocado-wrapper which I will submit once my iscsi tests are added to this repo.
Thanks,
Kyle
=> Add iSCSI test suite

generic/ltp.py
Patch adds check before dir creation
=> Fix: Add check before dir creation

generic/ltp.py
Like temporary directories' access, there are few binaries which are part of the build directory that needs access when tests are
utilizing them. Hence replacing teststmpdir as the build directory so that tests still have access to the entire path of binary.
=> Fix: Tests binaries access for LTP

io/driver/driver_parameter.py.data/driver_parameter_bnx2x.yaml
yaml file for Shiner bnx2x driver.
=> shiner parameters for driver_parameter.py test

io/net/network_test.py, io/net/network_test.py.data/network_test.yaml
include a parameter for ip config as an option to config ip.
and fixed lro test to handle bondig interface.
=> fixed lro test and add ip config as an option in network_test

toolchain/glibc.py, toolchain/glibc.py.data/glibc.yaml
The `glibc.py` test specifies a _prefix_ of `self.build_dir` when doing
`./configure`.
This is mostly innocuous unless a `make install` is performed, which
is not done by `glibc.py`.
It is an issue, however, when doing a `make check` because some glibc
tests are unable to find the system's `libgcc_s.so.1` and FAIL.
There is an obscure reference to this known issue at
https://sourceware.org/glibc/wiki/Testing/Testsuite#Known_testsuite_failures
Thus, default _prefix_ to `/usr`.
Signed-off-by: Paul A. Clarke <pc@us.ibm.com>
=> Use `--prefix=/usr` by default for glibc

io/net/iperf_test.py.data/iperf_virt_test.yaml
sriov virtual devices do not support all MTUs, so created a
separate yaml
=> iperf test yaml for virtual devices

cpu/ebizzy.py, cpu/ebizzy.py.data/ebizzy.yaml, cpu/em_smt_folding_test.py, cpu/em_smt_folding_test.py.data/em_smt_folding_test.yaml
1-Fix ebizzy tar file link as old link not valid any more
2-add expire param for fecth as it avoid download again
=> fix as ebizzy as bug fix and enhancement

perf/perf_basic.py, perf/perf_c2c.py, perf/perf_fuzzer.py
Fix perf install command by linux-perf for debian as bellow files
perf_basic.py
perf_c2c.py
perf_fuzzer.py
Signed-off-by:  xiaohaiyan <xiaohaiyan@uniontech.com>
=> Fix perf install command by linux-perf for debian

io/disk/softwareraid.py, io/disk/softwareraid.py.data/Readme, io/disk/softwareraid.py.data/softwareraid.yaml, io/disk/softwareraid.py.data/softwareraid_cleanup.yaml, io/disk/softwareraid.py.data/softwareraid_setup.yaml
Moved all functions to utils, so that they can be used in
other tests.
Use case: avocado-misc-tests/issues/1674
=> softwareraid: Overhaul using utils

io/net/Network_config.py, io/net/bonding.py, io/net/ethtool_test.py, io/net/iperf_test.py, io/net/multicast.py, io/net/multiport_stress.py, io/net/netperf_test.py, io/net/network_test.py, io/net/switch_test.py, io/net/tcpdump.py, io/net/uperf_test.py
for restore_from_backup(), if backup file is there it will move or
else it shouldn't raise exception.to avoid test fail.
=> handle for Exception shouldn't raise if backup file not available

cpu/cpustress.py
Fix pylint warning against cpu/cpustress.py
With this fix pylint score improves to 9.1
"Your code has been rated at 9.10/10"
=> Fix pylint warning against cpu/cpustress.py

io/net/bonding.py
1) Ping check after slave gets reinstated
2) Change MTU of bond interface
=> bonding enhancements

security/keyutils-tests.py
security/keyutils-tests.py adds keyutils tests
=> Adding tests of keyutils

io/net/tcpdump.py, io/net/tcpdump.py.data/tcpdump-virt.yaml, io/net/tcpdump.py.data/tcpdump.yaml
nping count is calculated as 20% more than the count value.
=> Calculate nping count

cpu/ebizzy.py
Patch fixes a minor typo issue introduced in a recent commit
=> Fix: typo in ebizzy URL

generic/ltp.py.data/ltp-security.yaml
Adding the following test suites:
crypto
cve
ima
net_stress.ipsec_dccp
net_stress.ipsec_icmp
net_stress.ipsec_sctp
net_stress.ipsec_tcp
net_stress.ipsec_udp
securebits
tpm_tools
=> Adding security related test suites

security/selinux-tests.py
Added splitlines while processing the output, on some of the
environments fail criteria is not processed correctly with out
splitlines()
=> Add splitlines while processing the output

ras/ras_extended.py
Changed ifconfig command to lsvio in bootlist test.
[root@ltc-zz8-lp4 ras]# avocado run ras_extended.py 
JOB ID     : 4e75ca57bbb2888fda94adee0c55b635978a046a
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2020-10-01T11.10-4e75ca5/job.log
(01/11) ras_extended.py:RASTools.test1_uesensor: PASS (1.77 s)
(02/11) ras_extended.py:RASTools.test1_serv_config: PASS (1.92 s)
(03/11) ras_extended.py:RASTools.test1_ls_vscsi: PASS (1.73 s)
(04/11) ras_extended.py:RASTools.test1_ls_veth: PASS (1.85 s)
(05/11) ras_extended.py:RASTools.test1_ls_vdev: PASS (1.76 s)
(06/11) ras_extended.py:RASTools.test1_lsdevinfo: PASS (5.18 s)
(07/11) ras_extended.py:RASTools.test1_hvcsadmin: PASS (2.14 s)
(08/11) ras_extended.py:RASTools.test1_bootlist: …
=> Patch to fix bootlist testcase v2

security/annobin-tests.py
security/annobin-tests.py adding test cases of annobin.
A tool for checking the security hardening status of binaries
=> Adding annobin test cases

io/common/virtual_bind_unbind.py
added to the script,if virtual device is root disk or default interface
cancel the test,with the help of utils functions is_root_device() and
get_default_interface().
=> cancel test if it is root disk or default interface

security/selinux-tests.py
used linux.enable_selinux_enforcing lib to check/enable if selinux in enforcing mode in system
=> Adopt avocado library for selinux check

io/nvmf/nvmftest.py, io/nvmf/nvmftest.py.data/README.txt, io/nvmf/nvmftest.py.data/nvmftest.yaml
Using the ssh and scp utils for nvmf tests.
=> nvmftest: Using ssh and scp utils

io/net/tcpdump.py, io/net/tcpdump.py.data/tcpdump-virt.yaml, io/net/tcpdump.py.data/tcpdump.yaml, io/net/tcpdump.py.data/tcpdump_extended.yaml, io/net/tcpdump.py.data/tcpdump_extended_virt.yaml
mtu_timeout is added as yaml parameter
mtu_timeout  waits for link up after mtu change.
=> mtu_timeout param

io/net/virt-net/network_virtualization.py
fixed test_vnic_auto_failover test,getting error because of changed
output format after hmc passwordless.
=> fixed network_virtualization test for test_vnic_auto_failover

io/disk/fiotest.py
Patch uses tmpdir for pmdk source configuration replacing /usr, which avoids install on system path
=> fiotest.py: Use tmpdir for configuring pmdk library

memory/ndctl.py, memory/ndctl_selftest.py
Patch adds missing package for upstream ndctl configuration
=> Add missing package for ndctl test

io/net/tcpdump.py
Avocado converts the count field as a string when the test treats it as an int.
This fix converts the count field to an int when preforming arthmetic.
=> tcpdump: reads count field from input file as a string

io/net/network_test.py, io/net/virt-net/network_virtualization.py
removng controlpath if existing inside /root/.ssh before test.
=> removing controlpath file before test started

io/net/virt-net/network_virtualization.py
It takes time for ARP-request packets to resolve when trying to send packets to
the peer after a client failover. This fix allows the vNIC to wait 50
milliseconds for a replay for each packet sent.
Additionally, using write_file_or_fail instead of write_file to catch errors
when writing to a file.
Signed-off-by: Cristobal Forno <cris.forno@ibm.com>
Co-developed-by: Dany Madden <danymadden@ibm.com>
=> ibmvnic: increase wait time when pinging after client failover

io/net/virt-net/network_virtualization.py
added to enable debug mode before starting the test.
=> enabling the debug mode before starting vnic tests

io/net/virt-net/network_virtualization.py, io/net/virt-net/network_virtualization.py.data/README, io/net/virt-net/network_virtualization.py.data/multiple_vnic_nobacking.yaml, io/net/virt-net/network_virtualization.py.data/single_vnic_single_backing.yaml
script will create mutiple vnic with different adapter id and different port.
because we can't create bond interfcae with same adapter vnic interface.
=> changes for multiple vnic with different adapter id

io/net/htx_nic_devices.py
Fix htx_nic_devices.py to work with latest rpm and exit status.
Updating the code to work for latest htx rpm links. The command 'build_net help n' returns 43 for two-system tests.
Changing the code to work for this value.
=> Fix htx_nic_devices.py to work with latest htx rpm 

cpu/cpupower_monitor.py
Test covers below scenarios:
1- List the allowed Idle States using "cpupower monitor" command.
2 Run cpu intensilve workload and check that CPUs are not in Idle states, verify using "cpupower monitor" command.
Kill the workload run sleep command for sometime and check if the cpus have entered the idle states.
Disable one Idle state and check if the CPUs does not enter disabled Idle state.
Repeat the tests by offlining few CPUS.
Repeat the tests in different SMT modes.
=> Script to test idle states using cpupower monitor - v5

kernel/kselftest.py
New test introduced under vm directory of selftest requires libhugetlbfs devel packages. Without that building fails
[stderr] hmm-tests.c:24:23: fatal error: hugetlbfs.h: No such file or directory
[stderr]  #include <hugetlbfs.h>
[stderr]                        ^
[stderr] compilation terminated.
=> Fix: Add new package for kernel selftest

memory/mm_subsystem.py
Patch updates memory subsystem test link as the older link is no longer available
=> Fix: Update memory subsystem test link

io/net/virt-net/network_virtualization.py
Currently, when using avocado's ssh utils to create a session with the VIOS, it
does not check if the connection was successful. This fix fails thetest if
connecting to the VIOS has failed.
=> virt-net: Fail test if VIOS could not connect

memory/ndctl.py
Patch adds required bash-completion package for rhel and also removes duplicate entry
=> Add required package for rhel

kernel/kselftest.py, kernel/kselftest.py.data/kselftest.yaml
1. Make kselftest run simple on SuSE
Patch uses kernel-source package to install the source and run the kselftest from that on SuSE
2. Fix: Parsing test result for older sles releses
The sles12 distro kernel still executes kselftest with results displayed with older version, handle that and parse the test
results appropriately
=> kselftest.py: Fixes and enhancements for SuSE

memory/numa_test.py, memory/numa_test.py.data/softoffline.c
1. Fix: Use unsigned long for storing PFNs
Sometimes the old PFNs match due to pfn values stored as char's, also the type does not match with the get_pfn utility function.
This patch solves those compilation warnings also.
2. Add numa node check for specific tests
Patch adds checks for specific tests that allows other test to run even on a single numa machine
=> Numa test case fix and enhancement

ras/sosreport.py, ras/sosreport.py.data/options.yaml
The options ticket-number and -z bzip2 are not supporting
=> sosreport.py:Removed ticket-number and -z bzip2 options

io/net/virt-net/network_virtualization.py
Increasing wait time for all the failover vNIC tests to 1 minute to
fall in line with other testing infrastructures that test vNIC.
=> virt-net: increase waittime on failover tests for vNIC

generic/ipistorm.py
Patch verifies if DBL and XIVE IPIs are being used on pseries environment appropriately
=> Add test to verify IPIs usage in pseries

memory/ndctl.py, memory/pmem_dm.py
1) Fix: Handle namespace size align value based on sysfs
Patch fixes the assumption of default namespace size alignment for Hash and Radix. So going forward a sysfs attribute is used to correspond to be namespace size alignment.
2) Fix size alignment usage for write-infoblock test
Currently write-infoblock test uses namespace size alignment as base value for kernel mapping alignment. Fix it by using base
hugepage value (same as ndctl base kernel mapping alignment) as kernel mapping align value.
=> ndctl.py: namespace size align fixes

io/net/virt-net/network_virtualization.py
Currently, the get_failover_priority only checks if the first vNIC device has
the slot number. There is the case where the lshwres command retrieves multiple
vNIC devices. The output is formatted where it creates an array of all the
vNIC devices and checks if the slot number matches each one.
=> virt-net: handle more than one vnic backing device

io/net/netperf_test.py, io/net/netperf_test.py.data/netperf_test_virt.yaml
Currently the netperf stream tests have a hard value of 63000 bytes given as an
argument when it should depend on each system. This fix reads the default socket
buffer size from /proc/ and sends it as an argument.
=> netperf: make UDP/TCP_STREAM option have dynamic socket buffer arg

io/driver/module_unload_load.py.data/config
nvme_fc is driver module of nvmf which is a new module.
Hence added the dependent driver module of it in config file.
=> Adding nvme_fc module dependencies in config file

io/net/htx_nic_devices.py
The test was running into an issue where the HTX daemon was in the process of
creating MDT files when it tried to select the net.mdt file. This fix runs
htxcmdline -createmdt on both the peer and the host before selecting net.mdt.
=> htx_nic_devices.py: Generate MDT files before selecting net.mdt

io/net/virt-net/network_virtualization.py
added -t option to capture timestamps when enabling dynamic
debug for vnic module
=> Add timestamp to dynamic debug command

cpu/ebizzy.py, cpu/ebizzy.py.data/ebizzy.yaml
This patch adds capability to pin cpus using taskset and also record
perf statistics while running ebizzy.
This feature can be extended to other relevant wrappers in future. It
gives flexibility to the user to run perf monitors for specific runs
instead of a system wide monitoring.
Signed-off-by: Abhishek Goel <huntbag@linux.vnet.ibm.com>
=> cpu/ebizzy.py : Add taskset and perf stat for ebizzy

perf/perf_pmu.py
Adding test cases,
What PMUs got registered
different kernel configs - CONFIG_PMU_SYSFS, CONFIG_PPC_RTAS
cpu events count
hv_24x7 events count
IMC events count
nest events CPU mask
Core events CPU mask
=> perf_pmu.py: Adding test cases related to sysfs, registering events

cpu/schbench.py, cpu/schbench.py.data/schbench.yaml
This patch add schbench.py wrapper for schbench. Schbench is designed
to provide detailed latency distribution for scheduler wakeups.
This patch also provides schbench.yaml which contains sample
input points for running the benchmark.
Signed-off-by: Abhishek Goel <huntbag@linux.vnet.ibm.com>
=> Add schbench test for cpus

cpu/producer_consumer.py, cpu/producer_consumer.py.data/producer_consumer.yaml
This patch add producer consumer benchmark test which is a cache
affinity scheduler wakeup benchmark.
This patch also provides producer_consumer.yaml file with custom
input points for running the benchmark.
Signed-off-by: Abhishek Goel <huntbag@linux.vnet.ibm.com>
=> cpu/producer-consumer.py: Add producer-consumer test for cpu

io/disk/vfc-tests/vfc_dlpar.py, io/disk/vfc-tests/vfc_dlpar.py.data/README.txt, io/disk/vfc-tests/vfc_dlpar.py.data/vfc_dlpar.yaml
The script was failing when we have one of the vfc interfaces as bootable disk.
Hence added an option to skipp the bootable vfc interface and perform the dlpar
on rest of the vfc interfaces.
=> enhancing the vfc-dlpar.py to work with vfc bootable disk

cpu/cpuidle-latency.py, cpu/cpuidle-latency.py.data/cpuidle-latency.yaml
Cpuidle latency is a kernel module based userspace driver to estimate
the wakeup latency for cpus that are in idle stop states.
This patch also provides cpuidle-latency.yaml file with custom input
points for running the benchmark.
Signed-off-by: Abhishek Goel <huntbag@linux.vnet.ibm.com>
=> cpu/cpuidle-latency.py: Add cpuidle-latency test for cpu

io/net/bonding.py
adding physical_adapter param to check of the tested
interface is physical or virtual adapter
=> adding physical_adapter check

cpu/cpuidle-latency.py, cpu/ebizzy.py, cpu/producer_consumer.py, cpu/schbench.py
Scheduler tests needs to install perf package to run, adding it
=> Add perf package to scheduler tests

io/net/iperf_test.py
before it was showing PASS even if throughput is below
Expected value.so filter the throught according to iperf2 output.
=> fixed iprf test for iperf2

io/net/netperf_test.py
When building netperf on both the host and remote machines, a warning is
displayed "configure: WARNING: you should use --build, --host, --target".
To have the test pass cleanly, the flag --build is used when building netperf.
=> netperf: use tag --build

io/net/bridge.py
Check if the config file exists before deleting it.
=> bridge.py: check if config file exists before deleting

io/net/virt-net/network_virtualization.py
check_slot_availability was splitting the slot numbers with more than
one character. So instead of comparing slot 12, it would compare slot
1 then slot 2.
=> virt-net: fix check_slot_availability to search slots

generic/connectathon.py
Connectathon tests needs to install libtirpc-devel package to
compile and run, adding it
=> connectathon.py:Added libtirpc-devel package to compile and run tests

kernel/kernbench.py
changing the script to use 2 * nr_cpus if the yaml input is None
=> fixing FAIL: No vmlinux found, kernel build failed

memory/ndctl.py.data/map_sync.c
cc     map_sync.c   -o map_sync
map_sync.c: In function ‘error’:
map_sync.c:31:35: warning: implicit declaration of function ‘strerror’; did you mean ‘error’? [-Wimplicit-function-declaration]
printf("%s with %s\n", s, strerror(eno));
^~~~~~~~
error
=> Fix build warning in MAP_SYNC test.

ras/hwinfo.py
The test case fails on RHEL with following error
Hwinfo.test_list: CANCEL: Hwinfo not supported on RHEL (0.00 s)
Given that hwinfo tool is available with recent releases of Red Hat
Enterprise Linux, remove the check for rhel from the test case.
=> Update hwinfo test case to allow it to run on RHEL releases

generic/stress-ng.py.data/stress-ng.yaml
due to 'null' string the default value is not assigned properly,
due to which test command execution is not happening.
This patch fixes the issue and assigns the default value
correctly when workers value is null.
=> Remove workers value from yaml file

perf/perf_24x7_all_events.py
Running perf_24x7_all_events test on a POWER10 system fails with following 
error:
ERROR: 'hv_24x7_all_events' object has no attribute 'perf_stat' (0.84 s)
This test lacks support for POWER10 processor family. The patch adds that
support. It also fixes warnings reported by pycodestyle.
=> perf_24x7_all_events - add support for POWER10 processor family

generic/sysbench.py
checked path exists before remove operation
=> fixed sysbench test case

cpu/numatop.py
numatop testcase is currently supported only on Ubuntu distribution.
Enhance the test case to suport RedHat and SUSE distribution releases.
=> Enhance numatop testcase to run on RHEL/SLES distributions.

perf/lmbench.py, perf/lmbench.py.data/fix_lseek.patch
1.Added libtirpc-devel package for rpc related compilation error
2.Added extra args to make command for pmap related compilation
errors
3.Added patch file in order to get rid of lsleek related
compilation error
=> lmbench.py: Fixing Compilation errors

perf/perf_basic.py
Problem:
perf basics tests were failing as proper linux-tools package version was not selected under ubuntu distro
Fix:
os.uname command to get kernel release is fixed in order to get proper linux-tools package version
Signed-off-by:Spoorthy<spoorts2@in.ibm.com>
=> perf_basic.py: linux-tools package version is not selected properly for ubuntu distro

perf/perf_genericevents.py, perf/perf_genericevents.py.data/raw_code.cfg
perf_genericevents test fails on a POWER10 system with
ERROR: 'test_generic_events' object has no attribute 'generic_events' (0.04 s)
The testcase lacks support for POWER10.
This patch adds that support.
=> Add POWER10 support to perf_genericevents test

perf/perf_rawevents.py
perf_rawevent test iterates over all cpu families irrespective of where
the test is being run. For example running this test on IBM POWER9 will also
invoke (and skip) test scenarios meant for IBM POWER8 only family.
(1/3) perf/perf_rawevents.py:PerfRawevents.test_raw_events_power8: SKIP: Supported only on Power8
(2/3) perf/perf_rawevents.py:PerfRawevents.test_name_events_power8: SKIP: Supported only on Power8
(3/3) perf/perf_rawevents.py:PerfRawevents.test_raw_events_power9: PASS
Restructure the code to detect the cpu family and accordingly run the corresponding test scenario.
Second patch fixes code style warnings
Signed-off-by: Sachin Sant sachinp@linux.vnet.ibm.com
=> perf_rawevents test case functionality and code style fixes 

cpu/pvr.py, cpu/pvr.py.data/pvr.cfg
This patch adds a new test for Processor Version Register(pvr)
The test supported on IBM POWER architecutre checks pvr value for various
IBM POWER processor families and verifies it.
This work is based on code originally written by Pooja.
Signed-off-by: Pooja B Surya <pooja@linux.vnet.ibm.com>
=> This patch adds a new test for Processor Version Register(pvr)

fs/xfstests.py
Xfs tests were cancelled as libbtrfs-dev package not available in ubuntu 18.04.
Solution:
Checked in xfs git repository and observed that libbtrfs-dev package is no longer required(https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/README) for distro ubuntu.
Also verified building package without libbtrfs-dev. Hence removing the libbtrfs-dev from dependency list
Signed-off-by: Spoorthy<spoorts2@in.ibm.com>
=> xfstests - Remove libbtrfs-dev package from dependency list

security/audit-tests.py
Audit test fails to execute with following error:
Audit.test: ERROR: Failed to fetch main.zip (HTTP Error 404: Not Found).
url to download source code of audit-tests no longer works.
Use the correct url for download.
Also fix pycodestyle warning for > 79 characters.
security/audit-tests.py:70:80: E501 line too long (80 > 79 characters)    
=> Audit test case fixes

kernel/kselftest.py
Patch handles package name for RHEL 9 beta distribution
=> kselftest.py: Handle package name for RHEL9

memory/ndctl.py.data/ndctl.yaml, memory/pmem_dm.py.data/pmem_dm.yaml
Patch fixes default yaml input for few options so that the test runs with valid yaml value
=> ndctl.yaml: Fix default yaml input for few options

perf/perf_24x7_hardware_counters.py
Cancel test 'test_event_phys_core_param' on Operating Systems where
perf evnet 'HPM_0THRD_NON_IDLE_CCYC__PHYS_CORE' not found.
=> perf_24x7_hardware_counters.py fix test_event_phys_core_param

perf/perf_genericevents.py.data/raw_code.cfg
perf_genericevents test fails on a POWER10 machine running upstream kernel
due to mistmatch in values for mem-loads/mem-stores
FAIL : Expected value is 0x34340401e0 but got0x35340401e0
FILE in /sys/bus/event_source/devices/cpu/events is mem-loads
Fix the raw code values for mem-loads/mem-stores.
=> perf_genericevents - fix incorrect mem-loads/mem-stores values

security/cryptsetup-tests.py
Add libssh-devel dependency which requires for compilation.
=> cryptsetup-tests.py: add compilation dependency

cpu/numatop.py
Added code to skip POWER10 arch, numatop support is not there on POWER10.
=> Skip POWER10 Arch.

perf/perf_metric.py
Add perf metric/metric group test case. Collect all the events and run
the collected events one by one.
=> perf_metric.py: Add perf metric test case

perf/perf_cpu_hotplug.py
Add perf cpumask test case related to events hv_24x7 and hv_gpci.
validate cpumask picks up another CPU incase of the present CPU is not
available.
=> Add perf cpumask test case

memory/ndctl.py
Patch adds dmesg check for ndctl test using dmesg check decorator
=> ndctl.py: Add dmesg check for each test

perf/perf_nmem.py
Add nmem PMU test cases
Check for nmem PMUs in sysfs
Check for CONFIG_PAPR_SCM kernel configuration
Check for nmem PMU register messages in dmesg
Check PMUs found in sysfs and dmesg are matching
Count the number of PMU events
Run all events one by one per PMU
Run events by grouping per PMU
Run mixed PMU events - negative test case
Check PMU cpumask exists or not
Check cpumask is same for all the PMUs or not
Check cpumask by on and off cpu
=> perf_nmem.py: Add nmem PMU test cases

security/libgcrypt-tests.py
Add libgcrypt tests as part of security tests. These tests
exercise different cryptographic algorithms.
=> libgcrypt-tests.py: Add libgcrypt test cases

memory/ndctl_selftest.py
Add check for sysfs file exists or not.
With out this check, when sysfs file not exists it will result in error.
=> ndctl_selftest.py: checking for required sysfs file

memory/ndctl.py
With the latest avocado framework (commit "utils/partition.py: Fix fetching the
exact mount point") umount expect self.mountpoint to be set. Update
the test to track mount points so that an unmount is successful.
=> ndctl: Fix umount error with the test

memory/ndctl.py
This reverts commit adc42ae6a0a7e2ee7a7ba103214c8fb67febec3b.
Some of the tests like initializing the namespace with unsupported
alignment will result in dmesg logs. We should either split them into
different Test class or support indicating dmesg fail_on_error
per test. Until then revert the change.
=> Revert "ndctl.py: Add dmesg check for each test"

security/vTPM-tests.py
Adding vTPM test cases:
Device tree entry
dmesg entry
Kernel configuration
TPM devices presence
TPM binary measurement file
look in /proc/devices
=> vTPM-tests.py: Add vTPM test cases

io/disk/fiotest.py
libaio is pre-required package to run the fio tool.
the name of this package has changed from libaio to libaio1
So modified the script to handle the same
=> libaio package name, required for fiotest, has changed in Sles

ras/lparstat.py, ras/lparstat.py.data/options.yaml
Test lparstat command with a list of correct command line arguments and
in-correct command line arguments
=> lparstat.py: Add lparstat tests

io/net/virt-net/network_virtualization.py
Accomodating below changes:
- Keeping the rules in a single file
- Keeping the rules minimum
- Not calling the interface_naming() for now
=> udev rules for vnic interface

io/net/bridge.py
When bridge test was interrupted or avocado / os crash, the bridge setup
is not removed cleanly, so I have added pre test cleanup so the old bridge
interface is removed and sysfs files are deleted
=> bridge.py: fix unclean bridge setup from old runs

generic/stress.py
The stress-1.0.4.tar.gz link has been moved to another folder
so pointing the URL to the right folder
=> ERROR: Failed to fetch stress-1.0.4.tar.gz

io/net/tcpdump.py, io/net/tcpdump.py.data/tcpdump-virt.yaml, io/net/tcpdump.py.data/tcpdump.yaml, io/net/tcpdump.py.data/tcpdump_extended.yaml, io/net/tcpdump.py.data/tcpdump_extended_virt.yaml
This commit makes it possible to set a timeout for tcpdump, and
adds a timeout to all of the default config files.
Signed-off-by: Jacob Root <otis@otisroot.com>
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6811068/job.log)
=> Add timeout support to tcpdump

ras/ras.py
In Rhel9 rtas_event_code tool is failing so
changed the condition according to that
=> ras.py: Fix for rtas_event_code tool

io/disk/vfc-tests/virtual_fc.py, io/disk/vfc-tests/virtual_fc.py.data/README, io/disk/vfc-tests/virtual_fc.py.data/virtual_fc.yaml
there were some mpath and client_host verification issues and
naming conventions like define and undefine. I have changed to understandable
names like add and remove respectively. changing test names helps for quick
debug on occurance of any issues.
One more fix is kipping the bootable vfchost from testing list. earlier the script
used to collect all the vfchost data irrespective of whether it is bootable or
normal vfchost and used to perform unmap or remove operation on it which makes the OS
to get into read_only mode.
=> Resolving certain issues in virtual_fc.py

memory/libhugetlbfs.py
Patch removes condition kernel.check_version("2.6.16") which is not relevant anymore
=> Patch removes condition kernel.check_version("2.6.16")

memory/memhotplug.py
This patch fixes ERROR - "Failed to fetch stress-1.0.4.tar.gz" by updating the URL to fetch stress-1.0.4.tar.gz
=> Fix ERROR:Failed to fetch stress-1.0.4.tar.gz in memhotplug

io/net/virt-net/network_virtualization.py, io/net/virt-net/network_virtualization.py.data/multiple_vnic_nobacking.yaml, io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml, io/net/virt-net/network_virtualization.py.data/single_vnic_single_backing.yaml
Found a bug where I had a machine ltczep10 and another machine ltczep1. The test
would act on the latter machine because of the line `if line in self.lpar`.
This fix assumes the format of an LPAR
`<name_of_the_system>-lp<partiton_number>`.
=> virt-net: parsing for system name fix

README.rst
as avocado 91 onwards we defaulted nrunner as a runner , most of the misc test repository have  logic keeping in mind as   sequential run
=> Added section which relevent to avcoado 91 onwards

ras/kprobe.py, ras/kretprobe.py
Changed Makefile and strings to be check for kprobe.py, kretprobe.py to
eliminate compilation errors.
=> Correct the Makefile and strings to check

io/net/virt-net/network_virtualization.py
The interface takes around 30 to 60 secs for links to come
online after disable and enable the vnic interface
=> Add time delay after disable and enable test

io/disk/dbench.py, io/disk/dbench.py.data/dbench.yaml
1. Fixed to work for all the mux variants i.e device types
2. Fixed unclean test end after each test combination. added precleanup method
3. Input mount point to run test on test disk instead of local dir
4. Get proper logical device names lv, md etc to match to user inputs
5. Clear the disk metata data before test start, causing raid to fail
=> dbench.py: Unclean test end making setup unusable for other tests

io/pci/pci_hotplug.py, io/pci/pci_hotplug.py.data/README.txt, io/pci/pci_hotplug.py.data/pci_hotplug.yaml
After a adapter is hot_pluged and addded it back,
respective disk recovery check was not there.
instead it has some premitive check which is not enough.
So changed the code to take care the recovery check properly for Fc adapter.
we can also do for other adapters too.
=> Enhancing the recovery check for pci_hotplug.py

io/net/virt-net/network_virtualization.py
make sure the file name is generic to clean up control
files for lpar session and also hmc session
=> pre clean up control files for ssh

dlpar/cpu_unit.py, dlpar/dedicated_cpu.py, dlpar/dlpar_main.py, dlpar/memory.py
Fix has been added to take care of hmccmd for changing the profile and also added PowerVM only support for dlpar test runs.
=> Fixed hmccmd issue and added PowerVM only support

dlpar/dlpar_api/api.py
sendline-enabled command resulted in extra escape sequences, fixed by disabling enable-bracketed-paste off.
=> Fixes for pexpect when wrapping a sendline-enabled command

dlpar/cpu_unit.py, dlpar/dedicated_cpu.py, dlpar/memory.py
Added -w 0 option to disable time limit for dlpar operation. This option is must for larger value add/remove/move operations.
=> Dlpar -w 0 option added

cpu/ppc64_cpu_test.py, cpu/ppc64_cpu_test.py.data/ppc64_cpu_test.yaml
ppc64_cpu_test use 100 as a count for loop test. On systems with large number
of processors it takes several minutes to complete the execution.
Add a configurable yaml option 'test_loop' for loop count.
=> ppc64_cpu_test: Configurable yaml option for loop count

nx_gzip/nx_gzip.py
While using default 'master' branch of libnxz library code nx-gzip
test complains about missing configure script:
./configure: No such file or directory\n'\nadditional_info: None
configure script is only available with 'develop' branch.
Add a check for git branch to select correct build procedure.
Also fix indentation issues.    
=> nx-gzip: Fixes for compilation failure and indentation

memory/ndctl.py
Update NdctlTest.setUp() to accept a new value 'local' for test param
'package' that can be used to run NdctlTest against locally built
ndctl/daxctl binaries from the ndctl source tree. The path to the
ndctl build directory can be provided by the newly introduced
'location' test param that defaults to current directory.
With this patch following command can be used to execute NdctlTest
again locally built ndctl/daxctl binaries:
$ avocado run memory/ndctl.py -p package=local -p
location=/src/ndctl/build
Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>
=> ndctl.py: Add support for testing localy built binaries

io/common/bootlist_test.py
netifaces is required for only network related data collections,
and not for disk related stuff. bootlist is common test for both net
and block devices. Hence to avoid netifaces installation for block devices
test case, replacing netifaces usage with OS.listdir which servers the same
purpose in this case.
=> Removing netifaces from bootlist.py

fs/xfstests.py
added code to remove dump package to run xfstest
as it is no more supported in rhel9
=> remove dump package support in rhel9

toolchain/ltrace.py, toolchain/ltrace.py.data/ltrace.yaml
ltrace test fails to fetch ltrace source code and reports following error:
(1/1) toolchain/ltrace.py:Ltrace.test: ERROR: Command '/usr/bin/git fetch -q -f -u -t git@gitlab.com:cespedes/ltrace.git master:master' failed.\nstdout: b''\nstderr: b'git@gitlab.com: Permission denied (publickey,keyboard-interactive).\r\nfatal: Could not read from remote repository.\n\nPlease make sur... (0.61 s)
RESULTS  : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
Update the upstream url to point to https git repository.
=> toolchain/ltrace - Fix git repository url

io/net/bonding.py
Bug fix for the mtu changes for bond interface.
Ping test was reporting PASS even if the ping test failed
=> Ping test for bond with different mtu

cpu/pvr.py
Contains following fixes:
[Patch 1/2] : Code tidy-up to fix few code style warnings
[Patch 2/2] : test fails on POWER8 hardware with following error:    
(1/1) cpu/pvr.py:pvr.test: ERROR: Unsupported processor family (2.69 s)
Separate the logic to check for POWER8 pSeries and PowerNV platforms.
=> cpu/pvr: Fix error while running on POWER8 processor

perf/perf_genericevents.py
for failed events it was not showing event name,
added code to show event name in proper order
=> fixed perf_genericevents.py

toolchain/strace.py, toolchain/strace.py.data/strace.yaml
strace test supports upstream as the only target. 
Add a yaml file so that in addition to upstream, user can specify 
distro as a target. Default option is set to distro.
=> toolchain/strace: Add support to run with distro as a target

cpu/cpupower_monitor.py
[patch 1/2] Fix few code style warnings.
[patch 2/2] If cpupower utility is not installed the CpupowerMonitor test fails with following error:
ERROR: 'CpupowerMonitor' object has no attribute 'states_list'
Make sure cpupower utility is installed.
=> cpu/cpupower_monitor: Fix test error in case cpupower utility is not installed.

toolchain/glibc.py
glibc test errors out with following messages:
(1/1) glibc.py:Glibc.test;run-run_type-distro-a853:
ERROR: invalid literal for int() with base 10:
Fix this error by adding a isdigit check.
Also fix a >80 characters warning.
=> toolchain/glibc: Update result parsing logic to avoid test errors

io/driver/module_unload_load.py
current script checks the partial match for dependent modules from config file.
this is failing for closely same module names like 'nvme' and nvme_core.
So modified the script for exact match so that it fetches right dependent
sub_module
=> script fix for exact sub_module match from config file for module_unload_load.py

ras/lparnumascore.py
lparnumascore command is available for SuSE distro releases.
Remove the code restriction accordingly
Also fix code style warning.
=> ras/lparnumascore: Update supported distro release check

toolchain/gcc.py, toolchain/gcc.py.data/gcc.yaml
gcc test case by default downloads latest upstream code and runs the
selftests that comes with it. There is no option to use gcc tests
bundled with source pacakge available in a Linux distribution release.
Add support for distro as a target via a yaml file.
=> toolchain/gcc : Add support for distro as a target

ras/lparstat.py
lparstat command is packaged differently on various Linux distribution
releases. Add code to detect distro and accordingly install appropriate package.
Code changes to fix code style warning.
=> ras/lparstat: Fix package dependency

perf/perf_24x7_all_events.py, perf/perf_24x7_hardware_counters.py
removed cpu dependency to run with all the cpus present system wide
updated correct string for performance info collection property
enabled in hmc was not working
=> removed cpu dependency in perf_24/7 scripts

toolchain/valgrind.py, toolchain/valgrind.py.data/valgrind_source.yaml
script is updated so that it can pick the latest valgrind  version automatically
whenever its available.
Signed-off-by: preeti thakur <preeti.thakur@in.ibm.com>
[root@ltcever87-lp6 toolchain]# avocado run --test-runner runner valgrind.py
Fetching asset from valgrind.py:Valgrind.test
JOB ID     : a23ac84f87a1ee57703a9af355ab0b81dc54b4f6
JOB LOG    : /root/preeti/avocado-fvt-wrapper/results/job-2022-04-20T08.14-a23ac84/job.log
(1/1) valgrind.py:Valgrind.test:  PASS (1966.78 s)
JOB HTML   : /root/preeti/avocado-fvt-wrapper/results/job-2022-04-20T08.14-a23ac84/results.html
JOB TIME   : 1997.65 s
=> updated the script to pick latest version

ras/vpa_MaxMem_check.py
On a logical partition(LPAR) running Linux, number of online logical processors
aren't necessarily same as number of possible/configured logical processors.
This data is dependent on how the LPAR has been configured(minimum vs
desired vs maximum possible in LPAR profile).
On a LPAR configured with 48 available logical processors but 128 maximum
logical processors, the test fails as lscpu returns 48 processors while vpa
data is available for 128 possible processors.
Current logic to compare vpa data relies on lscpu o/p which only captures
online processors data. Instead obtain possible cpus data via sysfs
and compare it with vpa data.
=> ras/vpa_MaxMem_check: Update logic to compare vpa data

perf/perf_core_imc_non_zero_event.py
added code to check core imc events are available or not
[root@ltc-wcwsp3 perf]# avocado run --test-runner runner perf_core_imc_non_zero_event.py
JOB ID     : e7b0f3f0e1337739cd2f01b0f60ef4e32cd46d9b
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-04-21T05.42-e7b0f3f/job.log
(1/2) perf_core_imc_non_zero_event.py:PerfCoreIMCNonZeroEvents.test_perf_cpm_cyc: PASS (11.07 s)
(2/2) perf_core_imc_non_zero_event.py:PerfCoreIMCNonZeroEvents.test_perf_cpm_32mhz_cyc: PASS (10.88 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-04-21T05.42-e7b0f3f/results.html
JOB TIME   : 43.41 s
[root@lep8d perf]# avocado run --test-runner runner …
=> check_perf_core_imc_availability

io/net/bonding.py
ip addr add command for given test interface is exiting with
non zero exit code and failing the test, this patch will make
sure old ip is deleted before configuring new ip
Running 'ip addr add 115.10.10.197/24 dev enP49156p1s0'
[stderr] RTNETLINK answers: File exists
Command 'ip addr add 115.10.10.197/24 dev enP49156p1s0' finished with 2
after fix
Running 'ip addr flush dev enP49156p1s0'
Command 'ip addr flush dev enP49156p1s0' finished with 0
Running 'ip addr add 115.10.10.197/24 dev enP49156p1s0'
Command 'ip addr add 115.10.10.197/24 dev enP49156p1s0' finished with 0
=> bonding.py: ip address add fail if interface already configured

generic/stress-ng.py
As recetly in SLES15-SP4 test case is failing and that is due to actual build failure
but while running it shows Unsupported OS and that give False positive as test case was
working earlier
=> Patch address False alarm

cpu/producer_consumer.py
On sles15sp4 test is failing due to number of spaces mismatch, fixed this error.
=> Fixed out of index error.

perf/perf_duplicate_probe.py
perf/perf_duplicate: Fix code style warnings
Rename output variable to fix code style warnings.
Shorten the failure message as well to avoid code style warning.    
perf/perf_duplicate: Fix wrong package dependency
Testcase has a wrong package dependecy on kernel-default-base-debuginfo.
Change it to kernel-default-debuginfo.
=> perf/perf_duplicate: Minor testcase fixes

fs/xfstests.py, fs/xfstests.py.data/nvdimm.yaml
fixed UnicodeDecodeError and PMemException on namespace destroy
added ext4/048 in exclude list
JOB ID     : bb5c562cbb6087b427f249dee672d5b0beeeedc2
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-04-27T23.13-bb5c562/job.log
(1/2) xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_ext4-7fa0:  FAIL: One or more tests failed. Please check the logs. (2215.96 s)
(2/2) xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_xfs-e0a0:  FAIL: One or more tests failed. Please check the logs. (8930.24 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 1 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-04-18T16.34-4cb50de/results.html
JOB TIME   : 11246.2 s …
=> fix xfstest on pmem devices

kernel/kernbench.py
SLES distro specific config based upstream kernel source build fails with
following error:
No rule to make target '.kernel_signing_key.pem', needed by
'certs/signing_key.x509'.  Stop.
This is due to certain trusted/module signature key related options enabled
in the config. Extend the kernel config option fix function to also cover
SLES variant.
While at it also fix a code style warning.
=> kernel/kernbench: Fix kernel compile error on SLES

kernel/kselftest.py
patch enabled in case of test case not available or compilation fails
Reported-by:   Geetika <geetika@linux.ibm.com>
=> Patch address issue in case ksm bin not present

perf/perf_genericevents.py.data/raw_code.cfg
replaced mem-loads and mem-stores with new values on P10
as per commit https://github.com/torvalds/linux/commit/66d9b7492887d34c711bc05b36c22438acba51b4
before fix:
avocado run --test-runner runner perf_genericevents.py
JOB ID     : 03ef5d881ddf80033266c8986ae078f9c47a1379
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2022-05-04T15.18-03ef5d8/job.log
(1/1) perf_genericevents.py:test_generic_events.test: FAIL: Failed to verify generic PMU event codes (0.52 s)
JOB HTML   : /home/disha/avocado-fvt-wrapper/results/job-2022-05-04T15.18-03ef5d8/results.html
JOB TIME   : 9.22 s
after fix:
avocado run --test-runner runner perf_genericevents.py
JOB ID …
=> fix-perf_genericevents-P10

ras/smtstate.py
Existing check to detect distribution versions which support smtstate
tool is broken. The test will cancel out while running on any new major
versions for example RHEL9.0.
Simplify the code to detect and check distribution releases and versions,
also fix the warnings reported by pycodestyle.
=> ras/smtstate: Simplify and fix distribution release/version checks

fs/xfstests.py, fs/xfstests.py.data/btrfs-subpage.yaml
Modify fs/xfstests.py to pull and make fsprogs like e2fsprogs,
xfsprogs and btrfsprogs from upstream. This feature is useful
when testing upstream kernels and especially to be able to
correctly test btrfs subpage support, since the distro provided 
btrfs versions don't have the latest features/patches needed.
To test for upstream, we can use the run_type option in the
yaml. We also need to specify the upstream URLs of the fsprogs
we want to install, eg:
...
upstream:
run_type: 'upstream'		# Test with upstream fsprogs
xfsprogs_url: 'https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git'
e2fsprogs_url: 'https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git'
btrfsprogs_url: 'https://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git'
distro:
run_type: 'distro'		# Test with distro …
=> Add support to use upstream fsprogs while testing

kernel/kselftest.py
Newer Linux distribution releases no longer ship libhugetlbfs packages.
This breaks ksefltest.
Remove the dependency on this package with newer distributions.
=> kernel/kselftest: Remove dependency on libhugetlbfs package

memory/ndctl.py, memory/ndctl.py.data/ndctl.yaml
The pull request addresses below changes -
1. Extending support for meson way of building ndctl library
2. Extending support for backward compatibility to support the older versions of ndctl
3. Added a field to the ndctl.yaml file to hold the specific version of ndctl
4. Addressed & accommodated the challenges arising due to the deviation in the placement of header file : iniparser.h
=> NDCTL : Extending support towards meson way of building the library

io/net/bonding.py, io/net/bonding.py.data/bonding.yaml, io/net/bonding.py.data/bonding_mode0.yaml, io/net/bonding.py.data/bonding_mode1.yaml, io/net/bonding.py.data/bonding_mode4.yaml, io/net/bonding.py.data/bonding_single.yaml, io/net/bonding.py.data/bonding_virtual.yaml
I have increased the Time required for the interfaces in Peer machine to come up and Generic Sleep time used in the test to 20 and 10 seconds respectively in the bonding yaml files
This is needed since it has been observerd that for interface ports of the different Network adapters we need more time to bring up their corresponding interfaces while executing bonding tests
=> Increased the wait time and sleep time in the .yaml files

io/disk/disktest.py
If the device total space is lower than 1073741824 bytes, then user needs to provide device with greater than 1 Gigabye size
Also checking if the variables gigabytes and self.chunk_mb values are zero, then thrown an error message
=> Checking on the input device total space available for testing

kernel/kselftest.py, kernel/kselftest.py.data/README, kernel/kselftest.py.data/kselftest_comp.yaml, kernel/kselftest.py.data/ksmtest.yaml
commit 730a557eb457 added support to run ksm_tests which is a subset of
tools/testing/selftests/vm tests. As a side effect running any kernel selftest
also unconditionally pulled in  ksm test.
This 3 patch series introduces a "subtest" YAML key:value pair which can be
used to specify a subset of tests to be executed. This key:value pair parameter
is then used to detect if ksm_tests or any other sub test is to be executed.
[PATCH 1/3] kernel/kselftest: Add support to run subset of kernel selftests
[PATCH 2/3] Update component specific YAML file to reflect subtest
Update component specific YAML file to reflect the added subtest key value
pair.
[PATCH 3/3] kernel/kselftest: Update the documentation
Update the documentation to reflect the usage of newly added subtest
key value pair. This …
=> kernel/kselftest: Add support to run subset of kernel selftests

toolchain/gcc.py
Gcc test case has a dependency on docbook package. The code assumed
docbook5-style-xsl package with RHEL 8.x.
RHEL 8.x ships docbook-style-xsl, fix the code accordingly.
=> toolchain/gcc: Fix docbook5 dependency

io/net/virt-net/network_virtualization.py
Test should cancel if it cannot find a logical port of a backing device. Often
the test fails with a message like "logport was assigned before declaration".
This gives it a more descriptive message.
=> [net] virt-net: logport assigned out of scope

memory/ndctl_selftest.py, memory/ndctl_selftest.py.data/ndctl_selftest.yaml
Removed implementations for upstream.patch and ppc.patch.
=> Fix for Distro: NDCTL Upstream Test Failing issue.

fs/xfstests.py
fixed userdel error while running xfstests.py
avocado run --test-runner runner xfstests.py -m xfstests.py.data/xfstests_ext4.yaml 
JOB ID     : fb82f1886d1220a568ab70274d2870758f3ae56f
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2022-05-25T17.59-fb82f18/job.log
(1/1) xfstests.py:Xfstests.test;run-setup-fs_type-fs_ext4-loop_type-disk-e481: PASS (106.44 s)
JOB HTML   : /home/disha/avocado-fvt-wrapper/results/job-2022-05-25T17.59-fb82f18/results.html
JOB TIME   : 115.42 s
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/8771156/job.log)
=> fix xfstest userdel error

memory/hugepage_sanity.py
This patch cancels the test for those sizes of hugepages which are not supported in the environment.
=> Cancel the test for the hugepage sizes that are not supported.

perf/perftool.py
fixed perftool test case by spliting two tests
and showing correct status
avocado run --test-runner runner perftool.py 
Fetching asset from perftool.py:Perftool.test_perf_test
Fetching asset from perftool.py:Perftool.test_perf_testsuite
JOB ID     : 3ddb12794843ac2f3dddf339aed7ebcb2b8d5757
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2022-05-25T22.49-3ddb127/job.log
(1/2) perftool.py:Perftool.test_perf_test: FAIL: 2 Test failed (53.99 s)
(2/2) perftool.py:Perftool.test_perf_testsuite: FAIL: 2 Test failed (303.74 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/disha/avocado-fvt-wrapper/results/job-2022-05-25T22.49-3ddb127/results.html
JOB TIME   : 366.50 s …
=> enhance perftool

io/genwqe/genwqetest.py
Initialize files_used and dirs_used in genwqe before checking if we want to cancel the test. Otherwise if the test is canceled we get a crash in tearDown due to missing files_used and dirs_used attributes.
=> Avoid exception in genwqe when canceling the test

cpu/cpustress.py, cpu/ppc64_cpu_test.py
confusing message when running on other arch - such as 'PPC64Test object doesn't have curr_smt attribute'.
This comes from the fact that we cancel the test in the setUp routine before initializaing the variables but then we use these variables in the tearDown.
This commits fix ppc cpu tests to check necessary attributes before using them in the tearDown.
=> Fix confusing failure messages in ppc cpu tests launched on non-ppc arch

ras/sosreport.py
JOB ID     : 38a35f2d6fc40f3ec2eca994b90438d1a0316eb3
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-05-26T23.13-38a35f2/job.log
(1/6) sosreport.py:Sosreport.test_short;run-ed60: PASS (131.76 s)
(2/6) sosreport.py:Sosreport.test_user;run-ed60: PASS (439.14 s)
(3/6) sosreport.py:Sosreport.test_plugins;run-ed60: PASS (135.37 s)
(4/6) sosreport.py:Sosreport.test_others;run-ed60: PASS (208.82 s)
(5/6) sosreport.py:Sosreport.test_archive;run-ed60: PASS (127.90 s)
(6/6) sosreport.py:Sosreport.test_PPC;run-ed60: PASS (11.40 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-05-26T23.13-38a35f2/results.html
JOB TIME   : 1055.04 s
=> Sosreport fix 14

memory/libhugetlbfs.py
libhugetlbfs package is not available in RHEL9.* hence the test case will be canceled
Signed-off-by: spoorthy <spoorts2@in.ibm.com>
=> Cancel libhugetlbfs tests on RHEL9*

perf/perf_sdt_probe.py
fixes below error
no SDT markers available in the /usr/lib64/libpthread.so
on SLES15 SPx
localhost: # avocado run --test-runner runner perf_sdt_probe.py
JOB ID     : cc9e43bd861bbb131692a46c32c6f3d935639462
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-06-03T21.33-cc9e43b/job.log
(1/1) perf_sdt_probe.py:PerfSDT.test: PASS (7.18 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-06-03T21.33-cc9e43b/results.html
JOB TIME   : 32.56 s
on RHEL 9.x
avocado run --test-runner runner perf_sdt_probe.py
JOB ID     : 302ae2ddb3604e222ce673afb6daede74ea60511
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2022-06-03T17.38-302ae2d/job.log …
=> fix perf_sdt_probe

io/driver/driver_parameter_block_device.py
dd command was not working with bs value as 1M and count as 102400 with different mux
So updated bs value to 512 and count to 1024 in dd command and
increased the timeout values for wait functions from 90 to 150 for multipath flush and recovery
before unloading and loading the driver with different parameters.
Signed-off-by: Srimannarayana Murthy Maram <murthymaram@li-675158cc-3534-11b2-a85c-d6f0e482d217.ibm.com>
=> Changing the dd command and timeout values for multipath in driver_parameter_block_device.py

cpu/xive.py
Linux kernel commit baed14de78b5 changed the debugfs file 'xive' into a
directory. When executed against a kernel containing this patch, the
testcase fails. This three patch series enhances the code.
cpu/xive: Handle xive as a directory or file
Enhance the test case to handle this condition.
cpu/xive: Reword fail messages for better clarity
Rewrite failure messages to provide clarity about the reason
cpu/xive: Few cosmetic and code style warn fixes
Fix few code style related warning.
=> cpu/xive: Test case enhancement to handle xive as directory

perf/perf_pmu.py
replaced fail with cancel in case of events not found
added check for power8 powernv
before fix on P8 powernv:
avocado run --test-runner runner perf_pmu.py
JOB ID     : 53662188a16efe6929b6f844e7097cd1c07d6bdc
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2022-06-06T06.27-5366218/job.log
(1/9) perf_pmu.py:PerfBasic.test_PMU_register: PASS (1.82 s)
(2/9) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: ERROR: 'power8e' (1.53 s)
(3/9) perf_pmu.py:PerfBasic.test_config_PPC_RTAS: SKIP: This test is for PowerVM
(4/9) perf_pmu.py:PerfBasic.test_cpu_event_count: PASS (1.42 s)
(5/9) perf_pmu.py:PerfBasic.test_hv_24x7_event_count: SKIP: This test is for PowerVM
(6/9) perf_pmu.py:PerfBasic.test_imc_event_count: FAIL: sysfs core_imc folder …
=> fix perf_pmu

ras/ras_tools.py
when we have multiple indicators on system, it is failing.
Modified the script to pick one indicator
=> usysattn/usysfault -l -s normal -t command failed to execute

io/disk/ioping.py, io/disk/ioping.py.data/README, io/disk/ioping.py.data/ioping.yaml
I have made the default value of count to 8 in the test case script ioping.py file also to be in sync with the yaml file parameter values
Also, created a README file inside ioping.py.data/ directory which was missing and moved the ioping Usage commented content lines in yaml file to this README file
=> made the default value of count to 8

memory/ndctl.py, memory/ndctl_selftest.py, memory/ndctl_selftest.py.data/ndctl_selftest.yaml
This PR addresses the below changes - 
1] Enabled meson build for ndctl
2] Added ndctl version in yaml file
3] Header file checks for iniparser.h
4] Incorporated code changes of PR#2330 : https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2330
5] ndctl.py : removed a conditional check that was meant for SLES15
=> memory/ndctl_selftest.py : Enabled the support for meson build

memory/ndctl.py, memory/pmem_dm.py, memory/pmem_dt_check.py, ras/lparstat.py, security/selinux-tests.py
Some tests are only intended for RHEL / SLES, and produce confusing failure messagescaused by the fact that some variables are not initialized in setUp but used in the tearDown (so we get an missing attribute Exception instead of a clear statement about unsupported system).
Proposed solution is like the following:
- In memory/pmem* and ndctl, let's check if we have corresponding attributes set before trying to use them
- In selinux-tests, we can initiate the problematic variable to None in the beginning and then use it only if it is not empty
- ras/lparstat is just missing explicit test cancelation for the OS other than rhel/suse.
=> Fix unclear failure messages when running tests on unsupported OS (Ubuntu)

perf/trace.py.data/README, perf/trace.py.data/trace.yaml
Update YAML file to match with ftrace kselftest subtests available with upstream Linux kernel
Also add a README with pointer to upstream kernel ftrace kselftest documentation.
=> perf/trace: add missing subtests to yaml file

ras/packages.py, ras/packages.py.data/list.yaml
powerpc-utils is split into 2 packages powerpc-utils
and powerpc-utils-core
=> Packages.py:Added check for powerpc-utils-core package

io/disk/disk_info.py, io/disk/fs_mark.py, io/driver/driver_parameter.py, io/driver/driver_parameter_block_device.py, io/net/sriov_device_test.py, io/net/switch_test.py, io/net/tcpdump.py, io/net/uperf_test.py, io/pci/dlpar.py, perf/perf_cpu_hotplug.py, perf/perf_genericevents.py, perf/perf_sdt_probe.py
Now, depending on the test, we either init the variables used in tearDown before
the test cancel or check if we have necessary attribute before using it in tearDown.
=> Avoid exceptions in tearDown of io and perf tests when canceling

io/disk/arcconf/arcconf_cntl_oper.py, io/disk/arcconf/arcconf_drive_oper.py, io/disk/arcconf/arcconf_migration.py, io/disk/arcconf/arcconf_raid_oper.py, memory/memory_api.py, perf/perf_core_imc_non_zero_event.py, perf/perf_metric.py, perf/perf_nmem.py, perf/perf_pmu.py
Newer versions of avocado (>v93.0) deprecated usage of
allow_output_check suboption in various process. api's.
Update various test cases which still use this suboption.
Remove this option wherever applicable. In cases where
both stdout & stderr is required build output
using stdout + stderr before processing.
=> Remove allow_output_check deprecated option

perf/perf_cpu_hotplug.py
added code to run script in compat mode instead of
power model using pvr value
before patch getting below error:
10:52:20 INFO    : Running: /usr/local/bin/avocado run --nrunner-max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_cpu_hotplug.py --force-job-id 9a147f41de859e1451670717ae82495667280e2e  --job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : 9a147f41de859e1451670717ae82495667280e2e
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-06-30T10.52-9a147f4/job.log
(1/2) /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask: STARTED
(1/2) /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_cpu_hotplug.py:perf_cpu_hotplug.tes …
=> fix compat mode perf_cpu_hotplug

README.rst
stress.py moved from test/ to generic/ in commit cb5f9fac40b0,
so update the README so that a reader could successfully copy-paste
this example.
Signed-off-by: Russell Currey <ruscur@russell.cc>
=> README: Fix directory of stress test

memory/numa_test.py
Test case failed because some kernel builds were not enabled for THP migration. When the ARCH_ENABLE_THP_MIGRATION macro is set into the kernel configuration then only the system will support THP migration. Also, we can check if THP migration is supported on the current system using "enable_thp_migration". Also, THP migration is enabled and disabled via
/sys/kernel/mm/transparent_hugepage/enable_thp_migration file.
=> Fix for numa_test failing issue.

security/libkmip-tests.py
security/libkmip: Remove deprecated allow_output_check switch
Remove this switch to avoid test failure.
security/libkmip: Fix incorrect test execution
libkmip selftests are invoked incorrectly using ./tests . Fix it accordingly
=> security/libkmip: Couple of miscellaneous fixes

toolchain/ltrace.py
removed patch as its not supported
Signed-off-by: preeti thakur <preeti.thakur@in.ibm.com>
the errors shown are specific to ltrace for which jira task is created
https://jsw.ibm.com/browse/LOP-4159
[root@ltcever60-lp15 toolchain]#  avocado run --test-runner runner ltrace.py
JOB ID     : c45de0753a03b156233c15875084132537ef6fd6
JOB LOG    : /root/Preeti/avocado-fvt-wrapper/results/job-2022-07-12T03.41-c45de07/job.log
(1/1) ltrace.py:Ltrace.test:  [ 6405.626601] filt[54717]: unhandled signal 5 at 00007fffa7b4d464 nip 00007fffa7b4d464 lr 00007fffa7b4d464 code 1
[ 6406.854923] filt.pie[54770]: unhandled signal 5 at 00007fff9b6bd464 nip 00007fff9b6bd464 lr 00007fff9b6bd464 code 1
FAIL: 45 test(s) failed, check the log for details. (51.97 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | …
=> updated script

kernel/kernbench.py
This commit:
1. Fixes kernbench testrun failure on ubuntu and rhel.
2. Adds a missing build dependecy package for Ubuntu distro.
Signed-off-by: Srikanth Aithal <srikanth.aithal@amd.com>
=> Fix kernbench test on Ubuntu,RHEL

ras/ras_extended.py
Locking mechanism prevents corruption of DB file when running vpdupdate.
This tests database (vpd.db) locking mechanism when multiple instances
of vpdupdate and lsvpd are running simultaneously.
=> ras_extended.py: Added locking mechanism testcase

memory/transparent_hugepages_defrag.py
THP defrag test fails with following syntax error:
self.device.mount(mountpoint=self.mem_path, fstype, mnt_check=False)
^
SyntaxError: positional argument follows keyword argument
commit 3237c43d2168 changed the keyword arg to positional. This
patch reverts that change.
=> memory/thp_defrag: Fix syntax error

io/net/netperf_test.py
Existing code copies the dir instead of tar file, messing up
the path and make command failing with below error
/usr/bin/ld/usr/bin/ld: : nettest_omni.o:(.bss+0x200): multiple
definition of `loc_nodelay'nettest_omni.o; :(.bss+0x200): multiple
definition of `loc_nodelay'; nettest_bsd.o:(.bss+0x28): first defined here
=> netperf build over peer is failing due to path issues

perf/perf_pmu.py
test_PMU_register subtest searches for a particular text string
in dmesg log. This may not work if the dmesg log has been cleared
by previous test.
There are other subtests related to PMU sysfs check as well as
kernel config check this test seem to be unnecessary.
Given the error prone nature remove this subtest.
=> perf/perf_pmu: Remove PMU register test

io/disk/bonnie.py, io/disk/dbench.py, io/disk/fiotest.py, io/disk/fs_mark.py, io/disk/iozone.py, io/disk/ltp_fs.py, io/disk/ltp_fsstress.py, io/disk/lvsetup.py, io/disk/softwareraid.py, io/disk/tiobench.py
[1] changed md raid name same as other test
dbench and software raid has mdsraid, changed to sraid
as in line with all other disks tests using sraid
[2]  block tests are failing due to vgcreate hung
sometimes vgcreate never completes waiting for 'y' input
from userspace, so this patch made sure the vgcreate command
is automatic
```
[stdlog] 2022-08-05 00:30:52,406 avocado.utils.process INFO | Command 'fdisk -l /dev/md/sraid' finished with 0 after 0.001004789s
[stdlog] 2022-08-05 00:30:52,406 avocado.utils.process INFO | Running 'vgdisplay avocado_vg'
[stdlog] 2022-08-05 00:30:52,417 avocado.utils.process DEBUG| [stderr]   Volume group "avocado_vg" not found
[stdlog] 2022-08-05 00:30:52,417 avocado.utils.process DEBUG| [stderr]
[stdlog] 2022-08-05 00:30:52,417 avocado.utils.process DEBUG| …
```
=> Block tests case fixes 

security/vTPM-tests.py
vTPM device is not constant on all the systems. This patch identifies the
vTPM device instead of hardcoding.
=> vTPM-tests.py: generalise the vTPM device name

io/common/distro_tools.py
option -a is not supported as of now. this will exit with non-zero
return code. And it is accepted as of now. So cancelling the test
for this option.
=> Cancelling the test distro_tools.py for -a option

io/disk/disktest.py.data/disktest.yaml
for larger size disks like nvme, this is utilizing the complete root space
to run the test when no_fs option is given and hence, OS will be left with
no space and other runs are failing. hence removing the no_fs support for
the disktest.
=> removing the no_fs support for disktest.py

io/disk/ssd/nvme_cli_selftests.py, io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
test was failing due to recent changes to the selftest.
so added the "--start-dir tests" so that it runs without any issue.
Also removed writeuncor test from yaml as it is not recommended
based on recent issues seen on nvme namespaces, i.e it disrupts the disk.
=> fixing the way nvme_cli_selftest.py runs.

perf/perf_sdt_probe.py
fixes error 'No SDT markers available' after adding probe event, not
listed in perf list immediately which resulted in failure
avocado run --test-runner runner perf_sdt_probe.py
JOB ID     : 44c89e5fb4f3473dfecaef16b777bec38f9b82dd
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-08-08T22.51-44c89e5/job.log
(1/1) perf_sdt_probe.py:PerfSDT.test: PASS (11.97 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-08-08T22.51-44c89e5/results.html
JOB TIME   : 26.52 s
=> fix-perfsdtprobe

generic/ltp.py.data/ltp-fs.yaml
added ltp-fs.yaml file to run ltp tests related to file system
[root@ltcrain108-lp1 generic]# avocado run --test-runner runner ltp.py -m ltp.py.data/ltp-fs.yaml
Fetching asset from ltp.py:LTP.test
Fetching asset from ltp.py:LTP.test
JOB ID     : 3bde13fae2af65b2139376a06c9537fc4a8f31b4
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2022-08-05T08.55-3bde13f/job.log
(1/4) ltp.py:LTP.test;run-runltp-fs-b8b1: PASS (1386.32 s)
(2/4) ltp.py:LTP.test;run-runltp-fs_perms_simple-2f68: PASS (139.40 s)
(3/4) ltp.py:LTP.test;run-runltp-fsx-b11a: PASS (141.26 s)
(4/4) ltp.py:LTP.test;run-runltp-fs_bind-d2ad: PASS (142.46 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : …
=> add ltp-fs.yaml

fs/filebench.py.data/filebench.yaml
changing predefined workload file name as per README
before patch:
[root@ltcden4-lp19 fs]# avocado run --test-runner runner filebench.py -m filebench.py.data/filebench.yaml
Fetching asset from filebench.py:Filebench.test
JOB ID     : b7732cf4b2dba8c7b7b0ae59174b05b007442c0d
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-08-10T08.35-b7732cf/job.log
(1/1) filebench.py:Filebench.test;run-filebenchrun-fb15: ERROR: Command '/home/avocado-fvt-wrapper/results/job-2022-08-10T08.35-b7732cf/test-results/tmp_dir4thb_xqk/1-filebench.py_Filebench.test_run-filebenchrun-fb15/install_prefix/bin/filebench -f /home/avocado-fvt-wrapper/results/job-2022-08-10T08.35-b7732cf/test-re... (8.96 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | …
=> fix_filebench.yaml

io/common/distro_tools.py
Make sure net-tools package is installed else cancel
the test
=> distro-tools: install net-tools pkg before test

perf/perf_script_bug.py, perf/perf_script_bug.py.data/probe.cfg
Current perf_script_bug test code only supported with RHEL, SLES.
So added Ubuntu support.
=> perf/perf_script_bug: Add Ubuntu support

io/net/netperf_test.py
when untaring netperf suite on peer, make sure you give
the tarball name instead a wrong path, this was a typo fix
from previous PR
=> netperf: provide the tar file name instead full path

io/net/iperf_test.py
When the iperf speed is in Kbits/sec the variable 'tput' was remained unassigned and test case was failing as there was no condition provided in code to handle this speed.
Action taken : Added and elif condition to capture the iperf speed in Kbits/sec and fail the test case with warning as the throughput will be less.
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
=> IO : iperf local variable 'tput' referenced before assignment

ras/lshw.py
Existing "lshw" test code uses device-tree to get Product Name and
Serial Number, which works for powerpc. On x86_64 platform, used "dmidecode" to get
Product/Seiral info.
=> Add "x86_64" check to get product name and serial number from dmidecode

io/net/uperf_test.py
include lksctp-tools-devel in the pkg list for
uperf to compile successfully on host and peer machines.
=> uperf compliation failed due to missing package

io/net/virt-net/network_virtualization.py
Test is now failing with expected messages so
added the string to skip message
=> Skip expected dmesg error to not fail test

kernel/kselftest.py.data/net.yaml
fixing ERROR: Multiple  leaves contain the key 'comp'; ['/run/component/net=>net', '/run/run_type/distro=>distro']
=> fix net.yaml to eliminate duplicate 'comp'

kernel/kselftest.py.data/ftracetest.yaml
Add yaml file to run ftracetest with kselftests
Signed-off-by: Akanksha J N <akanksha@linux.ibm.com>
avocado run --test-runner runner kselftest.py -m kselftest.py.data/ftracetest.yaml 
JOB ID     : 47c31a57ba03ad42b41e55f55387b3323eb9625c
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-09-14T01.56-47c31a5/job.log
(1/2) kselftest.py:kselftest.test;run-component-ftrace-run_type-distro-7b46: FAIL: Testcase failed during selftests (106.06 s)
(2/2) kselftest.py:kselftest.test;run-component-ftrace-run_type-upstream-2f43: FAIL: Testcase failed during selftests (408.99 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-09-14T01.56-47c31a5/results.html …
=> add_ftrace_yaml

generic/ipistorm.py, ras/lparstat.py
Enable following tests to run on Ubuntu
- generic/ipistorm.py
- ras/lparstat.py
=> Update few tests to support Ubuntu distro

generic/ltp.py.data/ltp-security-stress.yaml, generic/ltp.py.data/ltp-security.yaml
split the ltp security tests in to two categories
ltp-security.yaml: contains the security tests
ltp-security-stress.yaml: contains the security stress tests
=> ltp.py: split security tests in to normal and stress

io/pci/pci_info_lscfg.py, io/pci/pci_info_lscfg.py.data/Readme.txt
Test case fetch the information from lscfg of pci devices using
pci adress and compares this data with lspci data. Comparision is
done for all the pci devices available in the server.
Signed-off-by: Maram Srimannarayana Murthy <Maram.Srimannarayana.Murthy@ibm.com>
=> Validating lscfg information against lspci information

ras/vpa_MaxMem_check.py
This two patch series add support for Ubuntu OS
[Patch 1/2] ras/vpa_MaxMem_check: Add package dependeny
Add a check to ensure lparstat utility is installed on the systems. This is in preparation for patch 2.
[Patch 2/2] ras/vpa_MaxMem_check: Add Ubuntu support
Extend the support to include Ubuntu distribution.
=> ras/vpa_MaxMem_check: Extend OS support

perf/perf_24x7_all_events.py
some of the events were failing with domain value 1 
as per domain interface, updated domain range to start with 2 instead of 1 as we have condition to run chip events separately
1: Physical Chip
2: Physical Core
3: VCPU Home Core
4: VCPU Home Chip
5: VCPU Home Node
6: VCPU Remote Node
avocado run --test-runner runner perf_24x7_all_events.py
JOB ID     : f23598aeab31443d8727cebaaf5284556a501867
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-15T19.47-f23598a/job.log
(1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: PASS (2971.15 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-15T19.47-f23598a/results.html
JOB TIME …
=> fix_perf_24x7_domain_range

kernel/kselftest.py.data/security.yaml
Adding security.yaml with the following tests
kexec
tpm2
safesetid
seccomp
powerpc/security
=> kselftest.py: adding security.yaml

security/vTPM-tests.py
Change the dmesg search string to the device found on the system.
=> vTPM-tests.py: change to dynamic dmesg search string

security/openssl-tests.py, security/openssl-tests.py.data/openssl.yaml
=> openssl-tests.py: add distribution specific test cases

security/xmlsec-tests.py, security/xmlsec-tests.py.data/xmlsec.yaml
=> xmlsec-tests.py: add distribution specific test cases

generic/connectathon.py
On Ubuntu connectathon tests fails to compile if pkg-config is not already installed.
Add a dependency on this package.
=> generic/connectathon: Update package dependency

security/ima-modsig-tests.py
Add IMA modsig test cases, to check the required kernel config options and check whether the signing key exists in both ima and builtin_trusted_keys
=> ima-modsig-tests.py: Add IMA modsig test cases

security/libgcrypt-tests.py, security/libgcrypt-tests.py.data/libgcrypt.yaml
=> libgcrypt-tests.py: add distribution specific test cases

security/libkcapi-tests.py, security/libkcapi-tests.py.data/test_name.yaml
=> libkcapi-tests.py: add distribution specific test cases

io/driver/module_unload_load.py.data/config
mlx_fpga tool allows the user to burn and update a new FPGA image on Mellanox Innova adapter cards
On IBM Power box we don't support Mellanox Innova adapter cards
As per the bug 192581 we don't need to check this module in the testcase
=> We don't use mlx5_fpga_tools sub module

security/audit-tests.py, security/audit-tests.py.data/audit.yaml
=> audit-tests.py: add distribution specific test cases

security/annobin-tests.py, security/annobin-tests.py.data/annobin.yaml
=> annobin-tests.py add distribution specific test cases

io/disk/iozone.py, io/disk/iozone.py.data/iozone.yaml
iozone package version is updated to version
http://www.iozone.org/src/current/iozone3_492.tar
Earlier version http://www.iozone.org/src/current/iozone3_434.tar has compilation issues with RHEL 9.x
Signed-off-by: Maram Srimannarayana Murthy <Maram.Srimannarayana.Murthy@ibm.com>
=> iozone package version is updated

security/cryptsetup-tests.py, security/cryptsetup-tests.py.data/cryptsetup.yaml
=> cryptsetup-tests.py: add distribution specific test cases

security/seccomp-tests.py, security/seccomp-tests.py.data/seccomp.yaml
=> seccomp-tests.py: add distribution specific test cases

security/openssh-tests.py, security/openssh-tests.py.data/openssh.yaml
=> openssh-tests.py: add distribution specific test cases

security/selinux-tests.py, security/selinux-tests.py.data/selinux.yaml
=> selinux-tests.py: add distribution specific test cases

security/pam-tests.py, security/pam-tests.py.data/pam.yaml
=> pam-tests.py: add distribution specific test cases

security/libkmip-tests.py, security/libkmip-tests.py.data/libkmip.yaml
=> libkmip-tests.py: add distribution specific test cases

security/krb5-tests.py, security/krb5-tests.py.data/krb5.yaml
=> krb5-tests.py: add distribution specific test cases

security/nettle-tests.py, security/nettle-tests.py.data/README.txt, security/nettle-tests.py.data/nettle.yaml
=> nettle-tests.py: add distribution specific test cases

security/secvarctl-tests.py, security/secvarctl-tests.py.data/README.txt, security/secvarctl-tests.py.data/secvarctl.yaml
Add secvarctl test cases.
This package helps in creating keys.
=> secvarctl-tests.py: Add secvarctl test cases

security/keyutils-tests.py, security/keyutils-tests.py.data/keyutils.yaml
=> keyutils-tests.py: add distribution specific test cases

security/evmctl-tests.py, security/evmctl-tests.py.data/evmctl.yaml
=> evmctl-tests.py: add distribution specific test cases

io/net/virt-net/network_virtualization.py
sometimes user input for slot num is not always in qoutes so the test fails saying cannot split integer type, this will handle both string and integer input values
=> vnic: handle if slot num is given as integer

perf/perf_genericevents.py, perf/perf_genericevents.py.data/raw_code.cfg
Perf generic events test case has been updated to add AMD 16h, 17h family default generic events.
=> perf/perf_genericevents.py: Add generic events for AMD platform

ras/supportconfig.py
This code tests the supportconfig with different smt levels ie., 2, 4, 8 and off
=> supportconfig.py: Test the supportconfig with different smt levels

perf/perf_sched.py, perf/perf_sched.py.data/perf_sched.yaml
added perf_sched.py testcase which tests perf sched and it's options with all possible flags with the help of yaml file
avocado run --test-runner runner perf_sched.py -m perf_sched.py.data/perf_sched.yaml 
JOB ID     : a52b2bbed1c5b092a69d89c6dfcf487586c33c4c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-27T05.10-a52b2bb/job.log
(01/36) sched.py:perf_sched.test_sched;run-subsystem-latency-1953: PASS (3.66 s)
(02/36) sched.py:perf_sched.test_sched;run-subsystem-script-1269: PASS (3.78 s)
(03/36) sched.py:perf_sched.test_sched;run-subsystem-replay-9bfb: PASS (6.73 s)
(04/36) sched.py:perf_sched.test_sched;run-subsystem-map-variants-compact-1ddc: PASS (3.63 s)
(05/36) …
=> add perf_sched

io/net/network_test.py
Fetch ipv6 address for host and peer and run the ping test to see if its success.
=> ipv6 ping test included as a part of network test

io/net/infiniband/ib_pingpong.py.data/ib_pingpong_infiniband.yaml, io/net/infiniband/ib_pingpong.py.data/ib_pingpong_roce.yaml
Any number beyond this range will fail
Please use value less than or equal to 8192 for your test
=> ibv_xsrq_pingpong maximum allowed number of -n option value is 8192

io/net/virt-net/network_virtualization.py
It is important to check for link connectivity after adding active and also after adding backing device, make sure test fails for any link issues
=> vNIC: check network connectivity after adding active and backing

io/net/bonding.py, io/net/network_test.py, io/net/virt-net/network_virtualization.py
Some case of interuption causes unclean master files, to clean the old code is removed and used cleanup_master utill
=> Remove master file cleanup code and use utils

io/net/sriov_device_test.py
Added a check to make sure the device mac addr
is not changed across hmc and Linux OS
=> SRIOV: check MAC addr mismatch with OS

perf/perf_c2c.py, perf/perf_c2c.py.data/record_report.yaml
With earlier versions -k & --vmlinux works with any provided input which is fixed in rhel 9.1. Starting rhel 9.1 we need to pass exact vmlinux path with -k & --vmlinux report option. Fixed script to take correct path and store c2c report in perf.data file. This change works fine in older releases also.
avocado run --test-runner runner perf_c2c.py -m perf_c2c.py.data/record_report.yaml
JOB ID     : 53388269137ac47a82b353412d928d271aaa3264
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-11-01T16.32-5338826/job.log
(001/210) perf_c2c.py:perf_c2c.test_c2c;run-record-event_load-report-coalesce-ec55: PASS (1.68 s)
(002/210) perf_c2c.py:perf_c2c.test_c2c;run-record-event_load-report-coalesce_full-6412: PASS (1.65 s)
(003/210) …
=> fix perf_c2c vmlinux path

io/net/infiniband/rdma_tests.py.data/ib_atomic_bw_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_atomic_lat_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_read_bw_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_read_lat_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_write_lat_extended_roce.yaml
For bandwidth type app we need to use 32bit integer value equal to 2147483647
=> use a 32-bit integer value for --burst_size option

ras/lparstat.py, ras/ras_lsvpd.py, ras/ras_ppcdiag.py, ras/rtas_dbg.py
Various tools bundled with Linux distribution are not supported inside a KVM guest.
Update the platform detection logic for such tests.
=> Improve platform detection logic for various ras tools

io/disk/port_bounce.py.data/port_bounce.yaml, io/disk/vfc-tests/virtual_fc.py.data/virtual_fc.yaml, io/pci/dlpar.py, io/pci/dlpar.py.data/dlpar.yaml
removing the access details of switch from yaml for security reason.
=> Removing the switch credetails details from yaml for port_bounce

cpu/cpupower_monitor.py
As all cpus need not enter idle state after killing workload, so changing the log to info instead of fail.
=> Fixed failure due to cpus not entering idle states.

io/net/virt-net/network_virtualization.py
Hello,
I was hitting issues running vnic add and remove tests (`test_add` and `test_remove`) when there was already an existing vnic device on the lpar. The error was from `update_backing_devices` : "local variable 'index' referenced before assignment".
The reason for the error was that the wrong list of backing devices was returned from `get_backing_devices`. Rather than returning a list of backing devices for the new vnic device, `get_backing_devices`  returned a list of backing devices for the older backing device. This is because `get_backing_devices` does not return backing_devices for a specific slot, it instead returns all the backing devices for all the vnic devices on the lpar.
Therefore, this PR adds an argument `slot` to `get_backing_devices` so that it can retrieve only the …
=> vnic: Get backing devices for specific slot

kernel/kselftest.py.data/ptrace.yaml
Adding ptrace.yaml file to run with kselftest.py
Signed-off-by: Akanksha J N <akanksha@linux.ibm.com>
=> add_ptrace_yaml

io/iommu/iommu_tests.py, io/iommu/iommu_tests.py.data/README.txt, io/iommu/iommu_tests.py.data/iommu_tests.yaml
Various combination of unbind, bind, change iommu group domain type, reset and rescan is used to form sub-tests that test and exercise iommu code.
Signed-off-by: Dheeraj Kumar Srivastava <dheerajkumar.srivastava@amd.com>
=> Added test for iommu

nx_gzip/nx_gzip.py
glibc-static and zlib are not available in sles added corresponding sles packages.
=> Changed package names for sles.

fs/xfstests.py.data/nvdimm.yaml, fs/xfstests.py.data/nvdimm_log.yaml
updated xfstest nvdimm yaml file with correct mkfs/mount and other config options
avocado run --test-runner runner xfstests.py -m xfstests.py.data/nvdimm.yaml
JOB ID     : 7fb98693697c143f8752df71d951dd3ddbd073a3
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-11-05T09.21-7fb9869/job.log
(1/2) xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_ext4-7dfa: PASS (52.92 s)
(2/2) xfstests.py:Xfstests.test;run-disk_type-fs_type-fs_xfs-5038: PASS (21.68 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-11-05T09.21-7fb9869/results.html
JOB TIME   : 75.51 s
[xfstest_nvdimm-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/file …
=> update xfstest nvdimm.yaml

io/net/netperf_test.py
When running netperf tests. I got:
```
[stdlog] 2022-06-15 10:26:23,260 avocado.utils.process INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 10.1.0.238 'unzip /tmp/netperf-2.7.0.zip -d /tmp;cd /tmp/netperf-netperf-2.7.0;./configure --build=powerpc64le;make''
[stdlog] 2022-06-15 10:26:23,295 avocado.utils.process DEBUG| [stderr] bash: unzip: command not found
[stdlog] 2022-06-15 10:26:23,295 avocado.utils.process DEBUG| [stderr] bash: line 0: cd: /tmp/netperf-netperf-2.7.0: No such file or directory
[stdlog] 2022-06-15 10:26:23,295 avocado.utils.process DEBUG| [stderr] bash: ./configure: No such file or directory
[stdlog] 2022-06-15 10:26:23,313 avocado.utils.process DEBUG| [stderr] make: *** No …
```
=> netperf: Add unzip dependency check

fs/xfstests.py.data/xfstests.yaml
updated xfstest yaml file to run only with loop devices and added ext4 & xfs tests with 4k & 64k block size
previously it was giving error as contains both loop and disk type
ERROR: Multiple  leaves contain the key 'type'; ['/run/loop_type=>loop', '/run/disk_type=>disk']
[root@ fs]# avocado run --test-runner runner xfstests.py -m xfstests.py.data/xfstests.yaml 
JOB ID     : 51b6eba3eb84dbabb3149e1da488ee0feb1c5dbc
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-12-09T02.10-51b6eba/job.log
(1/4) xfstests.py:Xfstests.test;run-fs_type-fs_ext4_4k-loop_type-60cb: PASS (34.51 s)
(2/4) xfstests.py:Xfstests.test;run-fs_type-fs_ext4_64k-loop_type-5070: PASS (18.00 s)
(3/4) xfstests.py:Xfstests.test;run-fs_type-fs_xfs_4k-loop_type-d140: …
=> update xfstest yaml

ras/ras_ppcdiag.py, ras/ras_ppcdiag.py.data/options.yaml
Add capabilities to download and compile upstream source
for ppc64-diag utilities
=> ras/ras_ppcdiag: Add support for upstream target

perf/perf_top.py, perf/perf_top.py.data/perf_top.yaml
added perf_top.py testcase which tests perf top command a system profiling tool with all possible options with the help of yaml file
tested script on RHEL, SLES15 on P9/P10
[root@]# avocado run --test-runner runner perf_top.py -m perf_top.py.data/perf_top.yaml
JOB ID     : 8ceab80317ab88d94c31d724203448cfae92a5ba
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-11-17T11.41-8ceab80/job.log
(01/84) perf_top.py:perf_top.test_top;run-variants-all_cpus-640d:  PASS (41.57 s)
(02/84) perf_top.py:perf_top.test_top;run-variants-all_cpus_full-15dd:  PASS (41.42 s)
(03/84) perf_top.py:perf_top.test_top;run-variants-count-cce5:  PASS (41.51 s)
(04/84) perf_top.py:perf_top.test_top;run-variants-count_full-dd4d:  PASS (41.43 s)
(05/84) …
=> add_perf_top

trace/dawr.py, trace/dawr.py.data/Makefile, trace/dawr.py.data/dawr_v1.c, trace/dawr.py.data/dawr_v2.c, trace/dawr.py.data/dawr_v3.c
Reading single dawr register and multiple dawr registers with gdb interface
Signed-off-by: Akanksha J N <akanksha@linux.ibm.com>
JOB ID     : 7ba758268998e02e31f0950ed2ebe7f74d8873e7
JOB LOG    : /root/ak/avocado-fvt-wrapper/results/job-2022-12-01T00.00-7ba7582/job.log
(1/3) dawr.py:Dawr.test_read_dawr_v1: PASS (2.41 s)
(2/3) dawr.py:Dawr.test_read_dawr_v2: PASS (32.58 s)
(3/3) dawr.py:Dawr.test_read_dawr_v3: PASS (2.33 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/ak/avocado-fvt-wrapper/results/job-2022-12-01T00.00-7ba7582/results.html
JOB TIME   : 67.53 s
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/10129800/job.log)
=> add_dawr_test

trace/dawr.py.data/dawr_v1.c, trace/dawr.py.data/dawr_v2.c, trace/dawr.py.data/dawr_v3.c
dawr test fails to compile the c code due to invalid preprocessing directive.
Use correct style for comments in the c source code.
=> trace/dawr: Fix compile time failure

perf/perftool.py
Perf test sometimes generates an output that can cause this test to
error out. Utf-8 decoding fails when certain invalid characters are encountered.
Fix this issue by ignoring such invalid characters.
=> perf/perftool: Fix unicode decode errors

trace/dawr.py
dawr test is applicable to POWER10 processor. Add relevant check
to restrict the run on non Power10 processor version.
=> trace/dawr: Add check for POWER processor family

io/net/bonding.py, io/net/bridge.py, io/net/bridge.py.data/bridge.yaml
Handling cleanups and test configurations that were causing the tests to be failed while running cfg on VNIC for good_path_scenario
=> Good path scenario on vnic --> cfg handles

ras/ras_lsvpd.py
With upstream as a value for run_type, code compile fails if
sg3_utils-devel package is not installed.
Make sure the package is installed.
=> ras/ras_lsvpd: Add sg3_utils package dependency

perf/perf_duplicate_probe.py, perf/perf_duplicate_probe.py.data/perf_duplicate.yaml
This 2 patch series adds support to run the test against
upstream kernel. Second patch is a test case fixup.
perf/duplicate_probe: Run test against upstream kernel
perf/duplicate_probe: Delete probes only if previously installed
=> perf/duplicate_probe: Run test against upstream kernel

security/libgcrypt-tests.py, security/libgcrypt-tests.py.data/libgcrypt.yaml
libgcrypt tests fail to execute when using distro as a run_type.
The test only installs corresponding source package. Steps to
compile the code is missing.
Add the corresponding steps to compile the source code before
attempting to run the self tests.
=> security/libgcrypt: Fix failure with distro as run_type

io/disk/disktest.py, io/disk/parallel_dd.py
With latest avocado code, the get_sub_process_klass method is removed in process.py utils, causing the test to ERROR: module 'avocado.utils.process' has no attribute 'get_sub_process_klass', this patch fixes the error
Reported-by: Maram Srimannarayana Murthy <Maram.Srimannarayana.Murthy@ibm.com>
=> Fix disktest and paralleldd for new subprocess call

io/net/ethtool_test.py
Due to args not intialize before take connections, the test gives wrong message when ping fails, so this change will fix Error: 'Ethtool' object has no attribute 'args'
=> fix arg problem when ping fails

security/pam-tests.py
When distro is specified as a value for run_type the tests fail due to
missing source code compilation steps. Add the same.
Depending on pam version autogen.sh script may not be available.
Add a check for the same and skip the step if this script is not
part of source code.
=> security/pam: Fix runtime failures with distro as target

security/annobin-tests.py
annobin-tests.py test fails due to missing package. Add a dependency
for that package.
The test does not check return code for make check due to which it
is marked as pass inspite of make command failure. 
=> security/annobin: Runtime failure fixes

generic/ltp.py.data/ltp-tracing.yaml
Add ltp-tracing.yaml file in order to run the LTP tracing tests
Signed-off-by: Akanksha J N <akanksha@linux.ibm.com>
avocado run ltp.py -m ltp.py.data/ltp-tracing.yaml 
Fetching asset from ltp.py:LTP.test
Fetching asset from ltp.py:LTP.test
JOB ID     : ab5dc3ac09624cd95c1c46752d813e4d9de59262
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-01-17T03.20-ab5dc3a/job.log
(1/1) ltp.py:LTP.test;run-runltp-tracing-a507: STARTED
(1/1) ltp.py:LTP.test;run-runltp-tracing-a507: PASS (263.36 s)
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-01-17T03.20-ab5dc3a/results.html
JOB TIME   : 282.25 s
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/10433751/job.log)
=> Add yaml file to run the LTP tracing tests

io/net/iperf_test.py, io/net/netperf_test.py, io/net/uperf_test.py
On a fresh os, the source compilation is failing due to missing packages like flex bison for test like iperf, uperf and netperf
configure: error: Neither flex nor lex was found
configure: error: ./configure failed for libpcap
=> Basic packages like flex, bison required for test

generic/stress-ng.py, generic/stress-ng.py.data/stress-ng-fs.yaml
added code to run stress-ng fs test with different file systems(ext4/xfs/btrfs) mounted
on RHEL9
[root@]# avocado run --test-runner runner stress-ng.py -m stress-ng.py.data/stress-ng-fs.yaml
Fetching asset from stress-ng.py:Stressng.test
JOB ID     : 1b7de62f952cfb3d01fe517b8fbedbb106038af9
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-01-12T00.18-1b7de62/job.log
(1/3) stress-ng.py:Stressng.test;run-exclude-fs_type-ext4-stressors-workers-f640:  PASS (2983.27 s)
(2/3) stress-ng.py:Stressng.test;run-exclude-fs_type-xfs-stressors-workers-411a:  PASS (2984.93 s)
(3/3) stress-ng.py:Stressng.test;run-exclude-fs_type-btrfs-stressors-workers-ccec:  CANCEL: btrfs is not supported on rhel (16.43 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL …
=> enhance stress-ng-fs

io/disk/rawread.py
"Libaio-devel" -> libaio-dev on Ubuntu distro's
and make needs cleaning on x86_64 systems for rawread.tar.
=> Fixing Ubuntu dependency and make cleaning in "x86_64"

memory/fork_mem.py.data/forkoff.c
This patch modifies the code to print the detailed error in case of fork failure, thus aiding the debug in case of failure.
Suggested-by: Tarun Sahu <tsahu@linux.ibm.com>
=> Print detailed error for fork failure

ras/sosreport.py
Added "powerpc" check for /proc/device-tree and also skip tests if it is powerpc specific.
=> ras/sosreport.py: Skip powerpc specific tests and checks

cpu/numactl.py.data/numa_fc.yaml
The name of a parameter in yaml is "input_device" and in .py file it is "input_file" names were not matching. so changed yaml parameter name to "input_file" which is appropriate.
=> Mis-match of yaml parameter name for numactl test

memory/migrate_pages.py.data/node_move_pages.c
In read_memory function in node_move_pages.c, the 'pattern' being compared
with the 'value' which is a char, this leads to an sign extension issue.
=> Fix sign extension issue with read_memory function.

io/disk/bonnie.py, io/disk/disktest.py, io/disk/fiotest.py, io/disk/ltp_fs.py, io/disk/ltp_fsstress.py
Redefining err_msg parameters in testcases before they get called by functions. Fix for ERROR: list.append() takes exactly one argument by changing to extending lists.
=> Fixing no attribute 'err_mesg'

toolchain/gdb.py, toolchain/gsl.py
fixed test validation, instead of checking from stdout, checking out only on the command output.
Signed-off-by: Hariharan T S <hariharan.ts@linux.vnet.ibm.com>
=> Fix the test failure validation

perf/perf_basic.py
The issue is seen when desired packages are not installed, the tests gets
cancelled and go through "tearDown", where it check for temp_file. Since
temp_file creation is below package cancel code. It will never go through
that code path. So, moved the creation of temp_file before checking for
package cancel code.
=>  perf/perf_basic: handle file existenace issue in tearDown

io/disk/ssd/nvmetest.py
The fw-commit uses an option called action (-a) to commit the flashed firmware on nvme drive. 0-3 are the valid values we have to use for this option. value  4 is not applicable and on using the test is failing. So changing it to 0-3.
=> Changing the fw-commit action values from 0-4 to 0-3 in nvmetest.py

perf/perf_uprobe.py
"Device or resource busy" error thrown from the tearDown() even
though events gets deleted. To avoid passed "ignore_status=True"
to process.run in cmd_verify to ignore the status. However, the cmd
output has been taken care in parsing the results.
=>  perf/perf_uprobe: handle tearDown failure case

ras/smtstate.py
If a system isn't SMT capable, this test fails with 
ERROR: Command 'ppc64_cpu --smt=on' failed.
stderr:'Machine is not SMT capable
Add a check for the same and cancel out the test if its not
=> ras/smtstate: Cancel the test on non SMT config

io/disk/disktest.py, io/disk/disktest.py.data/README.txt
In contineous test setups where device names undertest are unpredicatable and this code will help run the test by accepting unique device id which are persistant across os installs.
=> disktest.py:add support for test run by device id

generic/stress-ng.py
stress-ng run with other components was giving error because of last commit 736b0d186d04 for filesystem
this patch fixes the error by adding condition in teardown
before patch
avocado run stress-ng.py -m stress-ng.py.data/stress-ng.yaml 
Fetching asset from stress-ng.py:Stressng.test
JOB ID     : dbc595441100a6a29f0ef55db3ecfbb8418b2195
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-02-03T04.50-dbc5954/job.log
(1/1) stress-ng.py:Stressng.test;run-subsystem-cpu-workers-8835: STARTED
(1/1) stress-ng.py:Stressng.test;run-subsystem-cpu-workers-8835: ERROR: 'Stressng' object has no attribute 'loop_dev' (328.77 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : …
=> fix-stress-ng

perf/perf_nmem.py
fixed error 'bytes' object has no attribute 'stdout'
make 8th test skip in case of multiple numa nodes as cpumask values are determined based on nearest numa node and can be different
test was not able to bring back disabled cpu online, patch fixes this
before patch:
localhost: # avocado run --test-runner runner perf_nmem.py
JOB ID     : 3443460f0e63f8b13d14dcc75d575239c76d779d
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-01-16T11.10-3443460/job.log
(1/9) perf_nmem.py:perfNMEM.test_pmu_register_dmesg: PASS (0.93 s)
(2/9) perf_nmem.py:perfNMEM.test_sysfs: PASS (0.86 s)
(3/9) perf_nmem.py:perfNMEM.test_pmu_count: PASS (0.85 s)
(4/9) perf_nmem.py:perfNMEM.test_all_events: PASS (52.62 s)
(5/9) …
=> fix perf_nmem

fs/xfstests.py
as earlier test has failure in skip case as it  try to run tearDown user deletion step , this patch address delete user only when it exists
=> Added condition for user exists

generic/stress-ng.py
replace hardcoded value to get free loop device as using losetup utility to get free loop device node
=> Remove hard coded value of loop device

generic/ltp.py.data/ltp.yaml
Remove timers as its ported to syscalls runtest file, and avoid no file found error.
=> Remove timers from ltp.yaml

perf/perf_bench.py
Sometimes on some of the systems perf bench test fails with some ‘Assertion’ and the test gets stuck and will not proceed further. Adding a condition for test to fail when hitting assertion error.
Signed-off-by: Disha Goel [disgoel@linux.vnet.ibm.com](mailto:disgoel@linux.vnet.ibm.com)
=> perf_bench: add condition to check assertion error

kernel/kselftest.py
adopted passing -bp option to as rpmbuild
=> Fix kself test cases in case of distro provided src

io/net/ethtool_test.py.data/ethtool_veth_test.yaml, io/net/ethtool_test.py.data/ethtool_vnic_test.yaml
vNIC and veth yamls is added with latest channel parameters -l, -L, rx and tx options. there are few bugs reporting for vnic crashing for channel parameter set
=> Add support for vnic channel parameters

ras/ras_ppcdiag.py
commit 7b8017c77a97 ras/rastools: Consolidate sub tests added
test_usysident subtest to ppcdiag. While doing so a subtle difference
of command usage was missed -- normal vs identify as a value.
This causes the test to fail. Fix it by using correct command to be
passed to run_cmd() routine.
Credits to Shirisha for spotting this error.
Reported-by: Shirisha Ganta <shirisha.ganta1@ibm.com>
=> ras/ras_ppcdiag: Fix usysident test failure

io/net/virt-net/lpm.py.data/lpm_withvnic.yaml
Make sure both the config options --vniccfg 1 and 2 getting tested when running the lpm tests with vNIC
=> vNIC LPM: test both config options

io/pci/dlpar.py, io/pci/dlpar.py.data/dlpar.yaml
The current code will not work if the lpar name
does not have the managed system name
=> dlpar: provide manage system explicitly

perf/perf_test.py, perf/perf_test.py.data/perf_test.yaml
This 2 patch series adds following support
perf/perf_test: Add support for upstream as run_type
Add upstream as a target support so that matching set of
tests are executed while running against upstream kernel.
perf/perf_test: Add debuginfo packages as dependency
=> perf/perf_test: Add package dependency and upstream support

io/disk/port_bounce.py, io/disk/port_bounce.py.data/README, io/disk/port_bounce.py.data/port_bounce.yaml
current script doesn't work for NVMeoFC adapters as they do not support multipath. and cuurent script works with wwid's of any fc adapter. So enhanced the script to support nvmf adapter too along with fc/vfc adapters.
=> Enhancing the port_bounce.py to support nvmf adapters.

io/disk/smartctl.py, io/disk/smartctl.py.data/Readme, io/disk/smartctl.py.data/smartctl.yaml
smartctl do not support logical disks and also it requires only single input device to test. so this patch will cancel test if it is logical device and cleanup yaml
=> smartctl: works on single disk and skip if logical disk

perf/perf_pmu.py
first test fails with error as process.system_output does not have stdout/stderr, fixing it by using process.run 
(1/8) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: STARTED
(1/8) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: ERROR: 'bytes' object has no attribute 'stdout' (0.19 s)
after fix:
[root@]# avocado run --max-parallel-tasks=1 perf_pmu.py
JOB ID     : 2da5627c32887494f6d795468ef381f3d70de6d7
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-03-13T04.25-2da5627/job.log
(1/8) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: STARTED
(1/8) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: PASS (0.18 s)
(2/8) perf_pmu.py:PerfBasic.test_config_PPC_RTAS: STARTED
(2/8) perf_pmu.py:PerfBasic.test_config_PPC_RTAS: PASS (0.27 s)
(3/8) perf_pmu.py:PerfBasic.test_cpu_event_count: STARTED
(3/8) …
=> fix perf_pmu error

io/net/virt-net/network_virtualization.py
Make sure the test can be run for given iterations and always check the device config post every iteration
=> vNIC: Enable iteration for disable-enable test

io/iommu/iommu_tests.py
Subtests were failing when iommu=off. Ideally for iommu=off case, subtests should cancel.
This patch addresses that.
=> Cancel test if iommu is off (iommu=off)

ras/lshw.py
disable option is failing as the condition is failing on powernv. 
So changing the if condition in order to work for both PowerVM and PowerNV
=> lshw.py:Failed commands are: ['lshw -disable network|grep -i interface']

io/net/iperf_test.py, io/net/iperf_test.py.data/iperf_test.yaml, io/net/iperf_test.py.data/iperf_virt_test.yaml, io/net/uperf_test.py
iperf and nmap tar files used for testing is updated to the latest released levels
=> Updating nmap and iperf source version releases

memory/fork_mem.py.data/forkoff.c
Here below are the logs of duplicate msg "mmaping xx anonynous bytes"
[stdlog] 2023-01-19 06:20:26,564 avocado.utils.process DEBUG| [stdout] mmaping 10485760 anonymous bytes
[stdlog] 2023-01-19 06:20:26,564 avocado.utils.process DEBUG| [stdout] PID 31747 touching 160 pages
[stdlog] 2023-01-19 06:20:26,564 avocado.utils.process DEBUG| [stdout] mmaping 10485760 anonymous bytes
[stdlog] 2023-01-19 06:20:26,564 avocado.utils.process DEBUG| [stdout] PID 31753 touching 160 pages
[stdlog] 2023-01-19 06:20:26,564 avocado.utils.process DEBUG| [stdout] mmaping 10485760 anonymous bytes
Becuase, stdout is streamed to some file, the return character ('\n') is not able to flush the stdout stream
and on each time fork is called, the parent log are printed again.
Also this patch resolve some compiler …
=> Resolve duplicate debug msg in memory/fork_mem test

memory/dma_memtest.py
When the test cancels it throws the ERROR:
[Errno 2] No such file or directory: 'linux.0' because tearDown tries to remove files that do not exist due to test canceling this patch fixes that.
=> Fix ERROR: [Errno 2] No such file or directory: 'linux.0'

fs/xfstests.py, fs/xfstests.py.data/README, fs/xfstests.py.data/btrfs-subpage.yaml, fs/xfstests.py.data/nvdimm.yaml, fs/xfstests.py.data/nvdimm_log.yaml, fs/xfstests.py.data/xfstests.yaml, fs/xfstests.py.data/xfstests_disk.yaml
added group parameter support in xfstest to run any group specific tests
fixed cleanup in teardown
update all yaml files with group and test_range parameter
Signed-off-by: Disha Goel [disgoel@linux.vnet.ibm.com](mailto:disgoel@linux.vnet.ibm.com)
with both group and test_range as null
JOB ID     : a8f8df6816cf620a827159a931b4e7e2bc0a3175
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-02-28T02.32-a8f8df6/job.log
(1/1) xfstests.py:Xfstests.test;run-fs_type-fs_ext4_4k-gen_exclude-share_exclude-group-loop_type-disk-test_range-bd68: STARTED
(1/1) xfstests.py:Xfstests.test;run-fs_type-fs_ext4_4k-gen_exclude-share_exclude-group-loop_type-disk-test_range-bd68: CANCEL: incorrect yaml parameter, group and test range can                          not be run/none at same time (0.61 s)
RESULTS …
=> Xfstest group support

io/disk/fiotest.py.data/fio-pmem.yaml
On running fiotest.py with fio-pmem.yaml we see make errors as below :
```
(1/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-xfs-785d: STARTED
(1/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-xfs-785d:  ERROR: Command 'make' failed.\nstdout: b'test -f .skip-doc || make -C doc all\nmake -C src all\nmake[1]: Entering directory \'/var/tmp/avocado_cimxovdo/pmdk-1.8/src\'\nmake -C libpmem\nmake -C common\nmake[2]: Entering directory \'/var/tmp/avocado_cimxovdo/pmdk-1... (4.85 s)
```
This seems to have been fixed in pmdk-1.12.1 thus updating the url to point to this as default.
=> Fix : make error on running fio test with fio-pmem

ras/ras_ppcdiag.py
Added a condition check to cancel the testcase if the system fault indicators are not supported on the system
=> Fixing usysfault testcase failure and usysattn wrong condition check

io/disk/disk_info.py, io/disk/disk_info.py.data/Readme.txt
This commit adds support for block device names which persistent accross installs, dlpar, reboot etc.
Block devices names like /dev/sdb are not same across install in some	distros, so disk_info.py currently supports only the the /dev/sdX as	input device, now with the new code changes a user can provide any of sdX, mpathX, dm-0, /dev/mapper/mpathX ,/dev/disk/by-id/scsi-xxx, /dev/disk/by-path/fc-xxx, /dev/dmX for the	below tests
=> disk_info: support for any device names for input disk

io/disk/bonnie.py, io/disk/bonnie.py.data/Readme.txt, io/disk/dbench.py, io/disk/dbench.py.data/Readme.txt, io/disk/disktest.py, io/disk/dlpar_vscsi.py, io/disk/dlpar_vscsi.py.data/Readme.txt, io/disk/fs_mark.py, io/disk/fs_mark.py.data/README.txt, io/disk/ioping.py, io/disk/ioping.py.data/README, io/disk/iozone.py, io/disk/iozone.py.data/README, io/disk/ltp_fs.py, io/disk/ltp_fsstress.py, io/disk/ltp_fsstress.py.data/Readme.txt, io/disk/parallel_dd.py, io/disk/parallel_dd.py.data/README, io/disk/rawread.py, io/disk/rawread.py.data/README, io/disk/smartctl.py, io/disk/tiobench.py
This commit has similar code changes accross common block device tests to support block device names which persistent accross installs, dlpar, reboot etc.
Block devices names like /dev/sdb are not same across install in some distros, so all the io/disks tests currently supports the /dev/sdX as input device, now with the new code changes a user can provide any of sdX, mpathX, dm-0, /dev/mapper/mpathX ,/dev/disk/by-id/scsi-xxx, /dev/disk/by-path/fc-xxx, /dev/dmX for the below tests
io/disk/bonnie.py
io/disk/dbench.py
io/disk/disktest.py
io/disk/fs_mark.py
io/disk/ioping.py
io/disk/iozone.py
io/disk/ltp_fs.py
io/disk/ltp_fsstress.py
io/disk/parallel_dd.py
io/disk/rawread.py
io/disk/smartctl.py
io/disk/tiobench.py
io/disk/dlpar_vscsi.py
=> Add support for all device names as input block device tests

kernel/kselftest.py, kernel/kselftest.py.data/bpf.yaml
Add bpf.yaml file and modify kselftest.py in order to compile the source kernel and run the bpf selftest for distro
```
JOB ID     : d71bb5568fa28aaf23edbe84461abdddbcc21e54
JOB LOG    : /root/avocado/job-results/job-2023-04-17T01.52-d71bb55/job.log
(1/1) kselftest.py:kselftest.test;run-component-bpf-run_type-distro-da72: STARTED
(1/1) kselftest.py:kselftest.test;run-component-bpf-run_type-distro-da72:  FAIL: Testcase failed during selftests (9568.69 s)
JOB HTML   : /root/avocado/job-results/job-2023-04-17T01.52-d71bb55/results.html
JOB TIME   : 9581.15 s
```
=> enable_bpfselftest

io/disk/fiotest.py
On running fiotest with fio-pmem.yaml file we see below errors when the test throws warning instead of dispalying warning :
```
(1/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-xfs-fefe: STARTED
(1/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-xfs-fefe:  ERROR: 'FioTest' object has no attribute 'warn' (49.89 s)
(2/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-ext4-54b7: STARTED
(2/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-ext4-54b7:  ERROR: 'FioTest' object has no attribute 'warn' (32.03 s)
```
these are fixed by changing self.warn to self.log.warn
After change :
```
(1/3) fiotest.py:FioTest.test;run-setup-disk-run_type-libpmem-filesystem-xfs-fefe: STARTED
(1/3) …
```
=> Fix : ERROR: 'FioTest' object has no attribute 'warn'

memory/fork_mem.py.data/README.md, memory/fork_mem.py.data/forkoff.c
This commit does the following:
1. fixes the wrong printing of no. of pages touched. 
no. of pages touched is the number of "itterartions". 
size/psize is the maximum no. of pages in the memory block of size
2. corrects format specifiers that throw warning on compilation.
3. adds comments for code readability and clear description of parameters.
4. adds a README file for better understanding of this test
----
Before :
```
forkoff.c:55:120: warning: format specifies type 'int' but the argument has type 'unsigned long' [-Wformat]
printf("\nNumber of Children %d provided is higher than maxpid supported on this system %d.. Exiting!!\n",procs,maxpid);
~~                                                                           ^~~~~
%lu
forkoff.c:65:43: warning: format specifies type 'unsigned …
```
=> Improve the forkoff test

security/grub-extend-pcr.py
Add grub extend PCR08 and PCR09 test cases to validate the output of grub extended PCRs ie 08 & 09 from tsspcrread and tsseventextend commands.
=> Add grub extend PCR test cases

io/disk/bonnie.py, io/disk/dbench.py, io/disk/disktest.py, io/disk/fs_mark.py, io/disk/ltp_fs.py, io/disk/ltp_fsstress.py, io/disk/tiobench.py
Defaulting self.dir to self.workdir instead of /mnt. 
Cancelling test when self.disk is missing.
Initialising self.err in the beginning.
[log_io_disk_changes.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11268373/log_io_disk_changes.txt)
=> Fixing self.disk and self.dir parameter

memory/homenode.py, memory/homenode.py.data/Makefile, memory/homenode.py.data/README.md, memory/homenode.py.data/homenode.c, memory/homenode.py.data/homenode.yaml
mm/mempolicy: add set_mempolicy_home_node syscall
This syscall can be used to set a home node for the MPOL_BIND and MPOL_PREFERRED_MANY memory policy. The syscall allows specifying a home node/preferred node from which kernel will fulfill memory allocation requests first.
Link: https://lkml.kernel.org/r/20211202123810.267175-3-aneesh.kumar@linux.ibm.com
=> Add new test for testing the home node feature in linux kernel

ras/sosreport.py
```
JOB ID     : 6873f93a47c716029af1d73ff80f81c7fa8ba296
JOB LOG    : /home/*/results/job-2023-05-03T01.00-6873f93/job.log
(1/2) sosreport.py:Sosreport.test_fs;run-dir-filesystem-ext4-1c60: STARTED
(1/2) sosreport.py:Sosreport.test_fs;run-dir-filesystem-ext4-1c60:  PASS (105.57 s)
(2/2) sosreport.py:Sosreport.test_fs;run-dir-filesystem-xfs-e780: STARTED
(2/2) sosreport.py:Sosreport.test_fs;run-dir-filesystem-xfs-e780:  PASS (107.60 s)
JOB HTML   : /home/*/results/job-2023-05-03T01.00-6873f93/results.html
JOB TIME   : 216.17 s
```
2023-05-03 01:02:22,408 avocado.utils.process INFO | Command '/usr/bin/dnf -y install java' finished with 0 after 0.829737151s
2023-05-03 01:02:22,408 avocado.utils.process INFO | …
=> Remove Hardcoded loop device value and Use self.workdir as default 'dir'

generic/stress-ng.py, generic/stress-ng.py.data/readme.rst
For a test run having multiple stressors, there are common and stressor specific arguments. Common arguments can be passed using "common_args" and stressor specific arguments can be passed using "<stressor_name>" parameter.
for eg. if stressors: "readahead hdd"
then 	readahead: '--readahead-bytes 16M'
hdd: '--hdd-opts dsync'
common_args: '-k'
Here "common_agrs" is used for both stressors i.e. readahead and hdd but "readahead" is used for readahead and "hdd" is used for stressor hdd.
=> Add support to pass common and stressor specific args for stress-ng

workload/smt.py.data/smt.sh
1. ppc64_cpu --smt=8 and ppc64_cpu --smt=on mean the same thing. So there is no point running these commands one after another.
2. added ppc64_cpu --smt=on followed by ppc64_cpu --smt=off so that we have an instance where maximum no. of threads in a core (7) go offline at once.
=> Improve the smt workload sh script

memory/homenode.py, memory/homenode.py.data/homenode.c, memory/homenode.py.data/homenode.yaml
Add the option to mbind the memory mapped region with either MPOL_BIND flag or MPOL_PREFERRED_MANY flag. Also Add the corresponding yaml file parameter.
=> Add option of mpol flag in home node test

io/disk/fiotest.py, io/disk/fiotest.py.data/README
This commit adds support for block device names which persistent accross installs, dlpar, reboot etc.
Block devices names like /dev/sdb are not same across install in some distros, so fio-test.py currently supports only the the /dev/sdX as input device, now with the new code changes a user can provide any of sdX, mpathX, dm-0, /dev/mapper/mpathX ,/dev/disk/by-id/scsi-xxx, /dev/disk/by-path/fc-xxx, /dev/dmX for the below tests
=> fio_test: support for any device names for input disk

io/disk/htx_block_devices.py, io/disk/htx_block_devices.py.data/Readme.txt
This code change will allow user to provide not only device node name /dev/sdx, but any name of the disk by-id, by-path, by-uuid a mapper device etc which is required in cases where the disks names are not persistent across os installs etc
=> htxblock: Add support for persistent device name as input disks

io/disk/lvsetup.py, io/disk/lvsetup.py.data/README
This commit adds support for block device names which are persistent accross installs, dlpar, reboot etc.
Block devices names like /dev/sdb are not same across install in some distros, so lvsetup.py currently supports only the the /dev/sdX as input device, the new code changes a user can provide any of sdX, mpathX, dm-0, /dev/mapper/mpathX ,/dev/disk/by-id/, /dev/disk/by-path/fc-xxx, /dev/dmX.
=> lv_setup.py: support for any device names for input disk

kernel/kselftest.py, kernel/kselftest.py.data/pmu.yaml
patch adds a yaml file to run pmu selftests
also add a condition to cancel the pmu/event_code_tests for distro as its not supported
avocado run --max-parallel-tasks=1 kselftest.py -m kselftest.py.data/pmu.yaml
JOB ID     : 4f5adad8f9c17d6ef2be44ac186f014326e86043
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-05-17T03.02-4f5adad/job.log
(1/6) kselftest.py:kselftest.test;run-component-pmu/ebb-run_type-distro-77ee: STARTED
(1/6) kselftest.py:kselftest.test;run-component-pmu/ebb-run_type-distro-77ee: PASS (208.80 s)
(2/6) kselftest.py:kselftest.test;run-component-pmu/event_code-run_type-distro-109d: STARTED
(2/6) kselftest.py:kselftest.test;run-component-pmu/event_code-run_type-distro-109d: CANCEL: selftest not supported on distro …
=> add pmu selftest

io/disk/softwareraid.py
self.raid when not defined, ignoring in teardown and exiting testcase.
Before:
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: STARTED
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: PASS (0.63 s)
(08/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-0.9-raidlevel-raid1-raidname-spare_disks-88e8: STARTED
(08/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-0.9-raidlevel-raid1-raidname-spare_disks-88e8: ERROR: 'SoftwareRaid' object has no attribute 'sraid' (0.48 s)
After:
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: STARTED
(07/23) …
=> Handle Attribute not found error in teardown

perf/perf_metric.py, perf/perf_rawevents.py
patch1 adds fail condition for invalid metric events
fix error as process.getstatusoutput has no attribute stdout/stderr
changed perf stat metric events to run with cpu 0
patch2 adds fail condition for invalid perf_rawevents
Signed-off-by: Disha Goel <disgoel@linux.ibm.com>
avocado run --test-runner runner perf_rawevents.py
JOB ID     : 050a3688bba2b2fc14e16aa1532a5f9638480c07
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2023-05-10T18.54-050a368/job.log
(1/2) perf_rawevents.py:PerfRawevents.test_raw_code: FAIL: perf_raw_events: refer log file for failed events (11.41 s)
(2/2) perf_rawevents.py:PerfRawevents.test_name_event: PASS (13.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : …
=> add fail condition for invalid perf rawevents and metric events

io/disk/htx_block_devices.py, io/disk/htx_block_devices.py.data/Readme.txt, io/disk/htx_block_devices.py.data/htx_all_devices.yaml, io/disk/htx_block_devices.py.data/htx_block_devices.yaml, workload/htx_test.py, workload/htx_test.py.data/htx_pmem.yaml
As we have different htx test requires same rpm link so it is better to keep same parameter name to avoid duplicate entries in CI/CR environments
=> htx: keep rpm parameter common accross all test

generic/stress-ng.py, generic/stress-ng.py.data/stress-ng-iommu.yaml
avocado-misc-tests# avocado run generic/stress-ng.py -m generic/stress-ng.py.data/stress-ng-iommu.yaml --test-runner runner
Fetching asset from generic/stress-ng.py:Stressng.test
JOB ID     : 4f1d9c496d082cb0f8f1de463caec4fcde8bf3a7
JOB LOG    : /root/avocado/job-results/job-2023-05-29T02.11-4f1d9c4/job.log
(1/2) generic/stress-ng.py:Stressng.test;run-variants-readahead-workers-5a2f: WARN: Test passed but there were warnings during execution. Check the log for details. (135.67 s)
(2/2) generic/stress-ng.py:Stressng.test;run-variants-hdd-workers-2f47: WARN: Test passed but there were warnings during execution. Check the log for details. (138.15 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 2 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 274.12 s
=> Add iteration support and iommu specific yaml for stress-ng test

memory/memhotplug.py, memory/memhotplug.py.data/memhotplug.yaml
Running memhotplug.py test is causing the error:
(1/4) tests/avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_loop: STARTED (1/4) tests/avocado-misc-tests/memory/memhotplug.py:MemStress.test_hotplug_loop: ERROR: 'MemStress' object has no attribute 'blocks_hotpluggable' (2.51 s)
Issue: Old link of stress tar is no longer valid
Fixes:
1. Add new link of stress tar
2. Add the stress tar as a parameter that can be configured from yaml
3. Make the necessary changes to run the new stress tar
=> Fix ERROR : 'MemStress' object has no attribute 'blocks_hotpluggable'

.github/workflows/xfstests.yaml
Currently github actions will run for push to any branch for changes in fs/xfstests.py*. 
Intead limit it to only master and xfstestsci* branch.
=> .github/workflows/xfstests: Limit github actions to set branches

io/iommu/iommu_tests.py
self.fail throws error when used in tearDown() function. Replacing it with check_dmesg() and calling it at the end of each tests fix this issue.
=> Fix self.fail not working in tearDown()

io/disk/ssd/blkdiscard.py, io/disk/ssd/blkdiscard.py.data/README, io/disk/ssd/ezfiotest.py, io/disk/ssd/ezfiotest.py.data/README.txt, io/disk/ssd/nvme_cli_selftests.py, io/disk/ssd/nvmetest.py, io/disk/ssd/nvmetest.py.data/README.txt
This code change will allow user to provide not only device node name /dev/sdx, but any name of the disk by-id, by-path, by-uuid a mapper device etc which is required in cases where the disks names are not persistent across os installs etc
=> ssd: support any device names of test disk

io/disk/port_bounce.py
Current value of 4000 is not sufficient to capture entire information on switches with more ports. So the value is increased to 8192 bytes.
Test was failing on FC switch with 64 ports
[root@ltcden4-lp7-murthy disk]# avocado run --max-parallel-tasks=1 port_bounce.py -m port_bounce.py.data/port_bounce.yaml                                                                                   
JOB ID     : 43e9d614976258c0a261ecc10ecf573bbacb07c9                                                                                                                                                       
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-06-15T11.51-43e9d61/job.log …
=> Change in paramiko recv fucntion hard coded parameter value

io/net/htx_nic_devices.py, io/net/htx_nic_devices.py.data/README.txt, io/net/htx_nic_devices.py.data/htx_nic_devices.yaml
RHEL for both Host and Peer as per RHEL OS version.
Ex: 1. For RHEL-8 installs RHEL-8 based HTX rpm.
2. For RHEL-9 installs RHEL-9 based HTX rpm.
Tested with
----------------------
Host LPAR as RHEL 8 and Peer LPAR as RHEL 9
Host LPAR as RHEL 8 and Peer LPAR as RHEL 8
Both conditions version based installation getting sucessful.
Currently this code does not support on SLES, for 
1. Host/SLES <--------> Peer/SLES
2. Host/SLES <---------> Peer/RH  
and separate JIRA has been initiated on same.
Run logs:
------------
Host - RH-9.2 <---------->  Peer RH-9.2
------------------------------------------------
[root@ltcden4-lp14 net]# avocado run htx_nic_devices.py -m htx_nic_devices.py.data/htx_nic_devices.yaml --max-parallel-tasks=1
JOB ID     : 298c60412a0a5ea8ba1684759934e6f6c4dc1a6a
JOB LOG …
=> Fetch latest HTX build automatically for Host and peer

perf/perf_genericevents.py
Current event loop logic uses magic number '9' which is not required.
Instead check if val if none and continue for next event in the loop.
Suggested-by: Sandipan Das <sandipan.das@amd.com>
=>    Fix event loop logic

cpu/cpupower_monitor.py
Commit 4f6d80666c2c renamed test_disable_idlestate() function name
to test_idlestate_mode() but missed updating instances where this function is used.
Update the script to use the new function name.
=> cpu/cpupower_monitor: Regression bug fix

io/disk/ssd/blkdiscard.py
if any disk left with some metadata like LVM or fs after running some test and if same disk is used for running blkdiscard, it will fail. So added the force option to over write it and continue to run the test case without any issue.
=> Adding -f flag to run blkdiscard.py forcefully.

perf/perf_hv_gpci.py
This script allows a non root user to execute perf commands and
has checks in place to add such a non root user if it does not exist.
If addition of non root user fails, the script logs a warning message.
Extend this logic to run_cmd() function as well to avoid runtime
error if user does not exist.
=> perf/perf_hv_gpci: Handle non root user addition

kernel/kselftest.py, kernel/kselftest.py.data/README, kernel/kselftest.py.data/kselftest.yaml, kernel/kselftest.py.data/ksmtest.yaml
Component vm renamed to mm on upstream kernel
On upstream kernel component vm renamed to mm by commit id
commit baa489fabd01 ("selftests/vm: rename selftests/vm to
selftests/mm") [Link](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=baa489fabd0159)
Handling the same in testfile ,yaml and updating README
accordingly.
Fix kseleftest run setup on a SUT
Make headers and install kselftest in SUT before run_tests.
Skip powerpc related tests on any non ppc64 and ppc64le platform.
Before:
`
JOB ID     : 5a558f521c16aebe15c90261dc2727ab555db411
JOB LOG    : /root/AvocadoTests_src/results/job-2023-07-26T09.48-5a558f5/job.log
(1/6) kselftest.py:kselftest.test;run-component-vm-run_type-distro-9ddb: STARTED
(1/6) …
=> Fixing Kselftest run setup and selftests/vm to selftests/mm rename

perf/perf_sdt_probe.py
sometimes after adding libpthread event not reflected in perf list immediately and test fails.
patch adds sleep for 10s before checking perf list
Signed-off-by: Disha Goel <disgoel@linux.ibm.com>
before fix
10:02:20 INFO    : Running Host Tests Suite perf_sanity_perf_sdt_probe
10:02:20 INFO    : Running: /usr/local/bin/avocado run -nrunner-max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_sdt_probe.py --force-job-id 56a226744188d16c99b3198bcd8cbb417f0f96b8  -job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : 56a226744188d16c99b3198bcd8cbb417f0f96b8
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-12-08T10.02-56a2267/job.log
(1/1) /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_sdt_probe.py:PerfSDT.test: STARTED
(1/1) …
=> fix perf_sdt_probe to add sleep

perf/perf_stress_ng.py, perf/perf_stress_ng.py.data/perf_stress_ng.yaml
Perf data and vmstat comparison with different stress-ng CPU workload
Test runs different CPU workload and tries to capture the perf data and vmstat with multiple iterations. Average is taken to compare if the test PASS/FAIL.
=> Perf data and vmstat comparison with different stress-ng CPU workload

perf/perf_metric.py
perf mertrics test parses the o/p of perf list command to identify
list of metrics that are then passed to perf stat command. The
parsing logic does not work correctly which causes failures as
mentioned:
perf stat -M executing in the branch unit] -C 0 sleep 1'
[stderr] Cannot find metric or group `executing'
[stderr] Workload failed: No such file or directory
Command 'perf stat -M executing in the branch unit] -C 0 sleep 1' 
finished with 255 after 0.072842537s
Update the parsing logic to also look for lines which has all
upper case characters.
=> perf/perf_metrics: Improve parsing logic

ras/servicelog.py
'-t' option in log_repair_action is deprecated.
Loc code is sufficient for device lookup with v1 API. However, needs to be retained for v0.2.9 for backward compatibility.
Also, Fix code style warnings reported by pycodestyle.
=> Use '-t' option in log_repair_action only for Servicelog v0.2.9

kernel/kselftest.py
Logic to cancel the tests when detected distro arch is not ppc or ppc64le changed to use logical operator "and" instead of "or" , to get appropriate results
Signed-off-by: Spoorthy S<spoorts2@in.ibm.com>
=> Fix the logic to cancel tests when arch other than [ppc.ppc64le]

perf/perf_trace.py, perf/perf_trace.py.data/perf_trace.yaml
add test to run perf trace record and perf trace report with different options
ref bz197236 perf trace -i SEGFAULT when perf.data is provided
avocado run perf_trace.py
JOB ID     : 72277427bf00047a6976115aa441bee18dda1806
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-08-09T06.04-7227742/job.log
(1/1) perf_trace.py:perf_trace.test_trace: STARTED
(1/1) perf_trace.py:perf_trace.test_trace: PASS (3.11 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2023-08-09T06.04-7227742/results.html
JOB TIME   : 5.49 s
avocado run perf_trace.py -m perf_trace.py.data/perf_trace.yaml --max-parallel-tasks=1
JOB ID     : bc43aa4ad38b541df7bf95bbafe4ec91336815e5
JOB LOG    : …
=> add perf trace test

perf/perf_stress_ng.py
Made changes in perf/perf_stress_ng.py test to fix vmstat calculation and change percentage calculation part.
Also add code to find system CPU frequency for calculations.
This pull request changes are rebased on top of latest master branch and also had changes suggested by Naresh.
Thanks!
=> Perf stressng test fixes

io/disk/fiotest.py
The last changes has error in getting path of the device in case if the device type is nvdimm as the fio test do not expect disk input instead it creates its own vpmem device so this changes make sure test do not fail if disk input is empty
=> fio: fix device path issue for vpmem device type

io/net/ethtool_test.py, io/net/ethtool_test.py.data/README.txt, io/net/ethtool_test.py.data/ethtool_infiniband.yaml, io/net/ethtool_test.py.data/ethtool_sriov_test.yaml
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar and os install with different linux flavours, also the legacy interface name as input is still intact with these changes
=> ethtool: Enable mac addr as an input option

io/net/bridge.py, io/net/bridge.py.data/README.txt, io/net/bridge.py.data/bridge.yaml
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name as input works as is.
=> bridge.py: add support for mac address as input

io/net/virt-net/veth_dlpar.py, io/net/virt-net/veth_dlpar.py.data/README.txt
In a contineous test environement setups where device names are not persistent accross os, having a unique key like mac addr as yaml input which does not change across reboots,dlpar or os install with different linux flavours, also the legacy interface name still works.
=> vethdlpar: add support for mac id base test

io/net/htx_nic_devices.py, io/net/htx_nic_devices.py.data/README.txt, io/net/multiport_stress.py, io/net/multiport_stress.py.data/README.txt
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name still works.
=> htx, multiport: add support for mac base input

io/net/Network_config.py, io/net/Network_config.py.data/README.txt, io/net/iperf_test.py, io/net/iperf_test.py.data/README.txt, io/net/multicast.py, io/net/multicast.py.data/README.txt, io/net/netperf_test.py, io/net/netperf_test.py.data/README.txt, io/net/switch_test.py, io/net/switch_test.py.data/README.txt, io/net/tcpdump.py, io/net/tcpdump.py.data/README.txt, io/net/uperf_test.py, io/net/uperf_test.py.data/README.txt, io/net/vlan_test.py, io/net/vlan_test.py.data/README.txt
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name still works.
=> io/net: add support for mac id as input

perf/perf_24x7_hardware_counters.py
in P9 compat mode test fails with below error as events are written based on pvr version
'perf unable to recognize it has invalid event'
patch modifies the test to use pvr values instead of power processor version
```
avocado run perf_24x7_hardware_counters.py --max-parallel-tasks=1
JOB ID     : 57b0d143a6d99b18bf90f2a997cb0a4ac8bd0ae9
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-06-12T10.32-57b0d14/job.log
(01/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: STARTED
(01/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: PASS (66.50 s)
(02/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: STARTED
(02/11) …
```
=> modify 24x7 based on pvr value

perf/perf_24x7_all_events.py
in P9 compat mode test fails with below error as events are written based on pvr version
'perf unable to recognize it has invalid event'
modify the test to use pvr values instead of power processor version
correct code to get number of chips available in the machine from lscpu output and run chip events in that range
also added condition to check for events which are not supported in exit criteria
[root@ perf]# avocado run perf_24x7_all_events.py
JOB ID     : 538c80afef6de6c4a155b910c686d18a4103c51d
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-08-31T06.45-538c80a/job.log
(1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: STARTED
(1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: PASS (3306.99 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | …
=> modify test to use pvr values and get number of chips available to run chip events

io/net/infiniband/rdma_tests.py.data/ib_read_bw_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_read_lat_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_send_bw_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_send_lat_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_write_bw_extended_roce.yaml, io/net/infiniband/rdma_tests.py.data/ib_write_lat_extended_roce.yaml
Fixing the parameter values passed in yaml files to be integers
fail case logs
(001/261) rdma_tests.py:RDMA.test;run-ib_read_bw_extended-mtu-1500-test_opt--D_10s-0b64: STARTED
(001/261) rdma_tests.py:RDMA.test;run-ib_read_bw_extended-mtu-1500-test_opt--D_10s-0b64: FAIL: Client cmd: ib_read_bw -D 10s (5.47 s)
(002/261) rdma_tests.py:RDMA.test;run-ib_read_bw_extended-mtu-2000-test_opt--D_10s-57a4: STARTED
(002/261) rdma_tests.py:RDMA.test;run-ib_read_bw_extended-mtu-2000-test_opt--D_10s-57a4: FAIL: Client cmd: ib_read_bw -D 10s (4.13 s)
(003/261) rdma_tests.py:RDMA.test;run-ib_read_bw_extended-mtu-3000-test_opt--D_10s-268d: STARTED
=> Duration period argument should be integer instead of string

perf/perf_c2c.py, perf/perf_sched.py
[perf_sched_job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/12523401/perf_sched_job.log)
[perf_c2c_job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/12523415/perf_c2c_job.log)
[root@ perf]# avocado run --max-parallel-tasks=1 perf_c2c.py -m perf_c2c.py.data/record_report.yaml
JOB ID     : a385aaeb517c3bb0d58f112ece1e9e74a6132043
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-09-05T07.04-a385aae/job.log
(001/210) perf_c2c.py:perf_c2c.test_c2c;run-record-event_load-report-coalesce-ec55: STARTED
(001/210) perf_c2c.py:perf_c2c.test_c2c;run-record-event_load-report-coalesce-ec55: PASS (2.04 s)
... 
(210/210) perf_c2c.py:perf_c2c.test_c2c;run-record-all_user_full-report-stdio-97a2: STARTED
(210/210) …
=> Output validation for perf_c2c and perf_sched

generic/ltp.py
Cleaning up ltp directory at the end of each test case.
The job log file remains same. Hence debug logs can be used to analyse the test results
=> Cleaning up ltp directory at the end of each test case.

perf/aiostress.py, perf/aiostress.py.data/aiostress.yaml
remove libaio package as not needed anymore
fix below compilation error by building and compiling LTP first and then run aio-stress test
"ERROR: Command 'gcc -Wall -o aio-stress /root/avocado/data/cache/by_location/1045d5a4350b89433ad0cb55a0f87cb8ba4fc0b2/aio-stress.c -laio -lpthread' failed."
[root@]# avocado run aiostress.py
JOB ID     : 75bcbb78787102a2196015ae7802892f00a01ea6
JOB LOG    : /home/geet/avocado-fvt-wrapper/results/job-2023-09-14T08.15-75bcbb7/job.log
(1/1) aiostress.py:Aiostress.test: STARTED
(1/1) aiostress.py:Aiostress.test: PASS (36.41 s)
JOB HTML   : /home/geet/avocado-fvt-wrapper/results/job-2023-09-14T08.15-75bcbb7/results.html
JOB TIME   : 56.44 s
=> fix LTP aio-stress test

io/net/netperf_test.py, io/net/netperf_test.py.data/nettest_omni.patch
Use nettest_omni.patch for fixing make issue seen during compilation of package on host and peer machine
=> Patching netperf package for successful compilation

generic/ltp.py, generic/ltp.py.data/ltp-net.yaml
1. The code had input parameter called two-host-configuration passed into yaml file. If the parameter is set to "True" Ltp runs between 2 hosts, otherwise default value is "False" and ltp runs on single machine
2. Necessary services restart is added.
3. Ltp Network-Stress bucket is added.
4. README.txt file is added for the understanding of single host and two host configurations.
=> Adding network-Stress cases and support for two host configuration for ltp network tests

io/common/bootlist_test.py, io/common/bootlist_test.py.data/bootlist_test_network.yaml, io/net/multiport_stress.py, io/net/multiport_stress.py.data/README.txt, io/net/multiport_stress.py.data/multiport_stress.yaml, io/net/multiport_stress.py.data/multiport_stress_virt.yaml
To simplify and avoid extra parameters, keep a common input parameter name across all network test i.e rename host_interface to just interfaces
=> interfaces: use common name accross all tests

io/pci/dlpar.py, io/pci/dlpar.py.data/README, io/pci/dlpar.py.data/dlpar.yaml
Adding support for multiple PCI devices to perform DLPAR test.
multipile pci devices can be mentioned in yaml file for "param: pci_device" separated by space. Dlpar test runs on each pci device one after other in a loop.
EX : pci_device: "01xx:xx:x.0 02xx:xx:x.0"
=> Adding support for multiple PCI devices to perform DLPAR test.

security/kernel-hardening-tests.py
Cancel the test for RHEL8 series. This feature is there in RHEL9 and SLES15 series of releases.
=> kernel-hardening-tests.py: Cancel the test for RHEL8 series

memory/memhotplug.py.data/memhotplug.yaml
In yaml "=" is not supported, updating to ":"
Before:
avocado run --max-parallel-tasks 1 memhotplug.py -m memhotplug.py.data/memhotplug.yaml
JOB HTML : /home/AvocadoTests_src/results/job-2023-10-11T05.23-3e7f92e/results.html
JOB TIME : 434.15 s
JOB ID : a7793f2978f3fa74b9b234b1d51f34f4f43375d6
JOB LOG : /home/AvocadoTests_src/results/job-2023-10-11T05.36-a7793f2/job.log
(1/4) memhotplug.py:MemStress.test_hotplug_loop;run-fb7c: STARTED
Invalid multiplex file 'memhotplug.py.data/memhotplug.yaml': mapping values are not allowed in this context
in "memhotplug.py.data/memhotplug.yaml", line 2, column 10
Make sure !tags and colons are separated by a space (eg. !include :) : memhotplug.py.data/memhotplug.yaml
After:
JOB ID     : 3e7f92e7642c6d9e43fc9e27acc1a4325c1414d9
JOB LOG    : …
=> correct syntax in yaml "=" to ":"

ras/smtstate.py
time package was missing, installed time package
smtstate test failing as `/usr/bin/time` not always a time binary
Signed-off-by: Sneh Shikha Yadav <syadav@linux.vnet.ibm.com>
=> fix /usr/bin/time binary issue for smtstate test

cpu/numatop.py
Using custom built latest numatop binary for test
As distro built numatop doesnt support on AMD cpu's
> $numatop
> CPU is not supported!
--BEFORE--
> (1/1) numatop.py:Numatop.test: STARTED
> (1/1) numatop.py:Numatop.test: FAIL: Numatop failed to record mgen latency. Please check the record file: /home//results/job-2023-09-27T05.11-4b6470f/test-results/1-numatop.py_Numatop.test/tmp_dirz9h_td2_/1-numatop.py_Numatop.test/num... (43.59 s)
--AFTER--
> Fetching asset from numatop.py:Numatop.test
> JOB ID     : 046a8ac1d6165e2ed1f0a099506f105c8f777f11
> JOB LOG    : /home/AvocadoTests_src/results/job-2023-09-27T05.57-046a8ac/job.log
> (1/1) numatop.py:Numatop.test: STARTED
> (1/1) numatop.py:Numatop.test: PASS (42.93 s)
> RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | …
=> Use built latest numatop binary only

toolchain/binutils.py
Patch fix issue the issue undefind variable
without this patch
[stdlog] 2023-10-16 07:45:46,510 stacktrace       L0040 ERROR|
[stdlog] 2023-10-16 07:45:46,510 stacktrace       L0045 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-102.0-py3.6.egg/avocado/core/test.py:616
[stdlog] 2023-10-16 07:45:46,510 stacktrace       L0049 ERROR| Traceback (most recent call last):
[stdlog] 2023-10-16 07:45:46,510 stacktrace       L0049 ERROR|   File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/toolchain/binutils.py", line 60, in setUp
[stdlog] 2023-10-16 07:45:46,510 stacktrace       L0049 ERROR|     self.check_install(pkg)
[stdlog] 2023-10-16 07:45:46,510 stacktrace       L0049 ERROR|   File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/toolchain/b …
=> Test error out due to undefind variable name

security/ima-modsig-tests.py
Cancel the test for RHEL8 series. This feature is there in RHEL9 and SLES15 series of releases.
=> ima-modsig-tests.py: Cancel the test for RHEL8 series

memory/memhotplug.py
After Commit 44b8f8bf2438 ("mm: memory-failure: add memory failure stats to sysfs") got merged /sys/devices/system/node/node${X}/memory_failure was intoduced, resulted in Out of Index error in get_hotpluggable_blocks().
Solving it by looking for only memory[0-9]* files and ignoring others.
Before:
[stdlog] 2023-10-12 00:16:27,777 avocado.test INFO | Hotplug all memory in Numa Node 0
[stdlog] 2023-10-12 00:16:27,778 avocado.test ERROR|
[stdlog] 2023-10-12 00:16:27,778 avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.9/site-packages/avocado/core/test.py:631
[stdlog] 2023-10-12 00:16:27,778 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2023-10-12 00:16:27,779 avocado.test ERROR|   File "/root/avocado-misc-tests/memory/memhotplug.py", line 222, in …
=> Exclude memory_failure from memory hotplug

perf/aiostress.py
aiostress test compilation fails with libaio and other pkg dependency. 
Add dependent pkgs to compile ltp first and run aiostress test.
before fix:
avocado run aiostress.py
JOB ID : a7d12e0a55835858a27871d458b3abb21607e718
JOB LOG : /home/avocado-fvt-wrapper/results/job-2023-11-28T03.47-a7d12e0/job.log
(1/1) aiostress.py:Aiostress.test: STARTED
(1/1) aiostress.py:Aiostress.test: ERROR: Command 'make autotools' failed.\nstdout: b"sed -n '1 {s:LTP-:m4_define([LTP_VERSION],[:;s:$:]):;p;q}
' VERSION > m4/ltp-version.m4\nmake -C testcases/realtime autotools\nmake -C testcases/open_posix_testsuite autotools\naclocal -I m4\nmake[1]: Entering dire... (2.99 s)
RESULTS : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : …
=> fix package dependency for aiostress

cpu/schbench.py, cpu/schbench.py.data/schbench.yaml
This patch is intended to revise the script by integrating the most recent updates from latest schbench (upstream).
**Before Patch:**
```
JOB ID     : e0a0a4c0718efe23a57a0c890c5d52b15a88d85f
JOB LOG    : /root/avocado/job-results/job-2023-11-24T01.42-e0a0a4c/job.log
(1/1) cpu/schbench.py:Schbench.test: STARTED
(1/1) cpu/schbench.py:Schbench.test: FAIL: The test failed. Failed command is   /root/avocado/job-results/job-2023-11-24T01.42-e0a0a4c/test-results/1-cpu_schbench.py_Schbench.test/tmp_dirqc2plqkc/1-cpu_schbench.py_Schbench.test/schbench -m 10 -t 10 -p 1000 -r 100 -s 10000  (0.96 s)
JOB TIME   : 3.54 s
Test summary:
cpu/schbench.py:Schbench.test: FAIL
```
**After Patch:**
```
JOB ID     : …
```
=> cpu/schbench: fix schbench test to incorporate the latest updates

kernel/kselftest.py, kernel/kselftest.py.data/ftrace_powerpc.yaml, kernel/kselftest.py.data/trace_tests.yaml
[debug.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/12273177/debug.log)
Modify kselftest.py to run upstream ftracetest from 'merge' branch or powerpc tree. Add ftrace.yaml to run the test.
=>  add_upstream_ftrace

cpu/numactl.py
On running 'avocado run numactl.py:test' all the tests are being executed. As per docuemntation, when the test references are about Instrumented Tests, Avocado will find any Instrumented test that starts with the reference, like a “wildcard”.
Thus renaming 'test' to 'test_basic' in order to be able to run it singly.
=> Rename test 'test' to 'test_basic' in order to run singly

cpu/numactl.py
For block device netifaces module is not required and it is failing on not getting it installed. So I changed it by /sys/ dir value for getting the network interfaces and it works fine after re-place this
=> Removing the netifaces module from a common numactl.py script

io/iommu/amd/iommu_v2pgmode_test.py
IOMMU in v2 mode should use the same level of paging as host page table. For e.g. if the host uses 5-level of paging and IOMMU is using v2 page table then IOMMU should also use 5-level paging for v2 page table.
=> io/iommu: Add test to validate paging level in IOMMU v2 mode

generic/ltp.py.data/ltp-fs.yaml
fsx test has been removed from runtest suite in LTP. So renaming fsx to ltp-aiodio.part3 which covers fsx-linux tests.
Also add fs_readonly tests.
https://github.com/linux-test-project/ltp/commit/fb2b6a0b3c840aa80229acf4360b7bdc3ced5edb
avocado run --max-parallel-tasks=1 ltp.py -m ltp.py.data/ltp-fs.yaml
Fetching asset from ltp.py:LTP.test
Fetching asset from ltp.py:LTP.test
JOB ID     : 6ec078fe0e728bb3e828c91317d52c5e5218f7b1
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2024-01-08T18.28-6ec078f/job.log
(1/5) ltp.py:LTP.test;run-runltp-fs-a975: STARTED
(1/5) ltp.py:LTP.test;run-runltp-fs-a975:  PASS (1599.48 s)
(2/5) ltp.py:LTP.test;run-runltp-fs_perms_simple-1a00: STARTED
(2/5) ltp.py:LTP.test;run-runltp-fs_perms_simple-1a00:  PASS (207.43 s)
(3/5) …
=> fix ltp fsx test

perf/pgbench.py, perf/pgbench.py.data/README, perf/pgbench.py.data/pgbench.yaml
Introduce the pgbench benchmark to enable performance benchmarking of postgres databases. This will be useful in identifying performance regressions quickly.
> [root@localhost perf]# avocado run pgbench.py -m pgbench.py.data/pgbench.yaml
JOB ID     : c0fcdc9b3a30b93249b9dc6cdb07a681375cf394                                                                         
JOB LOG    : /root/avocado/job-results/job-2023-12-21T06.56-c0fcdc9/job.log                                                   
(1/1) pgbench.py:Pgbench.test;run-transaction_count-f854: STARTED                                                                      
(1/1) pgbench.py:Pgbench.test;run-transaction_count-f854: PASS (82.17 s)                                                               
RESULTS    : PASS 1 | ERROR 0 | …
=> perf/pgbench: Introduce pgbench benchmark

perf/perf_top.py, perf/perf_top.py.data/perf_top.yaml
--group option has been removed from perf top, so remove the option from yaml file.
Enhance test to fail if exit status is non zero, any error message and when hit segmentation fault.
example of segfault error:
./perf top -g
perf: Segmentation fault
-------- backtrace --------
./perf[0x102aa6f8]
linux-vdso64.so.1(__kernel_sigtramp_rt64+0x0)[0x7fff83a10444]
./perf[0x1018e43c]
[0x7fff2debd7f0]
./perf[0x1012466c]
./perf[0x10288444]
./perf[0x10183b5c]
./perf[0x1017d83c]
./perf[0x101d3d48]
./perf[0x1003cb68]
./perf[0x1019cbc8]
./perf[0x1003c1b0]
/lib64/glibc-hwcaps/power10/libc.so.6(+0xaa0b0)[0x7fff824aa0b0]
/lib64/glibc-hwcaps/power10/libc.so.6(clone+0xa0)[0x7fff82552f48]
avocado run perf_top.py -m perf_top.py.data/perf_top.yaml --max-parallel-tasks=1
JOB ID     : …
=> perf/perf_top: fix group option

perf/perf_duplicate_probe.py
remove kernel-default-debuginfo package as it's not required to run the test.
on rhel
avocado run perf_duplicate_probe.py
JOB ID     : a475d0454a40ec7433a46c014c9c4382a2e0383c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-01-17T02.37-a475d04/job.log
(1/1) perf_duplicate_probe.py:PerfDuplicateProbe.test_duplicate_probe: STARTED
(1/1) perf_duplicate_probe.py:PerfDuplicateProbe.test_duplicate_probe: PASS (0.93 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-01-17T02.37-a475d04/results.html
JOB TIME   : 5.16 s
on suse
avocado run perf_duplicate_probe.py
JOB ID     : 432a65c768efb31dce3478e05260a20cfec5d578
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-01-17T03.47-432a65c/job.log …
=> perf_duplicate: fix package dependency

perf/perf_24x7_all_events.py
test gives error saying 'hv_24x7_all_events' object has no attribute 'physical_sockets'. 
Fix this by defining the attributes before attempting to access.
avocado run perf_24x7_all_events.py
JOB ID     : 84266c5177555061f9e97e16781fbff2b35717f8
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2023-11-16T14.36-84266c5/job.log
(1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: STARTED
(1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: PASS (2163.66 s)
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2023-11-16T14.36-84266c5/results.html
JOB TIME   : 2167.29 s
=> fix 24x7 attribute error

fs/xfstests.py.data/ext4/64k_adv_auto.yaml, fs/xfstests.py.data/ext4/64k_auto.yaml, fs/xfstests.py.data/ext4/64k_ext3.yaml
Exclude ext4/048 test from 64k block size yaml files as test gets stuck which results in timeout and blocks test run.
Link to CR run log:
http://9.40.192.188/DistroCR/246/results/TestRunner/log
[ 3055.512082] run fstests ext4/048 at 2023-12-01 15:18:06
[ 3055.516181] Lockdown: check: debugfs access is restricted; see man kernel_lockdown.7
[ 3055.620194] EXT4-fs (loop1): mounted filesystem with ordered data mode. Quota mode: none.
[ 3055.635937] EXT4-fs (loop1): unmounting filesystem.
[ 3055.657436] EXT4-fs (loop1): mounted filesystem with ordered data mode. Quota mode: none.
[ 3055.660966] EXT4-fs (loop1): unmounting filesystem.
[ 3055.669196] EXT4-fs (loop1): mounted filesystem with ordered data mode. Quota mode: none.
[ 3055.672608] EXT4-fs (loop1): unmounting filesystem.
[ 3055.689216] …
=> fs/xfstest: exclude ext4/048 test

perf/perf_stress_ng.py
Changed default run_type to distro. Corrected typos and spelling errors.
avocado run perf_stress_ng.py -m perf_stress_ng.py.data/perf_stress_ng.yaml
Fetching asset from perf_stress_ng.py:Stressng.test
JOB ID     : 07960e1d2974035fd5c85fc0eb1d5c730a532394
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-01-19T01.25-07960e1/job.log
(1/1) perf_stress_ng.py:Stressng.test;run-coverage-run_type-df37: STARTED
(1/1) perf_stress_ng.py:Stressng.test;run-coverage-run_type-df37: FAIL:  CPU load 10 50 80 combination's failed with percentage difference {'50': 11.799999999999997, '80': 17.4} (235.61 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-01-19T01.25-07960e1/results.html
JOB TIME   : 263.85 s
Test …
=> Fix perf stress ng

io/disk/dlpar_vscsi.py
lscfg -vl do not support device id input, so
get the node name for given device id to fix
device not found error
=> dlpar_vscsi: get device node for lscfg

io/driver/module_unload_load.py, io/driver/module_unload_load.py.data/config
multipath flush was failing due to string not matching exactly as below,
nvme                   55964  4
nvme_core             183368  5 nvme
we were expecting only : "nvme                   55964  4"
the first line only. But it is matching all the line that contain the module name.
-w option resolve this as below.
nvme                   55964  4
=> fixing multipath flush problem in module_load_unload.py

fs/filebench.py
Filebench causes segmentation fault on system when ASLR is enabled as memory starts to overlap when many processes are defined with same binary of filebench. So running benchmark with addr_no_randomize personality making the benchmark to run cleanly.
------------------Before------------------
```
kernel: [ 2289.327296] filebench[20097]: segfault at 55f32aecd0f0 ip 000055f32aecd0f0 sp 00007fa0d09ffde8 error 14 likely on CPU 33 (core 33, socket 0)
kernel: [ 2289.327318] Code: Unable to access opcode bytes at 0x55f32aecd0c6.
```
------------------After------------------
```
avocado run filebench.py
Fetching asset from filebench.py:Filebench.test
JOB ID     : 8eac884d619047d3dbdb6859c3cf6f5f847bddf5
JOB LOG    : /root/AvocadoTests_src/results/job-2024-02-19T18.35-8eac884/job.log
(1/1) …
```
=> Run filebench with addr_no_randomize

cpu/numactl.py, io/net/irqbalance.py, io/net/network_test.py
Add support for mac addr as input, in case if the
device names are not persistent across os install
the test should still run via unique mac addr in
end to end automated environment
=> network_stress: support hw addr as input name

io/net/virt-net/lpm.py
checking the error levels up to level 4 for LPM tests than the default level 5
1 - emerg
2 - emerg,alert
3 - emerg,alert,crit
4 - emerg,alert,crit,err
5 - emerg,alert,crit,err,warn
=> dmesg error level check for lpm test

ras/ras_lsvpd.py
get_pci_info() routine was added with avocado v99.0. A check for this version
was added to ensure part of the test is cancelled for older avocado releases.
Remove this dead code since most users have switched to using newer
avocado releases
=> ras/ras_lsvpd: Remove avocado version check

generic/ltp.py, io/disk/ltp_fs.py
With latest ltp source, a user id check has been added causing the test to wait for user response to this check
..user ids and/or groups are missing, would you like these created? [y/N]
This code solves this check by passing the 'y' string to automatically proceed the test
=> ltp_fs : resolve interactive user check

kernel/kselftest.py, kernel/kselftest.py.data/kselftest.yaml, kernel/kselftest.py.data/kselftest_cpufreq.yaml, kernel/kselftest.py.data/kselftest_upstream.yaml
Modify kselftest.py to run upstream cpufreq testcase
Adding kselftest_cpufreq.yaml and modified kselftest.yaml
to run with basic mode of cpufreq.yaml.
Tests to run with upstream kernel only.
=> kernel/kselftest: Modify kselftest to run cpufreq testcases

security/grub-extend-pcr.py
localhost:# avocado run --max-parallel-tasks=1 grub-extend-pcr.py
JOB ID     : 1dfd2c3459f708c42271d21a32e6251d5706d9d4
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-01-16T00.36-1dfd2c3/job.log
(1/4) grub-extend-pcr.py:GrubExtendPCR.test_tsspcrread_8: STARTED
(1/4) grub-extend-pcr.py:GrubExtendPCR.test_tsspcrread_8: PASS (0.04 s)
(2/4) grub-extend-pcr.py:GrubExtendPCR.test_tsspcrread_9: STARTED
(2/4) grub-extend-pcr.py:GrubExtendPCR.test_tsspcrread_9: PASS (0.04 s)
(3/4) grub-extend-pcr.py:GrubExtendPCR.test_tsseventextend: STARTED
(3/4) grub-extend-pcr.py:GrubExtendPCR.test_tsseventextend: PASS (0.04 s)
(4/4) grub-extend-pcr.py:GrubExtendPCR.test_boot_aggregate: STARTED
(4/4) grub-extend-pcr.py:GrubExtendPCR.test_boot_aggregate: PASS (0.04 s)
RESULTS    : PASS 4 | ERROR 0 | …
=> Test boot aggregate

cpu/em_cpufreq.py, cpu/em_cpufreq.py.data/em_cpufreq.yaml
cpu/em_cpufreq: fix and refactor cpufreq test
- Ensure validation of cpufreq setting in `cpuinfo_cur_freq`.
- Validate cpufreq with absolute difference to ensure and detect both positive and negative discrepancies.
- Add a configuration file to make a few attributes configurable.
**On PowerNV:**
```
JOB ID     : eb78a83466c7e2cc5e2126cd5b852cb860ce5f29
JOB LOG    : /root/avocado/job-results/job-2024-01-10T04.50-eb78a83/job.log
(1/1) cpu/em_cpufreq.py:Cpufreq.test: STARTED
(1/1) cpu/em_cpufreq.py:Cpufreq.test: PASS (61.24 s)
JOB TIME   : 63.50 s
```
**Some logs on PowerNV:**
```
DEBUG| 1-cpu/em_cpufreq.py:Cpufreq.test: [stdout] Setting cpu: 127
INFO | 1-cpu/em_cpufreq.py:Cpufreq.test: Getting CPU frequency …
```
=> cpu/em_cpufreq: fix and refactor cpufreq test

cpu/load_balancer.py, cpu/load_balancer.py.data/load_balancer.yaml
This test case entails executing a workload and subsequently analyzing how a load balancer distributes the workload among the available CPU cores. 
Below steps are implemented as a part of the test case,
1. Running the stress-ng workload.
2. Changing the SMT modes.
3. Validating the mpstat command output for CPU utilization as per SMT mode.
=> Added new test case to validate the scheduler load balancer.

kernel/kselftest.py
Fix following warnings from python code style checker tool
113:80: E501 line too long (87 > 79 characters)
119:80: E501 line too long (85 > 79 characters)
121:80: E501 line too long (88 > 79 characters)
214:15: E275 missing whitespace after keyword
218:17: E275 missing whitespace after keyword
=> kernel/kselftest: Fix code style issue

ras/hwinfo.py
Added check to "--save-config SPEC" test to FAIL
when hwinfo fails to save the configuration file
Added check to "--show-config SPEC" test to CANCEL 
when there is no saved configuration file present
Removed reduntant self.log(..) function wherever
necessary
Added "=all" to "--save-config" self.fail() message
to make it more meaningful
Signed-off-by: Misbah Anjum N [misanjum@linux.vnet.ibm.com](mailto:misanjum@linux.vnet.ibm.com)
=> ras/hwinfo.py: fix false positive test-cases

kernel/kselftest.py.data/kselftest_comp.yaml
Recent upstream kernel has new selftests added for powerpc.
dexcr via commit bdb07f35a52f: Add hashst/hashchk test
papr_attributes via commit 57201d657eb7: PAPR sysfs attributes sniff test
papr_sysparm via commit 76b2ec3faeaa: Add test for papr-sysparm
papr_vpd via commit 9118c5d32bdd: Add test for papr-vpd
Update the powerpc component specific yaml file to include these tests.
=> kernel/kselftest: Update powerpc component yaml

workload/ebizzy_workload.py, workload/ebizzy_workload.py.data/perf_top_args.yaml
[root@ workload]# avocado run --max-parallel-tasks=1 ebizzy_workload.py -m ebizzy_workload.py.data/perf_top_args.yaml
Fetching asset from ebizzy_workload.py:ebizzy.test_start_ebizzy_workload
Fetching asset from ebizzy_workload.py:ebizzy.test_stop_ebizzy_workload
JOB ID     : 1f9dce400f42a9799dd68a0f7e8f15984ad6f9be
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-22T02.49-1f9dce4/job.log
(1/2) ebizzy_workload.py:ebizzy.test_start_ebizzy_workload;run-2baa: STARTED
(1/2) ebizzy_workload.py:ebizzy.test_start_ebizzy_workload;run-2baa: PASS (30.62 s)
(2/2) ebizzy_workload.py:ebizzy.test_stop_ebizzy_workload;run-2baa: STARTED
(2/2) ebizzy_workload.py:ebizzy.test_stop_ebizzy_workload;run-2baa: PASS (0.63 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL …
=> Added ebizzy workload to run with YAML parameters

trace/dawr.py, trace/perf_uprobe.py, trace/trace_UDT_probes.py
- Added distros "fedora", "centos" in trace_UDT_probes.py for installing packages: "perf", "systemtap-sdt-devel.ppc64le"
- Added self.distro_name == "fedora" in perf_uprobe.py for testing of "perf record .." command
- Added self.distro_name == "fedora" in dawr.py to enable extra setting required to run gdb for fedora
Signed-off-by: Misbah Anjum N [misanjum@linux.vnet.ibm.com](mailto:misanjum@linux.vnet.ibm.com)
=> trace: Add Fedora Support to trace testing

fs/xfstests.py
With upstream as a target following failures are observed
- inih header file dependency during xfsprogs code compilation
- local.config file not found
This 2 patch series fixes these problem.
=> Xfstest fixes with upstream as a target

fs/xfstests.py
Commit 3fc8e18 introduced a regression as it missed a
comma after userspace-rcu-devel.
Update the code accordingly to fix this regression.
=> fs/xfstest: Fix a regression introduced by 3fc8e18

ras/ras_ppcdiag.py
upstream source code for ppc64_diag fails to compile due to
dependency on libudev header
[stderr] configure: error: libudev header files are required for
building ppc64-diag
Update the package dependency list to reflect the same
=> ras/ras_ppcdiag: Update package dependency

perf/perf_genericevents.py, perf/perf_genericevents.py.data/raw_code.cfg
CPU event mappings for AMD Zen processors can vary within the same family. Hence, switch to using the core generation for mapping events. The core generation can be determined by inspecting family and model combinations.
Also update raw_code.cfg with latest event mappings and add an AMD Zen specific formula for computing the raw event code. The formula assumes that the "event" field occupies bits 35:32,7:0 and the "umask" field occupies bits 15:8 as described in the AMD PPRs.
Suggested-by: Sandipan Das <sandipan.das@amd.com>
=> perf/perf_genericevents.py: Use AMD Zen for parsing

fs/fsx.py
Fix issue caused by last commit of extra spaces in link
Before:
```
L0141 DEBUG| PARAMS (key=url, path=*, default=https: // github.com/linux-test-project/ltp/archive/master.zip) => 'https: // github.com/linux-test-project/ltp/archive/master.zip'
[stdlog] 2024-04-05 12:33:22,940 avocado.utils.asset asset            L0398 INFO | Fetching asset ltp-master.zip
[stdlog] 2024-04-05 12:33:22,940 avocado.utils.asset asset            L0402 INFO | Asset not in cache, fetching it.
[stdlog] 2024-04-05 12:33:22,941 avocado.utils.asset asset            L0152 DEBUG| Asset not in cache after lock, fetching it.
[stdlog] 2024-04-05 12:33:22,941 avocado.utils.download download         L0096 INFO | Fetching https:/// // github.com/linux-test-project/ltp/archive/master.zip -> …
```
=> fs/fsx:Fixing URLError for ltp link

ras/hwinfo.py
1. Updated: test_list as test_list_options to test all list options
2. Updated: test debug N to test hwinfo --debug 1,2 options
3. Updated: test dump N to test hwinfo --debug 1,2 options
4. Updated: test_disk by renaming it to test_only option to make it more suitable corresponding to the command
5. Updated: test_unique_id_save to CANCEL test if directory /var/lib/hardware/udi is not present. In Fedora, Rhel, etc Operating Systems, this directory is not part of the file system. The save config option will look for the presence of the directory to save the file. If it is not present, it will fail.
6. Updated: test_unique_id_show to CANCEL for same reason as test_unique_id_save
7. Updated: test_save_config to CANCEL for same reason as test_unique_id_save
Signed-off-by: Misbah Anjum N …
=> ras/hwinfo: Update testcases and their options

perf/perf_duplicate_probe.py, perf/perf_script_bug.py, perf/perf_script_bug.py.data/probe.cfg, perf/perf_test.py
Updated perf tests to enable fedora testing
This patch will also enable "perf test" failures
which were earlier cancelled due to missing
"fedora" support in distro.detect()
Signed-off-by: Misbah Anjum N [misanjum@linux.vnet.ibm.com](mailto:misanjum@linux.vnet.ibm.com)
=> perf: Fix false results and add Fedora support

cpu/numatop.py
commit 25839aa added POWER10 support in numatop
numatop/powerpc: Add power10 support
Remove the POWER10 check from the test so that it can run
on POWER10.
=> cpu/numatop: Remove POWER10 check

perf/perf_mem.py
Add a check to identify Ubuntu OS and install the required package.
Without this check the test fails to run on Ubuntu.
=> perf/perf_mem: Add support for ubuntu

io/net/htx_nic_devices.py, io/net/htx_nic_devices.py.data/htx_nic_devices.yaml
The build_net multisystem command introduced is for automatic configuration of network interfaces on both host and peer. The command set's the interfaces with some local net id's and pings the interfaces. The command also starts the htx deamon creates/selects and activates net.mdt for the network devices. No need to explicitely start the htx deamon or create/select or activate net.mdt file.
Also removing the code that was supporting the old htx network topology and made compatible to new configuration changes.
=> Adapting the new changes made in htx setup/configuration.

perf/perf_stress_ng.py, perf/perf_stress_ng.py.data/README.txt
Commit 1
The test result shows test passed with warning when test did not ran. Fix the tear down by adding a check to ensure removal of files only occurs if they exist.
Before fix:
avocado run perf_stress_ng.py -m perf_stress_ng.py.data/perf_stress_ng.yaml
Fetching asset from perf_stress_ng.py:Stressng.test
JOB ID     : 2abafaa0af699b4a3918c7838dff061c9e774aaf
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-03-06T04.10-2abafaa/job.log
(1/1) perf_stress_ng.py:Stressng.test;run-coverage-run_type-df37: STARTED
(1/1) perf_stress_ng.py:Stressng.test;run-coverage-run_type-df37: WARN: Test passed but there were warnings during execution. Check the log for details. (1.31 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 0
JOB HTML   : …
=> fix tear down and add readme file

ras/ras_ppcutils.py
We are verifying the device by comparing ls-vdev and lsblk outputs, by adding a condition check
=> ras_ppcutils.py: compare ls_vdev output with lsblk

perf/perf_genericevents.py, perf/perf_genericevents.py.data/raw_code.cfg
Correct ref cycles event rawcode of amd64 respectively in zen4 and later in config file
debug.log ->
[stdlog] 2024-04-16 13:31:10,450 avocado.test perf_genericeven L0062 INFO | AMD Family: 25 ZEN4
...
[stdlog] 2024-04-16 13:31:10,451 avocado.test perf_genericeven L0096 INFO | FILE in /sys/bus/event_source/devices/cpu/events is ref-cycles
[stdlog] 2024-04-16 13:31:10,451 avocado.test perf_genericeven L0102 INFO | PASS : Expected value: 0x100000120 or 4294967584 and got 4294967584
...
=> Correct ref cycles raw codes

io/net/iperf_test.py, io/net/virt-net/network_virtualization.py, io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
The patch enables runnign of irqbalance service, tuning rx tx queue values before starting iperf tests.
The command to run iperf test from client side is improvised to include parallel threads, interval between periodic bandwidth reports and time in seconds to transmit for values
=> RX TX queue tuning before running iperf test

perf/perf_test.py
patch adds dependent packages needed to run the perf test
avocado run perf_test.py
JOB ID     : adedac829e04aa8c8feac87ed390f59fb2f8ba09
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-04-24T02.03-adedac8/job.log
(1/1) perf_test.py:Perftest.test_perf_test: STARTED
(1/1) perf_test.py:Perftest.test_perf_test: FAIL: 4 Test failed (104.39 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-04-24T02.03-adedac8/results.html
JOB TIME   : 123.77 s
=> perf/perf_test: add dependent packages

io/disk/ssd/nvmetest.py
Due to recent changes in nvmecli tool, the total capacity of disk is listed as string as comma (,) separated, but the test need the integer value due to which the tests were failing. fixed the same and now tests are running fine.
=> enhanced nvmetest.py to convert the total capacity of disk from strig to integer.

perf/perf_sdt_probe.py
On recent SLES distro test fails with below error due to issues locating libpthread and libc.
ERROR: Unable to remove 1062 libs found in cache `/etc/ld.so.cache’
On older distros, the path were identified as follows: 
libpthread.so.0 (libc6,64bit, OS ABI: Linux 3.10.0) => /lib64/libpthread.so.0 
libc.so.6 (libc6,64bit, OS ABI: Linux 3.10.0) => /lib64/libc.so.6
On current distro, the format changed to:
libpthread.so.0 (libc6,64bit) => /lib64/libpthread.so.0 
libc.so.6 (libc6,64bit) => /lib64/libc.so.6
To address this, the parsing logic is updated to correctly identify the paths in both cases.
```
On SLES
avocado run perf_sdt_probe.py
JOB ID     : 234e5315e5ae74fa969e9f9cdbe34b2f9a9dfaf2
JOB LOG    : /home/rohan/avocado-fvt-wrapper/results/job-2024-04-29T21.16-234e531/job.log
(1/1) …
```
=> perf/perf_sdt_probe: refine parsing logic for locating libpthread & libc

cpu/ppc64_cpu_test.py, cpu/ppc64_cpu_test.py.data/ppc64_cpu_test.yaml
This two patch series add following support:
Add upstream as a target for ppc64_cpu test
Add capabilities to download and compile upstream source for
powerpc-utils tools(ppc64_cpu).
Add a test case to validate following scenario:
A system with single online core along with consecutive smt
level change to ensure number of online cores do not change
=> cpu/ppc64_cpu: single core plus smt and upstream as a target

ras/sosreport.py
- Missing: self.sos_cmd = "sos report" for Fedora, Rhel and CentOS while checking distro name
- This was leading to 10 ERRORS, 1 PASS in test-cases causing FALSE TEST RESULTS
- This simple patch will result in 8 PASS, 1 ERROR, 2 FAILURES
Signed-off-by: Misbah Anjum N [misanjum@linux.vnet.ibm.com](mailto:misanjum@linux.vnet.ibm.com)
=> ras/sosreport.py: Fix errors/false-results

kernel/will-it-scale.py, kernel/will-it-scale.py.data/README, kernel/will-it-scale.py.data/will-it-scale.yaml
This patch adds a test to validate scalability aspect of kernel. Will It Scale
takes a testcase and runs n parallel copies to see if the testcase will scale. 
This test is based on https://github.com/antonblanchard/will-it-scale
The test includes yaml based input for each supported testcase.
=> kernel/will-it-scale: Add scalability test

security/annobin-tests.py
Run 'make' before running 'make check'.
Reproted-by: Kowshik Jois B S <kowsjois@linux.ibm.com>
=> annobin-tests.py: Run 'make' before 'make check'

perf/perf_c2c.py.data/record_report.yaml, perf/perf_sched.py.data/perf_sched.yaml, perf/perf_top.py.data/perf_top.yaml
Update perf_c2c, perf_sched and perf_top yaml files with new options available and removing unsupported options from perf_top yaml. commit 57594454ceb92 which adds support for addr2line and objdump
Also perf sched replay fails on some lpar where it reaches the limitation of the maximum open files. This is fixed by using -f option. commit 939cda521a24
Update values for pid and tid in perf_top yaml as with current value it fails with error Unknown option -p 10.
```
avocado run --max-parallel-tasks=1 perf_c2c.py -m perf_c2c.py.data/record_report.yaml
JOB ID     : e6ba5680e1b73cd7961b5a89e308e5447bab6bac
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-05-08T01.54-e6ba568/job.log
(1/4) perf_c2c.py:perf_c2c.test_c2c;run-record-verbose-report-5336: STARTED
(1/4) …
```
=> perf: update c2c/sched/top yaml files

perf/perf_cpu_hotplug.py
Add two new test cases.
The first test case offlines n-1 cpus randomly and checks if hv_24X7 points to any offline cpu.
The second test case checks the cpu pointed to by hv_24X7 event and offlines it. It then checks if the new cpu pointed to by hv_24X7 event is an online cpu, else the test fails. This is repeated n-1 times in a loop
Logs:
avocado run perf_cpu_hotplug.py
JOB ID     : a128bdd0142561e3399d997d05a25f6c70fce192
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-04-23T10.20-a128bdd/job.log
(2/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off: STARTED
(1/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask: STARTED
(3/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: STARTED
(1/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask: PASS (1.22 s) …
=> perf_cpu_hotplug_enhancements

workload/ebizzy_workload.py
One extra space was coming in start of output of "ps -e" command, added the fix using python strip() function and pycodestyle fix.
[root@ workload]# avocado run --max-parallel-tasks=1 ebizzy_workload.py:test_stop_ebizzy_workload
Fetching asset from ebizzy_workload.py:ebizzy.test_stop_ebizzy_workload
JOB ID     : eba7f5e70489870232d14b44919b30b21afd48bd
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-05-15T01.30-eba7f5e/job.log
(1/1) ebizzy_workload.py:ebizzy.test_stop_ebizzy_workload: STARTED
(1/1) ebizzy_workload.py:ebizzy.test_stop_ebizzy_workload: CANCEL: Ebizzy workload is not running or already execution finished (0.64 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-05-15T01.30-eba7f5e …
=> Added the fix for stop ebizzy workload function

ras/smtstate.py
As eval() is expecting argument as string,bytes or code object but we are getting an integer value so converted that to string.
=> smtstate.py: fix ERROR: eval() arg 1 must be a string, bytes or code object

perf/perf_json.py, perf/perf_json.py.data/perf_json.yaml
This patch adds a new test case to run all the perf pmu events. Also compares the event list and event code between perf command and json files from kernel source.
Result on RH8.x
avocado run --max-parallel-tasks=1 perf_json.py
JOB ID     : afb342cdee4ec378bcd801445c82977563930073
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-03-15T03.09-afb342c/job.log
(1/2) perf_json.py:perf_json.test_pmu_events: STARTED
(1/2) perf_json.py:perf_json.test_pmu_events:  PASS (2755.50 s)
(2/2) perf_json.py:perf_json.test_compare: STARTED
(2/2) perf_json.py:perf_json.test_compare:  PASS (2738.79 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-03-15T03.09-afb342c/results.html
JOB TIME   : 5505.32 s
Result on …
=> perf: add test to run json events

io/net/netperf_test.py, io/net/netperf_test.py.data/README.txt, io/net/netperf_test.py.data/netperf_test.yaml, io/net/netperf_test.py.data/netperf_test_virt.yaml
This patch assigns netperf command timeout values dynamically which helps to avoid "command execution timeouts" errors during the test execution.
=> Patch to fix Netperf_test "timeout" issues.

cpu/cpustress.py, ras/ras_ppcutils.py, ras/sosreport.py, ras/supportconfig.py
Some of the tests sosreport, supportconfig and likes invoke
drmgr to add/remove cpu/memory resources. The commands
used during the execution are syntatically incorrect.
For example:
drmgr -c mem -r 2
Correct command to use:
drmgr -c mem -r -q 2
Update the relevant tests to use correct syntax
=> Use correct syntax during drmgr invocation

cpu/xive.py
The file contains characters that are not valid UTF-8 encoded. This patch will fix the errors while reading the file.
=> cpu/xive.py : fixed 'utf-8' codec error

io/net/virt-net/network_virtualization.py, io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
Test is extended to run EEH for non-mellanox drivers. A new yaml parameter 'is_mlx'driver' is introduced for this test
=> Adding EEH support for non mellanox driver

ras/packages.py
Package powerpc-utils-core is specific to RHEL distribution so added distro check to the code.
Before on SLES distro:
localhost:# avocado run --max-parallel-tasks=1 packages.py
JOB ID     : f8e51817fb84fa0e6d5207d4273e1be128a044ad
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-06-04T05.40-f8e5181/job.log
(1/1) packages.py:Package_check.test: STARTED
(1/1) packages.py:Package_check.test: FAIL: ['powerpc-utils-core'] packages not installed by default (0.13 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-06-04T05.40-f8e5181/results.html
JOB TIME   : 47.14 s
Test summary:
1-packages.py:Package_check.test: FAIL
After patch on SLES: 
localhost:# avocado run --max-parallel-tasks=1 packages.py …
=> Added changes to distro specific packages

perf/perf_24x7_all_events.py, perf/perf_24x7_hardware_counters.py
This patch changes the logic to run domain=2 with physical cores and domain>2 with virtual cores available in the lpar.
Reference for above changes:
1: Physical Chip
2: Physical Core
3: VCPU Home Core
4: VCPU Home Chip
5: VCPU Home Node
6: VCPU Remote Node
Also integrated getting core and chip values directly from cpu.lscpu from avocado utils.
```
avocado run --max-parallel-tasks=1 perf_24x7_hardware_counters.py
JOB ID     : 022e5a78dd28c7deeccde4f8a90e005958883273
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-04-24T07.17-022e5a7/job.log
(01/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: STARTED
(01/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: PASS (1.32 s)
(02/13) …
```
=> perf/perf_24x7: fix domain and core values

perf/perf_lock.py, perf/perf_lock.py.data/readme.txt, perf/perf_lock.py.data/record_report.yaml
Adding test of "perf lock" command with options called "record", 
"report", "info", "script", "contention" with all possible through YAML file.
=> Adding "perf_lock" Tests.

io/disk/htx_block_devices.py
Some cases the old htx daemon is still running causing the htxd start command failing and exiting test, with this code we close old daemon before we start new
=> htx: fix htxd start daemon fail

kernel/kselftest.py
Ftrace tests were ending with a pass even if there were failures in the tests. This was due to the code reading the older snapshot of the log file for matching the 'not ok' string. Therefore, modify logic to paste the log to a different raw file and read the file to match for 'not ok' string.
JOB ID     : 715abe0fa709f9ff99eecd8d1b706825380746b7
JOB LOG    : /root/avocado/avocado-fvt-wrapper/results/job-2024-06-10T10.47-715abe0/job.log
(1/1) kselftest.py:kselftest.test;run-component-ftrace-run_type-distro-9c69: STARTED
(1/1) kselftest.py:kselftest.test;run-component-ftrace-run_type-distro-9c69: FAIL: Testcase failed during selftests (246.50 s)
JOB HTML   : …
=> ftrace_log_fix

security/trextest.py
Added code to execute all binaries inside trextest, it will replace kh_safeside.py test.
[root@]# avocado run --max-parallel-tasks=1 trex.py
JOB ID     : 98bf46b1756eb5e624793ab8bb8bb4efb9c29f8a
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-06-10T03.53-98bf46b/job.log
(1/1) trex.py:Trex.test_trex: STARTED
(1/1) trex.py:Trex.test_trex: PASS (374.56 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-06-10T03.53-98bf46b/results.html
JOB TIME   : 405.78 s
=> Added code to execute Trextest binaries.

cpu/perf_pipe_benchmark.py, cpu/perf_pipe_benchmark.py.data/README.txt, cpu/perf_pipe_benchmark.py.data/sched_pipe.yaml
Here in this test case  the command is running a scheduler benchmark using perf with the perf bench subcommand, specifically testing the scheduler's performance with a pipeline workload. The benchmark is repeated 5 times for accuracy, and the pipeline length is set to 10,000,000 tasks. The perf stat command is used to collect performance statistics during the benchmarking process.
=> Automated "perf sched benchmark" test.

dlpar/dlpar_main.py
While running test_mem_add passed wrong order of params to mem_payload_data function where it is unable to get the list of memory values to be added.So corrected the orderof passing params
=> dlpar_main.py: there is a wrong order of params passed to mem_payload_data

io/net/netperf_test.py
This code support to overwrite on already existing "netperf" files while unzipping from "netperf" tar file, rather than waiting user confirmation for abort, continue or replace for an existing files.
=> Overwrite already existing "netperf" files while tar file unzip

io/net/netperf_test.py, io/net/netperf_test.py.data/README.txt
This code supports to run the "netperf" server listening only with IPv4 address on both Host and Peer machines.
=> limiting "netperf" server to run only with IPv4/AF_INET 

io/net/htx_nic_devices.py, workload/htx_test.py
As htxd is already running then testcase is erroring out.So killing the existing pid of htxd and starting it fresh in order to select different mdt's required for testing
=> htx_test.py: Fixed the error where htxd is already running

cpu/lockstorm_benchmark.py, cpu/lockstorm_benchmark.py.data/lockstorm.yaml
Added support to capture and run the lockstorm_benchmark multiple times.
For this introduced new .yaml parameter
test_iter.
=> Added support to run the lockstorm benchmark multiple times

memory/pmem_dm.py
unmount function is not unmounting the pmem device because of which namespace destroy is failing so using the umount command.
=> Fix pmem_dm test failure due to 'Namespace destroy command failed'

cpu/pvr.py, cpu/pvr.py.data/pvr.cfg, cpu/xive.py, security/grub-extend-pcr.py, security/kernel-lockdown-tests.py, trace/dawr.py
Wave 1 of changes to add support for Power11.
- cpu/pvr.py
- security/grub-extend-pcr.py
- security/kernel-lockdown-tests.py
- cpu/xive.py
- trace/dawr.py
=> Add support for Power11

io/net/virt-net/network_virtualization.py
Patch initiates remote session for enabling
irqbalance , setting rxtx values on peer lpar
=> Initiating remote session before performance tune

.github/workflows/xfstests.yaml
For ubuntu:latest
Latest pip3 mandates to use virtual managed environment for pip packages. However since this is mainly automation and we know what we ar doing so pass the flag ("--break-system-packages") to force pip to install the package system wide.
For opensuse/leap:latest
Latest avocado-framework=100 and PyYAML=6.0.2 are incompatible. So move avocado-framework to 100.1 and PyYAML=6.0.1 which are still compatible.
=> .github/workflows/xfstests: Fix ubuntu and opensuse version requirements

io/net/virt-net/network_virtualization.py, io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
- tune vnic adapter queue to max supported values
- Use dmesg level=4 for vnic related tests
=> tune queue values for vnic adapter

nx_gzip/nx_gzip.py
Running the test on power11 system fails even though it
is supported. To support this and future generations of
IBM Power processors rewrite the processor family check
logic. Instead of checking for processor version, add a
check to detect nx-gzip support.
While at it, also remove the condition to execute configure
command.
=> nx-gzip/nx-gzip: Rewrite processor version check logic

memory/memhog.py
memhog test is failing due to arguments mismatch, this patch is to fix this issue.
=> Fix memhog test failure.

io/net/irqbalance.py
This fix supports to avoid caputuring "False" string when no process of ping running,instead of retuning False, the script cancel the test-case.
=> Fix to avoid returning "False" PID while no process running.

memory/migrate_pages.py
HAVE_HUGETLB_HEADER is not defined for sles because of which hugepage tests are failing, this patch is to fix this issue.
=> Fix migrate_pages.py hugepage test failures.

perf/perf_24x7_all_events.py, perf/perf_24x7_hardware_counters.py, perf/perf_cpu_hotplug.py, perf/perf_genericevents.py, perf/perf_json.py, perf/perf_metric.py, perf/perf_rawevents.py
This commit enhances the perf tests to support Power11 processor.
[results.tar.gz](https://github.com/user-attachments/files/16514536/results.tar.gz)
=> perf: enhance tests to support Power11

perf/perf_pmu.py
Add test (test_sysfs_events) for randomly picking files from sysfs and check if a normal user has write access to those files
(3/9) perf_pmu.py:PerfBasic.test_cpu_event_count: PASS (0.04 s)
(4/9) perf_pmu.py:PerfBasic.test_sysfs_events: STARTED
(4/9) perf_pmu.py:PerfBasic.test_sysfs_events: PASS (1.51 s)
(5/9) perf_pmu.py:PerfBasic.test_hv_24x7_event_count: STARTED
(5/9) perf_pmu.py:PerfBasic.test_hv_24x7_event_count: PASS (0.04 s)
(6/9) perf_pmu.py:PerfBasic.test_imc_event_count: STARTED
(6/9) perf_pmu.py:PerfBasic.test_imc_event_count: SKIP: This test is for PowerNV
(7/9) perf_pmu.py:PerfBasic.test_thread_event_count: STARTED
(7/9) perf_pmu.py:PerfBasic.test_thread_event_count: SKIP: This test is for PowerNV
(8/9) perf_pmu.py:PerfBasic.test_nest_cpumask: STARTED
(8/9) …
=> perf_pmu_test_enhancement

io/net/virt-net/network_virtualization.py, io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
Patch does the following:
- Use a common name for tx rx variables across tests
- Call the right variable in the ethtool command line
=> Setting persistent names for rx tx variables

io/net/htx_nic_devices.py
This code has fix for HTX hung issue that causes by killing the HTXD deamon during the setup, due to this HTX setup was existing with "cannot connect to peer" Error.
_**actual Error on HTX Host and Peer setup:**_
++++++++++++++++++++++++++++++++++++
[stdlog] 2024-08-26 17:11:50,863 avocado.utils.process process          L0658 INFO | Running 'pingum'
[stdlog] 2024-08-26 17:11:50,885 avocado.utils.process process          L0472 DEBUG| [stdout] Class B n/w configured, thisid=194.229, mylastnib=229
[stdlog] 2024-08-26 17:11:50,885 avocado.utils.process process          L0472 DEBUG| [stdout] Ping Com 9.40.194.229---->
[stdlog] 2024-08-26 17:11:50,886 avocado.utils.process process          L0472 DEBUG| [stdout] OK
[stdlog] 2024-08-26 17:11:50,886 avocado.utils.process process          L0472 …
=> Fix for HTX hung issue while setting Host and Peer setup.

io/disk/htx_block_devices.py
code fix to kill/shutdown all HTX/HCL processes that was initiated by HTX before initiating HTX for block devices.
Also this code fix re-initiating the HTX process when its already running.
**Actual Issue**
[stdlog] 2024-09-12 00:43:03,092 avocado.utils.process process          L0715 INFO | Command ' ps -C htxd -o pid=|xargs kill -9' finished with 1 after 0.001392055s
[stdlog] 2024-09-12 00:43:03,092 avocado.test stacktrace       L0041 ERROR|
[stdlog] 2024-09-12 00:43:03,092 avocado.test stacktrace       L0043 ERROR| Reproduced traceback from: /usr/local/lib/python3.9/site-packages/avocado_framework-106.0-py3.9.egg/avocado/core/test.py:607
[stdlog] 2024-09-12 00:43:03,092 avocado.test stacktrace       L0050 ERROR| Traceback (most recent call last):
[stdlog] 2024-09-12 00:43:03,093 …
=> Fix to shutdown all HCL process that initiated by HTX.

memory/pmem_dm.py
as Test error out while executing tearDown in case of Test cancles due to some dependencies
Failure log :
[stdlog] 2024-09-04 13:08:26,128 avocado.test stacktrace       L0041 ERROR|
[stdlog] 2024-09-04 13:08:26,128 avocado.test stacktrace       L0043 ERROR| Reproduced traceback from: /usr/local/lib/python3.9/site-packages/avocado_framework-106.0-py3.9.egg/avocado/core/t
est.py:604
[stdlog] 2024-09-04 13:08:26,129 avocado.test stacktrace       L0050 ERROR| Traceback (most recent call last):
[stdlog] 2024-09-04 13:08:26,129 avocado.test stacktrace       L0050 ERROR|   File "/usr/local/lib/python3.9/site-packages/avocado_framework-106.0-py3.9.egg/avocado/core/decorators.py", line
54, in wrapper
[stdlog] 2024-09-04 13:08:26,129 avocado.test stacktrace       L0050 ERROR|     raise exc
[stdlog] …
=> Patch fixes script error out issue in case early cancle

cpu/ebizzy.py
We have implemented support to store the ebizzy benchmark data in the job directory by creating a dedicated ebizzy_workload folder. Additionally, we are capturing the .json data for each iteration and saving it in the same ebizzy_workload folder for further analysis.
**Run logs:**
` avocado run ebizzy.py -m ebizzy.py.data/ebizzy.yaml  --max-parallel-tasks=1
Fetching asset from ebizzy.py:Ebizzy.test
JOB ID     : 41af3e8d54c5684efcf26b80318bf827ab457053
JOB LOG    : /root/Work/fvt/avocado-fvt-wrapper-1/results/job-2024-09-09T22.51-41af3e8/job.log
(1/2) ebizzy.py:Ebizzy.test;run-duration-default-perf-pin-size-threads-workers-22d2: STARTED
(1/2) ebizzy.py:Ebizzy.test;run-duration-default-perf-pin-size-threads-workers-22d2: PASS (201.60 s)
(2/2) …
=> Added support for ebizzy benchmark to dump stats data in to speical file.

workload/smt.py
Added support in the SMT workload to validate dmesg logs and copy the SMT logs from the /tmp/ directory to the current job run directory at intervals equal to the runtime duration specified in the .yaml configuration.
=> Added support in smt workload to validate dmesg logs.

cpu/podman_container.py, cpu/podman_container.py.data/podman.yaml
In this test case, we create a container with a specified period and quota, then run the ebizzy workload inside it. We capture the Podman statistics to verify that the CPU utilization percentage does not exceed the allocated resources.
=> Automated podman container test.

cpu/lockstorm_benchmark.py
Added support for lockstorm benchmark to dump data under "lockstorm_benc" dir under current job directory.
=> Added support for lockstorm benchmark to dump data in special file.

perf/perf_24x7_all_events.py, perf/perf_hv_gpci.py
Fix to accomodate event descripter in perf list.
On the current RHEL Distro, we have event descriptor along with events and while testing it is taking an event descriptor to test and is throwing an error. Change in the perf list command to remove event descriptors from the list.
=> perf_hv_gpci.py & perf_24x7_all_events.py: Fix

io/net/ethtool_test.py
ethtool -L option tests for different rx and tx length. The patch works on retrieving the original values for the interface and setting the rx and tx values to original values after the test.
=> set the queue length to original values after test

ras/ras_ppcutils.py
Lparstat test have multiple if/else statements to check for different options, if one fails then test execution stops, added fix to execute every statement and check failure at the end.
****
We can see multiple Fail conditions getting executed.
[root@ltcrain8oj-lp7 ras]# avocado run --max-parallel-tasks=1 ras_ppcutils.py:test_lparstat
JOB ID     : 690e2d43f40fde6cc7cb8216971d1a21e1dfcd77
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-10-03T22.44-690e2d4/job.log
(1/1) ras_ppcutils.py:RASToolsPpcutils.test_lparstat: STARTED
(1/1) ras_ppcutils.py:RASToolsPpcutils.test_lparstat: FAIL: ['Normalised busy plus idle value                                   does not match with Frequency percentage', 'number of physical processors consumed                                   are not …
=> Added fix to run every if/else statements in case of failure.

io/pci/pci_hotplug.py, memory/memhotplug.py
platform.processor is returning the unknown value and hence tests were failing. So changed this checking with other util functions like cpu.get_arch()
=> Fixing the issue of getting "Unknown" value with platform.processor

io/pci/dlpar.py
drmgr pci test is showing FAIL for test_drmgr_pci
this needs to be test CANCEL as sriov interface does not support drmgr -c pci option.
ls -l /sys/bus/pci/slots/<SLOT> is not available for sriov interface and the hence the -c pci option is failing.
=> print CANCEL message instead of FAIL for sriov

generic/stress-ng.py
Fix the teardown function to prevent AttributeError by adding checks to see if the attribute and path exists before trying to remove it.
Before fix:
ERROR: 'Stressng' object has no attribute 'loop_dev' 
ERROR: 'Stressng' object has no attribute 'stressmnt'
After fix:
CANCEL: Build Failed, Please check the build logs for details !!
```
avocado run stress-ng.py -m stress-ng.py.data/stress-ng-fs.yaml
Fetching asset from stress-ng.py:Stressng.test
JOB ID     : 6fc94c4cdaeba93499384ac1ca4b3790620f005a
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-10-23T13.59-6fc94c4/job.log
(1/1) stress-ng.py:Stressng.test;run-exclude-fs_type-ext4-stressors-workers-f640: STARTED
(1/1) stress-ng.py:Stressng.test;run-exclude-fs_type-ext4-stressors-workers-f640: CANCEL: Build Failed, Please check the …
```
=> stress-ng: fix teardown

perf/perf_c2c.py, perf/perf_genericevents.py, perf/perf_genericevents.py.data/raw_code.cfg, perf/perf_json.py, perf/perf_mem.py, perf/perf_pmu.py, perf/perf_rawevents.py
perf_c2c, perf_mem tests give error incase perf mem command fails when events are not available. Fix it by adding ignore_status check so test cancels.
```
Before fix:
ERROR: Command 'perf mem record -e list' failed.\nstdout: b''\nstderr: b'failed: memory events not supported\n'\nadditional_info: None
After fix:
CANCEL: perf c2c is not available
CANCEL: perf mem is not available
```
Added event raw codes for generic compat pmu for perf_genericevents test.
```
Before fix:
FAIL: Failed to verify generic PMU event codes
After fix:
JOB ID     : a2cf174c0134ef38b143831c6bdddbfd85946ee2
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2024-11-04T21.23-a2cf174/job.log
(1/1) perf_genericevents.py:test_generic_events.test: STARTED
(1/1) perf_genericevents.py:test_generic_events.test: PASS …
```
=> perf: fix perf tests to support generic compat pmu

io/pci/pci_hotplug.py, io/pci/pci_hotplug.py.data/pci_hotplug.yaml
nvme splitter location codes(slot numbers) are slightly different. They ends with R1/R2 values hence the script is failing. So added a method that handles to get the right slots numbers.
=> Adding support for nvme splitter in pci_hotplug.py

io/disk/bonnie.py, io/disk/bonnie.py.data/bonnie.yaml
The old url link do not work, as it moved from http to https and also update to latest version
=> bonnie: fix url link for test suite

io/disk/disk_info.py
Resolving platform.processor and other pylint issue in disk_info.py
=> Resolving platform.processor and other pylint issue in disk_info.py

memory/transparent_hugepages.py
Adding check to verify count value is non-zero.
[Bug 209952] RHEL10 [ P10 ] [ 6.11.0-0.rc5.22.el10.ppc64le ] [ FW1110.00 ]: transparent_hugepages.py test is failing on RHEL10
=> Patch to fix test failure on lpar with 1GB hugepages - v2

cpu/dwh.py, cpu/ebizzy.py, cpu/linsched.py
Fix patch application issue caused by incorrect current directory Fixes 8c1cc5b52a06: ("fix patch apply issue")
--Before--
ERROR| Traceback (most recent call last):
ERROR|   File "ebizzy.py", line 76, in setUp
ERROR|   File "/usr/lib64/python3.9/posixpath.py", line 375, in abspath
ERROR|     path = os.fspath(path)
ERROR| TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR|
ERROR| ERROR 1-ebizzy.py:Ebizzy.test;run-duration-default-perf-pin-size-threads-workers-e56a ->
TestSetupFail: expected str, bytes or os.PathLike object, not NoneType
And similar issue in dwh and linsched tests
This change fixes that
--After--
DEBUG| DATA (filename=dwh.cpp) => /root/avocado-misc-tests/cpu/dwh.py.data/dwh.cpp (found at file source dir) DATA (filename=Makefile) => …
=> Fix patch apply issue

kernel/will-it-scale.py.data/README, kernel/will-it-scale.py.data/will-it-scale.yaml
While running the will-it-scale test suite, it was observed that certain tests are getting stuck indefinitely, causing the entire test suite to be blocked. To avoid this, we are temporarily removing the following tests from the will-it-scale test bucket
1. malloc1
2. malloc2
=> Skip malloc1 and malloc2 due to indefinite runtime

ras/sosreport.py
Distro version and release should be compared as integer, added type cast of string to integer.
Before type casting-
For RHEL 10 also this is getting executed: 
if dist.name == "rhel" and dist.version <= "7" and dist.release <= "4":
self.sos_cmd = "sosreport"
=> Added type casting for Distro Version and Distro Release.

memory/ndctl.py.data/ndctl.yaml
test_fsdax_write, test_map_sync and test_devdax_write tests are failing with error 'Namespace create command failed' because of previously created namespace so changing preserve_change to false.
=> Fixes testcases failure due to previously created namespace.

io/disk/fiotest.py
nvdimm related packages are not getting installed for sles as they are under else condition, moved them out of else condition and added cmake and gcc-c++ dependent packages as compilation was failing due to missing packages.
=> Fix fiotest failure due to package dependency.

.github/workflows/lint_cehck.yml
Enable githubAction for lint check against any code changes in repo
=> Enable githubAction for lint check against any code changes in repo

io/disk/dbench.py, io/disk/fiotest.py, io/disk/fs_mark.py, io/disk/ltp_fsstress.py, io/disk/lvsetup.py, io/disk/tiobench.py, ras/lshw.py
Recently, avocado distro utils had a fix to return the full version number in ubuntu and debian distros, instead of just the major number earlier. This patch handles change that in tests.
Mentioned commit: https://github.com/avocado-framework/avocado/commit/55d1cd3a143d3a9a5667458da1e3014a7bc46939
=> Ubuntu version number handling in tests.

kernel/kselftest.py
result variable, which stores the command output of selftest, was being run either from test() or run_cmd(). This is based on the component for which it was being run. This patch makes it to be accessed from inside test() irrespective of where it is run, to access the output for post process.
Additionally, packages to be installed are also fixed to be in line with latest verions of Ubuntu.
=> kselftest: result variable to be accessed universally

io/net/tcpdump.py
Reprase the CANCEL message to
Cannot install package: pkg_name
=> rephrase message when test is cancelled

io/disk/fiotest.py
fiotest depends on libio-dev on ubuntu. But the package libio-devel was added to generic list, which is unavailable on ubuntu. This patch fixes it.
=> Fix wrong package name for fiotest

io/disk/disk_info.py, io/pci/pci_hotplug.py, memory/memhotplug.py
earlier we were validating "ppc" for power server, Now it has changed to power as from RH10 onwards this has been changed and the utility is also now returning powerpc
=> Changing the plotform validation to power for IBM power servers

io/iommu/amd/iommu_v2pgmode_test.py
**This patch series**
1. [Patch 1] Update check_kernelconf_5lvl() to usem "/lib/modules/<kernel_version>/build/.config" to check for kernel config
file making test work for both ubuntu and rhel.
2. [Patch 2] Add addtional journalctl check for kernel logs in addition to dmesg.
**Run**
avocado-misc-tests# avocado run io/iommu/amd/iommu_v2pgmode_test.py
JOB ID     : 3cc7db3ef40f8195a00951bf6c7f6556d79beefc
JOB LOG    : /root/tests/results/job-2025-03-04T08.04-3cc7db3/job.log
(1/1) io/iommu/amd/iommu_v2pgmode_test.py:IommuPageTable.test: STARTED
(1/1) io/iommu/amd/iommu_v2pgmode_test.py:IommuPageTable.test: PASS (0.21 s)
JOB HTML   : /root/tests/results/job-2025-03-04T08.04-3cc7db3/results.html
JOB TIME   : 1.91 …
=> io/iommu/amd: Update kernel config and dmesg check methods

io/iommu/iommu_tests.py
**This patch series**
1. [Patch 0/2] Add check to validate pci address (pci_addr) user input.
2. [Patch 1/2 and 2/2] Update the process of checking and validating dmesg for each subtest. Current process clears the dmesg 
affecting subsequent tests that depends on dmesg.
**Run**
```
avocado-misc-tests# avocado run io/iommu/iommu_tests.py -p pci_devices="0000:01:00.0" -p dmesg_grep="iommu|AMD-Vi" -p count='1' --max-parallel-tasks=
1
JOB ID     : 132c8969e459f615389a975bced0ded359a49735
JOB LOG    : /root/tests/results/job-2025-03-04T08.09-132c896/job.log
(1/6) io/iommu/iommu_tests.py:IommuTest.test_unbind_bind: STARTED
(1/6) io/iommu/iommu_tests.py:IommuTest.test_unbind_bind: PASS (6.55 s)
(2/6) io/iommu/iommu_tests.py:IommuTest.test_unbind_changedomain_bind: STARTED
(2/6) …
```
=> io/iommu: Validate pci_addr input and update check_dmesg()

io/iommu/amd/iommu_v2pgmode_test.py
Instead of canceling the test if kernel config file is not found, rely and derive cpu page table level from /proc/cpuinfo.
**Run**
```
avocado-misc-tests# avocado run io/iommu/amd/iommu_v2pgmode_test.py
JOB ID     : d36a3fa532950d598b273529a8854e1fe7be3944
JOB LOG    : /root/tests/results/job-2025-03-04T12.40-d36a3fa/job.log
(1/1) io/iommu/amd/iommu_v2pgmode_test.py:IommuPageTable.test: STARTED
(1/1) io/iommu/amd/iommu_v2pgmode_test.py:IommuPageTable.test: PASS (0.22 s)
JOB HTML   : /root/tests/results/job-2025-03-04T12.40-d36a3fa/results.html
JOB TIME   : 1.93 s
```
=> io/iommu/amd: Derive cpu page table level from va bits of /proc/cpuinfo

io/disk/fiotest.py, io/disk/ltp_fsstress.py, io/disk/lvsetup.py, io/disk/tiobench.py
The current utility returns the exact version and not required to further maniculate. hence changing the those .py files which has this further maniculations.
=> Fixed split error occured while getting distro version

kernel/will-it-scale.py, kernel/will-it-scale.py.data/makefile.patch
On certain Linux distributions libhwloc may not be available. This blocks the
execution of will-it-scale. Add support to compile and install libhwloc library
using the hwloc source code.
Update the will-it-scale source code to use the installed libhwloc library. 
Restrict this check to the distribution releases that do not ship hwloc-devel
package.
=> kernel/will-it-scale: Add support to download libhwloc

memory/libhugetlbfs.py
Fix make failures in test
Link 3a9d51c107e1 ("build: automake support")
--Before--
JOB ID     : 7a795476fc2f2ebb762692593821d6d30c1b81f2
JOB LOG    : /root/avocado-misc-tests/results/job-2025-03-13T18.34-7a79547/job.log
(1/1) libhugetlbfs.py:LibHugetlbfs.test;run-hugepages_requested-default-mount_dir-f2fd: STARTED
(1/1) libhugetlbfs.py:LibHugetlbfs.test;run-hugepages_requested-default-mount_dir-f2fd: ERROR:
Command 'make BUILDTYPE=NATIVEONLY' failed.\nstdout: b''\nstderr: b'make: *** No targets specified
and no makefile found.  Stop.\n'\nadditional_info: None (0.92 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-misc-tests/results/job-2025-03-13T18.34-7a79547/results.html
JOB TIME   : 13.14 s
--After--
JOB ID     : …
=> memory/libhugetlbfs.py: Handle make failures

kernel/kselftest.py, kernel/kselftest.py.data/bpf.yaml
=> [v2] Enhancing kselftest to support BPF selftests

io/disk/bonnie.py, io/disk/dbench.py, io/disk/disk_info.py, io/disk/fs_mark.py, io/disk/iozone.py, io/disk/ltp_fsstress.py, io/disk/tiobench.py
The btrfs-tools package has been deprecated and
replaced by btrfs-progs
=> Update btrfs package name in ubuntu

kernel/kselftest.py
Move the cancellation check for pmu/event_code_tests to the test execution block to ensure it correctly verifies the existence of the required directory and avoids early cancellation.
```
JOB ID     : 4f1f1f0d6bee4ef33117ad5ff1cd8b3b5fe8825f
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2025-02-26T14.03-4f1f1f0/job.log
(1/6) kselftest.py:kselftest.test;run-component-pmu/ebb-run_type-distro-77ee: STARTED
(1/6) kselftest.py:kselftest.test;run-component-pmu/ebb-run_type-distro-77ee:  PASS (128.73 s)
(2/6) kselftest.py:kselftest.test;run-component-pmu/event_code-run_type-distro-109d: STARTED
(2/6) kselftest.py:kselftest.test;run-component-pmu/event_code-run_type-distro-109d:  PASS (0.97 s)
(3/6) …
```
=> kernel/kselftest.py: fix cancellation check for pmu event_code_tests

io/iommu/iommu_tests.py.data/README.txt, io/iommu/iommu_tests.py.data/iommu_tests.yaml
Add the dmesg_grep key to iommu_tests.yaml to filter logs specific to IOMMU. The test will fail if any warnings or error messages related to IOMMU are found.
Test Run logs:
==Before==
Without 'dmesg_grep' key in the YAML file:
JOB ID     : 861808368cf52c4c4e7bd143f4960fd1bc28423f
JOB LOG    : /home/amd/iommu_test/tests/results/job-2025-03-25T08.25-8618083/job.log
(1/6) avocado-misc-tests/io/iommu/iommu_tests.py:IommuTest.test_unbind_bind;run-81a2: STARTED
(1/6) avocado-misc-tests/io/iommu/iommu_tests.py:IommuTest.test_unbind_bind;run-81a2: FAIL: Running test logged warn,err,alert,crit logs in dmesg. Please refer whiteboard of the test result (5.54 s)
(2/6) avocado-misc-tests/io/iommu/iommu_tests.py:IommuTest.test_unbind_changedomain_bind;run-81a2: STARTED
(2/6) …
=> Add dmesg_grep key to iommu_tests.yaml

io/disk/bonnie.py, io/disk/dbench.py, io/disk/disk_info.py, io/disk/disktest.py, io/disk/fiotest.py, io/disk/fs_mark.py, io/disk/iozone.py, io/disk/ltp_fs.py, io/disk/ltp_fsstress.py, io/disk/lvsetup.py, io/disk/parallel_dd.py, io/disk/tiobench.py, kernel/kselftest.py
Refactor distro detection to avoid redundant calls
Store distro detection result in detected_distro
instead of calling distro.detect() multiple times
Fix distro version detection
Update distro version detection as per update in
avocado utils change
https://github.com/avocado-framework/avocado/commit/55d1cd3a143d3a9a5667458da1e3014a7bc46939
Signed-off-by: Ayush Jain [Ayush.jain3@amd.com](mailto:Ayush.jain3@amd.com)
=> Refactor distro and its version detection

io/net/ethtool_test.py, io/net/multicast.py, io/net/network_test.py, io/net/tcpdump.py
restore_slave_cfg_file is failing incase of hbond
as slave_cfg_file is not being created and saved for hbond tests. Only the bond interface file is saved during the setUp
=> remove restore_slave_cfg_file for hbond tests

io/net/virt-net/network_virtualization.py
The correct way to access the logger is to use
self.log.debug or .info or .warning etc instead
of just self.log which fails with below error
self.log("failed to enable debug mode")
TypeError: 'Logger' object is not callable
=> vnic: replace self.log with proper self.log.debug

cpu/pvr.py
pvr value is never part of device tree (verified with Power8/9/10/11). Removing the un-necessary test
=> pvr.py: Remove un-necessary test

security/kernel-lockdown-tests.py
Enable debugfs on SLES and fix the filename
=> kernel-lockdown-tests.py: Enable debugfs test on SLES

security/ima-modsig-tests.py
Modify testcase:
test_ima_keyring_integrity
Add new testcases:
test_ima_signing_key
test_builtin_trusted_keys
test_ima_policy_with_secure_boot_enabled
test_ima_keyring_integrity
=> ima-modsig-tests.py: Add new testcases

cpu/lockstorm_benchmark.py
Handle insmod failure case when secure boot enabled
=> lockstorm_benchmark.py: handle insmod failure case

perf/perf_sdt_probe.py
This patch adds logic to test all the SDT events present and later removes them. 
Also increase the sleep time to avoid failure in cases where perf list is not updated after adding probe.
```
JOB ID     : 4dc31fdc2089b8cad5dda2de1650e181251a571a
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2025-02-25T13.52-4dc31fd/job.log
(1/1) perf_sdt_probe.py:PerfSDT.test: STARTED
(1/1) perf_sdt_probe.py:PerfSDT.test: PASS (247.02 s)
```
[debug.log](https://github.com/user-attachments/files/18962884/debug.log)
=> perf/perf_sdt_probe: enhance test to run all sdt events

io/pci/pci_hotplug.py
Introducing the generic check to see if the slot directory is present to perform add and remove operation
Since for SRIOV VF Ethernet and ROCE ports there will be no slot directory available and hence pci hotplug cannot be done
=> Checking if the pci slot obtained is present or not

cpu/dwh.py
LOG:
` (1/1) /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/dwh.py:Dwh.test:  ERROR: cannot access local variable 'cmd' where it is not associated with a value (0.07 s)
=> fixing script in SLES as cmd variable not defined

perf/perf_fuzzer.py
Fix perf fuzzer test false pass by checking the command exit status.
```
avocado run perf_fuzzer.py
Fetching asset from perf_fuzzer.py:Perffuzzer.test
JOB ID     : 7360348089cbc0d4a1b69c8152307392bf09e99c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2025-06-18T13.12-7360348/job.log
(1/1) perf_fuzzer.py:Perffuzzer.test: STARTED
(1/1) perf_fuzzer.py:Perffuzzer.test: FAIL: perf fuzzer failed with exit code 1 (33.36 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2025-06-18T13.12-7360348/results.html
JOB TIME   : 59.73 s
```
[debug.log](https://github.com/user-attachments/files/20791273/debug.log)
=> perf_fuzzer: Fix false pass by properly checking command exit status

.github/workflows/xfstests.yaml
Github Action fix as upload-artifact: v3 is deprecated
=> fixing github action

fs/xfstests.py, fs/xfstests.py.data/btrfs/4k.yaml, fs/xfstests.py.data/btrfs/4k_adv.yaml, fs/xfstests.py.data/btrfs/4k_adv_upstream.yaml, fs/xfstests.py.data/btrfs/4k_auto.yaml, fs/xfstests.py.data/btrfs/4k_upstream.yaml, fs/xfstests.py.data/btrfs/ci.yaml, fs/xfstests.py.data/ext4/dax.yaml, fs/xfstests.py.data/xfs/dax.yaml, fs/xfstests.py.data/xfstests_disk.yaml
btrfs: drop explicit -n option to use default nodesize
Recent versions of Btrfs default to a 16K nodesize when using a 4K block size. This commit updates the 4k.yaml configs to remove the '-n' option from mkfs_opt, allowing Btrfs to use its default nodesize logic.
dax: change test group from quick to auto
Update the dax configs to run tests from the 'auto' group instead of 'quick'. The 'auto' group includes a broader set of relevant tests and provides better coverage.
xfstest: remove xmlto and asciidoc package
Remove xmlto and asciidoc packages from prerequisite as they are used for creating documentation and slow down the tests.
=> Improve xfstest

ras/hwinfo.py, ras/ras_ppcutils.py
Enhanced regular expression to capture NVME disk along with SCSI/SATA.
Before this patch:
(05/21) ras_ppcutils.py:RASToolsPpcutils.test_lsprop: STARTED
(05/21) ras_ppcutils.py:RASToolsPpcutils.test_lsprop: CANCEL: Couldn't get Disk name. (0.09 s)
(01/12) hwinfo.py:Hwinfo.test_list_options: STARTED
(01/12) hwinfo.py:Hwinfo.test_list_options: CANCEL: Couldn't get Disk name. (0.06 s)
.......
After this patch:
(05/21) ras_ppcutils.py:RASToolsPpcutils.test_lsprop: STARTED
(05/21) ras_ppcutils.py:RASToolsPpcutils.test_lsprop: PASS (96.20 s)
(01/12) hwinfo.py:Hwinfo.test_list_options: STARTED
(01/12) hwinfo.py:Hwinfo.test_list_options: PASS (7.08 s)
=> Added NVME disk support along with SCSI/SATA.

perf/hackbench.py, perf/hackbench.py.data/hackbench.yaml
Replace unmaintained hackbench source with LTP version and improve logging and analysis
Previously, the hackbench test used an outdated and now-inaccessible source: http://people.redhat.com/~mingo/cfs-scheduler/tools/hackbench.c (also referenced in: https://github.com/autotest/autotest-client-tests/tree/master/hackbench)
This commit updates the setup to use the actively maintained hackbench version from the Linux Test Project (LTP). Along with this, the codebase is improved to:
- Store benchmark logs under a dedicated test directory with structured subdirectories
- Enable easier parsing and analysis of results for performance evaluation
- Introduce a smart log analysis module to extract min, max, and average metrics
These changes make the hackbench test setup more reliable, maintainable, …
=> Modified the existing hackbench test case with new LTP repository.

perf/perf_extended_regs.py
This test identifies available registers based on platform with perf record -I?,
runs perf record with all and selected registers and validates registers via perf report -D output.
```
avocado run perf_extended_regs.py
JOB ID     : 1f9ff64d4eab6d9ef0c3be6145fbd7f41425e691
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2025-07-09T16.40-1f9ff64/job.log
(1/1) perf_extended_regs.py:PerfExtendedRegs.test_extended_registers: STARTED
(1/1) perf_extended_regs.py:PerfExtendedRegs.test_extended_registers: PASS (4.92 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2025-07-09T16.40-1f9ff64/results.html
JOB TIME   : 28.51 s
```
[debug.log](https://github.com/user-attachments/files/21141618/debug.log)
=> perf: add test for verifying extended register sampling

io/disk/ssd/nvmetest.py, io/disk/ssd/nvmetest.py.data/nvmetest_splitter.yaml
Added changes/support as follows
1. Device name can be provided as follows in yaml file a. subsystem name b. device nqn name
2. Added paramter in yaml to enable shared namespace functionality, Default value is set to False as it should not impact exisitng functionality.
3. Added function calls for shared namespace creation. Conclusion: Changes works for sing controller nvme dis and multi controller nvme disk
=> Added support for taking device name as susbys or nqn of nvme disk and added support for shared namespaces.

io/pci/EEH.py, io/pci/EEH.py.data/EEH.yaml
The patch addresses
1) check if the test is on network device
2) if network device , then yaml is populated with the interface details 3) start network traffic (flood ping) which is important for EEH test to succeed 4) stop the network traffic after error injection
=> start network traffic before EEH test

io/disk/ssd/nvmetest.py
list-ns command has first line as string and shows below error ValueError: invalid literal for int() with base 10: 'Namespace'
This code change will make sure the string line is ommited
=> nvmetest: ns_list() shows string value error

trace/dawr.py, trace/dawr.py.data/Makefile, trace/dawr.py.data/boundary_check.c
- Introduced a new DAWR test case 'Boundary_check.c' to validate unalignedcmemory access around a 512-byte boundary.
- Integrated the test into the existing Avocado test framework in dawr.py using the new function 'test_boundary_check'.
- Updated the build setup to include Boundary_check.c and Makefile for compilation during runtime.
- Ensures accurate detection of watchpoint triggers at misaligned addresses.
This helps validate hardware watchpoint behavior across unaligned memory windows for DAWR on Power10/P11 platforms.
=> Add DAWR boundary check test case for unaligned 512-byte window

io/disk/ssd/nvme_sedtest.py, io/disk/ssd/nvme_sedtest.py.data/README.txt, io/disk/ssd/nvme_sedtest.py.data/nvme_sedtest.yaml
Added following tests as part of nvme SED validation
1. SED Initialization.
2. SED lock and unlock with keyring.
3. SED revert.
4. SED destructive revert.
5. teardown added to bring drive to same state as before.
=> NVME SED feature tests[depends on avocado/pull/6196]

memory/integrity.py.data/mem_integrity_test.c
With latest releases mem_integrity_test.c file compilation is failing since NULL is passed to optional flags.
=> Modified mbind call to fix compilation error

ras/live_patching.py, ras/live_patching.py.data/Makefile, ras/live_patching.py.data/libc_livepatch1.c, ras/live_patching.py.data/libc_livepatch1.dsc, ras/live_patching.py.data/libc_livepatch_2func.c, ras/live_patching.py.data/libc_livepatch_2func.dsc, ras/live_patching.py.data/test.c, ras/live_patching.py.data/test_2func.c
[logs.txt](https://github.com/user-attachments/files/21433283/logs.txt)
The test case ensures that the live patching feature works as expected by applying and reverting a patch, and verifying the presence of "glibc-livepatch" messages in the output.
=> Test case to verify live patching feature.

generic/ipistorm.py
Previously, cpu.get_arch was incorrectly called, resulting in TypeError. This commit fixes the same and also, searches the correct keyword for cpu arch.
=> Fix: Rectifying arch detection logic

generic/stress-ng.py.data/stress_ng_interrupt.yaml
Stress_ng_interrupt_tc config in stress-ng.yaml to run only interrupt stressors.
Added a new Stress_ng_interrupt_tc config in stress-ng.yaml to run only interrupt stressors.
Purpose: isolate and validate interrupt handling validation without running full stress-ng tests.
Verified locally using avocado run generic/stress-ng.py with the updated stress_ng_interrupt.yaml file
=> Add stress-ng interrupt test case yaml

io/net/ethtool_test.py
We are redirecting the stderr and stdout contents to a file
This helps in resolving EEPROM DUMP option taking less time to complete
=> Fixing the ethtool eeprom dump issue

cpu/stressng_cpu.py, cpu/stressng_cpu.py.data/stressng_cpu.yaml
This patch introduces functionality to stress individual Linux scheduling classes using stress-ng. Each class is exercised independently to evaluate scheduler behavior and system responsiveness under different policies.
Supported scheduling classes:
1. SCHED_OTHER
2. SCHED_IDLE
3. SCHED_BATCH
4. SCHED_FIFO
5. SCHED_RR
This enhancement enables better coverage of scheduler-related test scenarios as part of system stress and performance validation
=> Add support to stress all scheduling classes using stress-ng

io/disk/ssd/nvme_sedtest.py
All the nvme sed utils definitions defined ealier in avocado framework are reverted due to pexpect dependency.
All those utils definitions are added in the same tests file here
No changes to defined functionality.
=> nvme sed utils definitions added to nvme tests
