- io/driver/driver_bind_test.py
- io/driver/driver_bind_test.py.data/README.txt
- io/driver/driver_bind_test.py.data/driver_bind_test.yaml
> Adding Driver Bind test [v2]

- cpu/sensors.py
Added sensors command test for avocado.
Signed-off-by: Harish <harisrir@linux.vnet.ibm.com>
> Adding sensors command Test

- .travis.yml
- Show a minimal commit message template in case of check error.
- Skip commit message check for merge commits.
> Travis commit message check improvements

- generic/oprofile.py
Added correct git link.
Addressed failure during grep operation.
Signed-off-by: Pooja <pooja@linux.vnet.ibm.com>
> Added Oprofile test which covers oprofile test scenarios-v5

- io/disk/softwareraid.py
- io/disk/softwareraid.py.data/Readme
- io/disk/softwareraid.py.data/softwareraid.yaml
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/458707/job.txt)
Added the check in the script for number of drives.
> Software Raid Test

- io/net/net_data.py
- io/net/net_data.py.data/net_data.yaml
Test Network Data
Test Network Statistics
Test LRO
Test GRO
Test Big Ping
Test Network Interface
> Test Network Data

- memory/eatmemory.py
- memory/eatmemory.py.data/eatmemory.yaml
The Test fetches the master zip and extracts it and runs the test
Removed all git related as per the review comments.
Final output is validated for making the test pass.
> Added Eatmemory test.

- memory/eatmemory.py
- memory/eatmemory.py.data/eatmemory.yaml
Styles changes to make eatmemory test easier to read.
Signed-off-by: Amador Pahim <apahim@redhat.com>
> eatmemory: cleanup

- fs/xfstests.py
- fs/xfstests.py.data/README
- fs/xfstests.py.data/group
- fs/xfstests.py.data/xfstests.yaml
v3: #45 
fixed: while test runm not geting valid test releated
to file system in xfs test suite
: remove unused log
> Added Xfs test to avocado[V4]

- io/disk/ssd/blkdiscard.py
Varibale "size" type is changed from str to int
as I have to use it for arthimatic operations
> Changed type of variable "size"

- kernel/rmaptest.py
- kernel/rmaptest.py.data/rmaptest.yaml
Rmaptest create random VMAs mapped tasks
> Added Rmaptest in Avocado

- fs/filebench.py
- fs/filebench.py.data/README
- fs/filebench.py.data/filebench.yaml
FileBench Test run File System Workload
> Added filebench Test in Avocado

- cpu/pmqa.py
- cpu/pmqa.py.data/pmqa.yaml
v1 #59 
v2 #63 
removed unused varaible
make logic more clear
> Added Pmqa Testsuite test in avocado[V3]

- generic/rcutorture.py
Fixed code issues and reused linux_modules to optimise code
> rcutorture: optimise code using avocado modules

- perf/unixbench.py
- perf/unixbench.py.data/Makefile.patch
- perf/unixbench.py.data/README
- perf/unixbench.py.data/unixbench.yaml
The Test git clone the test suite and runs the tests.
Then, output is parsed for error and Benchmarking score is Displayed
Removed unwanted args and modified README.
> Added unixbench test 

- memory/stutter.py
- memory/stutter.py.data/stutter.yaml
stutter testsuite which run memory Test(memhog)
> Added stutter testsuite Test[V3]

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/ib_pingpong.py.data/README.txt
- io/net/infiniband/ib_pingpong.py.data/ib_pingpong.yaml
Ping Pong Tests
using four tools ibv_ud_pingpong,ibv_uc_pingpong,ibv_rc_pingpong,ibv_srq_pingpong
> Ping Pong Tests

- io/net/infiniband/ucmatose.py
- io/net/infiniband/ucmatose.py.data/README.txt
- io/net/infiniband/ucmatose.py.data/ucmatose.yaml
ucmatose is RDMA CM connection and simple ping-pong test.
> Adding ucmatose test [v2]

- generic/connectathon.py
- generic/service_check.py
- io/net/infiniband/ib_pingpong.py
- io/net/net_data.py
- kernel/tlbflush.py
- perf/lmbench.py
fix Undefined variable (pylint issue) in repo
> Fix pylint issue in avocado-misc-tests

- io/net/infiniband/ib_latency_perf.py
- io/net/infiniband/ib_latency_perf.py.data/README.txt
- io/net/infiniband/ib_latency_perf.py.data/ib_latency_perf.yaml
InfiniBand Latency Performance tests
using four tools ib_send_lat,ib_write_lat,ib_read_lat,ib_atomic_lat
> InfiniBand Latency Performance tests

- io/net/infiniband/ib_bw_perf.py
- io/net/infiniband/ib_bw_perf.py.data/README.txt
- io/net/infiniband/ib_bw_perf.py.data/ib_bw_perf.yaml
Infiniband Bandwidth Performance Tests
using four tools ib_send_bw,ib_write_bw,ib_read_bw,ib_atomic_bw
> Infiniband Bandwidth Performance Tests

- io/net/infiniband/rping.py
- io/net/infiniband/rping.py.data/README.txt
- io/net/infiniband/rping.py.data/rping.yaml
rping is RDMA CM connection and RDMA ping-pong test.
> Adding rping test

- io/net/infiniband/udaddy.py
- io/net/infiniband/udaddy.py.data/README.txt
- io/net/infiniband/udaddy.py.data/udaddy.yaml
udaddy is RDMA CM datagram setup and simple ping-pong test.
> Adding udaddy test

- io/net/infiniband/ping6.py
- io/net/infiniband/ping6.py.data/README.txt
- io/net/infiniband/ping6.py.data/ping6.yaml
ping6 is ICMP ECHO_REQUEST test.
> Adding ping6 test

- io/net/infiniband/mckey.py
- io/net/infiniband/mckey.py.data/README.txt
- io/net/infiniband/mckey.py.data/mckey.yaml
mckey is an RDMA CM multicast setup and simple data transfer test.
> Adding mckey test

- memory/libhugetlbfs.py
- memory/libhugetlbfs.py.data/falloc.patch
```
*added patch file as well logic for RHEL and fedora 24 which
enable test suite able to run in RHEL/Fedora
*logic for catch 32 bit 64 bit test failure
```
> Enhance libhugetest v2

- perf/perftool.py
Added test which run perftool-testsuite and notify
user when test fail
> Added perftool-testsuite test[v3]

- io/net/scp_ssh.py
- io/net/scp_ssh.py.data/README.txt
- io/net/scp_ssh.py.data/scp_ssh.yaml
Test Scp and Ssh and ping
test scp with copy a 1GB file into peer and test ping with 5ICMP packets
Signed-off-by: prudhvi mprudhvi@linux.vnet.ibm.com
> Test Scp and Ssh and ping

- perf/tbench.py
- perf/tbench.py.data/tbench.yaml
Added tbench test that produces only the TCP and process load.
Signed-off-by: poojabs <pooja@oc2013156016.ibm.com>
> Added tbench test - v3

- io/net/tcpdump.py
- io/net/tcpdump.py.data/README.txt
- io/net/tcpdump.py.data/tcpdump.yaml
Runs tcpdump on given interface for given number of packets.
> Adding tcpdump test

- io/net/multicast.py
- io/net/multicast.py.data/README.txt
- io/net/multicast.py.data/multicast.yaml
Test receive multicast
using ping tool
> Test receive multicast

- toolchain/glibc.py
- toolchain/glibc.py.data/glibc.yaml
The test fetches the latest glibc zip and execute the tests
in it.
> Added glibc_v3

- toolchain/gsl.py
- toolchain/gsl.py.data/version.yaml
Script downloads gsl tar ball from ftp://ftp.gnu.org/gnu/gsl/ and runs self test.
> Test to run gsl self test - v3

- io/net/Network_config.py
- io/net/Network_config.py.data/Network_config.yaml
- io/net/Network_config.py.data/README.txt
Test Network Configuration Details
configuration details like speed, driver,transmission mode, link state
> Test Network Configuration Details

- toolchain/supportconfig.py
- toolchain/supportconfig.py.data/supportconfig.yaml
The supportconfig script gathers system troubleshooting information on
SUSE Linux Enterprise Server systems.It captures the current system
environment and generates a tar-archive
Signed-off-by: Basheer K<basheer@linux.vnet.ibm.com>
Tested-by: Basheer K<basheer@linux.vnet.ibm.com>
> Supportconfig Testcase

- io/disk/Avago_storage_adapter/avago3008.py
- io/disk/Avago_storage_adapter/avago3008.py.data/Readme
- io/disk/Avago_storage_adapter/avago3008.py.data/avago3008.yaml
This script will run few basic test on the adapter
> Script to run sanity test on Avago3008 adapter

- io/disk/arcconf/arcconf_raid_oper.py
- io/disk/arcconf/arcconf_raid_oper.py.data/Readme
- io/disk/arcconf/arcconf_raid_oper.py.data/arcconf_raid_oper.yaml
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/609702/job.txt)
[test_results.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/609705/test_results.txt)
1. code optimized the filesystem functionality
2. included teardown function
> arcconf configuration utility - v3

- io/disk/arcconf/arcconf_raid_oper.py
updated the script to include the conditions for raid50 and raid60
> arcconf with raid50 and raid60 - v1

- io/disk/Avago_storage_adapter/avago3008.py
- io/disk/Avago_storage_adapter/avago3008.py.data/Readme
- io/disk/Avago_storage_adapter/avago3008.py.data/avago3008.yaml
Added test cases like CC,BGI,Rebuild,logir etc
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/626900/job.txt)
> Complete LSI-3008 test script

- io/disk/multipath_test.py
Tests Flushing, Blacklisting, patch_checker policy.
Signed-off-by: Narasimhan V sim@linux.vnet.ibm.com
> Adding Multipath test [v2]

- io/disk/arcconf/arcconf_migration.py
- io/disk/arcconf/arcconf_migration.py.data/Readme
- io/disk/arcconf/arcconf_migration.py.data/arcconf_migration.py.yaml
arcconf_migration.py tests Migration and rebuild specific tests.
includes the suggestion from v2 review.
> arcconf Migration and rebuild specific tests - v3

- generic/lshw.py
Description:
lshw is a small tool to provide detailed informaton on the hardware
configuration of the machine. It can report exact memory
configuration, firmware version, mainboard configuration, CPU version
and speed, cache configuration, bus speed, etc. on DMI-capable x86
systems and on some PowerPC machines (PowerMac G4 is known to work).
Signed-off-by: Ramya BS ramya@linux.vnet.ibm.com
Tested-by : Ramya BS ramya@linux.vnet.ibm.com
> Test case for lshw tool (Hardware lister)

- io/disk/parallel_dd.py
- io/disk/parallel_dd.py.data/README
- io/disk/parallel_dd.py.data/parallel_dd.yaml
Added default values in yaml file.
Signed-off-by: poojabs <pooja@oc2013156016.ibm.com>
> Adding parallel_dd test [V6]

- io/disk/Avago_storage_adapter/avago9361_vd.py
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
This script Creates 16VD for each raid array, and 64VD for raid0
and runs CC operations
> Script creates multiple VD and max config, also runs CC operations_v3

- io/net/bonding.py
- io/net/bonding.py.data/README.txt
- io/net/bonding.py.data/bonding.yaml
Test Interface Bonding(V5)
check all seven interface bonding modes for any number of interfaces
> Test Interface Bonding(V5)

- io/disk/Avago_storage_adapter/avago9361_vd.py
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/Readme
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
Added test cases like JBOD, changing VD policy, disk
online/offline
> Enhanced the script to run, some more functionality_V1

- perf/bonnie.py
- perf/bonnie.py.data/Readme.txt
- perf/bonnie.py.data/bonnie.yaml
Tool creates and deletes sequential and random files in a dir
> Fixing bonnie test

- io/disk/Avago_storage_adapter/avago9361_vd.py
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/Readme
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
Added following test case:
Rebuild
Copyback
create and delete GHS/DHS
> Enhancing avago9361_vd.py script

- cpupower/cpupower.py
The test case does the following:
1)To get the initial frequency and governor set on system
2)Get the list of governors available on the system
3)Get the cur,min,max freequency on the system
4)Validate Performance,Powersave,Ondemand Governor
5)Set the final values which was taken initially.
> Added cpupower test cases.

- io/disk/ltp_fs.py
- io/disk/ltp_fs.py.data/README.txt
- io/disk/ltp_fs.py.data/ltp_fs.yaml
This test uses LTP to run fs tests
> Test to run filesystem tests on a user specified disk

- kernel/kselftest.py
v1: #233 
v2:
1-removed variable name as udeps,rdeps,sdeps,cdeps 
extend base packages list (deps) required distro packages
2- use variable name count instead of self.count as boolean variable 
rectified  message string
> Fix kernel selftest [v2]

- io/net/net_data.py
- io/net/scp_ssh.py
Fixed the scripts for installing openssh-client package
for ubuntu correctly.
And some pylint fixes.
> Fixing openssh package for Ubuntu

- io/disk/Avago_storage_adapter/avago9361_vd.py
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
Added proper check to skip the test varients that are not applicable,
Also chenaged the variable name in yaml file, now its consistant accross
the script
> Fix for the Bug_241

- io/net/multicast.py
> Patch for Multicast test

- io/net/net_data.py
BigPing and LRO code fixed to work on distros
> Patch to fix net_data script

- toolchain/libvecpf.py
This test fetches latest library, compiles and runs tests in it.
> Added libvecpf library test [v2]

- fs/fsx.py
This test uses system calls like write, read, mmap
etc. to exercise file system
> Added fsx test for exercising file system [v2]

- io/pci/pci_info_lsvpd.py
- io/pci/pci_info_lsvpd.py.data/Readme.txt
check the lsvpd pci info with sys pci inf lsvpd information
> verify lsvpd information

- io/net/infiniband/ib_bw_perf.py
fixes the below issues:
1. server data from /tmp/ib_log is now printed.
2. Disabled firewall before the test start, which is an prerequisite.
[test_run.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/766009/test_run.txt)
[job.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/766010/job.txt)
> ib_bw_perf - v1

- io/net/infiniband/ib_latency_perf.py
- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/ip_over_ib.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rping.py.data/rping.yaml
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
Made following changes:
1. disable firewall for all the scripts.
2. fix the server data which wasn't reported
3. fix server and client data for few tests
> infiniband -v1

- io/disk/Avago_storage_adapter/avago9361_vd.py
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
A parameter in yaml file tool_location is added, so now the user
can give the location of the tool and can run the script from any
location
> Added a parameter in yaml file for tool location

- io/net/infiniband/dapl.sh
- io/net/infiniband/dapl.sh.data/README.txt
- io/net/infiniband/dapl.sh.data/dapl.yaml
Moved the inputs in dapl test from config file to yaml file.
Also some minor debug message fixes.
> Multiplexer changes in Dapl Test

- generic/openblas.py
OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version.
Signed-off-by: poojabs <pooja@oc2013156016.ibm.com>
> Added test that runs openblas tests_v2

- io/disk/lvsetup.py
Fix to handle xfs and btrfs filesystems
> Patch to fix lvsetup.py script

- perf/bonnie.py
Bonnie test expects the username in args.
So modified the args in the test.
> Added username in args of bonnie test

- toolchain/valgrind.py
Valgrind is an instrumentation framework for building dynamic analysis tools. Valgrind tools that can
automatically detect many memory management and threading bugs
> Added valgrind test case with various self tests [v2]

- io/disk/ltp_fs.py
Replaced the direct command execution usage for mount,unmount and for
creating file system in ltp_fs.py by using Partition utility.
> Replaced un/mounting and file system creation with Partition utility

- memory/transparent_hugepages_defrag.py
workload and then turns on the defrag.And finally, checks whether
the defrag has occured.
> The test turns off the defrag and fragments the memory using dd

- io/disk/tiobench.py
*Script was disk depend
* Now it is independent of disk and run on give directory or source
directory
* Added tearDown function too
> Enhanced tiobench.py, made it to run without any external disk pass

- io/disk/ltp_fs.py
if some one does not have external disk to pass it and wants to run
ltp, then this script fails, due to disk value as None.
So edited it and Now it will run on given/source directory without
mounting any disk on it and one can with external disk too..
> Edited ltp_fs.py, enhanced it to run when no external disk is given

- cpu/sensors.py
Without setup test errors out in case of skip. Added setUp to address it.
> Added setUp to sensors test

- io/pci/pci_info_lsvpd.py
vpdinfo test checks without updating vpd.
Have fixed it.
> Added vpdupdate to vpdinfo test

- generic/interbench.py
Tar is not accessible. Interbench tar is updated.
> Update tar for interbench

- memory/libhugetlbfs.py
And also changed self.error to self.skip for
package dependencies.
> Added pthread deps to install

- memory/transparent_hugepages.py
- memory/transparent_hugepages_defrag.py
- memory/transparent_hugepages_swapping.py
Did proper cleanup after execution of tests
> Removed the thp directory

- cpu/cpupower.py
Provided the fix to install packages and also incorporated the script changes.
cpupower is the collection of tools to monitor the idle state, frequency information and set it.
This test sets the frequency and governor and validate it.
Fix will help to install cpupower utility on all the distros.
> Fix to install cpupower utility

- generic/lshw.py
Description:
lshw is a small tool to provide detailed informaton on the hardware
configuration of the machine.
> Fixed few failures in lshw - v3

- generic/ras.py
Modified code to skip tools which are not supported on LPAR and KVM guest
> RAS tools test - v3

- io/disk/htx_block_devices.py
- io/disk/htx_block_devices.py.data/Readme.txt
- io/disk/htx_block_devices.py.data/htx_block_devices.yaml
Script run the Stress on block devices for given amount of time
using the HTX tool.
> Script to run the HTX stress on block devices [v3]

- cpu/ebizzy.py
- fuzz/fsfuzzer.py
- generic/interbench.py
- io/disk/iozone.py
- kernel/posixtest.py
- kernel/tlbflush.py
- memory/libhugetlbfs.py
- perf/blogbench.py
- perf/lmbench.py
- perf/unixbench.py
few packages needs to be checked and installed like patch
make, with out this packages skip the tests.
Based on https://github.com/avocado-framework-tests/avocado-misc-tests/pull/344
> Added deps list to include must install packages [v2]

- cpu/sensors.py
1-remove not needed check
a- remove ppc64 as distro check BML is always ppc64le
b- remove powerkvm as distro check
2-Used avocado utility for config check
Signed-off-by: Praveen K Pandey praveen@linux.vnet.ibm.com
> Sensors fix1

- io/net/net_data.py
Patch fixes testinterface execution for interface check based
on timeout
> patch for net-data script

- io/net/ethtool/ethtool_tests.sh
Checks for interface coming up based on timeout
> Patch to fix ethtool script

- memory/libhugetlbfs.py
Git package added twice in packages list so it is removed
> Removed unwanted git in packages list

- io/disk/htx_block_devices.py
- io/disk/htx_block_devices.py.data/Readme.txt
- io/disk/htx_block_devices.py.data/htx_block_devices.yaml
Enhanced HTX test to change SMT values also while running HTX.
> Enhanced htx test to change SMT also

- memory/stress-ng.py
> Fixed stress-ng failure - v2.

- cpu/linsched.py
- cpu/linsched.py.data/fix.patch
- cpu/linsched.py.data/linsched.yaml
added linux-scheduler-testing as automative way test linux-scheduler
> Linux scheduler testsuite[V2]

- io/net/Network_config.py
Fixes mtu match scenario for the network interface
> Patch to fix Network_config script

- generic/sosreport.py
- generic/sosreport.py.data/options.yaml
sosreport generates an archive of configuration and diagnostic information from the running system.
> Added test for sosreport - v4

- generic/ras_extended.py
This test tests various options of RAS tools.
> Added test for RAS tools -v3

- io/net/multicast.py
- io/net/net_data.py
- io/net/netperf_test.py
- io/net/scp_ssh.py
patch fixes ssh package conflict for required tests
under io/net directory
> Patch to fix ssh package conflict for SUSE distro

- generic/lshw.py
Added test for -disable, -enable, -quiet, -numeric and -notime options and validating product id and serial number.
> Added few more tests for lshw.

- toolchain/binutils.py
- toolchain/binutils.py.data/version.yaml
1. Fixed required packages check for binutils
2. Support to run specific version of binutils
> binutils package fix and added binutils version support

- io/disk/ssd/nvmetest.py
nvme-cli is available in major distros now.
So, using that package for tests makes sense going forward.
> Using nvme-cli package available in distro repo

- io/net/multiport_stress.py
This patch takes care of iputils package for distros
> Patch for multiport stress test to handle iputils package issue

- fs/xfstests.py
Added support to run xfstests on Suse distro
> Support to run tests on Suse

- io/pci/PowerVMEEH.py.data/PowerVMEEH.yaml
- io/pci/PowerVMEEH.py.data/Readme
Changed the directory name from PowerVMEEH.data to PowerVMEEH.py.data
> Changed the name yaml file directory to the correct name

- io/disk/Avago_storage_adapter/avago9361.py
Added extensive set of adapter functinality, for which
values can be set=<ON|OFF>
> Enhanced avago9361.py script

- toolchain/systemtap.py
- toolchain/systemtap.py.data/systemtap.yaml
Addressed review comments.
Signed-off-by: Pooja <pooja@linux.vnet.ibm.com>
> Added systemtap testsuite_v4

- io/net/multicast.py
- io/net/net_data.py
- io/net/scp_ssh.py
This patch includes dependency check for iputils package in required
network scripts for Linux Distros
> Patch to have iputils dependency for Linux Distro

- io/net/infiniband/ib_bw_perf.py
- io/net/infiniband/ib_latency_perf.py
- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/ip_over_ib.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
Handled dependencies for ssh and iputils packages for different
distros for all infiniband tests.
> Handling package dependencies in infiniband tests

- io/pci/pci_hotplug.py
Checking if the machine is booted with PowerVM hyp, if yes
loading the rpadlpar_io rpaphp modules, if not loaded already.
> Loading necessary modules to run this script on PowerVM

- io/disk/softwareraid.py.data/Readme
This Readme Patch update is to define the minimum count of block
device requirement to test software RAID level 1.
> Update the softwareraid Readme file 

- fuzz/fsfuzzer.py
With out these packages test will not continue
so added in the list.
> fuzz/fsfuzzer : Add dependency packages

- fs/xfstests.py
Added package for creating brtfs file system in Ubuntu
> Add package for btrfs file system in Ubuntu

- io/disk/disk_info.py
- io/disk/disk_info.py.data/Readme.txt
- io/disk/disk_info.py.data/disk_info.yaml
This tests different storage block device operations against different
block device list tools. and verifies certain parameters like
disk name, size, UUID, mount point, filesystem type and IO sector
sizes(Logical/phyiscal block size, minimum and optimal block size)
> Disk Info Test

- io/net/bonding.py
- io/net/bonding.py.data/README.txt
- io/net/bonding.py.data/bonding.yaml
The enhancement contains an option to create a Bonding Peer
interface if needed and failure check added when all interfaces
are down
> Enhancement to Bonding script

- io/net/net_data.py
BigPing test would fail if it fails for one value. Fixed that
with storing the failures for last.
Also, original mtu value for interface was not retained. Fixed
that as well
> Multiple fixes for BigPing Test

- io/disk/Avago_storage_adapter/avago3008.py
- io/disk/Avago_storage_adapter/avago3008.py.data/Readme
- io/disk/Avago_storage_adapter/avago3008.py.data/avago3008.yaml
With this patch, user can just pass the tool location in yaml
file, instead of making it mandatory to place the script in a
particular folder
> Improvements to avago3008.py script

- io/net/net_data.py
Script includes a function that waits for the interface to be up
and then check for it's status using Ethtool and ip link
> Script to enhance testinterface function in net_data test

- README.rst
- fs/filebench.py
- fs/fsx.py
- fs/xfstests.py
This is a collection of tags to the filesystem tests, together with some formatting fixes for `README` and finally changes to `filebench` to make it run as a regular unprivileged user.
> Add tags to "fs" (filesystem) tests 

- io/genwqe/genwqetest.py
- io/genwqe/genwqetest.py.data/genwqetest.yaml
> Added GenWQE tests

- io/disk/ssd/nvmetest.py
- io/disk/ssd/nvmetest.py.data/nvmetest.yaml
* Added firmware upgrade test to nvme test.
* Added controller reset via sysfs test to nvme test.
> Added Firmware upgrade test to nvme test

- perf/aiostress.py
Added dependency packages to run on Suse
> Support for running aiostress on suse

- io/net/netperf_test.py
- io/net/netperf_test.py.data/README.txt
- io/net/netperf_test.py.data/netperf_test.yaml
Enhancement contains a variable to allow user to
choose the download location for netperf tool
> Patch to enhance netperf script

- io/net/bridge.py
- io/net/bridge.py.data/README.txt
- io/net/bridge.py.data/bridge.yaml
Test the ethernet bridge configuration in the linux kernel using brctl command
> Added bridge interface test

- io/disk/ssd/ezfiotest.py
> Fix typo in ezfio test

- io/disk/disk_info.py
Fixed the failure flow in disk_info test.
Fixed some error messages in disk_info test.
> Enhanced the error flow in disk_info test

- io/disk/ssd/nvme_cli_selftests.py
- io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
> Adding nvme-cli selftests

- io/net/bridge.py
- io/net/bridge.py.data/bridge.yaml
Changing yaml parameter to be uniform across tests
> Changing yaml parameter to be uniform across tests

- io/disk/disk_info.py
Added grub2-probe to disk_info test
> Added grub2-probe to disk_info test

- generic/stress-ng.py
The stressng package has old code, so always take source from git and
compile. increase time of test. and add more component support.
> stress-ng : improved stress-ng testcase to support multiple component

- io/pci/pci_hotplug.py
Earlier script used to fail for PowerNV as the slots listed in
PowerNV machine is different than in PowerVM, and its handeled now
properly.
Signed-off-by: root <root@ltc-tuleta4u-l.aus.stglabs.ibm.com>
> Enhanced the script to run for PowerNV systmes as well

- io/net/bonding.py
patch will replace all ifconfig related commands used
with ip commands and will also unload bonding module
while removing the bonding configuration in Host and
Peer machines
> Patch to enhance Bonding script

- io/net/scp_ssh.py
Flood ping is an option for the ping command
that will send new data as soon as it is
received
> Patch to include flood ping test to scp_ssh script

- perf/libunwind.py
- perf/libunwind.py.data/libunwind.yaml
Removed self.fail and used self.cancel.
Signed-off-by: Pooja <pooja@linux.vnet.ibm.com>
> Added test to run Libunwind tests_v1

- cpu/numactl.py
> Added numactl test

- memory/libhugetlbfs.py
Patch fixes syntax provided in the tests error message
> Fix libhugetlb error message

- cpu/ebizzy.py
- cpu/numactl.py
- fuzz/trinity.py
- generic/criu.py
- generic/gdb.py
- generic/interbench.py
- generic/stress-ng.py
- io/disk/dbench.py
- io/disk/fs_mark.py
- io/disk/iozone.py
- kernel/kselftest.py
- kernel/posixtest.py
- memory/eatmemory.py
- memory/memtester.py
- memory/stutter.py
- perf/compilebench.py
- perf/libunwind.py
- perf/lmbench.py
- perf/perf_events_test.py
- perf/perftool.py
- perf/rt_tests.py
- perf/stress.py
- perf/tbench.py
- perf/unixbench.py
- toolchain/binutils.py
- toolchain/gcc.py
- toolchain/gsl.py
- toolchain/libvecpf.py
- toolchain/valgrind.py
Properties are not supposed to be overwritten, but since some of them
were still not protected, we ended up abusing them. Now, with the recent
PR https://github.com/avocado-framework/avocado/pull/2129 they are about
to be protected and this commit fixes the tests before they break. No
actual changes in functionality though.
Signed-off-by: Amador Pahim <apahim@redhat.com>
> Don't overwrite properties

- io/net/netperf_test.py
- io/net/netperf_test.py.data/README.txt
- io/net/netperf_test.py.data/netperf_test.yaml
* Moved the tests as options to yaml file
* Updated the latest netperf download location
* Enhanced the way throughput is calculated
* Added yaml parameters for duration and iterations
> Enhancements to netperf test

- io/net/infiniband/ib_bw_perf.py
- io/net/infiniband/ib_bw_perf.py.data/README.txt
- io/net/infiniband/ib_bw_perf.py.data/ib_bw_perf.yaml
- io/net/infiniband/ib_latency_perf.py
- io/net/infiniband/ib_latency_perf.py.data/README.txt
- io/net/infiniband/ib_latency_perf.py.data/ib_latency_perf.yaml
* Removed the previous fastfail method, and now the tests report
failures after running all yaml parameters.
* Also enhanced some yaml parameters.
> Infiniband Bandwidth and Latency test enhancements

- io/net/multiport_stress.py
- io/net/multiport_stress.py.data/README.txt
This patch will run a flood ping test parallely on the
test interfaces
> Patch for enhancement of multiport test

- io/net/htx_nic_devices.py
- io/net/htx_nic_devices.py.data/README.txt
- io/net/htx_nic_devices.py.data/htx_nic_devices.yaml
This patch has a fix which takes care of pingum failure
for Infiniband interfaces
> Patch for htx_nic_devices.py script

- io/net/net_data.py
* The test used to error out if host or peer interface's mtu value
change fails.
* Also, when the peer interface is not connected, test would error
out.
Handled these 2 cases as test FAILures.
> Big ping fixes

- generic/nstress.py
- generic/nstress.py.data/config.yaml
Duration for each test can be specified in yaml file.
> Test to stress cpu and memory using nstress - v4

- io/net/infiniband/ib_bw_perf.py.data/ib_bw_perf.yaml
- io/net/infiniband/ib_latency_perf.py.data/ib_latency_perf.yaml
Removing unsupported options from Infiniband tests
> Removing unsupported options from Infiniband tests

- toolchain/bcc.py
Runs bcc self test. Added support only for Ubuntu.
> Added bpfcc/bcc test

- perf/perfmon.py
change git URL for test suite as earlier URL is not accessible
> Fixed perf:perfmon

- cpu/numatop.py
Test for numatop command using a self built mgen application. Currently supports only Ubuntu.
> Added numatop test

- io/disk/fs_mark.py
- io/disk/fs_mark.py.data/README.txt
- io/disk/fs_mark.py.data/fs_mark.yaml
* Changed the URL to a working one.
* Moved the Readme section in yaml file to README file.
* Removed unwanted data from yaml file.
> URL Fixes for fs_mark

- io/disk/ioping.py
- io/disk/ioping.py.data/ioping.yaml
ioping test is a Disk I/O latency monitoring tool
> Added ioping test

- io/disk/disktest.py
- io/disk/disktest.py.data/README.txt
- io/disk/disktest.py.data/disktest.yaml
* Added capability to get disk as input, and create fs and run tests
* Log file path contains a ';' due to which test might error. Fixed
it
* Updated yaml and Readme
* And some pylint fixes
> Fixes for disktest

- generic/service_check.py
Added opal_errd, opal_prd and rtas_errd.
> Added new services.

- io/pci/PowerVMEEH.data/PowerVMEEH.yaml
- io/pci/PowerVMEEH.data/Readme
Removed PowerVMEEH.data folder which was introduced wrongly
> Removed unnecessary folder PowerVMEEH.data

- kernel/kselftest.py
Patch adds required packages for kernel compile in kselftest
> Added packages for Ubuntu in kselftest

- cpu/em_cpuhotplug.py
The script will select random core from the list, picks the random cpus and does
offline and online in random order for that core.Make sure that all cores
are online.Script will set smt to maximum value,later it
works in random order to offline and online the cpu for 100 iterations.
> Hotplug the cpus in random order by selecting random core

- generic/pstore.py
Added check for pstore in config file and check for debugfs mount.
> Test to verify pstore - v4

- generic/pstore.py
Added code to verify whether latest files are saved under /sys/fs/pstore.
> Test to verify pstore - v3

- io/disk/multipath_test.py
Enhanced the script with few more scenarios on failing and
re-instating the multipaths.
Signed-off-by: Naresh Bannoth <nbannoth@linux.vnet.ibm.com>
> Enhancing the multipath_test.py with new scenarios (v5)

- memory/integrity.py
Added numactl-devel package for rhel,fedora distro
> Add package for integrity test

- io/net/uperf_test.py
- io/net/uperf_test.py.data/README.txt
- io/net/uperf_test.py.data/uperf_test.yaml
tool
This script will calculate the performance of the Network
adapter
> Script to add Uperf which is a network performance benchmark

- generic/sysbench.py.data/sysbench.yaml
It will enable user to understand yaml easily and change the
paraments on demand by the user.
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>
> added additional parameters to yaml for sysbench

- io/pci/dlpar.py
- io/pci/dlpar.py.data/README
- io/pci/dlpar.py.data/dlpar.yaml
Added a yaml parameter num_of_dlpar, and all dlpar operations will
run number of times sepcifeid in the ymal file
> Added iteration

- memory/vatest.py
- memory/vatest.py.data/Makefile
- memory/vatest.py.data/va_test.c
- memory/vatest.py.data/vatest.yaml
added VA test which test virtual address limit on linux
> Added VA test[V2]

- fs/xfstests.py
change self.srcdir to self.teststmpdir as self.srcdir
will be deprecate
> cleanup fs:xfstest

- memory/integrity.py
```
1-move scenario_arg varibale from test to setup subroutine
2- added check about scenario_arg as it should 1,2 or 3
```
> Fixed memory:integrity test 

- fs/xfstests.py
Patch replaces specified yaml inputs(mnt dirs) in local.config file
> Replace the config file with yaml inputs

- io/pci/pci_hotplug.py
- io/pci/pci_hotplug.py.data/README.txt
- io/pci/pci_hotplug.py.data/pci_hotplug.yaml
Added a for loop to iterate hotplug for number of times
specified by the user
> Iteration of Hotplug

- generic/htx_test.data/htx_test.yaml
- generic/htx_test.py
> Added generic Htx test

- memory/memcached.py
Support to run on SUSE distribution and a minor fix.
>  Support to run on SUSE distribution

- fs/xfstests.py
- fs/xfstests.py.data/xfstests.yaml
Added shared tests exclusion support and fixed hard-coded size check for loop disk.
> Added shared tests exclusion support and minor fix

- io/disk/Avago_storage_adapter/avago9361_vd.py
Tests such as ghs_dhs rebuild online_offline were failing, due to perticular
MFC values, and all those scenario are handeled now. Also changes made for migrate
test case, if there is no enough drives to pop for migration, test will exit.
> Fix: Certain tests were failing due to MFC values, which is handeled

- io/pci/PowerNVEEH.py
- io/pci/PowerVMEEH.py
> cancel pci eeh test if system is no ppc

- generic/ras_extended.py
Added few negetive cases for vpdupdate.
> Test to verify RAS tools.

- generic/gdb.py
- generic/gdb.py.data/gdb.yaml
- generic/gdb.py.data/version.yaml
Added support to run tests from distrution gdb source
> Support to run distribution specific gdb test

- toolchain/glibc.py
- toolchain/glibc.py.data/glibc.yaml
Added support to run tests from distrution glibc source
> Support to run distribution specific glibc test

- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
Modified yaml file to minimum default runs, as usually in test
scenario we dont have enough disk, and there by in result we see
lot of tests as cancel/skip
> Modified yaml file

- toolchain/binutils.py
- toolchain/binutils.py.data/binutils.yaml
- toolchain/binutils.py.data/version.yaml
Added support to run tests from distrution binutils source
> Support to run distribution specific binutils test

- io/net/net_data.py
Interface state change test did not restore interface configuration
after the test. Fixing that by restoring in tearDown()
> Restore interface config on interface state change

- io/disk/disk_info.py
Some linux distros do not support certain filesystems. In such
cases, mount throws an error. Since that was not handled in the
test, test ERRORs out. So, handling the exception and failing
gracefully.
Also, taking care of cleaning the filesystem on the disk, in
tearDown()
> Handling Exception when unable to mount filesystem

- io/pci/PowerNVEEH.py
* Revamped PowerNV EEH to use memory address and mask.
* Fixed the code to pass only necessary data between functions.
* Pylint fixes
[EEH_avocado_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1571569/EEH_avocado_log.txt)
[Direct_PHB_Power8_EEH_job_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/1578650/EEH_job_log.txt)
> Revamp of PowerNVEEH using memory address and mask

- io/net/bonding.py
* Adding route information to interfaces in bonding test.
* PEP8 and Pylint Fixes for Bonding Test.
> Network bonding add route v2

- memory/transparent_hugepages.py
thp_split_page is not available on redhat, support has been added in this patch with thp_split
> Add proper stat for thp on redhat

- io/disk/bonnie.py
Fixed io:disk:bonnie
1-added support as bonnie++ available from distro if it use distro version otherwise use available web source 
2-fixed pep8 issue in test
Signed-off-by: Praveen K Pandey praveen@linux.vnet.ibm.com
> Fix bonnie[V2]

- generic/lshw.py
1-Added tag for generic:lshw
added privileged tag for this test as lshw must be run as super user
it will only report partial information
2-Fixed generic:lshw
fixed all pep8 issue in script
> lshw test fix

- memory/memhotplug.py
If stress package is not available in distro, tarball is fetched for running stress
> Added stress install from tarball

- generic/stress-ng.py
- generic/stress-ng.py.data/stress-ng.yaml
Support memory stress with variable stressors and ability to run stressor list in parallel and in linear way
> Added variable stressor option for memory stress

- kernel/kselftest.py
- kernel/kselftest.py.data/kselftest.yaml
Added yaml to run each component of selftest as a variant
> Support to run individual component of selftest

- perf/hackbench.py
- perf/hackbench.py.data/hackbench.yaml
This commit implement the parameter "iterations"
allowing the test to be run multiple time, in a similar
manner that "iterations" is implemented in kernel/kernbench.py
At AMD, we use the "iterations" feature to smooth out benchmark values by running them multiple times and using the average value.
> Implement the parameter "iterations".

- toolchain/papiTest.py
- toolchain/papiTest.py.data/papiTest.yaml
The tests downloads, compiles the source file and displays
the failed tests onto the stdout
Signed-off-by: Umesh S <umess1@linux.vnet.ibm.com>
> Papi toolchain test to download source file and compile

- io/disk/fiotest.py.data/fio-rand-RW.job
- io/disk/fiotest.py.data/fio-rand-read.job
- io/disk/fiotest.py.data/fio-rand-write.job
- io/disk/fiotest.py.data/fio-seq-RW.job
- io/disk/fiotest.py.data/fio-seq-read.job
- io/disk/fiotest.py.data/fio-seq-write.job
added thread parameter to the job files
with reference to https://github.com/axboe/fio/issues/512#issuecomment-356552337
Signed-off-by: Venu <venutiwa@in.ibm.com>
> Modified parameter direct=0 to 1 for fio job files as per the comments

- memory/hugepage_sanity.py.data/hugepage_sanity.c
This patch includes following fixes
1) Author name
2) Tab/space issues are made uniform throuhout files
2) Take existing hugepages, perform test and restore back the
hugepages required
> Use hugepages on top of existing setup and restore

- io/net/virt-net/Network_virtualization_dlpar.py
- io/net/virt-net/Network_virtualization_dlpar.py.data/Network_virtualization_dlpar.yaml
- io/net/virt-net/Network_virtualization_dlpar.py.data/README
This script will add and delete Network virtualized interfaces
using the SRIOV capable IO adapter given as an input by the user
and performs this operation multiple times based on the count
given by the user as well
> Script to add and delete Network Virtualisation interfaces

- io/disk/softwareraid.py
- io/disk/softwareraid.py.data/Readme
- io/disk/softwareraid.py.data/softwareraid.yaml
- io/disk/softwareraid.py.data/softwareraid_cleanup.yaml
- io/disk/softwareraid.py.data/softwareraid_setup.yaml
Considering a requirement of just creating / deleting a raid.
This is useful if some tests needs to be run on created raid.
> Setup and Cleanup for softwareraid test

- io/net/virt-net/Network_virtualization_driver_bind.py
- io/net/virt-net/Network_virtualization_driver_bind.py.data/Network_virtualization_driver_bind.yaml
- io/net/virt-net/Network_virtualization_driver_bind.py.data/README
This script will unbind and bind the driver of the
Network virtualized device based on the count given by
the user and will also test Network connectvity
> Script to unbind and bind the Network virtualized device

- memory/eatmemory.py
- memory/eatmemory.py.data/eatmem_getch.patch
eatmem fix for removing getch
Signed-off-by: Kalpana S Shetty <kalshett@linux.vnet.ibm.com>
> eatmem fix

- memory/memory_api.py
- memory/memory_api.py.data/memory_api.c
- memory/memory_api.py.data/memory_api.yaml
Patch enhances test with negative input and catches the error
> Induce error in syscall and catch

- cpu/em_cpuhotplug.py
- cpu/em_cpuidle.py
- fs/xfstests.py
- generic/gdb.py
- io/disk/arcconf/arcconf_cntl_oper.py
- io/disk/arcconf/arcconf_drive_oper.py
- io/disk/arcconf/arcconf_migration.py
- io/disk/arcconf/arcconf_raid_oper.py
- io/disk/multipath_test.py
- io/disk/scsi_add_remove.py
- io/net/Network_config.py
- io/net/virt-net/network_virtualization.py
- io/pci/PowerNVEEH.py
- io/pci/pci_hotplug.py
- memory/hugepage_sanity.py
- memory/memhotplug.py
- perf/unixbench.py
as travis is failing due to pylint style issue on older test case
this patch will address those fixes
> Fix Pylint failure on travis

- io/net/virt-net/network_virtualization.py
- io/net/virt-net/network_virtualization.py.data/README
- io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
network_virtualization script is enhaned to
include a driver unbind bind test for Network
virtualized device
> Enhancing network_virtualization script

- cpu/cpustress.py
Fix cpu:cpustress 
1-adding hard lockup dectection on test
2-fixed pep8 issue in test
> Fix cpu:cpustress 

- toolchain/libpfm.py
- toolchain/libpfm.py.data/libpfm.yaml
This patch provides way to way upstream and distro specific libpfm tests
> Test to check libpfm functionality

- memory/vatest.py
- memory/vatest.py.data/va_test.c
This patch addresses the following issues
1. Runs tests with multiple hugepages and allows to allocate chunk with different page sizes in both address spaces
2. Change three scenarios to run with non-default hugepages which is referred to as alternate hugepages in the script
> Support to run vatest with multiple hugepages

- io/nvmf/nvmftest.py
- io/nvmf/nvmftest.py.data/README.txt
- io/nvmf/nvmftest.py.data/nvmftest.yaml
Adding multiple subsystems support for NVMf test
> Adding multiple subsystems support for NVMf test

- generic/nstress.py
Test will be run only on Power Platform.
> Added check for platform.

- perf/unixbench.py
Fixed perf:unixbench 
1-fix test case is it reporting error on test but in actual it is test fail
even change function name as well
2.a fixed style issue in process.system command
2.b added ignore_status=True in process.system to avoid script error out if test fail
> Unixbench fix

- generic/sosreport.py
Fixed failure in -p and -s options.
> Fixed few failues.

- io/disk/softwareraid.py
- io/disk/softwareraid.py.data/Readme
- io/disk/softwareraid.py.data/softwareraid.yaml
- io/disk/softwareraid.py.data/softwareraid_cleanup.yaml
- io/disk/softwareraid.py.data/softwareraid_setup.yaml
Made the --force parameter to create raid as a configurable
parameter, from the yaml file.
> Made force as an option to create raid

- fs/xfstests.py
Patch replaces existing method with new utility in fstest
> Use utility in filesystem test

- io/disk/multipath_test.py
The error messages were not appended to new line.
Fixed it.
> Multipath test: Made error to be added to new line

- io/disk/disk_info.py
- io/disk/fiotest.py
- io/disk/fs_mark.py
dir is a keyword in python.
So, changed its usage to dirs in the tests.
> Changed variable name dir to dirs

- io/disk/ltp_fs.py.data/README.txt
- io/disk/ltp_fs.py.data/ltp_fs.yaml
Added fs_fill and fs_perm tests to ltp_fs test.
> Added tests to ltp_fs

- io/net/iperf_test.py
- io/net/iperf_test.py.data/README.txt
- io/net/iperf_test.py.data/iperf_test.yaml
Added iperf network performance test.
> Adding iperf test

- perf/lmbench.py
This patch shows the results with 'make see'.
> lmbench.py Showing the results

- fs/fs-fuzz.py
fs-fuzz : two simple fuzzers
one for file system , second one for c stream
> Added fs-fuzz test

- fs/fsshrink.py
- fs/fsshrink.py.data/test-shrink.sh
Added fsshrink test that try to stress rmdir and unlink operation
> Added fsshrink test

- fs/pjdfstest.py
Added pjdfstest : test suite that  POSIX system calls
> Added pjdfstest

- generic/service_check.py
Patch adds package for opal-prd service in Ubuntu
> Add package for opal-prd service in Ubuntu

- memory/numa_test.py
Patch adds proper packages for numatest to execute
> Proper packages for numatest to execute

- requirements-travis.txt
update versions of modules used in lint/syntax checks
> Travis Fix

- fs/blktests.py
Added blktests
Blktests blktests is a test framework for the Linux kernel block layer
and storage stack
> Added blktests

- perf/hackbench.py
Fix the typo in the test failure message.
> perf/hack: Fix the test failure message

- ras/lshw.py
Older versions B.02.17 and below do not have support for '-notime'
option. Check for '-notime' option support before executing the
testcase and skip on the unsupported version of lshw.
> ras/lshw: Run -notime test only on supported version

- perf/perf_events_test.py
Refactor the perf_events_test to separate the code into functions
to build, test and analysis. Also add check for test suite build
failure and also consider 'unexplained' failure, as failed testcase.
> perf/perf_events_test: Refactor the code

- ras/packages.py
1-fixed pep8 issues in multiple places
2- Test case as this test only applicable on powerpc
so added check if this test case run on other than powerpc
test cancel
> Fix packages test case

- ras/diag_encl.py
Handle product_name for PowerNV platform
> Fix: Handle product_name for PowerNV platform

- cpu/dwh.py
- cpu/dwh.py.data/Makefile
- cpu/dwh.py.data/dwh.cpp
- cpu/dwh.py.data/dwh.yaml
- cpu/dwh.py.data/fofd.patch
Dwh program is to run a task with large (or small) numbers of pthreads, including worker and dedicated I/O threads. It's purpose is to generate heavy workloads for a single task.
> Added dwh testcase for exploiting thread issues

- memory/libhugetlbfs.py
This patch identifies the type of machine and mounts all supported hugepage sizes. This allows test coverage of supported hugepages in a single run.
> Enable multiple hugepage test run on supported hardware

- io/disk/ssd/nvmetest.py
changing the order of execution due to dependency of functions.
> Changing the function execution order

- io/disk/ssd/nvme_cli_selftests.py.data/nvme_cli_selftests.yaml
Changing the order of execution due to input dependency of next functions.
> Changing the order of execution.

- io/pci/PowerVMEEH.py
- io/pci/PowerVMEEH.py.data/PowerVMEEH.yaml
- io/pci/PowerVMEEH.py.data/Readme
PowerVM EEH can now handle individual PCI Address from yaml file.
> PowerVM EEH can now handle individual PCI Address

- io/pci/dlpar.py
Installing packages and starting services are organized as
separate functions, so that it is easier to use them better.
> Reorganizing DLPAR functionalities

- toolchain/oprofile.py
1- changed self.error  to self.cancel as it help on reporting
2- using %s for string concatenation
> Fixed oprofile test

- memory/stutter.py
1- Add make package as it needed to run test
2- changed self.error to  self.cancel as it reporting false alarm while reporting
> Fixed memory:stutter

- generic/stressapptest.py
- generic/stressapptest.py.data/stressapptest.yaml
Added stress app test with following options
1. memory copy
2. memory invert
3. file copy
> Added stress app test for memory interface testing

- perf/perf_genericevents.py.data/raw_code.cfg
Added new events namely mem-loads, mem-stores
> perf: Added new events

- perf/perf_24x7_hardware_counters.py
Instead of running group of tests and deciding whether they failed or not
at the end. With this patch tests run individually.
> perf: Added individual tests

- perf/perf_24x7_hardware_counters.py
Added offset test case to hv_24x7 tests
> perf: Added offset test case to hv_24x7

- perf/perf_basic.py
Removed unwanted function and arranged commands run in to
individual tests.
> perf_basic cleanup and arrange in to different tests

- perf/perf_24x7_hardware_counters.py
Enable power9 event along with power8 event.
And some cosmetic changes
> perf hv_24x7 enable power9 event

- perf/perf_pcp.py
Adding Performance Co Pilot(PCP) test cases
> perf Adding performance co pilot tests

- ras/ras_extended.py
added vpdupdate before running lscfg and lsvpd tests
> fixed lscfg and lsvpd failure

- cpu/em_smt_folding_test.py
1- Added cpu dlapr operation code which does cpu hot remove
and hot add
2- call main test as well dlpar cpu operation in thread
> Added new test functionality in cpu:em_smt_folding_test

- ras/ras.py
Improve error reporting. Instead of individual checks, used a function
to verify the failed commands and exit code.
with out patch:
FAIL: 1 command(s) failed in lsslot tool verification
with patch:
FAIL: RAS: Failed commands are: ['lsslot -c pci -o']
> ras.py: Improve error reporting

- ras/lshw.py
mprove error reporting. Instead of individual checks, used a function
to verify the failed commands and exit code.
with out patch:
FAIL: [] command(s) failed to execute
with patch:
FAIL: lshw: Failed commands are: ['lshw | grep product | head -1']
> lshw.py: Improved error checking

- perf/perf_24x7_hardware_counters.py
perf 24x7 counter test is applicable for PowerVM LPAR environment.
On non-virtualized environment it fails with
ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:843
ERROR| Traceback (most recent call last):
ERROR| File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pcp.py", line 86, in test_perfevent_24x7_events
ERROR| self.lpar_24x7_ppc64le_check()
ERROR| File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pcp.py", line 59, in lpar_24x7_ppc64le_check
ERROR| " only on LPAR" % self.event_sysfs)
ERROR| AttributeError: 'PCP' object has no attribute 'event_sysfs'
Add a check for POWER non virtualized and KVM guest platform and if true skip the test.
Signed-off-by: Sachin Sant …
> Skip perf 24x7 test on Power non virtualized and KVM environment.

- perf/perf_24x7_hardware_counters.py
- perf/perf_basic.py
- perf/perf_pcp.py
- perf/perf_rawevents.py
Pylint fixes and code improvements
> Fix: pylint and code improvements

- generic/ltp.py
LTP Test case on every run exits with failure even if there is no visible test case failure.
[124659.663797] Clock: inserting leap second 23:59:60 UTC
FAIL: No test failures detected, but LTP finished with 1 (1748.47 s)
RESULTS   : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1748.52 s
This happens as the coded logic for failure detection does not cover all types
of failures.This patch rewrites the test failure detection code.
The new mechanism relies on ltp.log generated by LTP run. Since ltp.log
contains information about test failures marked as BROK (in addition to TFAIL,
TCONF, TBROK) there are very little chances of missing any type of failures.
> Improve ltp test failure error handling logic

- io/disk/disktest.py
- io/disk/disktest.py.data/README.txt
- io/disk/disktest.py.data/disktest.yaml
disk size is automatically computed for the given disk.
> Automatically compute data for disktest

- ras/uprobe.py
> uprobe.py: remove unused code

- ras/supportconfig.py
> fix for supportconfig test.

- io/disk/htx_block_devices.py
- io/net/htx_nic_devices.py
This commit does the below:
* Builds HTX from git
* Enhancement to /etc/hosts file edit section
* Enhancements to tearDown
> Refactor HTX test for network

- memory/hugepage_sanity.py.data/hugepage_sanity.c
If hugepage attributes are not available in /proc/meminfo, handle
prior starting to test and error out gracefully.
fix compiler warnings implicit declaration for `access()` and `time()`
by including unistd.h, declare `alloc_hugepage()` definition before using
it in `check_alloc_free_huge_page()` and few style changes.
If hugepages attributes are not available in /proc/meminfo,
Before fix:
Using default hugepagesize and 1 hugepage
PAGESIZE: 137438926347 MB	Number of pages: 1
Given hugepage size is not supported in kernel
After fix:
Using default hugepagesize and 1 hugepage
Error: Pagesize is invalid or not available
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
> hugepage_sanity: handle error if hugepage attributes are not available

- memory/migrate_pages.py
- memory/migrate_pages.py.data/Makefile
- memory/migrate_pages.py.data/migrate_pages.yaml
- memory/migrate_pages.py.data/node_move_pages.c
This test validates migration of
a) normal pagesize
b) hugepages
c) hugepages with overcommit
d) transparent hugepages
> Add page migration tests with normal pages,hugepages and thp

- memory/dma_memtest.py
- memory/eatmemory.py
- memory/libhugetlbfs.py
- memory/memcached.py
- memory/memhotplug.py
- memory/memtester.py
- memory/mprotect.py
- memory/transparent_hugepages_defrag.py
- memory/transparent_hugepages_swapping.py
Patch makes sure memory tests are compliant with pylint and has some code improvements.
> memory: pylint and code improvements

- cpu/numatop.py
Made changes in zip file path and added step to run autogen.sh.
> Fixed numatop test.

- fuzz/trinity.py
- io/disk/dbench.py
- io/disk/parallel_dd.py
- io/disk/scsi_add_remove.py
- kernel/rmaptest.py
- memory/memcached.py
- perf/aiostress.py
- perf/rt_tests.py
- perf/tbench.py
- toolchain/atlas.py
- toolchain/gdb.py
- toolchain/glibc.py
- toolchain/gsl.py
Patch replaces self.error to self.cancel wherever applicable
> Cancel tests instead of error-ing out

- cpu/dwh.py
- io/disk/dbench.py
- perf/unixbench.py
Patch adds/removes 'patch' packages based on requirement of test
> Fix: Install patch wherever applicable

- io/disk/bonnie.py.data/bonnie.yaml
- io/disk/disk_info.py.data/disk_info.yaml
- io/disk/fiotest.py.data/fio.yaml
- io/disk/ioping.py.data/ioping.yaml
- io/disk/ltp_fs.py.data/ltp_fs.yaml
- io/disk/lvsetup.py.data/lvsetup.yaml
- io/disk/parallel_dd.py.data/parallel_dd.yaml
- io/disk/softwareraid.py.data/softwareraid.yaml
- io/disk/softwareraid.py.data/softwareraid_cleanup.yaml
- io/disk/softwareraid.py.data/softwareraid_setup.yaml
- io/disk/tiobench.py.data/tiobench.yaml
Some yaml contained values which were not needed, and some values
which could harm the system.
Some yaml contained meaningless explanation for parameter values.
Cleaned them all in this commit.
> Changes to yaml for all disk related tests

- io/disk/lvsetup.py
The lvsetup test tests multiple functionalities, so we are
splitting it into sub tests, to get better context of results.
Also, using only 45% of disk for lv instead of 50%, since
sometimes disk boundaries do not allow 100% utilisation.
And a small pep8 fix.
> Splitting lv setup test into sub tests

- kernel/kselftest.py
Parsing of selftest failure was not working due to a recent change in upstream kernel. This patch fixes it.
> Fix: Pattern of upstream selftest

- kernel/kselftest.py
Patch adds function to parse FAILs which reduces the repeated code
> Add function to parse selftest failures

- memory/hugepage_sanity.py
- memory/integrity.py
- memory/ksm_poison.py
- memory/libhugetlbfs.py
- memory/memory_api.py
- memory/migrate_pages.py
- memory/mprotect.py
- memory/numa_test.py
- memory/sum_check.py
- memory/transparent_hugepages.py
- memory/transparent_hugepages_defrag.py
- memory/transparent_hugepages_swapping.py
- memory/vatest.py
Patch adds appropriate tags for memory tests
> Add appropriate tags for memory tests

- cpu/em_smt_folding_test.py
- cpu/em_smt_folding_test.py.data/em_smt_folding_test.yaml
1-Added customize support as cpu unit and loop in test 
2- Fixed style issue in test
> Fix em_smt_folding_test Test

- cpu/em_cpufreq.py
- cpu/em_cpuhotplug.py
- cpu/em_cpuidle.py
- cpu/em_quad_level_frequency_transitions.py
- cpu/em_smt_folding_test.py
Patch adds appropriate tags for EM tests
> Added tag for EM test cases

- io/net/virt-net/lpm.py
- io/net/virt-net/lpm.py.data/README.txt
- io/net/virt-net/lpm.py.data/lpm.yaml
> LPM Test with virtual network

- cpu/cpustress.py
Fixed dmesg fail string look up for Hard LockUp
> Fixed dmesg fail string look up for Hard LockUp

- perf/perf_uprobe.py
Corrected the command syntax for SuSE distributions.
> perf_uprobe.py: corrected the command syntax for SuSE distro

- memory/ndctl.py
- memory/ndctl.py.data/ndctl.yaml
Add test for multiple namespace in a single region using the existing regions size
> Add test for multiple namespace in a single region

- memory/ndctl.py
Patch adds test for namespaces re-configuration and verification.
It also fixes a minor issue with "memmap" which should be defaulting to "dev" instead of "mem"
> Add test for namespace re-configuration and verification

- io/net/virt-net/network_virtualization.py
- io/net/virt-net/network_virtualization.py.data/README
- io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
[1/2] Get HMC ip and server and dlpar package fix
[2/2] vNIC: add dlpar add/remove of vNIC virtual slot test
> vNIC tests enhancement

- perf/perf_sdt_probe.py
perf/perf_sdt_probe: Add userpace SDT markers 
This adds SDT marker event probe via perf:
1. Load the libpthread to the perf
2. Probe SDT marker event exported by libpthread library
3. Record perf for the planted SDT marker probe
4. Unregister the SDT marker probe/unload the library
Fixed Test perf:perf_sdt_probe 
1- Address review comments
2- made test as pep8 compliant
>  perf/perf_sdt_probe test case

- memory/ndctl.py
Add test to create multiple namespaces with multiple regions
> Add test to create multiple namespaces with multiple regions

- io/net/iperf_test.py
- io/net/netperf_test.py
- io/net/uperf_test.py
this code will display the output in percentage format.
> Converting output in to percentage format

- cpu/em_cpuhotplug.py
- cpu/em_cpuhotplug.py.data/em_cpuhotplug.yaml
1-Fix: few pylint issues 
2-cleanup and use Avocado library 
> Fix em_cpuhotplug test

- io/net/virt-net/network_virtualization.py
- io/net/virt-net/network_virtualization.py.data/README
- io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
7534bf0b Get LPAR and Server from HMC
8cc6167 enable vNIC priority option for vNIC tests
> Vnic enhancements [v2]

- io/net/htx_nic_devices.py
- io/net/iperf_test.py
- io/net/netperf_test.py
- io/net/uperf_test.py
This code will help to install the packages on peer sysytem.
> Installing packages on peer machine

- io/driver/module_unload_load.sh.data/config
> Add dependency to the USB driver module

- io/net/ethtool_test.py.data/ethtool_test.yaml
Added few option to the ethtool test.
> Ethtool Enhancement

- io/net/bridge.py
Use iputils for creating, testing and deleting bridge. bridge-utils
is being deprecated in few distros, hence using ip commands to
test bridge functionality.
> Enhancement for bridge test

- io/net/Network_config.py
create separate function for all the comparing test and removed
link test,because its already there in ethtool test.
> Network config Enhancement

- memory/ndctl.py
- memory/ndctl.py.data/ndctl.yaml
Add option for size and mode to be used as input
> Add option for size and mode to be used as input

- io/net/infiniband/rdma_tests.py.data/ib_send_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_lat_extended.yaml
Fixed -g option for RDMA cards
> Fixed -g option for RDMA cards

- io/net/iperf_test.py
- io/net/netperf_test.py
- io/net/uperf_test.py
removing the space from between the line of output.
> Removing space in output

- io/net/infiniband/dapl.sh
- io/net/infiniband/dapl.sh.data/README.txt
- io/net/infiniband/dapl.sh.data/dapl.yaml
optimised dapl script code and added additional scenarios to dapl tests
> Fixed dapl tests script and parameters v2

- perf/perf_24x7_all_events.py
- perf/perf_24x7_hardware_counters.py
- perf/perf_basic.py
- perf/perf_c2c.py
- perf/perf_events_crash_test.py
- perf/perf_events_test.py
- perf/perf_fuzzer.py
- perf/perf_genericevents.py
- perf/perf_hv_gpci.py
- perf/perf_nest_events.py
- perf/perf_pcp.py
- perf/perf_rawevents.py
- perf/perf_sdt_probe.py
- perf/perf_uprobe.py
- perf/perfmon.py
- perf/perftool.py
Added tags perf, probe, pcp, c2c, 24x7, events, hv_gpci, perfmon, testsuite
nest
> perf: Added relevant tags

- cpu/em_cpuidle.py
- io/disk/disktest.py
- io/disk/ssd/blkdiscard.py
Fix pylint issue as some funtion is not available python3
> [hot fix]Fix pylint issue as some funtion is not available python3

- .travis.yml
Added Python 3 support in travis run
> Added Python 3 support in travis run

- memory/memhotplug.py
Previous URL is not working
https://people.seas.harvard.edu/~apw/stress/stress-1.0.4.tar.gz
> memhotplug.py:Added new URL

- cpu/em_cpufreq.py
Fix environment detection logic for em_cpufreq test
> Backport Patch to python2 branch

- memory/memhotplug.py
Previous URL is not working
https://people.seas.harvard.edu/~apw/stress/stress-1.0.4.tar.gz
> [back-port]memhottplug.py:Added new URL

- fuzz/trinity.py
- generic/htx_test.py
- generic/ltp.py
- generic/stress-ng.py
Moved few testcases to python3, handled possible failures. Tested on latest operating systems.
> [python3] Move few tests to python3

- io/disk/disk_info.py
- io/disk/disktest.py
- io/disk/htx_block_devices.py
- io/disk/multipath_test.py
- io/disk/softwareraid.py
- io/disk/tiobench.py
Python 3 migration of tests - io/disk/
> Python 3 migration of tests - io/disk/

- ras/lshw.py
1-Removed + to concatenate string as that make script error out
2- Rectified cancel string
> Fix issue in ras:lshw test

- ras/lshw.py
lshw test as it is failing on our CR
> Back Port request for python2 for fixing lshw test 

- fs/blktests.py
- fs/filebench.py
- fs/flail.py
- fs/fs-fuzz.py
- fs/fsshrink.py
- fs/fsx.py
Move memory tests to run with python3 expect xfstest
> [python3]Move fs tests to run with python3.

- io/net/Network_config.py
correction of a spelling mistake.
> fixed network config test

- io/net/virt-net/network_virtualization.py
bffc558   [6/6] wait for 30 sec after hoplug
cbfa152  [5/6] test case for virtual nic auto priority failover feature
6f15243  [4/6] change_failover_priority: sets a new value for priority
c3fc3ff    [3/6] function get_failover_priority to get the priority value
59dab36 [2/6] function enable_auto_failover to set auto_priority_failover
a656f5b  [1/6] function is_auto_failover_enabled to check auto failover
> vNIC: patch series to test auto failover feature

- fs/pjdfstest.py
added openssl as package requirment in test
> [Backport] fix issue in fs:pjdfstest

- io/pci/dlpar.py
- io/pci/pci_hotplug.py
Python 3 migration of tests - io/pci/
> Python 3 migration of tests - io/pci/

- io/disk/ssd/nvme_cli_selftests.py
- io/disk/ssd/nvmetest.py
* Python 3 migration of tests - io/disk/ssd/
* Also some pep8 and pylint changes
> Python 3 migration of tests - io/disk/ssd/

- io/net/network_test.py
adding a new test for promisc mode testsing
> Adding promisc mode test

- io/net/bonding.py
- io/net/bonding.py.data/bonding.yaml
- io/net/iperf_test.py
- io/net/iperf_test.py.data/iperf_test.yaml
- io/net/multicast.py
- io/net/multicast.py.data/multicast.yaml
- io/net/netperf_test.py
- io/net/netperf_test.py.data/netperf_test.yaml
- io/net/uperf_test.py
- io/net/uperf_test.py.data/uperf_test.yaml
removing running command through ssh on peer machine and adding
login to the peer machine and running the command through function.
> passwordless ssh

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/ib_pingpong.py.data/ib_pingpong.yaml
- io/net/infiniband/mckey.py
- io/net/infiniband/mckey.py.data/mckey.yaml
- io/net/infiniband/ping6.py
- io/net/infiniband/ping6.py.data/ping6.yaml
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rdma_tests.py.data/ib_atomic_bw_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_atomic_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_atomic_lat_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_atomic_lat_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_read_bw_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_read_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_read_lat_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_read_lat_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_bw_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_lat_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_lat_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_write_bw_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_write_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_write_lat_basic.yaml
- io/net/infiniband/rdma_tests.py.data/ib_write_lat_extended.yaml
- io/net/infiniband/rping.py
- io/net/infiniband/rping.py.data/rping.yaml
- io/net/infiniband/ucmatose.py
- io/net/infiniband/ucmatose.py.data/ucmatose.yaml
- io/net/infiniband/udaddy.py
- io/net/infiniband/udaddy.py.data/udaddy.yaml
removing running command through ssh on peer and adding login function,
through that it will run command on peer machine.
> Passwordless ssh for infiniband

- io/net/multicast.py
- io/net/multicast.py.data/multicast.yaml
before it was sending 1 packet now we increased to 5 lakhs packet
and doing ping flood test.
> Increasing number of ping count from 1 to 5 lakhs

- memory/vatest.py.data/vatest.yaml
Skipped vatest scenario's from 3rd to 10th
because they are causing memory-space issues.
> Vatest:Skipped some of scenario's

- perf/perf_events_test.py
1-Rectified make failed cancel string
2- rectified unnecessary check
3- Added privileged tag
> fixed issues in perf:perf_events_test test

- io/net/bootlist_test.py
- io/net/bootlist_test.py.data/README.txt
- io/net/bootlist_test.py.data/bootlist_test.yaml
here we converting to different mode of bootlist and checking it.
> New Test case Bootlist testing

- memory/ndctl.py
Patch adds tests to verify numa nodes associated per region with its sysfs interface and ndctl command line
> Add test to verify nvdimm-numa node association

- fuzz/fsfuzzer.py
- generic/criu.py
- generic/rcutorture.py
- generic/sysbench.py
move more test case to python3
> Python 3 migration of tests

- cpu/cpustress.py
- cpu/ebizzy.py
- cpu/ppc64_cpu_test.py
- cpu/sensors.py
move rest cpu test cases as python3 compliant
> [Python3]move rest cpu test cases as python3 compliant

- perf/perf_script_bug.py
- perf/perf_script_bug.py.data/Makefile
- perf/perf_script_bug.py.data/perf_test.c
Adding testcase for perf script seg fault
with cpu cycle related events
> perf_script_bug.py:Testcase for perf script segfault

- io/net/Network_config.py
> Network config spelling fix

- perf/perf_24x7_all_events.py
- perf/perf_24x7_hardware_counters.py
- perf/perf_c2c.py
- perf/perf_events_test.py
- perf/perf_pcp.py
- perf/perf_uprobe.py
- perf/perfmon.py
- perf/perftool.py
To get rid of str and byte related errors,
changed the script
> added decode('utf-8') and 'b'

- io/disk/lvsetup.py
Overcomming lvm specific probles with older python2 which cannot be enhanced
> [Back-port] Overcomming lvm specific problems with older python2 -v2

- toolchain/oprofile.py
> updated github link in test case

- io/net/bonding.py
- io/net/iperf_test.py
- io/net/multicast.py
- io/net/netperf_test.py
- io/net/uperf_test.py
removed peer login and run command function and imported ssh file
from avocado utils for running command on peer machine.
> Passwordless ssh for network test cases

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
removed peer login and run command function and imported ssh file
from avocado utils for running command on peer machine.
> Passwordless ssh for infiniband test cases

- io/net/network_test.py
- io/net/network_test.py.data/network_test.yaml
added switch port enable and disable test to network_test.py.
> Added new test to network_test.py

- io/pci/distro_tools.data/distro_tools.yaml
- io/pci/distro_tools.py
Testing different distro tool for IO
> New test case distro_tools.py

- perf/perf_fuzzer.py
- perf/perf_sdt_probe.py
To get rid of arguments related errors,
changed the script
> added decode("utf-8") and changed fail() arguments

- toolchain/gsl.py
logs attached
avocado run gsl.py
JOB ID     : 322e6f021a074274d719977ea20627998fda9eab
JOB LOG    : /root/avocado/job-results/job-2019-10-21T01.43-322e6f0/job.log
(1/1) gsl.py:GSL.test: PASS (359.46 s)
JOB TIME   : 359.86 s
> regular exp updated in gsl test case

- io/disk/fiotest.py
- io/disk/ssd/ezfiotest.py
Adding dependency packages for fio and ezfio tests
> Adding dependency packages for fio and ezfio tests

- io/disk/fiotest.py
- io/disk/ssd/ezfiotest.py
Adding dependency packages for fio and ezfio tests
> [Backport] Adding dependency packages for fio and ezfio tests

- io/disk/Avago_storage_adapter/avago9361_vd.py
Added the Manual pre-requisite steps for avago9361
> Added the Manual pre-requisite steps for avago9361

- io/net/bonding.py
- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
- io/net/multicast.py
- io/net/netperf_test.py
- io/net/uperf_test.py
> Changed default password for infiniband and network test case.

- io/net/ethtool_test.py
> Fixed ethtool test

- perf/perf_UDT_probes.py
- perf/perf_UDT_probes.py.data/tick-dtrace.d
- perf/perf_UDT_probes.py.data/tick-main.c
By using dtrace and systemtap we are checking perf UDT instrumentation
> perf_UDT_probes.py:Added test-case for perf UDT instrumentation

- perf/hackbench.py
To get rid of str related error
> Added decode("utf-8")

- io/net/tcpdump.py.data/tcpdump_extended.yaml
> Extending tcpdump test cases

- io/pci/distro_tools.data/distro_tools.yaml
- io/pci/distro_tools.py
> Testing different distro tools for io

- io/net/virt-net/lpm_basic.py
- io/net/virt-net/lpm_basic.py.data/README.txt
- io/net/virt-net/lpm_basic.py.data/lpm_basic.yaml
This tests will tests LPM basic migration tests. For example,
the test code will take care of migrating from source -> target system and
moving it back to source system.
Signed-off-by: Kalpana Shetty kalshett@in.ibm.com
> [Backport]Adding basic lpm tests.

- fs/xfstests.py
Patch remove package which is not available in rhel8 distro
> [Backport] Fix: Remove unnecessary package

- io/net/iperf_test.py
- io/net/iperf_test.py.data/iperf_test.yaml
- io/net/netperf_test.py
- io/net/netperf_test.py.data/netperf_test.yaml
- io/net/network_test.py
- io/net/network_test.py.data/network_test.yaml
- io/net/uperf_test.py
- io/net/uperf_test.py.data/uperf_test.yaml
replace ping_check, mtu_set in network_test file and add mu_set to
iperf_test, uperf_test, netperf_test file.
> replace ping_check and mtu_set with configure_network module

- memory/ndctl.py
Add test to verify disabling/enabling namespace of a region
> Test for disable/enable namespace

- io/net/network_test.py
- io/net/network_test.py.data/network_test.yaml
- io/net/switch_test.py
- io/net/switch_test.py.data/README.txt
- io/net/switch_test.py.data/switch_test.yaml
new test case for switch port enable disable test and removing from
network_test case.
> creating new test file for switch test and removing from network_test

- io/net/infiniband/mckey.py.data/mckey.yaml
- io/net/infiniband/rdma_tests.py.data/ib_read_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_read_lat_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_send_lat_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_write_bw_extended.yaml
- io/net/infiniband/rdma_tests.py.data/ib_write_lat_extended.yaml
- io/net/infiniband/rping.py.data/rping.yaml
Modifing the packet size to an generic format.
> Modifing the packet size to an generic format.

- io/net/bonding.py
- io/net/bonding.py.data/README.txt
- io/net/bonding.py.data/bonding_infiniband.yaml
Fixed Bonding tests for infiniband based interfaces.
> [back-port] Fixed Bonding tests for infiniband based interfaces.

- io/disk/Avago_storage_adapter/avago9361_vd.py
- io/disk/Avago_storage_adapter/avago9361_vd.py.data/avago9361_vd.yaml
Added the Manual pre-requisite steps for avago9361
> [backport] Added the Manual pre-requisite steps for avago9361

- perf/perf_bench.py
- perf/perf_bench.py.data/bench_options.yaml
Adding perf bench tests with different arguments
> perf_bench.py: adding perf bench test cases

- io/net/virt-net/network_virtualization.py
Enhancement of network_virtualization for mulitple vnic interface.
> To create multiple Vnic interfaces

- perf/perf_duplicate_probe.py
Added test case to detect duplicates in probe
> Testcase for detecting duplicates in Probe

- perf/perf_duplicate_probe.py
Added test case to detect duplicates in probe
> [Backport]Testcase for detecting duplicates in Probe

- io/net/virt-net/network_virtualization.py
To create multiple vnic interface.
> Enhancement of network_virtualization for multiple vnic

- io/disk/multipath_test.py
converted the code into functions, based on different scenarios,
So that each scenario can be ran when needed.
script also works fine as a whole.
> modifying the multipath_test.py script for scenario testing

- io/driver/driver_parameter.py
- io/driver/driver_parameter.py.data/README.txt
- io/driver/driver_parameter.py.data/driver_parameter_mlx5_ib.yaml
Driver module parameter verification scripts for mlx5_ib
> Driver module parameter verification scripts for mlx5_ib

- cpu/cpustress.py
- cpu/dwh.py
- cpu/em_cpuhotplug.py
- cpu/numactl.py
- cpu/ppc64_cpu_test.py
SMT max value may be configured at boot and may not match arch max
We can get dynamically the max value
Signed-off-by: thierry <tfauck@free.fr>
modified:   em_cpuhotplug.py
modified:   ppc64_cpu_test.py
> SMT max setting

- memory/hugepage_sanity.py
- memory/libhugetlbfs.py
- memory/transparent_hugepages.py
- memory/transparent_hugepages_defrag.py
- memory/transparent_hugepages_swapping.py
Skip test if Hugepage not found in kernel
Signed-off-by: thierry <tfauck@free.fr>
> Hugepage setting on py2 branch

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/ib_pingpong.py.data/ib_pingpong_infiniband.yaml
- io/net/infiniband/ib_pingpong.py.data/ib_pingpong_roce.yaml
Enhance IB pingpong test to accomidate MTU variations.
> Enhance IB pingpong test to accomidate MTU variations.

- cpu/cpustress.py
- cpu/dwh.py
Prevent putting off the only available of the system
> The only cpu of the system can't be disabled

- io/net/network_test.py
- io/net/network_test.py.data/network_test.yaml
- io/net/network_test.py.data/network_test_infiniband.yaml
- io/net/network_test.py.data/network_test_one_variant.yaml
- io/net/network_test.py.data/network_test_virt_net.yaml
network_test.py is failing with
ERROR: 'NetworkTest' object has no attribute 'ping_check'
> Bug fix for network_test

- requirements-travis.txt
Bump up pylint version as travis requirement
> Bump up pylint version as travis requirement

- io/net/ethtool_test.py
- io/net/ethtool_test.py.data/ethtool_infiniband.yaml
- io/net/ethtool_test.py.data/ethtool_test.yaml
- io/net/ethtool_test.py.data/ethtool_veth_test.yaml
- io/net/ethtool_test.py.data/ethtool_vnic_test.yaml
Added private flag toggle function to ethtool
> Added private flag toggle function to ethtool

- io/net/network_test.py
- io/net/network_test.py.data/network_test.yaml
Enabling TSO and GSO for network tests.
> Enabling TSO and GSO for network tests.

- io/driver/driver_parameter.py
- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
- io/net/iperf_test.py
- io/net/multiport_stress.py
- io/net/netperf_test.py
- io/net/network_test.py
- io/net/tcpdump.py
- io/net/uperf_test.py
removed self from ping_check and mtu_set_host for all test files.
> Fixed in ping_check and mtu_set_hostfor network and infiniband test

- io/disk/vfc-tests/vfc_dlpar.py
- io/disk/vfc-tests/vfc_dlpar.py.data/README.txt
- io/disk/vfc-tests/vfc_dlpar.py.data/vfc_dlpar.yaml
Adding new test script of vfc_dlpar.py, that does the dlpar
operation for vfc interfaces.
> Adding dlpar test for vfc interfaces

- io/disk/bonnie.py
btrfs is not supported on rhel distros from 7.4 version onwards.
previously we had a fix for same but it was faling to enter the loop
after installing the required packages.
so just changed the order and it is working fine now.
> Fixed the btrfs dependency for bonnie test

- io/disk/scsi_add_remove.py
modified the script in python3 compatible.
> changing scsi_remove_add.py to python3 compatible

- io/disk/disk_info.py
converting disk_info.py file to python3 compatible
> Disk_info.py, converting to python3

- ras/servicelog.py
To avoid those failures,I have put a condition to check
> servicelog.py: servicelog_notify verification we are getting failures

- perf/perf_uprobe.py
Based on issue #1406 modified the script to run correctly
> Added condition to resolve issue in Rhel7.6alt

- io/net/virt-net/network_virtualization.py
- io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
vios failover using rmdev and mkdev commands.
> Added new failover test case to network_virtualization

- io/net/multiport_stress.py
> changing host_ip to host_ips in multiport_stress.py

- io/net/ethtool_test.py
fixed import error for ethtool_test.py
> Fix ethtool_test.py

- memory/ndctl_selftest.py
Add support to run ndctl selftest on RHEL
> Add support to run ndctl selftest on RHEL

- io/pci/dlpar.py
Fixed the python3 conversion error in dlpar.py
> Fixing python3 issue in dlpar.py

- perf/perf_uprobe.py
Based on issue #1406 modified the script to run correctly
Also changed Class name according to Classes naming convention
> [Backport]Added condition to resolve issue in Rhel7.6alt

- fs/fsx.py
- fs/fsx.py.data/fsx-mm.yaml
Add option to run fsx test with THP mount
> Add option to run fsx test with THP mount

- generic/stress-ng.py
- io/disk/multipath_test.py
- kernel/tlbflush.py
- toolchain/valgrind.py
Add debian as distro
decode() added when necessary
test on null string fixed
upgrade valgrind release to current one
> Add debian distro and fix python issues

- memory/ndctl.py
- memory/ndctl.py.data/ndctl.yaml
ndctl tests has few enhancements which include
1) w.r.t size alignment with namespace counts
2) renaming to suitable method names
3) Remove namespace count and size inputs which might not meet the alignment requirements
4) pylint issues
> ndctl fixes and enhancements

- generic/stress-ng.py
- io/disk/fiotest.py
- io/disk/lvsetup.py
- perf/perfmon.py
- toolchain/valgrind.py
Convert string to bytes for startswith and endswith in valgring.py
Add debian dependency
> python3 startswith, endswith needs bytes

- io/net/net_tools.py
Was running these test on python3 and failed, so fixed to py3 syntax
> net-tools test was failing for python 3

- io/disk/scsi_add_remove.py
- io/disk/scsi_add_remove.py.data/scsi_add_remove.yaml
Enhancing the scsi remove add test for stress run by adding count.
> Enhancing scsi_remove_add.py for stress testing

- memory/numa_test.py
- memory/numa_test.py.data/Makefile
- memory/numa_test.py.data/bench_movepages.c
- memory/numa_test.py.data/softoffline.c
- memory/numa_test.py.data/util.c
Patch adds test to validate PFN before and after softoffline
> Add test to validate PFN before and after softoffline

- io/net/Network_config.py
virtual interface/drivers such as ibmvnic, ibmveth does not have
pci bus id and the sysfs path differes from physical interface so
this code can handle both
> network_config: enable for virtual network test config

- io/disk/dbench.py
Added decode("utf-8") to avoid string pattern error.
> dbench.py: Added decode("utf-8")

- io/pci/dlpar.py
> Fixed Dlpar test.

- memory/ndctl.py
- memory/ndctl.py.data/map_sync.c
Add test to verify MAP_SYNC flag for DAX devices
> Add test to verify MAP_SYNC flag for DAX devices

- memory/ndctl_selftest.py
Add jq package for ndctl selftest
> Add jq package for ndctl selftest

- cpu/em_smt_folding_test.py
- cpu/numatop.py
- fs/blktests.py
- fs/xfstests.py
- kernel/kselftest.py
- memory/integrity.py
- memory/libhugetlbfs.py
- memory/memcached.py
- memory/migrate_pages.py
- memory/numa_test.py
- perf/perf_24x7_hardware_counters.py
- perf/perf_basic.py
- perf/perf_events_test.py
- perf/perf_pcp.py
- perf/perf_rawevents.py
- perf/perftool.py
- ras/lshw.py
- ras/sosreport.py
- ras/uprobe.py
- toolchain/oprofile.py
Mostly add debian support and prereq
> Support for Debian

- io/net/iperf_test.py
changing iperf_test from iperf3 to iperf2
> changed iperf3 to iperf2

- io/net/ethtool_test.py
Used instead of sleep and this function waits for max 120s
> ethtool_test.py: use is_interface_link_up from configure_network utility

- io/net/tcpdump.py
Used instead of sleep and this function waits for max 120s
> tcpdump.py:use is_interface_link_up from configure_network utility

- memory/ndctl.py
Account idle namespace when creating namespace.
> memory/ndctl: Update the available slot count

- io/net/switch_test.py
> Fixed import error for switch_test

- memory/ndctl.py
- memory/ndctl.py.data/ndctl.yaml
Add test to check device mapping option with available namespace
> Add test to check device mapping option

- io/net/bonding.py
bonding test fixed for back to back.
> fixed bonding test for back to back

- ras/diag_encl.py
> Skip test if run on KVM

- io/driver/driver_parameter.py
- io/driver/driver_parameter.py.data/driver_parameter_tg3.yaml
> tg3 parameters for  driver_parameter.py

- io/pci/pci_hotplug.py
- io/pci/pci_hotplug.py.data/pci_hotplug.yaml
Added the functionality to handle  multiple pci_address
of an adapter.
> Enhancing pci_hotplug.py

- io/disk/port_bounce.py
- io/disk/port_bounce.py.data/port_bounce.yaml
…apters
the existing script only works for physical adapter and not for virtual adapter.
And the current script will work for both the adapters
> Modifying the port_bounce.py to work for both physical and virtual adapter

- io/net/tcpdump.py
- io/net/tcpdump.py.data/tcpdump.yaml
added nping_count and changed to packets dropped by kernel.
> Fixed tcpdump test

- io/net/bonding.py
- io/net/bonding.py.data/bonding.yaml
- io/net/bonding.py.data/bonding_infiniband.yaml
- io/net/bonding.py.data/bonding_single.yaml
- io/net/bonding.py.data/bonding_virtual.yaml
added ip config set and unset in bonding.
> added ip config in bonding test

- io/net/htx_nic_devices.py
- io/net/htx_nic_devices.py.data/README.txt
- io/net/htx_nic_devices.py.data/htx_nic_devices.yaml
mnually set ip if pingum failed in htx test.
> added ip configuration for both host and peer interface in htx

- io/net/vlan_test.py
remove telnet for sitch access and add paramiko for switch access.
> Fixed vlan test by using paramiko for switch access

- io/net/vlan_test.py
- io/net/vlan_test.py.data/vlan.yaml
changed name peer_ip to peer_public_ip
> changed name peer_ip in vlan_test

- ras/ServiceReport.py
- ras/ServiceReport.py.data/option.yaml
Added ServiceReport as a Test case , Later will enhance this test case
having more validation
> Added ServiceReport as a Test case

- io/disk/vfc-tests/virtual_fc.py
- io/disk/vfc-tests/virtual_fc.py.data/README
- io/disk/vfc-tests/virtual_fc.py.data/virtual_fc.yaml
Adding test script for vfc_unmap_map test. skeleton is all done.
ignore cosmetic changes. review the logic and flow of the script run.
And also point out if any major changes is required for the script to get merge.
> vfc_unmap_map test script

- generic/openblas.py
Issue #1569 - python environment slightly changes the environment
Adding the setting for power
> openblas fails to compile because of the environment

- io/net/bonding.py
- io/net/bonding.py.data/bonding_advance.yaml
bonding.py and bonding_adavance.yaml to test advance bonding
module parameter testing.
Author: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>
> enhancement of bonding test for extended module

- io/net/bridge.py
- io/net/bridge.py.data/bridge.yaml
test_bridge_create(),test_bridge_run(),test_bridge_delete()
Author: Vaishnavi Bhat vaishnavi@linux.vnet.ibm.com
> Rewrite the code with three different tests

- memory/ndctl.py
Patch adds test to validate numa of created namespace through ndctl and its sys interface
> Add test to check numa of created namespace

- memory/ndctl.py
- memory/ndctl.py.data/ndctl.yaml
support for using a different branch with ndctl upstream git repo.
> Nvdimm test update

- fs/xfstests.py
Using partition with nvdimm is not really recommended.
> xfstest: Use namespaces instead of partitions

- fs/xfstests.py
Patch enables
a) xfstest to run of legacy nvdimm hardware
b) handling logdevices with single region on non-legacy devices
c) clearing created devices
> Enable xfstest to run of legacy nvdimm hardware

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
changed infiniband test according to module hosts.py and interfaces.py.
> changed infiniband tests according to configure_network module changed

- io/net/Network_config.py
- io/net/bonding.py
- io/net/bridge.py
- io/net/ethtool_test.py
- io/net/htx_nic_devices.py
- io/net/iperf_test.py
- io/net/multicast.py
- io/net/multiport_stress.py
- io/net/netperf_test.py
- io/net/network_test.py
- io/net/switch_test.py
- io/net/tcpdump.py
- io/net/uperf_test.py
changing network test according to module hosts.py and interfaces.py.
> changing all network test according to configure_network module changed

- io/net/bonding.py
- io/net/bonding.py.data/bonding.yaml
- io/net/bonding.py.data/bonding_advance.yaml
- io/net/bonding.py.data/bonding_infiniband.yaml
- io/net/bonding.py.data/bonding_mode0.yaml
- io/net/bonding.py.data/bonding_mode1.yaml
- io/net/bonding.py.data/bonding_mode4.yaml
- io/net/bonding.py.data/bonding_single.yaml
- io/net/bonding.py.data/bonding_virtual.yaml
added mtu set and differnt yaml files are also added to the list to
address different scenario based testing for mode 0,1, and 4
Author: Vaishnavi Bhat vaishnavi@linux.vnet.ibm.com
> added mtu set for host and peer in bonding.py

- cpu/em_cpufreq.py
- cpu/em_cpuidle.py
- cpu/em_quad_level_frequency_transitions.py
- cpu/numatop.py
- cpu/ppc64_cpu_test.py
- generic/stressapptest.py
- kernel/kernbench.py
- perf/perf_24x7_all_events.py
- perf/perf_24x7_hardware_counters.py
- perf/perf_hv_gpci.py
- perf/perf_nest_events.py
- perf/perf_pcp.py
- perf/perf_rawevents.py
- perf/perf_watch_point.py
Cpu library is getting refactored through this
PR https://github.com/avocado-framework/avocado/pull/3350,
This PR modified respective test code to reflect the same.
Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
> Adopt cpu library changes [Waiting for utils]

- io/driver/driver_parameter_block_device.py.data/driver_parameter_block_device_lpfc.yaml
yaml file for lpfc driver for driver_module_parameter for block device
> yaml file for lpfc driver for driver_module_parameter for block device

- io/disk/disk_info.py
added support for multipath device nodes in disk_info tests.
Signed-off-by: Hariharan T S <hari@linux.vnet.ibm.com>
> Add support for multipath device nodes in disk_info

- io/net/bonding.py
- io/net/bonding.py.data/README.txt
- io/net/htx_nic_devices.py
- io/net/htx_nic_devices.py.data/README.txt
- io/net/multiport_stress.py
- io/net/multiport_stress.py.data/README.txt
- io/net/multiport_stress.py.data/multiport_stress.yaml
- io/net/multiport_stress.py.data/multiport_stress_virt.yaml
As decided to follow space separated input values passed to any test
made the changes and updated readme to follow the same
> changed input values to a common format

- io/driver/driver_parameter_block_device.py.data/driver_parameter_block_device_qla2xxx.yaml
yaml file for qla2xxx driver_parameter test
> yaml file for qla2xxx driver_parameter test

- io/net/virt-net/Network_virtualization_driver_bind.py
- io/net/virt-net/network_virtualization.py
chnaged ping_check and add_ipaddr by importing module.
> changed vnic test by importing hosts.py and interface.py

- io/net/virt-net/veth_dlpar.py
- io/net/virt-net/veth_dlpar.py.data/veth_dlpar.yaml
new test for veth dlpar operation.
> new test Veth Dlpar.

- io/disk/dlpar_vscsi.py
- io/disk/dlpar_vscsi.py.data/dlpar_vscsi.yaml
new test for dlpar operation of vscsi device.
> New test vscsi dlpar

- io/pci/distro_tools.py
- io/pci/distro_tools.py.data/README.txt
fixed distro_tools for different interfaces.
> fixed distro_tools for other interface type.

- memory/ndctl.py
Patch adds test to create namespace with supported sector, fsdax and devdax capabilities
> Add test to create namespace with supported capabilities

- io/driver/driver_parameter.py
- io/driver/driver_parameter.py.data/driver_parameter_mlx4_core.yaml
- io/driver/driver_parameter.py.data/driver_parameter_mlx4_en.yaml
- io/driver/driver_parameter.py.data/driver_parameter_mlx4_ib.yaml
- io/driver/driver_parameter.py.data/driver_parameter_mlx5_core_infiniband.yaml
- io/driver/driver_parameter.py.data/driver_parameter_mlx5_core_roce.yaml
Driver module parameters for Mellanox based adapters.
> Driver module parameters for Mellanox based adapters - v2

- cpu/em_quad_level_frequency_transitions.py
So inorder to support the above operator changed the testcase
> Got an error '<' not supported between instances of 'int' and 'str'

- io/disk/iozone.py
this patch will fix the issue
https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1642
Reported-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>
> Fixed iozone issue

- io/net/vlan_test.py
vlan tests check to CANCEL tests for IB.
> vlan tests check to CANCEL tests for IB.

- perf/perfmon.py
So added that package for rhel and suse
> perfmon.py: make command failed due to package issue

- io/driver/driver_parameter.py.data/driver_parameter_slate.yaml
driver parameter testing for slate
> adding param file for slate adapter

- ras/sosreport.py
According to that changed the script, to make sure test case should pass
> Ideally quiet option with -e should be NULL.Now its printing version

- ras/servicelog.py
Service repair action is failing due to wrong condition
check. So changed the condition check
> servicelog.py:service repair action is failing

- io/net/network_test.py
removed code duplication network_test.
> removed code duplication in script.

- ras/kretprobe.py
condition check is failing. So changed it
> kretprobe.py:Failing because of kretprobe probing issues

- io/net/network_test.py
fixed this error, ERROR: [Errno 2] No such file or directory:
'/sys/class/net/enP6p1s0f0/device/name'. by changing interface
directory.
> fixed network lro test.

- io/net/sriov_device_test.py
- io/net/sriov_device_test.py.data/README.txt
- io/net/sriov_device_test.py.data/sriov_device_test.yaml
test to add and remove sriov logical device.
> new test for network sriov device test

- io/disk/vfc-tests/virtual_fc.py
To fetch the HMC_IP using "lsrsrc IBM.MCP HMCIPAddr" command.
we need the src, rsct and Dynamic_RM packages to be installed.
so added this package installation.
> Adding src and rsct package installation in virtual_fc.py to get hmc_ip

- perf/perf_sdt_probe.py
Added library libc.so.6 to make memory_mallopt_mmap_max available
and added -o option for perf record to create an output file.
we should not create static/hard coded files.so,
created temp file and deleted at the end
> SDT marker sdt_libc:memory_mallopt_mmap_max not available

- io/net/bridge.py
after delete bridge interface also if we will do ifup bridge interface,
that interface is coming back.
> added code to remove bridge config file

- memory/memhog.py
- memory/memhog.py.data/memhog.yaml
Add memory hog test with RAM and file backed mmap
> Add memory hog test

- io/net/Network_config.py
network_config test fix for veth interfcae.
Reported-by Abdul Haleem abdhalee@linux.vnet.ibm.com
> fixed network_config test for veth interface.

- io/pci/dlpar.py
- io/pci/dlpar.py.data/dlpar.yaml
dlpar function is enhanced for sriov adapters
> dlpar for sriov adapter

- io/disk/dlpar_vscsi.py
- io/net/virt-net/network_virtualization.py
- io/net/virt-net/veth_dlpar.py
- io/net/virt-net/veth_dlpar.py.data/veth_dlpar.yaml
passwordless ssh vios for network_virtualization, veth_dlpar and
dlpar_vscsi test.
> passwordless ssh for vios

- io/net/virt-net/network_virtualization.py
- io/pci/dlpar.py
removed login() and run_command(), handle through ssh module
for running command on hmc in dlpar.py and network_virtualization.py
> passwordless ssh for hmc

- ras/packages.py
> Modified the testcase to use avocado library

- memory/ndctl.py
Patch adds necessary size checks for namespace creation and also educes to minimum size wherever possible.
> Add necessary size checks for namespace creation

- io/net/bonding.py.data/bonding_mode0.yaml
- io/net/bonding.py.data/bonding_mode1.yaml
- io/net/bonding.py.data/bonding_mode4.yaml
- io/net/bonding.py.data/bonding_single.yaml
- io/net/bonding.py.data/bonding_virtual.yaml
add peer_password to other yaml of bonding test.
> added peer_password parameter to yaml of bonding.

- io/disk/lvsetup.py
Using the loop device APIs to create and delete loop devices.
> lvsetup: Using loop device APIs

- io/net/iperf_test.py
- io/net/netperf_test.py
- io/net/network_test.py
- io/net/uperf_test.py
chnaged passwordless scp in iperf, netperf and uperf
> changed scp with passwordless scp to avoid ssh-keygen

- generic/ltp.py.data/ltp-net.yaml
> ltp-net.yaml : Adding Network related testcases from LTP.

- io/disk/vfc-tests/vfc_dlpar.py
- io/disk/vfc-tests/virtual_fc.py
- io/net/htx_nic_devices.py
- io/net/sriov_device_test.py
- io/net/virt-net/lpm.py
- io/net/vlan_test.py
passwordless ssh for vfc_dlpar.py,virtual_fc.py,lpm.py,vlan_test.py
sriov_device_test.py file.remove pxssh and handle through ssh.py
in htx_text to avoid password during package installation during test
handle through pxssh.
> passwordless ssh for network and disk test

- memory/ndctl.py
Patch adds new test case using alignment and size with write-infoblock command
> Add new tests with write_infoblock

- fs/flail.py
this PR fix issue https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1632
> Fix issue as due sed command was not proper

- kernel/kselftest.py
Patch optimizes kselftest with removal of few variables where are not needed.
> Optimise kselftest removing repetitive code

- perf/perf_hv_gpci.py
- perf/perf_pcp.py
- perf/perf_uprobe.py
Removed unused variables from the following files
perf_hv_gpci.py
perf_pcp.py
perf_uprobe.py
> Removed unused variables

- io/driver/driver_parameter.py.data/driver_parameter_ibmveth.yaml
yaml file for driver parameter test for ibmveth module
> yaml file for ibmveth driver.

- io/net/multiport_stress.py.data/multiport_stress_virt.yaml
updated peer public ip parameter according to other yaml files.
> updated peer public ip parameter in yaml

- io/disk/fiotest.py
Patch fixes fiotest by adding a new file variable for devdax devices
> Fix: Add special case for devdax device

- io/driver/driver_parameter.py
replace configure-network.py with new utils files under
avocado/avocado/utils/network.
> driver_parameter.py test changed with latest network utils

- io/disk/dbench.py
- io/disk/dbench.py.data/dbench.yaml
- io/disk/fs_mark.py
- io/disk/fs_mark.py.data/README.txt
- io/disk/fs_mark.py.data/fs_mark.yaml
- io/disk/iozone.py
- io/disk/iozone.py.data/README
- io/disk/iozone.py.data/iozone.yaml
- io/disk/ltp_fsstress.py
- io/disk/ltp_fsstress.py.data/ltp_fsstress.yaml
Test creates FS, LV software raid and runs test on them, as an option.
> added LV,FS and Software raid to dbench,fs_mark,iozone,ltp_fsstress

- io/disk/bonnie.py
- io/disk/bonnie.py.data/bonnie.yaml
- io/disk/ltp_fs.py
- io/disk/ltp_fs.py.data/ltp_fs.yaml
- io/disk/tiobench.py
- io/disk/tiobench.py.data/tiobench.yaml
it create lv,software raid and run test on them.
> added LV and software raid in tiobench,bonnie,ltp_fs

- perf/perf_core_imc_non_zero_event.py
Adding test cases for core IMC events, which shouldn't return zero values
> Add core IMC non zero event test cases

- io/pci/pci_hotplug.py
Using pci library to get slot name, instead of test finding it.
Also some pylint fixes
> pci_hotplug: Enhancements

- fs/xfstests.py.data/xfstests_disk.yaml
in xfstests test make separate yaml for block device.
> make separate yaml for block devices

- memory/mm_subsystem.py
- memory/mm_subsystem.py.data/mm_subsystem.yaml
Patch adds test which focuses on specific tests in areas on memory subsystem
> Add tests focusing specific areas in memory subsystem

- security/selinux-tests.py
security/selinux-tests.py adds selinux-testsuite tests
> Adding selinux-testsuite tests

- security/audit-tests.py
security/audit-tests.py adds audit-testsuite tests
> Adding audit-testsuite tests

- io/net/virt-net/lpm.py
RMC service is must for migration to happen, make sure it gets
activated while or in between the test
> Start RMC services before migration

- security/cryptsetup-tests.py
security/cryptsetup-tests.py adds cryptsetup tests
> Adding tests of cryptsetup

- io/net/ethtool_test.py.data/ethtool_scenario.yaml
use the below option with HTX
--set-priv-flags and -w|--get-dump
> yaml file for scenario related to ethtool commands

- security/seccomp-tests.py
security/seccomp-tests.py adds cryptsetup tests
> Adding tests of seccomp

- security/libkcapi-tests.py
- security/libkcapi-tests.py.data/test_name.yaml
security/libkcapi-tests.py adds libkcapi tests
> Adding tests of libkcapi

- security/krb5-tests.py
security/krb5-tests.py adding Kerberos unit tests
> Adding kerberos tests

- security/pam-tests.py
security/pam-tests.py Adding Pluggable Authentication Module
tests
> Adding PAM tests

- security/openssl-tests.py
Adding tests from openssl, to run unit tests cases
> Adding tests from openssl

- security/openssh-tests.py
security/openssh-tests.py: adding openssh unit tests
> Adding openssh tests

- security/xmlsec-tests.py
security/xmlsec-tests.py adding XMLSec unit tests
> Adding XMLsec tests

- memory/ndctl.py
Patch adds test for dimm health check
> Add test for dimm health check

- perf/perf_script_bug.py
- perf/perf_script_bug.py.data/probe.cfg
changed the probe command according to that
> perf_script_bug.py:perf probe is failing

- generic/ltp.py
- generic/ltp.py.data/ltp.yaml
Added check that user can provide there hosted ltp url
> Extend LTP test that it can take url based ltp url

- io/driver/driver_parameter.py.data/driver_parameter_ixgbe.yaml
added ixgbe driver in to driver parameter test.
Signed-off-by: Bismruti Pattjoshi <bismruti@oc7660885027.ibm.com>
> ixgbe driver yaml for driver_parameter test

- io/driver/driver_parameter.py.data/driver_parameter_i40e.yaml
- io/driver/driver_parameter_block_device.py.data/driver_parameter_block_device_mpt3sas.yaml
make yaml for i40e and mpt3sas driver for driver_parameter.py and
driver_parameter_block_device.py
> i40e and mpt3sas driver yaml added for driver_parameter test

- ras/sosreport.py
Fixed failues in --build, --batch and --tmp commands.
> Fixed failures is few commands - v4

- perf/perf_duplicate_probe.py
Changed the event a/c to that in script
> Fail to add this event 'perf probe select_task_rq_fair:15'

- io/driver/driver_parameter_block_device.py.data/driver_parameter_block_device_ipr.yaml
driver_parameter_block_device_ipr.yaml added to driver_parameter_block_device.py
> ipr yaml for driver parameter test

- toolchain/libpfm.py
libpfm version changed from 4.9.0 to 4.10.1
> libpfm 4.10.1

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
- io/net/iperf_test.py
- io/net/iperf_test.py.data/README.txt
- io/net/iperf_test.py.data/iperf_test.yaml
- io/net/iperf_test.py.data/iperf_virt_test.yaml
- io/net/netperf_test.py
- io/net/netperf_test.py.data/netperf_test.yaml
- io/net/netperf_test.py.data/netperf_test_virt.yaml
- io/net/uperf_test.py
- io/net/uperf_test.py.data/README.txt
- io/net/uperf_test.py.data/uperf_test.yaml
- io/net/uperf_test.py.data/uperf_test_virt.yaml
using peer_user consistently across scripts
> changing peer_user_name to peer_user

- nx_gzip/nx_gzip.py
- nx_gzip/nx_gzip.py.data/nx_gzip.yaml
Test cases for nx-gzip feature.
> Added nx-gzip test cases.

- io/net/virt-net/network_virtualization.py
check dmesg error if any after test complete.
Signed-off-by: Bismruti Pattjoshi <bismruti@oc7660885027.ibm.com>
> add utils dmesg to vnic test

- io/net/virt-net/lpm.py
colletc dmesg error in the end of the test if any.
Signed-off-by: Bismruti Pattjoshi <bismruti@oc7660885027.ibm.com>
> add dmesg utils module to lpm test

- memory/ndctl.py
Patch adds test for configuring devdax device as system-ram and tries to hotplug/unplug after device is configured
> Add test for devdax device memory hotplug/unplug

- io/net/iperf_test.py
> adding tcp check after performance test

- io/disk/fiotest.py
Patch fixes configuration of pmem engines to be installed and run independently
> Fix pmem engines configuration for FIO

- io/net/virt-net/lpm.py
- io/net/virt-net/lpm.py.data/README.txt
- io/net/virt-net/lpm.py.data/lpm.yaml
- io/net/virt-net/lpm.py.data/lpm_withsriov.yaml
- io/net/virt-net/lpm.py.data/lpm_withvnic.yaml
Make sure the same script works for non vnic lpm runs, added
few yamls specific to basic and sriov lpm scenarios.
> Modify LPM test to work for basic and sriov options

- perf/perf_24x7_hardware_counters.py
changes made to the perf events to support on latest processor
Signed-off-by: Debaleena De <debade33@in.ibm.com>
> perf_24x7_hardware_counters.py: changes made to support latest processor

- ras/ras.py
changes made to eliminate ofpathname error
Signed-off-by: Debaleena De <debade33@in.ibm.com>
> ras.py: changes made to eliminate ofpathname error

- generic/service_check.py
- generic/service_check.py.data/services.cfg
changes made to eliminate the service check error
Signed-off-by: Debaleena De <debade33@in.ibm.com>
> service_check.py:changes made to eliminate the service check error

- io/net/bonding.py
- using bringup() from interface utility
- deleting ifcfg-bond file post test created during setup
> bug fix for bonding.py

- security/evmctl-tests.py
> evmctl-tests.py Adding ima-evmctl tests

- generic/interbench.py
Older URL is not working,so changed the URL
> interbench.py:Changed the URL as old one is not working

- cpu/cpupower_monitor.py
Added comments describing the testcases.
> Added comments for testcases.

- memory/ndctl.py
Patch handles kernel with no region alignment attribute and also uses LCM of mapping alignment and size alignment (region attr) to determine the size align value for a namespace
> ndctl.py: Handle kernel with no region alignment

- memory/soft_dirty.py
Patch adds test for soft dirty bits stability
> Add test for soft dirty bits stability

- memory/migrate_pages.py
- memory/migrate_pages.py.data/node_move_pages.c
Patch handles return code if test needs to skip
> migrate_pages.py: Handle return code if test needs to skip

- io/net/sriov_device_test.py
Removing hard coding of server name.
> bug fix for hnv_add script

- perf/trace.py
- perf/trace.py.data/trace.yaml
Added ftrace test cases from selftests
> trace: ftrace selftests

- io/net/infiniband/ib_pingpong.py.data/ib_pingpong_infiniband.yaml
- io/net/infiniband/ib_pingpong.py.data/ib_pingpong_roce.yaml
Added new tool xsrq_pingpong to pingpong tests.
> Added xsrq_pingpong tests to pingpong.

- generic/stressapptest.py
Added gcc-c++ package to the script in order to
compile the libraries
> fixing error: C++ compiler cannot create executables

- io/net/virt-net/lpm.py
- io/net/virt-net/network_virtualization.py
…by level
made changes in network_virtualization.py and lpm.py by passing skip messages
for remove while checking dmesg error by level.
> added messages to skip in dmesg error,while checking for dmesg error

- ras/sosreport.py
Added condition in the script according to rhel8.4 changes
> Modified sosreport command to "sos report" based on new changes in 8.4

- io/net/bridge.py
- io/net/bridge.py.data/bridge.yaml
- bridge enhancement to accept more than one interface
- cleanup of code in few areas.
> bridge enhancement to take more than one interface

- cpu/producer_consumer.py
Patch adds result parsing and stores it to json file
> producer-consumer.py: Parse results, store in json

- perf/rt_tests.py
- perf/rt_tests.py.data/rt_tests.yaml
Replaced the old tar with newer one in rt_tests.py and updated yaml file.
> Changed the value of tarball to newer tar also added option to yaml

- generic/openblas.py
gcc 10 would be required for power10 flags which is not there as
part of distro. So added extra args TARGET=POWER9 for fixing this
> openblas.py: fixing make command for Power10

- perf/compilebench.py
- perf/compilebench.py.data/fix_compilebench
Added patch file for python3 compilebench code
> compilenench.py:Changing compilebench code from python2 to python3

- toolchain/strace.py
New test for strace a Linux command line utility.
Strace is a command line utility in Linux used for diagnosis and debugging.
This test downloads the source code, compiles it and finally
invokes the built-in tests.
> New test for strace a Linux command line utility.

- cpu/schbench.py
Patch adds parsing the important heuristics of the schbench and store it as json
> schbench.py: Add parsing to schbench test

- cpu/ebizzy.py
- cpu/ebizzy.py.data/ebizzy.yaml
Patch adds iterations of ebizzy run and store logs for each iteration
> ebizzy.py: Add iterations for ebizzy run

- cpu/em_cpuidle.py
- cpu/sensors.py
added skip message as this test is not supported on
power vm platform
> Added code to skip the testcase on Power VM machine

- kernel/kselftest.py
- kernel/kselftest.py.data/kselftest_comp.yaml
OS sub-component level kselftest yaml added.
> Added kselftest yaml file.

- cpu/pvr.py
- cpu/pvr.py.data/pvr.cfg
Fixed p9 dd2.1 pvr value and p10 revision issue
> Fix for pvr issues on p9, p10

- perf/perf_duplicate_probe.py
Fix logical condition to find out multiple probes
> perf_duplicate_probe.py: fix logical condition

- generic/criu.py
- generic/criu.py.data/version.yaml
Added proper checking for pass/fail criu test cases
> Fixed criu tests false passes

- generic/ltp.py
In order to make sure network related testcases works fine,
added iputils package which contains network tools for IPv4 and IPv6
> ltp.py: Added iputils package to SuSE

- cpu/xive.py
Added new test cases for XIVE feature
> XIVE test cases

- ras/rtas_dbg.py
- ras/rtas_dbg.py.data/options.yaml
Tests the rtas_dbg command with a list of command line arguments
> Added rtas_dbg tests

- security/nettle-tests.py
Add Nettle crypto library test cases
> nettle-tests.py: Add Nettle crypto library tests

- cpu/numatop.py
Added libtool and autoconf packages.
> Fixed numatop compilation error due to missing packages.

- toolchain/oprofile.py
call perf if os is rhel
Signed-off-by: Preeti Thakur <preetithakur@Preetis-MacBook-Pro-2.local>
> profile replace by perf

- ras/ras_tools.py
- ras/ras_tools.py.data/options.yaml
Added nvsetenv,usysattn and usysfault test cases
> Added few ras tools tests

- ras/smtstate.py
This script tests smtstate tool for all smt states.
> Added testcase for smtstate tool- v2

- security/libkmip-tests.py
Add libkmip tests from OpenKMIP
> Add libkmip tets

- ras/lparnumascore.py
- ras/lparnumascore.py.data/options.yaml
Tests the lparnumascore command with a list of command line arguments
> Added lparnumascore tests

- cpu/pvr.py
Fixed PVR issues on P9 pSeries and PowerNV. Changed
the conditions according to that
> pvr.py: Fixing PVR issues on p9

- perf/perf_cpu_hotplug.py
Added condition check to support only on Power10
> perf_cpu_hotplug.py: Supports only on Power10

- ras/sosreport.py
Added proper checking for sosreport skip and only plugin options
> Fixed sosreport tests false passes

- ras/ras_tools.py
Added proper checking for ras tools
> ras_tools.py: Fix for false checking

- ras/vpa_MaxMem_check.py
Tests whether files are generated for all cpu's and
maximum memory values are same or not
> Added tests for raw per-cpu VPA data, maximum memory value via debugfs

- toolchain/ltrace.py
- toolchain/ltrace.py.data/ltrace.yaml
fixed style issue
Patch address issue ltarce upstrem URL not working
> Ltrace fix

- io/net/tcpdump.py
increase the nping value when count is less than 5
> increase nping count

- io/net/bonding.py
Bug fix for issue
https://github.com/avocado-framework-tests/avocado-misc-tests/issues/2032
> ssh control file check for bonding test

- nx_gzip/nx_gzip.py
Added "SuSE" support for nx-gzip tests.
> Add SLES support.

- gpu/README.md
- gpu/gpu.py
- gpu/gpu.py.data/Makefile
- gpu/gpu.py.data/xgemm.c
GPU cuda level testing and other gpu test cases added.
> Adding GPU test cases

- dlpar/README.md
- dlpar/config/tests.cfg
- dlpar/cpu_unit.py
- dlpar/dedicated_cpu.py
- dlpar/dlpar_api/api.py
- dlpar/dlpar_api/config.py
- dlpar/dlpar_api/pexpect.py
- dlpar/dlpar_api/pxssh.py
- dlpar/dlpar_main.py
- dlpar/dlpar_main.py.data/dlpar.yaml
- dlpar/memory.py
Dlpar cpu/memory test cases which coveres ded/shared lpar configuration with add/remove/move dlpar operations.
> Added dlpar cpu/memory test cases

- perf/perf_basic.py
Test failed when running test_perf_cmd_annotate, 
test_perf_cmd_evlist, test_perf_cmd_script individually.
Run perf record first to ensure that perf.data exists.
Signed-off-by: katrinzhou <katrinzhou@tencent.com>
> perf_basic.py: perf.data does not exist when running test individually

- toolchain/binutils.py
- toolchain/binutils.py.data/binutils.yaml
package updated to 2.37 in both py and yaml file
Signed-off-by: Preeti Thakur <preetithakur@Preetis-MacBook-Pro-2.local>
> binutil package verison update

- perf/perf_bench.py.data/bench_options.yaml
added new perf bench sub commands and their
functions in yaml file
> added new perf bench parameters in yaml file

- toolchain/valgrind.py
- toolchain/valgrind.py.data/valgrind_source.yaml
updated to latest release (3.18.1)
Signed-off-by: preeti thakur <preeti.thakur@in.ibm.com>
> updated to latest

- toolchain/gdb.py
makeinfo package removed from gdb
> makeinfo removed

- kernel/livepatch.py
> Fix for make command failed issue

- io/net/iperf_test.py
updating gcc-c++ packages in the list for
iperf package to compile successfully
> updating package in the pkg list

- memory/memhog.py
> Fix for memhog.py compilation failed issue

- cpu/cpuidle-latency.py
> Fix for cpuidle-latency.py test 'make' command fail

- io/driver/driver_parameter_block_device.py.data/driver_parameter_block_device_nvme.yaml
Added yaml file with different parameters and values for nvme module
to test different parameter of module by changing their values with
unload and load of module.
> Added yaml file for nvme module to test driver_module_parameters

- ras/uprobe.py
Code optimization for uprobe.py,
The enable_uprobes and disable_uprobes functions have been removed and a single function has been added to control uprobes.
Added support for handling system exceptions while writing data into the /sys/kernel/debug/tracing/ uprobe_events and other files
> Code optimization for uprobe.py test script.

- cpu/em_cpuhotplug.py
In present implementention for CPU online and offline function in utils/cpu.py file below cases are present,
online function implementation:
Case-1: In case the CPU is already online, it will return 1 if it is.
Case-2: Upon checking CPU status if the CPU is offline, we write 1 into the "online" file. Then, after writing into the "online" file, we check if the CPU is online and if it is, we return 0.
-> Above two different cases we are returning 1 & 0 when our CPU is online.
Note: Logically when the CPU is online it should return 1.
Added code changes to utils/cpu.py in order to return 1 when CPU is
online.
To support above code changes added support in em_cpuhotplug.py.
> Fix for em_cpuhotplug.py Test failing issue.

- io/net/uperf_test.py
nping with tcp packets is done after uperf test.
> uperf test followed by nping

- security/openssl-tests.py
> Fix for openssl-tests.py test issue

- kernel/kselftest.py
- kernel/kselftest.py.data/README
- kernel/kselftest.py.data/ksmtest.yaml
> Added test support for ksm_tests.c

- io/net/iperf_test.py
NIC : iperf local variable 'tput' referenced before assignment
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
[root@ltcrain41-lp4 net]# avocado run --test-runner runner iperf_test.py -m iperf_test.py.data/iperf_virt_test.yaml
JOB ID     : 0143a7cff6751bbacd0d5b58105327bdfd551e26
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-04-06T08.34-0143a7c/job.log
(1/2) iperf_test.py:Iperf.test;run-hbond-mtu-1500-0b8a: PASS (64.69 s)
(2/2) iperf_test.py:Iperf.test;run-hbond-mtu-9000-96d2: PASS (76.30 s)
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-04-06T08.34-0143a7c/results.html
JOB TIME   : 142.34 s
Attaching job.log
[iperf.log](https://github.com/avocado-framework-tests/avocado-misc-t …
> Iperf not executing

- io/net/ethtool_test.py
- io/net/ethtool_test.py.data/ethtool_test.yaml
ethtool -l
ethtool -L ethx tx [N] rx [N]
Signed-off-by: Tasmiya Nalatwad <tasmiya@li-bed3e0cc-3595-11b2-a85c-d36089afee59.ibm.com>
> Including the set-channel options in the ethool test

- io/net/ethtool_test.py
- io/net/ethtool_test.py.data/ethtool_test.yaml
Reverts avocado-framework-tests/avocado-misc-tests#2268 as all eth tool test is failing ,
> Revert "Including the set-channel options in the ethool test"

- io/net/virt-net/network_virtualization.py
adding wait for connecting to hmc session.
> adding wait for hmc session

- ras/smtstate.py
Moved Print statement to logger as it will log statemnt in logger file
> Style Fixes

- security/seccomp-tests.py
As libseccomp master branch moved as main branch
test failed to get test files
> Fixed url issue

- generic/service_check.py
distro_version is string, one should cast it to int before comparing with integers
> Fix distro version comparison in service_check

- io/net/ethtool_test.py
- io/net/ethtool_test.py.data/ethtool_test.yaml
ethtool -l
ethtool -L ethx tx [N] rx [N]
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
> Included the ethtool -l and ethtool -L options

- memory/ndctl.py
Commit 26b9f92(enable support for meson build) unconditionally fails
the tests when using upstream as a target. Remove this restriction
for releases that ship iniparser package.
Additionally the code in autotools_build_system unconditionally
copies iniparser headers to required directory. This copy operation
fails on releases that ship these headers. Add a check for such releases
and skip the copy operation to avoid test failures.
> memory/ndctl: Correct iniparser header dependency

- generic/rcutorture.py
Took the source code to get the rcutorture module
and compiled it to run the test
Signed-off-by: Akanksha J N <akanksha.j.n@ibm.com>
> Resolved ERROR"Command '/sbin/modinfo rcutorture' failed

- io/net/virt-net/network_virtualization.py
vnic dlpar with hmc cli commands. Existing dlapr
test is with drmgr commands only. Adding a new test
for testing dlpar operation with hmc cli way.
> vnic dlpar with hmc cli

- memory/transparent_hugepages_defrag.py
Allocated 75% of the memory from available free memory space to the mounted file system, Ex: tmpfs
In order to avoid the low memory issue,  Added support.
Furthermore, it avoids the dd command fail issue (), where it doesn't have enough space to defragment the memory.
> Fix for THP Test cases failing issue.

- toolchain/papiTest.py
- toolchain/papiTest.py.data/papiTest.yaml
updated URL for Papi in script
Signed-off-by: preeti thakur <preeti.thakur@in.ibm.com>
> updated URL for papi

- memory/vatest.py.data/va_test.c
With older implementations, MAP_CHUNK_SIZE is fixed to 16 GB, as a
result fix value, On low memory the test case is getting failed with
ENOMEM error message where it clearly indicates that not enough memory
is present in the system, which results in a few va_test cases failing.
The above changes will dynamically adjust the MAP_CHUNK_SIZE value
according to the amount of space in the system.
> Done rework for va_test.c

- io/disk/ltp_fs.py
- io/disk/ltp_fs.py.data/ltp_fs.yaml
enhancing yaml and the code to handle the proper cleanup after
each test varient runs.
> Resolving cleanup issue and enahncing yaml in ltp_fs.py

- io/disk/tiobench.py
- io/disk/tiobench.py.data/tiobench.yaml
script was not properly cleaning up while exiting
after each varient runs. so fixing it.
> Resolving cleanup issue on tiobench.py

- io/disk/disktest.py
- io/disk/disktest.py.data/disktest.yaml
Added softwareraid supportd and fixed the cleanup issue
and script is working fine now.
> Enhancing and fixing cleanup issue on disktest.py

- io/disk/fs_mark.py
- io/disk/fs_mark.py.data/fs_mark.yaml
Resolving the cleanup issue and enhancing the yaml and other
internal runs for fs_mark bench mark tool
> Enhancing the fs_mark.py and resolving cleanup issue resolve

- ras/ras_extended.py
- ras/ras_extended.py.data/options.yaml
Checking to turn on device identify indicators and other help
options of usysident
> ras_extended.py: Added test to verify usysident functionality

- generic/htx_test.py
- Provided support for picking up the latest available htx version
for the respective distro.
- Added a function install_latest_htx_rpm() for the same.
> Automated htx installation

- ras/ras.py
Verifying the lsmcode output by checking for FW, added a condition check
> ras.py: Verify lsmcode output by grep FW

- security/kernel-hardening-tests.py
Add kernel hardening configuration check tests.
> kernel-hardening-tests.py: Add kernel hardening config check test

- perf/perf_hv_gpci.py
added new parameter ids for perf hv_gpci
removed cpu dependency
RHEL 9.1
avocado run --test-runner runner perf_hv_gpci.py
JOB ID     : 9a574faae5a857e7124c29179e6eddd4ffc606f8
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-06-13T17.02-9a574fa/job.log
(1/1) perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: PASS (226.49 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-06-13T17.02-9a574fa/results.html
JOB TIME   : 273.18 s
RHEL 9.0
avocado run --test-runner runner perf_hv_gpci.py 
JOB ID     : d5c66afe5947a6b0f8a1f5140856a76029bfb853
JOB LOG    : /home/disha/avocado-fvt-wrapper/results/job-2022-06-13T18.15-d5c66af/job.log
(1/1) …
> enhance perf_hv_gpci

- security/ima-evm-utils-tests.py
- security/ima-evm-utils-tests.py.data/README.txt
- security/ima-evm-utils-tests.py.data/imaevmutils.yaml
Add ima-evm-utils test case for distribution and upstream
> ima-evm-utils-tests.py: Add ima-evm-utils test case

- security/fsverity-tests.py
- security/fsverity-tests.py.data/README.txt
fsverity tests verifies the integrity/authenticity associtated
with the file.
> fsverity-tests.py: Add fsverity test cases

- security/fscrypt-tests.py
- security/fscrypt-tests.py.data/README.txt
Adding fscrypt tests, fscrypt is a tool for managing Linux file system
encryption
> fscrypt-tests.py: adding test

- io/net/infiniband/dapl.py
Making the remote peer connection once the host interfaces are up
> Fixing failed connecting to peer issue

- ras/sosreport.py
This code tests the sosreport with different smt levels ie., 2, 4, 8 and off
> sosreport.py: Test the sosreport with different smt levels

- memory/stressng_mem.py
- memory/stressng_mem.py.data/README
- memory/stressng_mem.py.data/stressng_mem.yaml
- adding a new file by the name stressng-mem.py.
- added logic for downloading the source, building & installing stress-ng.
- added logic to calculate extra time & set the variable run time in the calculate_variable_time() method.
- added the core stress logic in the execute_stressor() routine to handle execution of each stressor
- added process_looping() routine to loop the list of stressors.
- added yaml file : stressng_mem.py.data/stressng_mem.yaml
- added README file : stressng_mem.py.data/README
> memory/stressng_mem.py: adding new test for stress

- memory/page_table.py
- memory/page_table.py.data/page_table.yaml
* Test will detect CPU feature i.e la57.
* Check for kernel support
* Run series of 5-level page tests from "pg-table_tests.git" that covers
- heap, mmap, shmat tests.
> memory: Add 5-level page table tests

- dlpar/config/cpu_fold.sh
- dlpar/config/smt.sh
- dlpar/config/tests.cfg
- dlpar/dedicated_cpu.py
- dlpar/dlpar_main.py
- dlpar/dlpar_main.py.data/dlpar.yaml
- dlpar/dlpar_workload_setup.py
Added support for below test case,
1. Dedicated mode: proc dlpar add, remove, move and mix operation with smt, cpu_fold workload.
2. shared mode: proc dlpar add, remove, move and mix operation with smt, cpu_fold workload.
3. Dedicated mode: memory add, remove and mix operation with smt, cpu_fold workload.
4. shared mode: memory add, remove and mix operation with smt, cpu_fold workload.
Fixed bugs from dedicated_cpu.py and dlpar_main.py modules.
Signed-off-by: Samir <samir@linux.vnet.ibm.com>
> DLPAR test case.

- cpu/stressng_cpu.py
- cpu/stressng_cpu.py.data/README
- cpu/stressng_cpu.py.data/stressng_cpu.yaml
- adding a new file by the name stressng-cpu.py for stressing the CPU
- added yaml file   : stressng_cpu.py.data/stressng_cpu.yaml
- added README file : stressng_cpu.py.data/README
> cpu/stressng_cpu.py: adding test for cpu stress

- cpu/cpupower_monitor.py
This test verifies cpupower idle-info with different smt states. Prints the duration for which CPUs are in snooze and CEDE state.
> Test verifies cpupower idle-info with different smt states - v2

- io/disk/vfc-tests/vfc_dlpar.py
- io/disk/vfc-tests/virtual_fc.py
Corrected few spelling mistakes in log.info
messages
> vfc: Correct spelling typos

- io/net/virt-net/network_virtualization.py
Fixing below issues:
- vnic backing device remove failure is seen when auto failover test is run for odd timings. Addressing this issue by setting back the priority
- Setting back original priorities after vnic auto failover which sets the priority to 1 and 100
- Seeting back active interface in teardown after every tests
> Bug fix for vnic backing device remove failure and vnic auto failover

- ras/sosreport.py
This code tests the sosreport after dlpar cpu/mem add remove
> sosreport.py: Test the sosreport after cpu, mem dlpar operations

- ras/supportconfig.py
This code tests the supportconfig after dlpar cpu/mem add remove
> supportconfig.py:Test the supportconfig after cpu, mem dlpar operations

- ras/sosreport.py
This code tests the sosreport while making cpu's
offline and online
> sosreport.py: Tests the sosreport while running cpufold

- ras/supportconfig.py
This code tests the supportconfig while making cpu's offline and online
> supportconfig.py:Tests the supportconfig while running cpufold

- ras/smtstate.py
- ras/smtstate.py.data/smtsate.yaml
- Added a new test "test_smt_state_switching" to validate the time taken for switching between different SMT levels
- Added a yaml file: smtstate.py.data/smtstate.yaml
> ras/smtstate.py: Added new test

- io/disk/htx_block_devices.py
- io/disk/htx_block_devices.py.data/Readme.txt
- io/disk/htx_block_devices.py.data/htx_all_devices.yaml
- io/disk/htx_block_devices.py.data/htx_block_devices.yaml
modified the script so that it support the rpm based install of htx tool and some other script enhancements.
> Enhancing the htx_block_device.py to support rpm based install

- cpu/xive.py
- test_verify_xive_cmdline: test that verifies whether xive is enabled through the kernel command line.
- test_verify_xive_config: test that verifies whether xive is enabled based on the config parameters
> cpu/xive.py: Added new tests

- cpu/numactl.py
- cpu/numactl.py.data/README.txt
- cpu/numactl.py.data/numa_fc.yaml
- cpu/numactl.py.data/numa_network.yaml
Patch for newly added test cases for NUMA FC and PCI devices.
> NUMA support for Network and PCI device [waiting utils #5513]

- ras/ras_lsvpd.py
- ras/ras_lsvpd.py.data/ras_lsvpd.yaml
Add capabilities to download and compile upstream source for
lsvpd tool.
> ras/ras_lsvpd: Add upstream as a target

- cpu/numactl.py
commit 611b2ed added support for Network and FC devices. While doing so
it changed the default behaviour of existing test. If no yaml input is provided
the test now cancels all sub-tests.
Introduce checks for various yaml parameters and skip corresponding tests
if one or more required paramter is missing.
> cpu/numactl: Add checks for missing parameters

- ras/sosreport.py
- ras/sosreport.py.data/options.yaml
This code creates different file systems and collects the sosreport
> sosreport.py: Taking the sosreport for different file systems

- security/libkmip-tests.py
libkmip tests under security subdir fails to execute when using distro
as a run_type. The test only installs corresponding source package
but is missing steps to compile the code.
Add the corresponding steps to compile the source code before
attempting to run the self tests. Additionally depending on KMIP
version tests binary can be present in different directory. Handle
it by adding check for tests binary.
> security/libkmip: Fix failure for distro as run_type

- cpu/xive.py
- Added fix for test_storeEOI.
- This fix handles a scenario wherein the store-eoi flag is identified either by using the ipis file or the interrupts file, whichever available.
- These files are checked under the following path: "/sys/kernel/debug/powerpc/xive/"
> cpu/xive.py: Fixed test_storeEOI for SLES15.x

- kernel/kselftest.py.data/kselftest_powerpc.yaml
kselftest yaml to support testing powerpc
Signed-off-by:Spoorthy S<spoorts2@in.ibm.com>
> Adding kselftest for powerpc

- io/disk/rawread.py
self cancel test if disk is not provided in yaml file in rawread.py test.
> Cancel test if disk not provided

- toolchain/gdb.py
> Fix Travis issue

- memory/fork_mem.py.data/forkoff.c
Adding the condition to check for the Maxpid supported on the system.
> Adding the condition to check for the Maxpid supported on the system.

- cpu/em_cpufreq.py
Recent versions of ppc64_cpu utility displays average cpu
frequency in a different way :
avg	:	3.059 GHz
This breaks the existing parsing logic to identify freq_read
value and results in a testcase failure:
ERROR: could not convert string to float:  (7.02 s)
Change the parsing logic to match the avg frequency o/p string
> cpu/em_cpufreq: Improve parsing logic

- generic/rcutorture.py
This makes sure rcutorture_test module can be loaded
and Hotplug only supported cpu's.
> Rcutorture test fixes

- ras/ras_lsvpd.py
as last two test case need pciutils should be installed
> Added  pciutils as package requirment

- io/net/infiniband/udaddy.py
Making the class name to Udaddy
> Correcting the spelling of the class name

- dlpar/dlpar_api/api.py
- dlpar/dlpar_main.py
Below code changes are done,
1. A separate test function has been added to execute CPU add, remove, and move operations separately.
2. Removed Dedicated mode reconfiguration code.
> DLPAR CPU operations have been enhanced.

- perf/perf_duplicate_probe.py
- perf/perf_script_bug.py
- trace/trace_UDT_probes.py
Changing class and definition names of the scripts as per the test case name.
> Change class and definition names to unique name

- ras/ras_lsvpd.py
lsmcode output validation is failing on PowerNV. So added a condition check which will take care of both PowerVM and POWERNV
> lsvpd.py: FAIL: lsmcode command failed in verification

- dlpar/dlpar_api/api.py
- dlpar/dlpar_main.py
Below code changes are done.
1. A proper message was added to cancel the test in case of a failed SSH connection.
2. A proper error message has been added to detect a failed DLPAR operation command.
3. Separate memory dlpar operation with proper error messages added.
> Improved error handling capability for DLPAR.

- memory/dma_memtest.py.data/README.md
Adding a README.md for dma_memtest
> Add README.md for dma_memtest

- security/kernel-lockdown-tests.py
> kernel-lockdown-tests.py: Add Kernel Lockdown test

- memory/eatmemory.py.data/README.md
Add README.md for memory/eatmemory.py test
> README: Add README.md for eatmemory test

- memory/hugepage_sanity.py.data/README.md
Add README.md for memory/hugepage_sanity.py test
> README: Add README.md for hugepage_sanity test

- io/pci/EEH.py
EEH failures are addressed with this change
> EEH Block device test for all devices

- io/pci/EEH.py
EEH for block devies are updated. Added validation to check multipath devices
after EEH.
EEH for block devies are updated. Added validation to check multipath devices after EEH.
> EEH for block devies are updated. Added validation to check multipath devices [wait for #5632]

- io/disk/htx_block_devices.py
HTX is successful on SUSE. Updated source as per PEP8 standards.
> HTX support for SUSE

- ras/ras_ppcutils.py
Added a new testcase to validate below two
1.laprstat -E output %busy and %idle should not be < 0 and > 100 
2.Normalized %busy + %idle = percentage under frequency
> ras_ppcutils.py: Validating lparstat functionality

- workload/cpu_fold.py
- workload/cpu_fold.py.data/cpu.sh
- workload/smt.py
- workload/smt.py.data/smt.sh
1. Added a new test case to run SMT workload as a daemon process.
2. Added a new test case to run CPU workload as a daemon process.
> Added SMT, CPU workload support for different components(Ex: DLPAR)

- ras/ras_ppcutils.py
Testcase checks for number of physical processors consumed on different smt levels
> ras_ppcutils.py: Added test which checks for physical processors consumed

- workload/cpu_fold.py.data/cpu.sh
Removed unused variables from for loop and assigned correct variables to online and offline variables. Ex: total_cores
> Fixed bug from cpu_fold workload. (Removed unused variable from cpu.sh)

- io/net/htx_nic_devices.py
Properly adding the hostname entries to the /etc/hosts file in host lpar and copying the same to peer lpar
> Fixing the issue with hostname entries being added

- ras/ras_ppcutils.py
Added a condition check which validates lpar's
security flavor is correct or not.
> ras_ppcutils.py: Validating lparstat -x option

- memory/homenode.py
- memory/homenode.py.data/homenode.c
- memory/homenode.py.data/homenode.yaml
This commit adds the option to choose preferred/home node. Necessary changes are made in homenode.c and homenode.py In yaml file the parameter to chose home node is added.
> Add option to choose preferred/home node

- io/pci/pci_hotplug.py
Added the new method for validating the nvme adapter functionality and status after pci_hotplug.
> Adding nvme validation in pci_hotplug.py

- io/net/sriov_device_test.py
Made changes to the script code inorder to add the basic SRIOV VF ports other than the veth and vnic backing devices
> Code to add the basic SRIOV VF ports

- io/disk/ssd/nvmetest.py
- io/disk/ssd/nvmetest.py.data/nvmetest.yaml
current test cases doesn't has any test that can create with given count so adding same to validate.
> Adding new subtest to create n number of namespaces in nvmetest.py

- io/pci/dlpar.py
- io/pci/dlpar.py.data/dlpar.yaml
added the validation of adapter functionalities after dlpar operation is performed like checking multipath state for FC, ping for n/w adapters, namespace status for nvme etc.
> Added the validation of adapters functionalities after dlpar test

- memory/numa_test.py
numa_test test_thp_compare cancels even when thp is enabled on the system. Correcting the sysfs file path and approach to cancel test.
CANCEL: THP migration is not enabled on the system.
> Test numa_test with thp cancels in all cases

- ras/smtstate.py
Fixed the object has no attribute error by fixing if condition
> smtstate.py: Fixing 'smtstate_tool' object has no attribute 'time_in_seconds

- perf/perf_pmu.py
This script allows a non root user to execute perf commands and has
checks in place to add such a non root user if it does not exist.
There are places where certain action is taken assuming such a non root
user exist. Update this logic to avoid runtime error if user does not exist.
> perf/perf_pmu: Handle non root user creation

- nx_gzip/nx_gzip.py
test_dictionary, test_kself_nxgzip, test_numamany and test_nxdht tests were failing since few script names have changed and few scripts are removed form power-gzip this patch fixes these failures. Also running selftests from power-gzip as now they are part of power-gzip tests [ https://github.com/libnxz/power-gzip ]
> Fixing nx_gzip test failures due to script issue.

- io/disk/sysfsdisk_att.py
- io/disk/sysfsdisk_att.py.data/README.txt
- io/disk/sysfsdisk_att.py.data/sysfsdisk_att.yaml
Reading all sysfs attributes of a disk from attribute files Write supported values to file and check attribute are reflected or not Check functionality after changing attribute value
> read and write to Sysfs attributes of disk

- io/common/bootlist_test.py
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name and disk names as input works as is.
> bootlist : add support for any device name as input

- io/driver/driver_parameter.py
In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name and disk names as input works as is.
> driver_param: support for mac addr as input

- io/net/htx_nic_devices.py
This patch supports to install latest HTX packages for SLES on Host and remote peer system setups.
> Adding support to install HTX packages on SLES/host and SLES/Peer.

- io/net/sriov_device_test.py
- io/net/sriov_device_test.py.data/README.txt
- io/net/sriov_device_test.py.data/sriov_max_logical_ports.yaml
This patch includes support of creating 'N' number of logical SRIOV ports from multiple physical ports serially when available.
Also included support to create and delete max number of SRIOV logical ports [ without MAC ].
> Code support to Create 'N' number of SRIOV logical ports.

- io/disk/ssd/nvmetest.py
compilation of upstream nvme-cli was failing. this script will fix this problem and it work fine
> Fixed the issue happening while conpiling the upstream nvme-cli

- io/net/sriov_device_test.py
- io/net/sriov_device_test.py.data/README.txt
- io/net/sriov_device_test.py.data/sriov_roce_device_test.yaml
Adding the code to support the adding and removal of single sriov roce vf port
> Adding and removing the SRIOV ROCE VF port

- fs/xfstests.py.data/ext4/4k_adv_auto.yaml
- fs/xfstests.py.data/ext4/64k_adv_auto.yaml
- fs/xfstests.py.data/ext4/64k_auto.yaml
This adds more adv_auto tests to ext4 for xfstests.
> Xfstests adv auto tests v1

- security/kernel-lockdown-tests.py
Fix exceptions, and customise for RHEL8 series of the OS.
> kernel-lockdown-tests.py: fix exceptions

- perf/perf_24x7_hardware_counters.py
[root@perf]# avocado run --max-parallel-tasks=1 perf_24x7_hardware_counters.py
JOB ID     : 2ca053ef8038d83ed373a9a289f6911b384d68fa
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-09-11T13.12-2ca053e/job.log
(01/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: STARTED
(01/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: PASS (1.63 s)
(02/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: STARTED
(02/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: CANCEL: HPM_0THRD_NON_IDLE_CCYC__PHYS_CORE not found (36.69 s)
(03/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_domain_param: STARTED
(03/13) …
> Added invalid domain check, invalid core check, invalid chip check

- io/net/virt-net/network_virtualization.py
- io/net/virt-net/network_virtualization.py.data/README
- io/net/virt-net/network_virtualization.py.data/multiple_vnic_nobacking.yaml
- io/net/virt-net/network_virtualization.py.data/network_virtualization.yaml
- io/net/virt-net/network_virtualization.py.data/single_vnic_single_backing.yaml
Keeping test count paramter same across all test
minizies input parameter maintainance
> vnic: keep count parameter same across test

- perf/perf_watch_point.py
On P9 no hardware breakpoints are available so watchpoint is not supported, make test skip on P9.
Enhance test to run on all other power platforms.
Also fix the module insert/remove logic by adding a check before running the command.
Result on P10
avocado run perf_watch_point.py
JOB ID     : 10e1a0cef0afe4563833b5a672a52f80181de56e
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2023-11-22T06.52-10e1a0c/job.log
(1/1) perf_watch_point.py:PerfWatchPoint.test_watch_point_check: STARTED
(1/1) perf_watch_point.py:PerfWatchPoint.test_watch_point_check: PASS (3.26 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2023-11-22T06.52-10e1a0c/results.html
JOB TIME   : 6.47 s …
> add P9/P10 support for watchpoint test

- memory/eatmemory.py.data/eatmem_getch.patch
After changes in eatmemory host repo internal patch file needs update. Updated same here.
> Update patch file for eatmemory.py

- io/disk/usb_tests.py
Added distro check and corresponding package
dependencies to be installed
> usb: add suse package dependencies

- workload/smt.py
Failing when it is checking for distro release and distro version comparision.So fixed the issue
> smt.py: Fixed the testcase

- security/security_flavor.py
localhost:/home/avocado-misc-tests/security # avocado run --max-parallel-tasks=1 security_flavor.py
JOB ID     : cd20d3057efc282bbc85aed93345a45fe2d60f53
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-01-22T21.21-cd20d30/job.log
(1/1) security_flavor.py:SecurityFlavor.test_security_flavor: STARTED
(1/1) security_flavor.py:SecurityFlavor.test_security_flavor: PASS (0.01 s)
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-01-22T21.21-cd20d30/results.html
JOB TIME   : 23.05 s
> Added test case to validate security flavor

- io/net/infiniband/mofed_install_test.py
Downloading the MOFED ISO matching the distro release installed
> MOFED ISO download from https path

- io/net/infiniband/mofed_install_test.py
keeping the legacy code for handling the full ISO path
> Adding support for full iso path

- security/secvarctl-tests.py
> secvarctl-tests.py: Adjust to upstream changes

- kernel/kselftest.py.data/security.yaml
Add 'dexcr' test to security.yaml
> kselftest.py: Add dexcr test to security.yaml

- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
supporting  mac address which is being provided as interface parameter value in yaml files
> Adding support for handling mac address

- cpu/schbench.py
- cpu/schbench.py.data/schbench.yaml
Added support to capture the benchmark stats multiple time.
> Added support to capture the schbench performance stats multiple time

- dlpar/dlpar_api/api.py
- dlpar/dlpar_main.py
Proc: Added support which do add and remove procs
based on the availability of system resources
Mem: added support which add memory quantity as per the lmb based on the availability of system resources
> Added support for proc and mem to perform sequentially

- cpu/producer_consumer.py
- cpu/producer_consumer.py.data/producer_consumer.yaml
Added support to capture the performance stats multiple times.
> Added support to capture the producer_consumer performance stats multiple time

- cpu/lockstorm_benchmark.py
- cpu/lockstorm_benchmark.py.data/lockstorm.yaml
This test case basically run the worklod and
capture the performance stats for kernel locks[spinlock].
> Automated lockstorm benchmark test

- cpu/dwh.py
- cpu/ebizzy.py
- cpu/em_smt_folding_test.py
- cpu/linsched.py
- fuzz/fsfuzzer.py
- memory/eatmemory.py
this patch address patch apply failure issue in couple of test as recent avocado has regression and community want that it should be fixed in test case
> fix patch apply issue

- perf/perf_metric.py
Patch adds a new function to test CPI_STALL_RATIO metricgroup by checking if its present in perf list or not. If metricgroup is present, collect counter statistics using perf stat and check if all stall metrics are present in the output. Also check for multiplexing of events should not happen.
Test for metricgroup events fails when performance information collection property is not enabled in hmc since internally it uses hv_24x7 events to collect statistics. Added a check to cancel the test in such cases.
```
On P10
avocado run --max-parallel-tasks=1 perf_metric.py
JOB ID     : 3266fa2f8fe417f605acf7a5f89d1861de33af5e
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-05-24T01.35-3266fa2/job.log
(1/3) perf_metric.py:perf_metric.test_all_metric_events_with_M: STARTED
(1/3) …
```
> perf/perf_metric.py: add test for CPI STALL json feature

- dlpar/dlpar_api/api.py
Have changed the validation code of DLPAR memory similar to cpu validation in order to avoid confusion
> api.py: Changed the validation check for DLPAR memory

- cpu/load_balancer.py
Removed python pandas package installation doc string.
> Removed unwanted docstring from load_balancer test script.

- cpu/perf_pipe_benchmark.py
- cpu/perf_pipe_benchmark.py.data/sched_pipe.yaml
Added support to run the benchmark multiple times, For this added a new parameter in .yaml : test_iter
> Added support to run the perf_sched benchmark.

- io/net/virt-net/network_virtualization.py
When secureboot is enabled, dynamic debug fails to get enabled. vnic dynamic debug is enabled if secureboot is disabled on the OS side.
> Enable dynamic debug only if secureboot is off [wait for avocado pull/5929]

- dlpar/dlpar_main.py
While running htx workloads we are trying to remove only 40% of memory.
> Added condition to remove only 40% memory removal during workloads

- perf/perf_pmu.py
- perf/perf_pmu.py.data/sysfs_PMU.cfg
Extend the test case to support Power11 processor
> perf/perf_pmu: Extend the test to support Power11

- kernel/kselftest.py
This commit:
1. adds gz file type against upstream location.
2. updates archive library call to handle uncompress in generic way
3. updates hardcoded path append with actual extracted folder name.
> Enhance kself test

- io/net/infiniband/mofed_install_test.py
Added the support for fetching the MOFED ISO from both http and https repository
> Handling both http and https repository path

- generic/ltp.py.data/ltp-security.yaml
Update according to upstream
Remove cap_bounds, securebits tests
> ltp-security.yaml: Update according to upstream

- workload/smt.py
- workload/smt.py.data/smt.yaml
Here to run SMT workload for a specific duration added `runtime` parameter using .yaml
> Added support to run smt workload for specific time

- cpu/producer_consumer.py
- cpu/schbench.py
Here we have changed the default iteartion number to capture the benchamrk stats multiple times.
> Changed the benchmark default iteration number.

- workload/cpu_fold.py
- workload/cpu_fold.py.data/cpu_fold.yaml
Here to run the CPU fold workload for a specific duration added runtime parameter using .yaml
> Added support to run cpu folding workload for specific time

- perf/perf_pmu.py
Remove unused check_ProcessorCompatMode function.
Improve test_write_sysfs_events function by adding write access test for root user as well and add fail condition if permission denied not found.
```
avocado run --max-parallel-tasks=1 perf_pmu.py
JOB ID     : 7ddbe4e1d0cb2227098654d18c880eb5453e6754
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-09-03T14.13-7ddbe4e/job.log
(01/10) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: STARTED
(01/10) perf_pmu.py:PerfBasic.test_config_PMU_sysfs: CANCEL: CONFIG_PMU_SYSFS not set. (0.03 s)
(02/10) perf_pmu.py:PerfBasic.test_config_PPC_RTAS: STARTED
(02/10) perf_pmu.py:PerfBasic.test_config_PPC_RTAS: PASS (0.42 s)
(03/10) perf_pmu.py:PerfBasic.test_cpu_event_count: STARTED
(03/10) perf_pmu.py:PerfBasic.test_cpu_event_count: PASS (0.03 s) …
```
> perf/pmu: fix commit f19028d

- kernel/kselftest.py.data/futex.yaml
Added futex.yaml to run the futext selftest case from upstream linux kernel.
> Added support to run the futex test case from linux selftest.

- workload/smt.py.data/smt.yaml
Increased SMT folding workload run time to 60 min.
> Increased smt workload run time.

- workload/cpu_fold.py.data/cpu_fold.yaml
Increased CPU folding workload run time to 60 min
> Increased cpu_folding workload run time.

- workload/cpu_fold.py
Added support in the CPU folding workload to validate dmesg logs and copy the cpu_fold logs from the /tmp/ directory to the current job run directory at intervals equal to the runtime duration specified in the .yaml configuration.
> Added support in cpu_folding workload to validate dmesg logs.

- perf/perf_hv_gpci_interface.py
- perf/perf_hv_gpci_interface.py.data/perf_hv_gpci_interface.yaml
Adding additional perf hv_gpci testcase, for files and access for system P10 or above.
> perf_hv_gpci_interface.py: Adding hv_gpci interface events

- .github/workflows/spellcheck.yml
adding workflow to check spell across any code change
> adding work flow to check spell across any code change

- generic/ltp.py.data/ltp-sched.yaml
Added separate .yaml file to run the scheduler LTP tests.
> Added .yaml file to run the ltp scheduler test.

- kernel/kselftest.py.data/futex.yaml
Quotes were missing in the yaml file.
> Fix: Missing Quotes

- io/disk/fiotest.py
- io/disk/ltp_fsstress.py
- io/disk/lvsetup.py
- io/disk/tiobench.py
For ubuntu, currently we have the issue in getting the distro version name when the file system is btrfs. so fixed this in this PR
> fixing to get the distro version based on distro name.

- workload/htx_test.py
Due to an SSL issue on the LPAR, the installation of the HTX RPM using rpm -ivh is failing.
To resolve this, we have implemented a curl-based
approach to download and install the HTX RPM packages
> Fixed htx ssl issue while accessing the HTX RPM

- fs/blktests.py
- fs/blktests.py.data/blktests.yaml
Incorporated review comments as part of https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2937
> [v2] Enhanced blktest

- ras/ras_ppcutils.py
"serv_config -b" updates the reboot policies interactively, added user input support for that.
localhost:/home/avocado-fvt-wrapper/tests/avocado-misc-tests/ras # avocado run --max-parallel-tasks=1 ras_ppcutils.py:test_serv_config
JOB ID     : b13e0cd5625f012e85aac53160ba575734fbacd8
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2025-03-16T23.15-b13e0cd/job.log
(1/1) ras_ppcutils.py:RASToolsPpcutils.test_serv_config: STARTED
(1/1) ras_ppcutils.py:RASToolsPpcutils.test_serv_config: PASS (1.42 s)
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2025-03-16T23.15-b13e0cd/results.html
JOB TIME   : 13.05 s
> Added user input for "serv_config -b" command.

- io/net/tcpdump.py
- io/net/tcpdump.py.data/tcpdump.yaml
Extend the package list and update the latest tcpdump package for sles16
> Extend package list for SUSE

- io/net/infiniband/dapl.py
- io/net/infiniband/ib_pingpong.py
- io/net/infiniband/mckey.py
- io/net/infiniband/ping6.py
- io/net/infiniband/rdma_tests.py
- io/net/infiniband/rping.py
- io/net/infiniband/ucmatose.py
- io/net/infiniband/udaddy.py
- io/net/iperf_test.py
use firewalld service for sles16
> use the right command for firewall service

- requirements-travis.txt
Moving right pylint version which able to run all supported matrix
> Moving right pylint version which able to run all supported matrix

- io/net/infiniband/mofed_install_test.py
So handling the different package names available to be installed accordingly
> Fixing different python package names

- security/kernel-lockdown-tests.py
Add new test case looking for 'operation not permitted' while writing in to serial port.
> kernel-lockdown-tests.py: add new test case with ioctl

- kernel/kselftest.py
The upstream run type of kselftest currently requires a Git repository URL and branch name to fetch the Linux kernel source. This commit introduces a custom run type, allowing users to specify a local directory containing the required Linux kernel source. The directory is validated for existence, a Makefile, and the tools/testing/selftests directory to ensure it is a valid kernel source from which kselftests can be run.
> kselftest run from custom linux source

- ras/hwinfo.py
convert bash commands to python
> hwinfo.py: pythonify bash commands

- io/net/tcpdump.py
The latest python is not supporting between instances of str and int
Also updating the nmap to be downloaded is the latest version
> Fixing the Timeout value to be integer

- cpu/cpuhotplug.py
- cpu/em_cpuhotplug.py
- cpu/lockstorm_benchmark.py
- fs/flail.py
- fs/fs-fuzz.py
- fuzz/trinity.py
- generic/stress-ng.py
- generic/sysbench.py
- io/disk/mvcli_test.py
- io/genwqe/genwqetest.py
- memory/memhotplug.py
- memory/mm_subsystem.py
- perf/perf_24x7_all_events.py
- perf/perf_bench.py
- perf/perf_hv_gpci.py
- perf/perf_hv_gpci_interface.py
- perf/perf_rawevents.py
- ras/hwinfo.py
- trace/kprobe.py
- trace/kretprobe.py
Change 'dmesg -c' to dmesg util ie dmesg.clear_dmesg()
> Change 'dmesg -c' to dmesg.clear_dmesg

- security/vTPM-tests.py
Modify tests:
test_tpm_kconfig
test_present_devices
test_tpm_measurement
Add new tests:
test_stat_user_group
> security/vTPM-tests.py: test case enhancements

- io/net/htx_nic_devices.py
Disable firewall service based on relevant services
> disable firewall serice before starting htx

- kernel/kselftest.py
as clang package rename with libclang13 in sles16 ,this patch address same
> SLES16 package fix

- memory/ndctl.py
- memory/ndctl.py.data/ndctl.yaml
Support for 1GB alignemnt is newly added feature, have added the testcases for same.
> Added tests for 1GB alignment - v2

- memory/ndctl.py
This test creates 1GB alignment namespace, checks for "Tail page reuse" message in dmesg to verify Device memory kernel mapping optimization Feature.
> Test to verify Device memory kernel mapping optimization Feature.

- generic/ltp.py.data/ltp-syscalls.yaml
Add yaml to run syscalls tests in ltp
> Add ltp-syscalls.yaml

- perf/perf_datatype_profiling.py
It checks the perf mem-loads and mem-stores and check whether the datatype, offset, etc are present in headers.
> perf_datatype_profiling.py: Add new testcase for datatype and offset recognising new feature.

- io/disk/htx_block_devices.py
Updated code to match changes to the HTX the way it work
1. option "-k" is added to avoid cert checks.
2. htx rpm downloaded to /tmp directory.
3. Install htx by providing absolute path.
4. Added a condition for mdt.hd to be created under mdt folder.
> Updated htx code for block devices as per changes to htx tool

- io/net/htx_nic_devices.py
Downloading the HTX rpm from the repository based on the distro OS installed Installing the HTX rpm on both the host and peer lpars
> Fixing the HTX network tests to work on network interfaces

- io/net/htx_nic_devices.py
Making htx test suite to execute on sles host and rhel peer on different network adapter ports
> Adding support for htx to execute on different distros
